import type { Material, MaterialLevel, QuizQuestion } from "./materials";

type Seed = { id: number; title: string; level: MaterialLevel; minutes: number; focus: string; analogy: string; story: string; practice: string; guardrail: string; check: string };

const coreResources: NonNullable<Material["resources"]> = [
  { label: "Video 1 pengguna: AI Engineering — Building Applications with Foundation Models", url: "https://youtu.be/JV3pL1_mn2M", note: "Ringkasan lifecycle foundation model, evaluation, RAG, agents, adaptation, dan production optimization." },
  { label: "Video 2 pengguna: AI Engineering in 41 Minutes — From Demo to Production", url: "https://youtu.be/geQqpO_AFMo", note: "Anas Riad: use case → evaluasi → prompting/RAG/agents → production → feedback loop." },
  { label: "O'Reilly: AI Engineering — Chip Huyen", url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/", note: "Rujukan struktur sistem: evaluation, prompting, RAG/agents, adaptation, inference, architecture, dan feedback." },
];

const evalResource: Material["resources"] = [{ label: "OpenAI Evaluation Best Practices", url: "https://developers.openai.com/api/docs/guides/evaluation-best-practices", note: "Objective, dataset, metrics, continuous evaluation, dan kalibrasi human feedback." }];
const agentResource: Material["resources"] = [{ label: "Anthropic: Building Effective Agents", url: "https://www.anthropic.com/engineering/building-effective-agents", note: "Mulai sederhana; bedakan workflow dan agents; tingkatkan kompleksitas bila bukti evaluasi mendukung." }];

function quiz(title: string, check: string, practice: string): QuizQuestion[] {
  return [
    { question: `Dalam “${title}”, prinsip yang paling penting adalah…`, options: [check, "Menambah tool sebelum tujuan jelas", "Mengandalkan satu demo yang tampak bagus"], answer: 0, explanation: `Benar. Fokusnya adalah ${check.toLowerCase()}.` },
    { question: "Langkah praktik yang paling sehat adalah…", options: [practice, "Merilis tanpa contoh uji", "Memperluas akses sebelum ada batas tindakan"], answer: 0, explanation: "Mulai dari bukti kecil yang dapat diperiksa, lalu iterasikan berdasarkan hasilnya." },
  ];
}

function lesson(seed: Seed, resources: NonNullable<Material["resources"]> = []): Material {
  return {
    id: seed.id,
    title: seed.title,
    category: "AI Engineering",
    specialization: "ai-engineering",
    level: seed.level,
    minutes: seed.minutes,
    emoji: "✦",
    summary: seed.focus,
    analogy: seed.analogy,
    sections: [
      { heading: "Peta dari sumber", body: `${seed.focus} Dua video sumber menempatkan keputusan ini dalam perjalanan dari demo menuju produk: pilih masalah, pilih pendekatan paling sederhana, ukur hasil, lalu tambahkan kompleksitas hanya jika bukti membutuhkannya.` },
      { heading: "Cerita kecil", body: seed.story },
      { heading: "Coba di dunia nyata", body: `${seed.practice}. Simpan contoh input, output, dan alasan keputusanmu agar perubahan berikutnya dapat dibandingkan.` },
      { heading: "Ringkasnya", body: `${seed.title} membantu kamu berpindah dari “terlihat bekerja” ke sistem yang punya bukti, batas, dan cara diperbaiki. ${seed.guardrail}` },
    ],
    resources: [...coreResources, ...resources],
    quiz: quiz(seed.title, seed.check, seed.practice),
  };
}

const seeds: Seed[] = [
  { id: 88, title: "Peta AI Engineering: Dari Demo ke Produk", level: "Pemula", minutes: 12, focus: "AI Engineering adalah praktik membangun aplikasi di atas foundation model dengan tujuan, bukti kualitas, batas risiko, dan operasi yang dapat dirawat.", analogy: "Demo seperti layang-layang di lapangan; produk seperti pesawat kecil yang perlu rute, pemeriksaan, bahan bakar, dan prosedur ketika cuaca berubah.", story: "Dimas membuat chatbot dalam satu sore dan hasilnya tampak hebat pada tiga pertanyaan. Ketika teman lain mencoba, pertanyaannya berbeda, jawaban tidak konsisten, dan tidak ada cara mengetahui kegagalan. Ia lalu menggambar lifecycle: use case, model, evaluasi, sistem, monitoring, dan feedback.", practice: "Pilih satu ide AI lalu petakan tujuh kotak: pengguna, tugas, data/konteks, model, ukuran berhasil, risiko, dan pemilik perbaikan", guardrail: "Jangan menyebut sistem siap produksi hanya karena satu demo terasa meyakinkan.", check: "membedakan demo menarik dari sistem AI yang dapat dipertanggungjawabkan" },
  { id: 89, title: "Use Case, Baseline, dan Batas Produk AI", level: "Pemula", minutes: 13, focus: "Use case yang sehat menyebut pengguna, keputusan atau tugas, baseline tanpa AI, dampak salah, dan batas yang tidak boleh dilewati.", analogy: "Sebelum membeli alat, kamu perlu tahu benda apa yang ingin diperbaiki dan apakah obeng sederhana sudah cukup.", story: "Tim Rara ingin membuat agent untuk semua inbox. Setelah memetakan kasus, mereka melihat FAQ sederhana lebih baik menjadi artikel, sedangkan AI paling berguna untuk membuat draf ringkasan tiket panjang. Baseline itu membuat scope pertama lebih masuk akal.", practice: "Tulis problem statement berisi pengguna, tugas, baseline saat ini, dampak jika salah, dan satu tindakan yang tidak boleh dilakukan otomatis", guardrail: "Jika salahnya mahal atau sulit dibatalkan, rancang review manusia sejak versi pertama.", check: "memilih masalah yang tepat sebelum memilih model atau agent" },
  { id: 90, title: "Memilih Model dengan Bukti, Bukan Hype", level: "Menengah", minutes: 14, focus: "Pemilihan model mempertimbangkan capability, kualitas pada tugasmu, biaya, latency, privacy, structured output, dan cara kegagalan—bukan leaderboard umum saja.", analogy: "Memilih model seperti memilih kendaraan: mobil tercepat belum tentu cocok untuk jalan, muatan, biaya, dan aturan perjalananmu.", story: "Aplikasi Niko memakai model paling besar untuk semua pertanyaan. Biaya naik dan jawaban sederhana menjadi lambat. Setelah membagi dataset evaluasi menurut kasus, ia melihat model kecil cukup untuk klasifikasi sementara model kuat dipakai pada ringkasan yang rumit.", practice: "Buat kartu pembanding untuk dua model: tugas, kualitas contoh, latency, biaya perkiraan, format output, dan risiko data", guardrail: "Benchmark publik adalah sinyal awal; evaluasi privat yang menyerupai penggunaanmu tetap menentukan.", check: "membandingkan model terhadap tugas dan batas produk yang nyata" },
  { id: 91, title: "Evals First: Mengubah Tebakan Menjadi Engineering", level: "Menengah", minutes: 16, focus: "Evals adalah tes terstruktur untuk mengukur apakah sistem AI memenuhi tujuan pada contoh normal, sulit, dan adversarial sebelum serta setelah perubahan.", analogy: "Evals seperti rute ujian kendaraan: bukan hanya melihat mobil bisa menyala, tetapi menguji belok, rem, cuaca, dan situasi tak terduga.", story: "Sebelum mengubah prompt, Sinta mengumpulkan 25 pertanyaan pengguna dan membuat rubrik grounded, lengkap, aman, serta sesuai format. Ia menemukan perbaikan yang menaikkan jawaban panjang justru menurunkan ketepatan pada pertanyaan singkat.", practice: "Kumpulkan sepuluh contoh representatif, tulis tujuan eval, rubrik pass/fail, dan tiga edge case yang sengaja menantang", guardrail: "Jangan memakai vibe atau satu contoh viral sebagai satu-satunya bukti kualitas.", check: "mendefinisikan tujuan, dataset, dan rubrik evaluasi sebelum optimasi" },
  { id: 92, title: "Prompt sebagai Sistem: Konteks, Format, dan Validasi", level: "Menengah", minutes: 15, focus: "Prompt produksi adalah instruksi yang jelas, konteks relevan, contoh bila perlu, format yang dapat diparse, versi yang terlacak, serta validator di sisi aplikasi.", analogy: "Prompt seperti brief kerja: jelas siapa yang mengerjakan, apa hasilnya, bahan yang boleh dipakai, dan bentuk dokumen yang harus dikembalikan.", story: "Draf prompt Rani hanya berkata 'buat ringkasan bagus'. Setelah ia menambahkan audiens, batas sumber, format JSON, contoh keluaran, dan validator, hasilnya lebih mudah dibandingkan dan gagal dengan pesan yang jelas bila format tidak sesuai.", practice: "Ubah satu prompt menjadi lima bagian: peran/tujuan, task, konteks, contoh, dan format; lalu tulis aturan validasi aplikasi", guardrail: "Jangan memperlakukan teks keluaran model sebagai perintah atau kode tepercaya tanpa validasi.", check: "mendesain prompt yang eksplisit dan hasil yang dapat diperiksa" },
  { id: 93, title: "RAG sebagai Sistem Grounding", level: "Menengah", minutes: 17, focus: "RAG menghubungkan model dengan pengetahuan eksternal melalui dua jalur: indexing offline dan retrieval online yang harus diukur bersama generation.", analogy: "RAG seperti perpustakaan: buku perlu dikatalogkan lebih dulu, lalu petugas mencari halaman relevan sebelum jawaban ditulis.", story: "Chatbot kebijakan Arif menjawab lancar tetapi sering memakai aturan lama. Tim memisahkan proses bersih-bersih dokumen, chunking, embedding, index, retrieval, dan sitasi. Mereka lalu tahu apakah masalah berasal dari dokumen, pencarian, atau jawaban.", practice: "Gambar pipeline offline dan online: sumber → cleaning → chunking → embedding/index, lalu pertanyaan → retrieve/rerank → context → jawaban bersitasi", guardrail: "Retrieved content adalah data tidak tepercaya; pisahkan dari instruksi dan jangan izinkan ia menentukan tindakan tool.", check: "membedakan indexing offline dari retrieval serta generation saat query" },
  { id: 94, title: "Mengevaluasi RAG: Jawaban, Konteks, dan Sitasi", level: "Menengah", minutes: 16, focus: "RAG perlu dievaluasi pada kualitas retrieval, faithfulness terhadap konteks, relevansi jawaban, sitasi, latency, dan perilaku ketika informasi tidak ada.", analogy: "Seperti memeriksa jawaban ujian dengan buku terbuka: bukan hanya jawabannya terdengar bagus, tetapi halaman rujukannya harus benar dan mendukung kesimpulan.", story: "Saat jawaban sistem salah, tim awalnya mengubah model. Setelah memeriksa jejak retrieval, mereka menemukan chunk yang benar tidak pernah terambil karena kata kunci dokumen berbeda. Perbaikan kemudian difokuskan pada data dan retrieval.", practice: "Untuk lima pertanyaan, catat dokumen yang seharusnya terambil, konteks yang benar-benar terambil, sitasi jawaban, serta skor grounded dan berguna", guardrail: "Jika bukti tidak ditemukan, sistem perlu mampu berkata tidak tahu atau meminta klarifikasi, bukan mengarang.", check: "mendiagnosis apakah kegagalan berasal dari retrieval, konteks, atau generation" },
  { id: 95, title: "Workflow Dulu, Agent Bila Perlu", level: "Menengah", minutes: 15, focus: "Workflow memakai jalur yang ditentukan kode untuk tugas terstruktur; agent memilih langkah dan tool secara dinamis untuk masalah yang benar-benar terbuka.", analogy: "Workflow seperti resep dengan langkah tetap; agent seperti koki yang memilih urutan berdasarkan bahan dan keadaan dapur.", story: "Permintaan support Fara memiliki tiga kategori jelas. Awalnya tim ingin multi-agent, tetapi routing sederhana ke tiga workflow lebih murah, mudah diuji, dan cukup akurat. Agent baru dipertimbangkan untuk investigasi yang urutannya tidak dapat diprediksi.", practice: "Ambil satu tugas lalu tandai apakah langkahnya tetap, bercabang sederhana, atau benar-benar membutuhkan keputusan dinamis; tulis alasanmu", guardrail: "Kompleksitas agent membawa biaya, latency, dan peluang error berantai; jangan menambahnya tanpa bukti manfaat.", check: "memilih workflow paling sederhana yang masih memenuhi kebutuhan" },
  { id: 96, title: "Agent, Tool, dan Approval yang Terbatas", level: "Lanjut", minutes: 18, focus: "Agent yang memakai tool membutuhkan daftar kemampuan yang sempit, input/output terstruktur, validasi server, izin minimum, budget, timeout, audit, dan approval untuk tindakan berdampak.", analogy: "Seperti asisten dengan kartu akses terbatas: ia boleh membaca katalog dan membuat draf, tetapi tidak otomatis boleh mengirim uang atau menghapus arsip.", story: "Agent Lila dapat mencari dokumen dan menulis draf email. Ketika akses kirim diaktifkan tanpa approval, sebuah instruksi dari dokumen eksternal hampir mengubah tujuan tugas. Tim lalu memisahkan read, draft, send, dan delete ke tingkat izin yang berbeda.", practice: "Buat matriks tool berisi aksi, data yang dipakai, izin, approval, timeout, budget, dan catatan audit untuk setiap tool", guardrail: "Prompt bukan sandbox; enforce batas tool serta izin pada aplikasi/server, bukan pada teks instruksi saja.", check: "membatasi kemampuan agent sesuai dampak tindakannya" },
  { id: 97, title: "Tangga Adaptasi: Prompt, RAG, atau Fine-tuning?", level: "Lanjut", minutes: 16, focus: "Adaptasi sebaiknya dimulai dari prompt dan konteks, lalu RAG untuk pengetahuan eksternal, dan fine-tuning hanya ketika ada pola perilaku stabil serta data berkualitas untuk diukur.", analogy: "Seperti mengajari rekan baru: mulai dengan brief jelas, berikan buku referensi, lalu adakan pelatihan khusus hanya jika pola pekerjaannya benar-benar berulang.", story: "Tim Beni ingin fine-tuning karena model salah menyebut harga produk. Setelah ditelusuri, informasi harga sering berubah. RAG dengan sumber terkontrol lebih tepat; fine-tuning tidak dipakai untuk menyimpan fakta yang cepat berubah.", practice: "Untuk satu masalah, tulis apakah kegagalan berasal dari instruksi, pengetahuan saat ini, format/perilaku stabil, atau data; pilih tingkat adaptasi paling ringan yang masuk akal", guardrail: "Data fine-tuning yang bising atau tanpa evaluasi dapat memperkuat perilaku salah dan sulit didiagnosis.", check: "memilih teknik adaptasi berdasarkan jenis masalah, bukan tren" },
  { id: 98, title: "Arsitektur Produksi: Gateway, Cache, Observability", level: "Lanjut", minutes: 18, focus: "Sistem produksi menyatukan guardrails, model routing/gateway, cache, logging terpilah, metrik kualitas-latency-biaya, monitoring, dan runbook respons gangguan.", analogy: "Seperti stasiun kereta: ada gerbang, rute, ruang tunggu, papan jadwal, kamera, dan prosedur ketika satu jalur ditutup.", story: "Aplikasi Maru terasa mahal dan kadang lambat. Setelah gateway mencatat model, token, latency, cache hit, dan error secara aman, tim menemukan prompt berulang serta jalur tertentu yang bisa dialihkan ke model lebih ringan.", practice: "Gambar request path: pengguna → guardrail → gateway/router → model/RAG/tool → validator → response; tambahkan tiga metrik dan satu langkah rollback", guardrail: "Jangan masukkan prompt mentah, informasi pribadi, atau secret ke log tanpa kebijakan redaksi dan akses yang tepat.", check: "membaca sistem AI sebagai rangkaian komponen operasional, bukan satu model call" },
  { id: 99, title: "Feedback Loop dan Checklist Rilis AI", level: "Lanjut", minutes: 17, focus: "Rilis AI adalah awal siklus: pantau contoh gagal, feedback pengguna, drift data, biaya, latency, keamanan, dan evaluasi regresi sebelum menaikkan scope atau otonomi.", analogy: "Seperti membuka kedai baru: hari pembukaan memberi banyak pelajaran, tetapi kamu perlu buku catatan, pemilik masalah, dan cara memperbaiki menu tanpa mengubah semuanya sekaligus.", story: "Sesudah rilis, tim Aji melihat pengguna sering mengoreksi kategori tertentu. Mereka menandainya sebagai kasus eval baru, memperbaiki workflow, membandingkan hasil lama-baru, lalu merilis bertahap daripada mengganti seluruh sistem sekaligus.", practice: "Tulis checklist rilis: dataset eval, ambang kualitas, fallback, owner insiden, metrik latency/biaya, feedback channel, privacy review, dan rollback", guardrail: "Jangan memperluas akses atau otonomi karena metrik rata-rata bagus jika edge case berisiko belum dibuktikan aman.", check: "menjadikan feedback dan evaluasi berkelanjutan sebagai bagian dari operasi" },
];

export const aiEngineeringMaterials: Material[] = seeds.map((seed) => lesson(seed, seed.id === 91 || seed.id === 94 || seed.id === 99 ? evalResource : seed.id === 95 || seed.id === 96 ? agentResource : []));
