/* Original long-form teaching notes. They follow the supplied book's topic sequence without reproducing its text. */
export const aiEngineeringAdvancedLectures: Record<number, string> = {
  112: `Evaluasi adalah kontrak kualitas antara tim dan pengguna. Dalam sistem AI, jawaban yang terdengar meyakinkan belum tentu menyelesaikan masalah. Karena itu, sebelum mengubah model atau prompt, tim perlu memutuskan apa yang dimaksud dengan respons yang benar, berguna, aman, dan sesuai format. Kontrak ini harus cukup spesifik sehingga dua orang dapat melihat keluaran yang sama dan menjelaskan mengapa keluaran tersebut layak atau tidak layak.

Bayangkan sebuah asisten kebijakan karyawan. Kualitasnya bukan hanya tata bahasa. Ia harus memilih kebijakan yang masih berlaku, menjawab pertanyaan yang diajukan, tidak menyimpulkan hal di luar dokumen, dan mengarahkan pengguna ketika pertanyaan membutuhkan petugas HR. Mulailah dengan beberapa dimensi yang paling berisiko, tulis contoh lulus serta gagal, lalu gunakan contoh itu setiap kali sistem berubah. Dengan cara ini, evaluasi menjadi alat belajar, bukan pemeriksaan di akhir proyek.`,
  113: `Dataset evaluasi adalah potret terpilih dari situasi yang benar-benar akan ditemui sistem. Ia tidak harus besar pada awalnya, tetapi harus jujur. Jika semua pertanyaan ditulis oleh pembuat produk dan semuanya jelas, skor tinggi hanya membuktikan bahwa sistem baik menjawab pertanyaan yang sudah dikenal pembuatnya. Pengguna nyata membawa singkatan, ejaan tidak baku, permintaan ganda, informasi hilang, dan kasus yang seharusnya ditolak.

Susun dataset sebagai kumpulan kelas risiko. Untuk asisten kebijakan, masukkan pertanyaan umum, pertanyaan yang meminta pengecualian, pertanyaan berdasarkan versi dokumen lama, pertanyaan tanpa bukti, dan pertanyaan sensitif yang perlu dialihkan. Setiap kasus harus menyimpan alasan keberadaannya. Saat sistem gagal, jangan hanya menambal prompt; tambahkan representasi kegagalan itu ke dataset. Dengan demikian, set evaluasi menjadi memori institusional tentang masalah yang pernah dipelajari tim.`,
  114: `Metrik berguna ketika ia mengukur sesuatu yang konsekuensinya dipahami. Untuk ekstraksi nomor dokumen, benar atau salah dapat dihitung dengan jelas. Untuk ringkasan rapat, satu angka kesamaan teks tidak cukup karena pengguna mungkin membutuhkan keputusan, pemilik tindakan, dan tenggat yang tidak boleh hilang. Pilih metode ukur berdasarkan bentuk tugas, bukan karena metrik tersebut mudah tersedia.

Praktiknya, pisahkan kualitas yang dapat dihitung dari kualitas yang harus dinilai. Validitas schema JSON, waktu respons, dan keberadaan kutipan dapat diukur otomatis. Ketepatan penalaran, keterbacaan, atau kecocokan nada mungkin memerlukan rubrik. Ketika melihat skor, tanyakan tiga hal: bagian apa yang diukur, bagian apa yang tidak diukur, dan jenis kesalahan apa yang masih dapat lolos. Pertanyaan tersebut menjaga tim dari optimasi angka yang tidak menghasilkan manfaat nyata.`,
  115: `Penilaian manusia diperlukan ketika kualitas bergantung pada konteks dan pertimbangan. Namun manusia tidak otomatis konsisten. Dua penilai dapat berbeda karena mereka membaca instruksi secara berbeda, bukan karena salah satu kurang teliti. Tugas dosen atau lead evaluator adalah mengubah istilah kabur seperti “membantu” menjadi rubrik yang dapat dipakai bersama.

Mulailah dengan skala kecil, misalnya satu sampai empat. Untuk groundedness, definisikan skor tertinggi sebagai semua klaim penting didukung sumber; skor terendah sebagai jawaban yang membuat klaim utama tanpa bukti. Tambahkan contoh batas yang sering menimbulkan perdebatan. Minta penilai memberi alasan singkat, lalu bandingkan perbedaan besar. Bila perbedaan berulang, perbaiki rubrik atau panduannya. Tujuan proses ini bukan memaksa semua orang sepakat secara sempurna, melainkan membuat penilaian cukup konsisten untuk memandu keputusan produk.`,
  116: `AI as judge berarti memakai model untuk menerapkan rubrik pada banyak keluaran. Ia dapat menghemat waktu, terutama ketika ribuan respons perlu diperiksa, tetapi ia tetap sebuah instrumen pengukuran yang bisa bias. Model penilai dapat terpesona oleh jawaban panjang, gaya bahasa percaya diri, atau format yang rapi walaupun fakta utamanya lemah. Karena itu, desain penilaian AI harus transparan dan dapat dibandingkan dengan penilaian manusia.

Berikan bahan yang lengkap kepada penilai: pertanyaan, sumber yang diizinkan, jawaban sistem, dan rubrik per dimensi. Minta keputusan serta alasan yang terstruktur. Lalu ambil sampel yang cukup untuk dibandingkan dengan reviewer manusia, terutama pada kasus berisiko tinggi dan kasus ketika skor penilai berubah drastis. Bila kesepakatan rendah, jangan memakai skor itu untuk keputusan rilis. Perbaiki rubrik, prompt penilai, atau batas penggunaan penilai terlebih dahulu.`,
  117: `Error analysis mengubah keluhan umum menjadi pekerjaan teknik yang terarah. Pernyataan seperti “chatbot sering salah” tidak memberi tahu tim apakah masalah berada pada dokumen, retrieval, instruksi, model, antarmuka, atau ekspektasi pengguna. Dengan mengumpulkan contoh gagal lalu memberi kategori, tim dapat melihat pola dan memilih perbaikan dengan dampak terbesar.

Gunakan tabel sederhana: gejala keluaran, penyebab dugaan, bukti, dampak, dan eksperimen berikutnya. Misalnya, jawaban kebijakan yang salah dapat disebabkan dokumen terbaru tidak terindeks, bukan model yang tidak mampu memahami pertanyaan. Perbaikan yang sesuai adalah memeriksa aliran data dan retrieval, bukan langsung melakukan finetuning. Setelah eksperimen, jalankan kembali set evaluasi untuk memastikan perbaikan tidak menurunkan kategori lain. Analisis kesalahan yang baik selalu menghasilkan hipotesis yang dapat diuji.`,
  118: `Evaluation pipeline adalah jalur kerja yang membuat perbandingan antarsistem dapat dipercaya. Setiap run perlu menjawab: data uji apa yang dipakai, prompt versi berapa, model apa, parameter apa, kapan dijalankan, metrik apa yang dihitung, dan contoh kegagalan apa yang diperiksa. Tanpa jejak ini, tim dapat melihat skor berubah tetapi tidak tahu perubahan mana yang menghasilkan perbedaan.

Mulailah dari pipeline kecil. Simpan konfigurasi dalam satu file, jalankan pertanyaan yang sama, simpan keluaran, lalu buat ringkasan metrik dan tautan ke sampel. Ketika provider memperbarui model, jalankan ulang baseline yang sama. Ketika prompt berubah, bandingkan hanya satu perubahan penting terlebih dahulu. Pipeline tidak menggantikan pembacaan keluaran; ia memastikan pembacaan itu dilakukan pada sampel dan kondisi yang dapat ditelusuri.`,
  119: `Versi adalah bagian dari bukti. Dalam aplikasi AI, perubahan kecil pada prompt, urutan konteks, model default, atau data evaluasi dapat mengubah perilaku secara besar. Jika beberapa komponen berubah pada hari yang sama, tim tidak dapat menyimpulkan apakah perbaikan benar-benar berasal dari model baru, prompt baru, atau kebetulan pada data.

Berikan identitas kepada setiap run dan setiap artefak penting. Catat versi dataset, prompt, model, parameter, dan kode retrieval. Simpan pula keputusan yang diambil setelah melihat hasil. Saat ada regresi, catatan ini memungkinkan rollback dan investigasi tanpa menebak. Kebiasaan versi mungkin terasa administratif pada awal proyek, tetapi nilainya muncul ketika sistem harus dipelihara oleh lebih dari satu orang atau saat perubahan kecil mulai menimbulkan dampak besar.`,
  120: `Evaluasi offline dan online menjawab pertanyaan yang berbeda. Offline menguji perilaku dalam lingkungan terkendali sebelum pengguna terkena risiko. Online mengamati apakah perilaku tersebut benar-benar membantu alur kerja nyata, termasuk kondisi yang belum tertangkap oleh dataset. Mengandalkan satu saja menghasilkan titik buta.

Contohnya, asisten pengetahuan dapat memperoleh nilai groundedness tinggi secara offline tetapi tetap tidak dipakai karena jawabannya terlalu panjang atau sulit ditemukan dalam antarmuka. Sebaliknya, metrik klik online yang tinggi tidak membuktikan jawaban benar. Gunakan offline sebagai pagar rilis dan online sebagai observasi manfaat serta risiko setelah rilis terbatas. Tinjau sampel dari keduanya secara rutin. Ketika sinyal online bertentangan dengan hasil offline, jadikan konflik itu bahan memperbaiki dataset, rubrik, atau desain produk.`,
  121: `Ambang rilis adalah keputusan manajemen risiko, bukan angka kosmetik. Rata-rata 90% mungkin cukup untuk fitur ideasi, tetapi tidak cukup untuk jawaban yang memengaruhi pembayaran, kesehatan, atau akses data. Tim perlu menentukan kategori mana yang kritis, kesalahan apa yang tidak dapat diterima, dan siapa yang boleh memberi pengecualian.

Nyatakan aturan dengan jelas. Sebagai contoh, jawaban kebijakan keuangan harus memiliki dukungan sumber di atas ambang tertentu dan tidak boleh memiliki kegagalan kritis pada set keamanan. Jika satu syarat gagal, rilis ditunda meskipun skor rata-rata tinggi. Pendekatan ini mencegah manfaat pada kasus mudah menutupi risiko pada kasus berat. Ambang perlu ditinjau saat penggunaan, dampak, atau mekanisme kontrol berubah.`,
  122: `Regression suite adalah kumpulan janji yang tidak boleh dilanggar kembali. Setiap insiden penting, bug yang sulit, atau kasus pelanggan yang representatif dapat diubah menjadi satu test. Ketika model, prompt, atau dokumen diperbarui, suite ini memeriksa apakah kemampuan lama tetap bertahan.

Buat kasus regresi sekecil mungkin tetapi lengkap. Simpan masukan, konteks yang diizinkan, perilaku yang benar, dan alasan mengapa kasus itu penting. Contoh: setelah instruksi pemendekan jawaban, sistem menghilangkan pengecualian pada kebijakan pengembalian. Kasus itu harus hidup dalam regression suite, bukan hanya dalam pesan percakapan tim. Suite yang tumbuh dari masalah nyata jauh lebih berharga daripada daftar contoh ideal yang tidak pernah gagal.`,
  123: `Eksperimen yang baik adalah cara menghasilkan pengetahuan, bukan hanya skor baru. Setiap eksperimen harus berangkat dari hipotesis: perubahan apa yang diyakini akan memperbaiki metrik tertentu, mengapa perubahan itu masuk akal, dan risiko apa yang mungkin muncul. Jika model, prompt, retrieval, dan parameter diubah bersama-sama, hasilnya sulit diinterpretasikan.

Rancang run dengan satu perubahan utama, set evaluasi tetap, dan sampel yang wajib dibaca. Misalnya, hipotesisnya adalah dua contoh format akan meningkatkan validitas JSON. Jalankan baseline dan kandidat, bandingkan validitas, lalu baca keluaran yang masih gagal. Bila peningkatan kecil tetapi biaya konteks besar, keputusan dapat menolak perubahan tersebut. Pengetahuan yang dapat diulang lebih berguna daripada kemenangan sesaat pada satu demo.`,
  124: `Prompt adalah spesifikasi operasional. Ia menjelaskan tugas, sumber informasi, batas perilaku, format keluaran, dan tindakan saat bukti tidak cukup. Prompt yang hanya berkata “jawablah dengan baik” menyerahkan terlalu banyak interpretasi kepada model. Prompt yang baik dapat dibaca rekan kerja, diuji dengan dataset, dan diberi versi.

Untuk asisten kebijakan, spesifikasi dapat menyebut bahwa model hanya memakai konteks yang disediakan, mengutip sumber, membedakan fakta dari saran, dan mengarahkan kasus sensitif ke petugas. Setiap instruksi harus memiliki tujuan yang jelas. Hindari menumpuk larangan tanpa prioritas karena konflik antaraturan membuat perilaku sulit diprediksi. Setelah ditulis, prompt harus dievaluasi pada kasus normal, ambigu, dan adversarial seperti komponen aplikasi lain.`,
  125: `Aplikasi AI harus memisahkan tiga jenis teks: aturan sistem, permintaan pengguna, dan data atau dokumen eksternal. Aturan sistem menjelaskan kebijakan aplikasi. Permintaan pengguna menyampaikan tujuan. Dokumen memberi isi yang dapat dianalisis tetapi tidak boleh otomatis memiliki kewenangan untuk mengubah aturan. Pemisahan ini adalah dasar keamanan dan keterbacaan.

Misalkan dokumen yang diunggah berisi kalimat “abaikan aturan sebelumnya”. Jika aplikasi mencampurkannya dengan system instruction, model dapat sulit membedakan mana data dan mana perintah. Tandai dokumen sebagai konten tidak tepercaya, batasi tool yang dapat dipanggil, dan validasi tindakan di server. Hierarki instruksi tidak hanya ditulis dalam prompt; ia juga harus didukung oleh desain aplikasi serta kontrol otorisasi.`,
  126: `Zero-shot cukup ketika tugas dan label sudah jelas bagi model. Few-shot berguna ketika tim membutuhkan pola khusus, misalnya format kategori internal, nada jawaban, atau contoh kasus batas. Namun contoh adalah bagian dari konteks yang mahal dan dapat membawa bias. Contoh yang terlalu mirip hanya membuat sistem menghafal gaya, bukan memahami aturan.

Gunakan evaluasi untuk memutuskan apakah contoh diperlukan. Jika model sering menukar dua label pada istilah internal, tambahkan contoh singkat yang membedakan keduanya. Jika model sudah stabil, jangan menambah contoh hanya karena terlihat canggih. Pilih contoh yang ringkas, mewakili variasi pengguna, dan konsisten dengan aturan sistem. Uji pula apakah contoh menyebabkan kategori lain memburuk.`,
  127: `Structured output menjembatani generasi bahasa dan perangkat lunak. Ketika keluaran akan masuk ke database, API, atau proses otomatis, aplikasi memerlukan bentuk yang dapat divalidasi. Meminta JSON membantu, tetapi bukan jaminan. Model dapat menambahkan prosa, memakai tipe yang salah, atau mengisi nilai yang melanggar aturan bisnis.

Rancang schema sebelum meminta keluaran. Tentukan nama field, tipe, nilai wajib, rentang, dan aturan lintas-field. Setelah respons diterima, parser dan validator aplikasi harus menolak bentuk yang tidak valid. Untuk kasus tertentu, sistem boleh mencoba perbaikan sekali dengan pesan error yang terarah; setelah itu, kasus perlu dialihkan untuk ditinjau. Prinsip pentingnya: model menghasilkan kandidat, tetapi aplikasi tetap memegang keputusan apakah kandidat aman digunakan.`,
  128: `Versi prompt diperlukan karena prompt adalah konfigurasi produksi, bukan catatan pribadi. Perubahan kecil seperti memindahkan instruksi, mengubah contoh, atau menambah format dapat meningkatkan satu kategori sambil menurunkan kategori lain. Tanpa versi dan evaluasi, tim sulit melakukan rollback saat dampak negatif muncul.

Simpan tujuan prompt, isi, contoh, pemilik, catatan perubahan, dan hasil evaluasi. Bandingkan kandidat dengan baseline pada set yang sama. Jika prompt baru membuat jawaban lebih singkat tetapi mengurangi ketepatan kutipan, pilihan dapat diputuskan berdasarkan bukti, bukan selera. Perlakukan perubahan prompt dengan disiplin yang sama seperti perubahan kode: tinjau, uji, rilis bertahap, dan siapkan jalur kembali.`,
  129: `Prompt injection adalah usaha membuat model mengubah tujuan aplikasi melalui teks yang tidak tepercaya. Serangan dapat muncul di dokumen, halaman web, email, atau bahkan hasil tool. Kalimat berbahaya tidak selalu tampak seperti serangan; ia dapat ditulis sebagai instruksi teknis yang mencoba meminta data rahasia atau tindakan eksternal.

Pertahanan utama bukan kalimat “abaikan instruksi jahat”. Pertahanan adalah desain berlapis: data eksternal dipisahkan dari instruksi, tool memiliki daftar izin sempit, parameter tool divalidasi server, tindakan sensitif memerlukan persetujuan, dan jejak audit disimpan. Uji sistem dengan dokumen yang memuat instruksi konflik. Jika sebuah agent dapat mengirim email atau mengubah data, kontrol otorisasinya harus tetap berlaku bahkan ketika model memberi alasan yang terdengar masuk akal.`,
  130: `Context engineering adalah disiplin memilih bukti yang tepat untuk satu keputusan. Ia meliputi seleksi dokumen, urutan informasi, ringkasan state, metadata, dan batas akses. Kesalahan umum adalah mengirim semua informasi yang tersedia. Konteks besar dapat meningkatkan biaya, menambah gangguan, dan membuat aturan penting tertutup oleh detail yang tidak relevan.

Mulailah dari pertanyaan pengguna. Informasi apa yang diperlukan untuk menjawabnya, versi mana yang berlaku, dan izin apa yang dimiliki pengguna? Untuk pertanyaan pembayaran kontrak, berikan klausul pembayaran dari kontrak aktif, status invoice terkait, serta instruksi jawaban yang didukung sumber. Jangan sertakan seluruh folder proyek hanya karena tersedia. Catat sumber dan alasan pemilihannya agar jawaban dapat dijelaskan serta diperbaiki.`,
  131: `RAG memisahkan pengetahuan yang berubah dari parameter model. Sistem mengambil bagian dokumen yang relevan saat pertanyaan diajukan, lalu meminta model menyusun respons berdasarkan bukti tersebut. Pola ini cocok untuk kebijakan, katalog, dokumentasi internal, atau data privat yang perlu diperbarui tanpa melatih ulang model.

Namun RAG memiliki dua masalah yang berbeda: apakah dokumen yang benar berhasil diambil, dan apakah model menggunakan dokumen itu dengan benar. Jawaban buruk dapat berasal dari retrieval, bukan generasi. Karena itu, ukur recall atau relevansi dokumen secara terpisah dari groundedness jawaban. Ketika tidak ada bukti memadai, desain yang baik mengizinkan sistem tidak menjawab atau meneruskan kasus kepada manusia.`,
  132: `Chunking menentukan unit pengetahuan yang akan dicari dan dikirim ke model. Potongan yang terlalu kecil dapat memisahkan aturan dari pengecualian. Potongan yang terlalu besar dapat membawa terlalu banyak gangguan dan menghabiskan context window. Tidak ada ukuran universal karena struktur dokumen dan jenis pertanyaan berbeda.

Gunakan struktur semantik bila memungkinkan. Sebuah prosedur sebaiknya menyimpan judul, prasyarat, langkah, pengecualian, dan metadata versi dalam satu unit yang cukup utuh. Tambahkan overlap hanya ketika hubungan antarbatas memang penting. Setelah memilih strategi, uji pertanyaan nyata: apakah potongan yang diambil mencakup bukti yang dibutuhkan tanpa memasukkan aturan yang sudah tidak berlaku?`,
  133: `Retrieval, reranking, dan metadata bekerja sebagai rantai bukti. Retrieval menghasilkan kandidat, metadata membatasi kandidat berdasarkan atribut seperti peran, lokasi, tanggal berlaku, atau izin, lalu reranking memilih konteks paling relevan untuk pertanyaan lengkap. Jika salah satu tahap lemah, model dapat menerima informasi yang salah walaupun mampu menulis jawaban dengan baik.

Evaluasi setiap tahap. Untuk pertanyaan pajak tahun berjalan, periksa apakah filter negara dan periode dilakukan sebelum pencarian luas, apakah dokumen benar masuk daftar kandidat, dan apakah reranker menaruhnya di bagian atas. Tampilkan sumber dan tanggal kepada pengguna ketika memungkinkan. Ini membantu audit sekaligus membuat sistem lebih jujur tentang dasar jawabannya.`,
  134: `Agent memberi model kemampuan memilih langkah dan tool dalam beberapa putaran. Kelebihan ini berguna ketika jalur kerja benar-benar bergantung pada informasi yang ditemukan selama proses. Namun kebebasan langkah juga memperbesar ruang kegagalan, biaya, dan risiko tindakan. Banyak tugas dapat diselesaikan lebih baik oleh workflow eksplisit yang urutannya sudah diketahui.

Sebelum membuat agent, tulis tujuan, daftar tool, batas langkah, kondisi berhenti, data yang boleh diakses, dan tindakan yang membutuhkan persetujuan. Uji terlebih dahulu dalam mode rencana, ketika agent hanya mengusulkan langkah tanpa menjalankannya. Jika sistem pemesanan rapat selalu mengikuti urutan cek kalender lalu minta konfirmasi, workflow deterministik lebih mudah dievaluasi. Pilih agent hanya ketika pemilihan langkah dinamis menghasilkan nilai yang nyata.`,
  135: `State menyimpan informasi yang dibutuhkan untuk menyelesaikan tugas saat ini. Memory menyimpan informasi lintas interaksi. Keduanya sering dicampur, padahal risiko dan tujuan keduanya berbeda. State perjalanan misalnya dapat berisi kota tujuan dan tanggal selama satu sesi; memory jangka panjang mungkin berisi preferensi format yang pengguna setujui untuk disimpan.

Setiap data tersimpan memerlukan alasan bisnis, masa retensi, kontrol akses, dan cara koreksi atau penghapusan. Jangan menjadikan seluruh riwayat percakapan sebagai memory default. Selain mahal, cara itu sulit dijelaskan dan dapat menyimpan data sensitif yang tidak relevan. Rancang memory sebagai fitur produk yang terlihat oleh pengguna, bukan sebagai tumpukan data tersembunyi.`,
  136: `Finetuning adalah keputusan untuk mengubah perilaku model melalui data contoh, bukan cara umum untuk menyelesaikan setiap masalah. Sebelum melatih, tim harus menunjukkan bahwa prompt, konteks, pemilihan model, atau perubahan alur kerja belum mencapai target. Jika masalah sebenarnya adalah dokumen tidak tersedia, finetuning tidak akan menggantikan RAG. Jika format masih bisa dipatuhi dengan schema dan validasi, pelatihan mungkin terlalu mahal.

Gunakan baseline yang jujur. Jalankan prompt terbaik pada model yang ada, ukur kualitasnya, lalu tetapkan perilaku khusus yang ingin diperbaiki. Misalnya, format ringkasan medis harus patuh pada struktur tertentu tanpa menurunkan ketepatan fakta. Kumpulkan data contoh legal dan ditinjau, pisahkan evaluasi, lalu bandingkan model hasil pelatihan dengan baseline pada kasus baru. Finetuning layak bila manfaatnya terukur dan biaya operasi dapat dijelaskan.`,
  137: `Kesiapan data lebih penting daripada jumlah data. Data untuk adaptasi harus memiliki asal yang dapat dijelaskan, hak penggunaan yang jelas, contoh yang relevan dengan tugas, serta pemisahan yang tegas antara data pelatihan dan data evaluasi. Percakapan historis sering mengandung jawaban lama, data pribadi, dan pola yang tidak seharusnya dipelajari model.

Lakukan audit sebelum melatih. Untuk setiap sumber, catat pemilik, izin, periode, tujuan, risiko data sensitif, dan alasan contoh dipilih. Ambil sampel untuk ditinjau manusia; periksa apakah jawaban target sesuai kebijakan dan apakah masukan mewakili kasus yang akan datang. Data yang bersih bukan hanya data tanpa karakter aneh. Data bersih adalah data yang legal, relevan, konsisten, dan tidak diam-diam membocorkan jawaban evaluasi.`,
  138: `Supervised finetuning mengajarkan pola melalui pasangan masukan dan keluaran target. Karena model belajar dari contoh, contoh harus menunjukkan bukan hanya jawaban yang ingin ditulis, tetapi juga kondisi ketika harus meminta klarifikasi, mengutip sumber, atau melakukan eskalasi. SFT sangat baik untuk format dan transformasi yang berulang, tetapi ia tidak menjamin fakta terbaru bila konteks sumber tidak diberikan.

Bayangkan tim membangun draf balasan pelanggan. Pilih jawaban senior yang telah disetujui, bersihkan data pribadi, dan simpan konteks kebijakan yang menjelaskan dasar jawabannya. Pisahkan contoh evaluasi yang tidak pernah terlihat saat pelatihan. Setelah model dilatih, uji variasi bahasa, pertanyaan ambigu, dan kasus di luar cakupan. Kesamaan gaya dengan target bukan ukuran tunggal; jawaban harus tetap benar, aman, dan dapat dioperasikan.`,
  139: `Preference optimization digunakan ketika tim dapat menjelaskan respons mana yang lebih baik dan mengapa. Berbeda dari SFT yang memberi satu jawaban target, pendekatan ini belajar dari perbandingan: respons A lebih dipilih daripada respons B menurut rubrik tertentu. Sinyal ini berguna untuk kualitas seperti kejelasan, keamanan, atau kepatuhan batas, tetapi mudah berubah menjadi selera pribadi jika alasan tidak didokumentasikan.

Rancang pasangan preferensi dengan dimensi yang dapat diaudit. Dua jawaban boleh sama-sama faktual, tetapi satu lebih baik karena menyebutkan ketidakpastian dan mengarahkan pengguna ke sumber resmi. Catat siapa penilainya, rubrik yang dipakai, serta contoh ketika penilai tidak sepakat. Evaluasi hasil optimasi terhadap set baru; jangan hanya membuktikan bahwa model memilih gaya yang serupa dengan data preferensi.`,
  140: `Parameter-efficient fine-tuning seperti LoRA berusaha menyesuaikan bagian kecil model sehingga eksperimen memerlukan memori dan komputasi lebih sedikit dibanding pelatihan penuh. Penghematan ini membantu tim bereksperimen, terutama saat model dasar besar. Namun teknik yang ringan tidak otomatis mempertahankan kualitas pada bahasa, domain, atau konteks panjang yang penting bagi aplikasi.

Bandingkan kandidat dengan baseline menggunakan tugas nyata. Catat memori, waktu pelatihan, biaya, ukuran artefak, latency, kualitas per kategori, dan kemudahan rollback. Bila adapter memperbaiki format tetapi menurunkan ketepatan bahasa Indonesia pada dokumen teknis, keputusan harus melihat dampak pengguna, bukan hanya biaya GPU. Teknik adaptasi adalah alat untuk memenuhi target produk, bukan tujuan itu sendiri.`,
  141: `Model merging atau penggabungan adaptasi dapat menjadi eksperimen yang menarik ketika tim memiliki beberapa perilaku target. Namun perilaku gabungan tidak selalu merupakan penjumlahan sederhana. Dua adaptasi yang baik secara terpisah dapat saling mengganggu pada instruksi panjang, format tertentu, atau domain berbeda. Karena itu, hasilnya harus diperlakukan sebagai kandidat baru yang belum terbukti.

Sebelum menggabungkan, tetapkan baseline untuk masing-masing model, konfigurasi gabungan, set evaluasi lintas kemampuan, dan kriteria rollback. Periksa bukan hanya skor rata-rata, tetapi kategori yang paling berisiko. Simpan konfigurasi persisnya agar eksperimen dapat diulang. Jika manfaat tidak jelas dibanding satu model yang lebih sederhana, pilih sistem yang lebih mudah dijelaskan dan dirawat.`,
  142: `Peta data menjawab pertanyaan yang harus dapat dijawab sebelum data masuk ke sistem: dari mana data berasal, siapa pemiliknya, klasifikasinya apa, untuk tujuan apa boleh dipakai, bagaimana data berpindah, dan kapan harus dihapus. Tanpa peta ini, tim dapat memasukkan folder yang mudah diakses tetapi tidak memiliki izin untuk digunakan dalam aplikasi AI.

Gambarkan aliran dari sumber hingga pengguna. Tandai titik ingest, transformasi, indeks, akses model, logging, dan penghapusan. Untuk setiap titik, tetapkan owner serta kontrol. Peta data tidak hanya membantu kepatuhan; ia juga mempercepat diagnosis ketika jawaban memakai dokumen salah atau data baru belum muncul. Data yang dapat ditelusuri lebih mudah diperbarui dan dipertanggungjawabkan.`,
  143: `Akuisisi data perlu didorong oleh kebutuhan tugas, bukan dorongan mengumpulkan sebanyak mungkin. Koleksi yang luas menambah biaya pemrosesan, risiko privasi, dan beban pembaruan. Mulailah dari sumber yang disetujui dan paling relevan, lalu perluas hanya jika evaluasi menunjukkan bahwa sistem kekurangan cakupan.

Untuk setiap sumber, dokumentasikan pemilik, izin, mekanisme akses, frekuensi pembaruan, kualitas yang diharapkan, dan kondisi penghentian pengambilan. Jika sumber berubah atau akses dicabut, pipeline harus mampu merespons. Pendekatan ini membuat akuisisi menjadi proses yang dapat diaudit. Sistem tidak hanya tahu apa yang dikumpulkan, tetapi juga mengapa data tersebut ada dan kapan ia tidak lagi layak dipakai.`,
  144: `Annotation mengubah contoh mentah menjadi sinyal yang dapat dipakai untuk melatih atau mengevaluasi. Tantangan utamanya bukan meminta orang memberi label, melainkan memastikan beberapa orang memahami label dengan cara yang cukup sama. Label seperti “aman”, “relevan”, atau “berkualitas” selalu membawa interpretasi bila tidak diberi batas dan contoh.

Panduan annotation yang baik berisi tujuan, definisi kelas, contoh positif dan negatif, kasus ambigu, serta jalur eskalasi. Uji panduan pada sampel kecil, bandingkan hasil antarannotator, lalu perbaiki sebelum skala diperbesar. Simpan alasan perubahan panduan. Ketika kualitas dataset dipertanyakan, tim harus dapat menelusuri bukan hanya label akhir, tetapi proses berpikir dan standar yang menghasilkan label tersebut.`,
  145: `Data sintetis dapat menambah variasi ketika kasus nyata langka, sensitif, atau belum cukup terwakili. Nilainya muncul bila sintesis menjawab kebutuhan yang jelas, misalnya variasi bahasa pengguna atau skenario edge case. Bahayanya muncul bila tim menggunakan data sintetis sebagai alasan untuk tidak memeriksa fakta, distribusi, atau bias yang dibawanya.

Gunakan siklus empat langkah: identifikasi celah, buat kandidat, audit kandidat, lalu ukur dampaknya pada evaluasi. Reviewer manusia atau aturan domain harus memeriksa fakta, label, privasi, dan kemiripan antarcontoh. Pisahkan data sintetis dari data asli dalam catatan provenance. Dengan begitu, tim dapat menilai apakah peningkatan kualitas datang dari variasi yang benar-benar membantu atau dari contoh yang hanya menyerupai pola lama.`,
  146: `Pemrosesan data adalah serangkaian keputusan yang dapat mengubah makna data. Normalisasi format, penghapusan duplikat, penyaringan PII, dan pemisahan dataset dilakukan agar sistem tidak belajar dari data yang salah atau memperoleh nilai evaluasi palsu. Transformasi yang tidak dicatat membuat hasil sulit direproduksi dan kesalahan sulit dilacak.

Rancang checklist processing: tipe file, bahasa, encoding, duplikasi, data sensitif, kualitas isi, aturan filtering, dan metode split. Untuk mencegah kebocoran, pertimbangkan pemisahan berdasarkan waktu, pengguna, atau sumber, bukan hanya baris acak. Simpan versi input dan catatan transformasi. Tujuannya bukan membuat dataset tampak rapi, melainkan memastikan ukuran kualitas mencerminkan kemampuan pada data yang belum pernah dilihat sistem.`,
  147: `Kualitas data mencakup relevansi, kebenaran, keberagaman, kebaruan, dan provenance. Kontaminasi evaluasi terjadi ketika contoh uji atau informasi yang sangat mirip sudah masuk ke pelatihan, indeks, atau model. Skor tinggi pada kondisi ini tidak membuktikan sistem mampu menangani kasus baru; ia bisa hanya mengingat pola yang pernah dilihat.

Audit set evaluasi secara khusus. Tanyakan apakah contoh berasal dari sumber publik yang terlalu populer, apakah ada duplikasi semantik dengan train set, dan apakah dokumen uji masih berlaku. Tambahkan kasus privat atau baru yang memiliki izin. Bila kontaminasi tidak dapat dihilangkan, nyatakan keterbatasannya ketika membaca skor. Kejujuran tentang batas evaluasi adalah syarat untuk mengambil keputusan produk yang benar.`,
  148: `Latency, throughput, dan biaya harus dibahas bersama karena pengguna mengalami ketiganya sebagai layanan. Latency menunjukkan waktu tunggu satu request, throughput menunjukkan kapasitas, dan biaya menunjukkan apakah fitur dapat dipertahankan saat penggunaan tumbuh. Mengurangi latency dengan model besar mungkin menaikkan biaya; batching dapat menaikkan efisiensi tetapi memperburuk waktu tunggu interaktif.

Tentukan target menurut pengalaman pengguna. Ukur bukan hanya rata-rata, tetapi p95 atau p99 untuk melihat pengguna yang paling lambat. Pecah biaya per fitur dan per kelas tugas, lalu kaitkan dengan manfaat. Jika asisten internal menghemat lima menit tetapi membutuhkan antrean panjang, mungkin desain alur kerja perlu diubah. Kinerja bukan pekerjaan akhir; ia adalah bagian dari keputusan produk sejak awal.`,
  149: `Model routing memilih model atau konfigurasi berdasarkan kompleksitas, risiko, biaya, dan kebutuhan kualitas. Tujuannya bukan selalu memakai model termurah, tetapi menggunakan kemampuan secukupnya dan mengeskalasi saat diperlukan. Router sendiri adalah komponen keputusan yang dapat salah, sehingga harus dievaluasi seperti sistem lain.

Kelompokkan tugas terlebih dahulu. Klasifikasi sederhana mungkin cukup memakai model ringan, sedangkan analisis kontrak atau kasus dengan keyakinan rendah dapat masuk ke jalur lebih kuat atau tinjauan manusia. Ukur kualitas rute, tingkat eskalasi, latency, dan biaya. Tambahkan fallback saat model pilihan gagal. Router yang baik memiliki alasan keputusan yang dapat dipantau; router yang tersembunyi hanya memindahkan ketidakpastian ke tempat lain.`,
  150: `Caching menghindari kerja berulang, tetapi harus mempertahankan batas privasi dan kebaruan. Pertanyaan kebijakan umum mungkin dapat di-cache dengan masa berlaku singkat. Ringkasan data pribadi tidak boleh dibagikan kepada request lain. Karena itu, desain cache harus memperhatikan key, pengguna atau tenant, masa berlaku, invalidasi, dan perubahan sumber.

Sebelum menambah cache, klasifikasikan respons: publik, per pengguna, atau tidak boleh disimpan. Tentukan kapan cache harus dibersihkan, misalnya ketika kebijakan berubah atau akses pengguna dicabut. Uji skenario kebocoran: apakah dua pengguna dengan pertanyaan sama dapat menerima data yang berbeda? Penghematan latency dan biaya hanya bernilai bila cache tidak menciptakan jawaban lama atau paparan data.`,
  151: `Batching, parallelism, dan antrean mengatur cara sistem memakai kapasitas terbatas. Memproses semua request sekaligus dapat membuat layanan eksternal kelebihan beban. Sebaliknya, antrean tanpa batas dapat membuat pengguna menunggu tanpa kepastian. Desain kapasitas membutuhkan batas konkurensi, prioritas, timeout, retry, dan komunikasi status.

Gambarkan alur request dari masuk hingga selesai. Tentukan tugas interaktif yang perlu prioritas, pekerjaan latar yang dapat dibatch, serta kondisi ketika request harus ditolak atau dijadwalkan ulang. Ukur bottleneck secara nyata; lebih banyak worker tidak membantu bila model provider menjadi batas utama. Ketika beban naik, sistem harus gagal secara terkendali dan memberi pengguna informasi yang jujur tentang apa yang terjadi.`,
  152: `Quantization dan optimasi model menukar sebagian representasi numerik atau struktur komputasi untuk mengurangi memori, latency, atau biaya. Dampaknya berbeda menurut model dan tugas. Penurunan kecil pada benchmark umum dapat berarti penurunan besar pada bahasa, format, atau domain khusus yang justru penting bagi pengguna.

Bandingkan baseline dan kandidat pada set evaluasi target, bukan hanya spesifikasi perangkat keras. Catat kualitas per kategori, latency, memori, error, kompatibilitas, dan biaya. Tentukan ambang yang tidak boleh dilewati. Bila penghematan hanya terlihat pada biaya tetapi meningkatkan kesalahan pada kontrak atau dokumen teknis, optimasi belum berhasil. Teknik performa harus tunduk pada definisi kualitas yang sama seperti perubahan model lain.`,
  153: `Budget guardrail dan capacity planning mengubah biaya dari kejutan menjadi batas operasional yang dapat dikelola. Aplikasi AI perlu mengetahui berapa biaya per fitur, per pengguna, dan per jalur model; kapan alarm dikirim; serta apa fallback ketika batas mendekat. Tanpa ini, peningkatan traffic atau loop agent dapat menghasilkan tagihan dan gangguan yang tidak dipahami tim.

Tetapkan budget harian atau bulanan, quota yang jelas, alarm sebelum batas tercapai, dan keputusan fallback. Fallback dapat berupa model lebih ringan, pembatasan panjang input, penundaan tugas batch, atau penonaktifan fitur mahal. Pastikan ada owner yang mengambil keputusan ketika alarm aktif. Guardrail yang baik tetap menjaga pengalaman inti sambil mencegah sistem menghabiskan sumber daya di luar nilai yang dihasilkan.`,
  154: `Arsitektur aplikasi AI memisahkan tanggung jawab agar sistem dapat diuji dan dirawat. Antarmuka menangani interaksi pengguna, API menegakkan autentikasi dan kontrak, orchestrator menyusun alur, gateway model mengelola provider, retrieval menyediakan konteks, sementara evaluasi dan observability memberi bukti perilaku. Pemisahan bukan berarti membuat sebanyak mungkin layanan; setiap komponen harus memiliki alasan dan batas yang jelas.

Mulailah dari arsitektur minimal lalu tuliskan kontraknya. Komponen mana yang boleh membaca dokumen, siapa yang memvalidasi tool call, di mana versi prompt disimpan, dan bagaimana request ditelusuri? Ketika sebuah jawaban salah, desain yang baik memungkinkan tim menentukan apakah masalah berasal dari akses, konteks, model, atau antarmuka tanpa membongkar semua kode.`,
  155: `Observability memungkinkan tim melihat perjalanan request secara aman: versi prompt, model, status retrieval, tool yang dipanggil, latency, biaya, dan error. Tanpa jejak yang terstruktur, insiden AI mudah berubah menjadi perdebatan tentang apa yang mungkin terjadi. Namun logging berlebihan juga dapat mengumpulkan data sensitif yang tidak perlu.

Rancang event menurut pertanyaan diagnosis. Untuk jawaban salah, tim mungkin perlu request ID, versi konfigurasi, dokumen mana yang dipilih, dan apakah validasi gagal. Masking data sensitif, retensi terbatas, dan kontrol akses harus dibangun bersama log. Observability yang baik memberi bukti cukup untuk memperbaiki sistem tanpa menjadikan log sebagai salinan tersembunyi dari seluruh percakapan pengguna.`,
  156: `Feedback pengguna hanya berguna bila dapat dihubungkan dengan konteks dan tindakan tim. Tombol suka atau tidak suka tanpa alasan sering tidak membedakan masalah fakta, gaya, akses dokumen, atau pengalaman antarmuka. Di sisi lain, meminta pengguna menulis evaluasi panjang pada setiap respons adalah beban yang tidak adil.

Tanyakan hal minimum yang membantu diagnosis, misalnya alasan pilihan: sumber salah, jawaban tidak relevan, terlalu panjang, atau masalah lain. Kaitkan sinyal itu dengan request yang telah disamarkan, lalu tetapkan owner serta jadwal tinjau. Setelah pola muncul, ubah menjadi kasus evaluasi atau eksperimen. Jelaskan kepada pengguna tujuan pengumpulan feedback dan perlakuan datanya agar partisipasi tidak menjadi pengambilan data tanpa konteks.`,
  157: `Monitoring kualitas memperhatikan perubahan dunia, bukan hanya status server. Dokumen dapat diperbarui, perilaku pengguna bergeser, provider mengganti model, dan distribusi pertanyaan berubah. Sistem dapat tetap online sambil memberi jawaban yang makin tidak relevan. Inilah alasan kualitas perlu dipantau sebagai sinyal berkelanjutan.

Tentukan perubahan yang paling mungkin memengaruhi fitur: coverage dokumen, tingkat retrieval kosong, eskalasi, feedback negatif, biaya per tugas, atau sampel groundedness berkala. Tetapkan baseline dan ambang investigasi. Ketika metrik berubah, jangan langsung menyalahkan model; periksa data, konfigurasi, akses, dan perubahan penggunaan. Monitoring yang baik memicu penyelidikan terarah sebelum keluhan menjadi insiden besar.`,
  158: `Incident response untuk aplikasi AI harus menjawab apa yang dilakukan ketika sistem melampaui batas. Insiden dapat berupa kebocoran data, tool call tidak semestinya, lonjakan hallucination, atau kegagalan provider. Rencana yang dibuat setelah kejadian biasanya terlambat. Tim perlu feature flag, kill switch, jalur komunikasi, owner on-call, dan bukti yang disimpan secara aman.

Tuliskan runbook yang praktis: pemicu insiden, tindakan pertama, cara membatasi atau mematikan fitur, cara rollback, siapa yang diberi tahu, dan bagaimana pengguna diinformasikan. Uji kill switch sebelum diperlukan. Bila agent memiliki hak menulis, pastikan hak itu dapat dinonaktifkan tanpa mematikan seluruh aplikasi. Respons yang baik memulihkan keselamatan terlebih dahulu, lalu mengumpulkan fakta untuk mencegah pengulangan.`,
  159: `Blueprint adalah cara menyatukan seluruh keputusan AI engineering ke dalam satu rencana yang dapat dikritik. Ia harus menyebut masalah dan pengguna, batas tugas, sumber data, pemilihan model, evaluasi, prompt atau konteks, performa, arsitektur, observability, feedback, serta prosedur insiden. Blueprint bukan dokumen untuk terlihat lengkap; ia adalah alat untuk menemukan asumsi yang belum diuji.

Mulailah dari rilis kecil yang dapat diukur. Nyatakan apa yang sistem tidak lakukan, siapa yang menyetujui tindakan berisiko, metrik keberhasilan, dan eksperimen berikutnya. Jika sebuah bagian belum diketahui, tulis sebagai risiko atau hipotesis, bukan sebagai janji. Dengan cara ini, capstone tidak menutup pembelajaran; ia mengubah seluruh bab menjadi rancangan sistem yang dapat dibangun, diuji, dan diperbaiki secara bertahap.`
};
