export type AiEngineeringChapterLecture = {
  title: string;
  body: string;
  questions: string[];
};

/* Original Indonesian teaching text following the supplied book's chapter workflow. */
export const aiEngineeringChapterLectures: Record<number, AiEngineeringChapterLecture> = {
  1: {
    title: "Pembukaan Bab 1 · Memilih masalah sebelum memilih model",
    body: "AI engineering dimulai jauh sebelum sebuah prompt ditulis. Pertanyaan pertama bukan ‘model apa yang paling canggih?’, melainkan ‘pekerjaan manusia apa yang ingin dibantu, untuk siapa, dan dengan konsekuensi seperti apa?’. Foundation model mampu mengubah, menjelaskan, dan menghasilkan bahasa atau konten lain. Namun kemampuan itu baru bernilai jika ditempatkan dalam alur kerja yang memiliki tujuan, data yang tepat, serta batas keputusan yang jelas.\n\nDalam bab ini, gunakan cara berpikir seorang perancang sistem. Bedakan tugas yang membutuhkan generasi atau pemahaman bahasa dari tugas yang cukup diselesaikan dengan aturan, pencarian, basis data, atau perbaikan pengalaman pengguna. Lalu ukur manfaatnya: seberapa sering tugas terjadi, berapa waktu yang dapat dihemat, seberapa mahal dampak jika respons salah, dan apakah manusia dapat meninjau atau membatalkan hasilnya. Urutan ini penting karena banyak proyek AI gagal bukan karena modelnya lemah, tetapi karena masalah yang dipilih tidak jelas atau risikonya diabaikan.\n\nEnam pelajaran pertama akan membawa Anda dari definisi masalah menuju keputusan awal tentang produk, model, data, pihak yang bertanggung jawab, dan bukti keberhasilan. Jangan terburu-buru memperluas fitur. Sistem kecil yang dapat diuji lebih bernilai daripada demo luas yang tidak dapat dijelaskan.",
    questions: ["Tugas siapa yang akan menjadi lebih cepat atau lebih baik?", "Bagian mana yang perlu dibantu AI, dan bagian mana harus tetap deterministik atau ditinjau manusia?", "Bukti apa yang akan menunjukkan bahwa manfaat sistem lebih besar daripada risikonya?"]
  },
  2: {
    title: "Pembukaan Bab 2 · Memahami perilaku foundation model sebelum mengandalkannya",
    body: "Untuk menggunakan foundation model secara bertanggung jawab, seorang builder tidak perlu menjadi peneliti model. Namun ia perlu memahami beberapa sifat kerja yang langsung memengaruhi desain produk. Model bahasa menghasilkan kelanjutan token berdasarkan probabilitas. Oleh sebab itu, respons dapat berubah, dapat terdengar meyakinkan tanpa bukti, dan sangat dipengaruhi oleh instruksi, konteks, serta pengaturan generasi yang diberikan.\n\nBab ini menjelaskan mengapa konteks adalah bagian inti dari aplikasi AI. Kapasitas konteks yang besar tidak berarti model otomatis menemukan fakta penting. Informasi harus dipilih, diberi struktur, dan dipisahkan berdasarkan peran: aturan sistem, data atau dokumen, serta permintaan pengguna. Pemahaman dasar tentang Transformer membantu Anda menyusun konteks secara lebih jelas, sedangkan pemahaman pretraining dan post-training mencegah Anda menganggap pengetahuan umum model sebagai sumber kebenaran untuk data internal atau informasi yang berubah.\n\nKeenam pelajaran berikut akan membahas prediksi token, context window, struktur Transformer, tahapan pelatihan, parameter generasi, dan hallucination. Tujuan akhirnya bukan menghafal istilah. Tujuannya adalah membuat Anda mampu menanyakan: bukti apa yang dipakai model, variabel apa yang dapat mengubah jawabannya, dan kapan sistem harus menyatakan bahwa ia tidak tahu.",
    questions: ["Apa perbedaan antara keluaran yang lancar dan keluaran yang didukung bukti?", "Informasi apa yang harus selalu masuk ke konteks aplikasi?", "Bagaimana aplikasi harus bersikap ketika model tidak memiliki dasar untuk menjawab?"]
  },
  3: {
    title: "Pembukaan Bab 3 · Menentukan arti kualitas sebelum mengoptimalkan sistem",
    body: "Evaluasi adalah cara sebuah tim menerjemahkan kata seperti ‘bagus’, ‘aman’, atau ‘berguna’ menjadi bukti yang dapat diperiksa. Tanpa evaluasi, diskusi produk mudah didominasi oleh contoh paling menarik dan perubahan sistem menjadi sulit dibandingkan. Dalam aplikasi AI, satu angka jarang cukup. Jawaban dapat fasih tetapi tidak relevan, formatnya benar tetapi tidak aman, atau terlihat akurat pada contoh mudah namun gagal ketika pengguna memakai bahasa yang berbeda.\n\nBab ini membangun fondasi evaluasi: memilih kasus uji yang mewakili penggunaan nyata, menentukan metrik yang benar-benar bermakna, menulis rubrik penilaian manusia, memakai AI sebagai penilai dengan skeptis, dan melakukan analisis kesalahan. Perhatikan urutannya. Dataset evaluasi memberi bahan, metrik dan rubrik memberi cara mengukur, lalu error analysis menjelaskan apa yang harus diperbaiki.\n\nDi akhir bab, Anda seharusnya dapat menolak klaim ‘model ini lebih baik’ bila tidak ada definisi kualitas, set uji, atau bukti tentang tipe kegagalan yang tersisa.",
    questions: ["Kualitas apa yang paling menentukan manfaat bagi pengguna?", "Kasus gagal apa yang tidak boleh tersembunyi di balik nilai rata-rata?", "Siapa yang dapat menilai kualitas ketika jawaban tidak memiliki satu jawaban benar?"]
  },
  4: {
    title: "Pembukaan Bab 4 · Mengubah evaluasi menjadi kebiasaan rekayasa",
    body: "Setelah kriteria kualitas diketahui, langkah berikutnya adalah membuat evaluasi dapat diulang. Evaluation pipeline menghubungkan dataset, versi prompt, model, parameter, metrik, keluaran sampel, dan keputusan rilis. Tanpa jejak ini, tim hanya melihat skor yang berubah tanpa tahu perubahan mana yang menyebabkannya.\n\nBab ini memisahkan dua lingkungan. Evaluasi offline digunakan sebelum rilis untuk membandingkan konfigurasi dalam kondisi terkontrol. Evaluasi online mengamati apakah sistem benar-benar membantu pengguna setelah dipakai. Keduanya diperlukan: offline mencegah regresi yang jelas, sedangkan online menunjukkan dampak alur kerja yang tidak terlihat pada dataset statis.\n\nPusat pembelajarannya adalah disiplin eksperimen. Ubah variabel seperlunya, simpan bukti, tentukan ambang rilis menurut risiko, dan jadikan setiap insiden sebagai regression test. Dengan demikian, peningkatan tidak sekadar terasa lebih baik; peningkatan dapat dipertanggungjawabkan.",
    questions: ["Bisakah hasil hari ini diulang oleh anggota tim lain?", "Ambang apa yang harus dipenuhi sebelum sistem bertemu pengguna?", "Sinyal online apa yang dapat membantah hasil offline yang tampak baik?"]
  },
  5: {
    title: "Pembukaan Bab 5 · Prompt sebagai spesifikasi perilaku dan batas sistem",
    body: "Prompt engineering bukan kegiatan mencari kalimat ajaib. Ia adalah proses menyatakan tujuan, batas peran, konteks, contoh, format, dan kondisi penolakan dengan cukup jelas sehingga perilaku model dapat diuji. Prompt yang baik selalu bekerja bersama komponen lain: model yang dipilih, data yang tersedia, validasi keluaran, dan aturan aplikasi.\n\nBab ini bergerak dari spesifikasi dasar menuju risiko keamanan. System instruction memiliki otoritas berbeda dari input pengguna dan dokumen eksternal. Few-shot example dapat memperjelas pola, tetapi juga dapat membawa bias. Structured output membantu integrasi, tetapi hasilnya tetap harus divalidasi program. Pada saat yang sama, prompt injection mengingatkan bahwa teks tidak tepercaya dapat mencoba mengubah perilaku sistem.\n\nSetelah bab ini, Anda tidak hanya akan menulis prompt. Anda akan mampu memberi versi pada prompt, mengevaluasinya, dan membangun pertahanan yang tidak bergantung pada janji model untuk selalu patuh.",
    questions: ["Perilaku apa yang harus dinyatakan secara eksplisit?", "Data mana yang tidak boleh diberi otoritas sebagai instruksi?", "Validasi apa yang harus terjadi setelah model menghasilkan keluaran?"]
  },
  6: {
    title: "Pembukaan Bab 6 · Membangun konteks: RAG dan agent sebagai pola yang berbeda",
    body: "Kualitas respons bergantung pada instruksi, konteks, dan model. Setelah instruksi dibahas pada bab sebelumnya, bab ini berfokus pada cara memberikan informasi yang tepat untuk setiap pertanyaan. Retrieval-augmented generation atau RAG mengambil pengetahuan dari koleksi eksternal agar jawaban dapat memakai informasi yang berubah, bersifat privat, atau perlu disertai sumber.\n\nRAG bukan hanya menaruh dokumen ke prompt. Tim perlu memutuskan bagaimana dokumen dipecah, direpresentasikan, dicari, disaring dengan metadata, dan direrank. Setiap tahap dapat menghasilkan kegagalan berbeda. Agentic pattern memiliki tantangan lain: model dapat memilih tool dan langkah berikutnya, tetapi kebebasan tersebut meningkatkan kebutuhan akan batas tindakan, state, observability, serta evaluasi.\n\nGunakan pola paling sederhana yang menyelesaikan tugas. Workflow deterministik sering lebih baik ketika urutan tindakan sudah diketahui. Agent hanya layak ketika pemilihan langkah dinamis memang menghasilkan nilai yang tidak dapat dicapai dengan alur tetap.",
    questions: ["Apakah masalah utama adalah kekurangan informasi atau kekurangan kemampuan model?", "Bagaimana Anda mengetahui bahwa dokumen yang benar benar-benar diambil?", "Tindakan apa yang tidak boleh dilakukan agent tanpa persetujuan?"]
  },
  7: {
    title: "Pembukaan Bab 7 · Mengubah perilaku model secara hemat dan terukur",
    body: "Finetuning berarti menyesuaikan parameter model dengan contoh data agar perilaku target lebih konsisten. Ini adalah opsi yang kuat, tetapi bukan titik awal otomatis. Prompt, konteks yang lebih baik, pemilihan model, atau perubahan alur kerja sering memberi hasil yang lebih cepat dan lebih mudah dipelihara.\n\nBab ini membedakan beberapa bentuk adaptasi: supervised finetuning untuk contoh respons target, preference optimization untuk mengajarkan pilihan antarrespons, teknik hemat parameter seperti LoRA, serta eksperimen model merging. Semuanya memerlukan data yang legal, representatif, dan dipisahkan dari evaluasi. Teknik bukan pengganti definisi kualitas.\n\nKunci pembelajarannya adalah membuat baseline. Sebelum menilai finetuning, Anda harus mengetahui kemampuan sistem sebelumnya dan target perbaikan yang ingin dibuktikan. Jika manfaat tidak terukur, biaya data, komputasi, serta operasi sulit dibenarkan.",
    questions: ["Masalah apa yang tidak selesai dengan prompt dan konteks?", "Data contoh seperti apa yang benar-benar mengajarkan perilaku target?", "Metrik apa yang harus membaik agar adaptasi layak diteruskan?"]
  },
  8: {
    title: "Pembukaan Bab 8 · Memperlakukan data sebagai produk yang perlu direkayasa",
    body: "Data bukan bahan netral yang tinggal dikumpulkan. Untuk aplikasi AI, setiap sumber memiliki asal, izin, kualitas, kebaruan, risiko privasi, dan kemungkinan bias. Dataset yang besar tetapi tidak jelas asalnya dapat menciptakan masalah teknis, hukum, dan produk sekaligus.\n\nBab ini mengikuti aliran data dari akuisisi, annotation, synthesis, processing, deduplication, hingga pemeriksaan kontaminasi evaluasi. Annotation membutuhkan pedoman serta kalibrasi agar label yang dihasilkan konsisten. Data sintetis dapat menutup variasi tertentu, tetapi harus diaudit karena dapat mewarisi kesalahan pembangkitnya. Pemisahan train, validation, dan evaluation menjaga agar ukuran kualitas tetap jujur.\n\nSetelah bab ini, Anda seharusnya dapat menjelaskan bukan hanya berapa banyak data yang dipakai, tetapi dari mana data itu datang, mengapa layak digunakan, perubahan apa yang dialami, dan apa yang belum terwakili.",
    questions: ["Apakah setiap sumber memiliki izin dan tujuan penggunaan yang jelas?", "Bagaimana label dijaga konsisten antarpenilai?", "Bagaimana Anda mencegah sistem tampak baik hanya karena pernah melihat data evaluasi?"]
  },
  9: {
    title: "Pembukaan Bab 9 · Mengelola latency, throughput, dan biaya sebagai keputusan produk",
    body: "Sistem AI yang berkualitas tetapi terlalu lambat atau terlalu mahal belum tentu dapat dipakai. Bab ini membahas inference sebagai gabungan keputusan model dan keputusan layanan. Latency menggambarkan waktu tunggu satu pengguna, throughput menggambarkan kapasitas, sedangkan biaya menentukan apakah nilai produk dapat dipertahankan ketika penggunaan meningkat.\n\nStrateginya meliputi model routing, caching, batching, parallelism, quantization, dan budget guardrail. Masing-masing membawa trade-off. Cache dapat mempercepat tetapi berisiko memberi jawaban lama. Quantization mengurangi kebutuhan memori tetapi harus diuji pada tugas target. Batching menaikkan efisiensi tetapi dapat memperpanjang tunggu pengguna interaktif.\n\nTujuannya bukan membuat sistem paling murah secara abstrak. Tujuannya adalah memenuhi batas layanan yang disepakati tanpa menurunkan kualitas, keamanan, atau kemampuan pulih ketika permintaan meningkat.",
    questions: ["Pengguna mana yang paling terdampak oleh latency tinggi?", "Kualitas apa yang tidak boleh dikorbankan demi penghematan?", "Batas biaya dan kapasitas apa yang harus diterapkan sebelum skala naik?"]
  },
  10: {
    title: "Pembukaan Bab 10 · Menyatukan sistem, pengukuran, dan pembelajaran berkelanjutan",
    body: "Bab terakhir menyatukan keputusan dari seluruh perjalanan: use case, model, evaluasi, prompt, konteks, data, performa, arsitektur, dan feedback. Aplikasi AI produksi tidak berhenti ketika respons pertama berhasil. Dokumen berubah, perilaku pengguna bergeser, model provider diperbarui, dan risiko baru muncul. Sistem perlu dapat diamati, dikendalikan, dan diperbaiki.\n\nArsitektur yang sehat memisahkan tanggung jawab. Model dapat menyusun bahasa, tetapi aplikasi tetap memeriksa akses, validasi, parameter tool, dan dampak tindakan. Observability membantu tim melihat input yang aman, konteks yang terpilih, versi konfigurasi, langkah tool, keluaran, serta respons pengguna. Feedback harus dikaitkan dengan konteks agar menjadi bahan perbaikan, bukan sekadar angka suka atau tidak suka.\n\nPenutup bab ini adalah blueprint yang dapat dikritisi. Rencana yang baik menyebutkan asumsi yang belum terbukti, batas operasi, mekanisme kill switch, dan eksperimen berikutnya. Inilah cara membangun sistem yang dapat dirawat setelah demo selesai.",
    questions: ["Siapa yang bertanggung jawab ketika sistem memberi dampak yang salah?", "Sinyal apa yang menunjukkan kualitas mulai memburuk walau server tetap hidup?", "Bagaimana sistem dapat dihentikan atau dipulihkan secara aman?"]
  },
};
