import type { Material, MaterialLevel } from "./materials";
import { aiEngineeringTeachingContent } from "./aiEngineeringTeachingContent";
import { employeePolicyAssistantCaseStudy } from "./employeePolicyAssistantCaseStudy";
import { aiEngineeringChapterLectures } from "./aiEngineeringChapterLectures";

type LessonSeed = { id: number; chapter: number; title: string; level: MaterialLevel; minutes: number; focus: string; story: string; practice: string; caution: string; check: string; speedrun?: boolean };

const chapterNames: Record<number, string> = {
  1: "Memutuskan Apa yang Layak Dibangun",
  2: "Memahami Foundation Model",
  3: "Fondasi Evaluasi",
  4: "Evaluation Pipeline yang Andal",
  5: "Prompt Engineering dan Pertahanan",
  6: "Context Engineering, RAG, dan Agent",
  7: "Finetuning dan Adaptasi Model",
  8: "Data Engineering untuk AI",
  9: "Inference Cepat dan Hemat",
  10: "Sistem Produksi dan Feedback Loop",
};

const bookResource = { label: "AI Engineering — Chip Huyen (acuan utama)", url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/", note: "Gunakan buku sebagai peta konsep utama; materi ini menjelaskan ulang dengan contoh dan bahasa orisinal." };
const companionResource = { label: "Companion repository AI Engineering", url: "https://github.com/chiphuyen/aie-book", note: "Referensi resmi pendamping buku untuk sumber lanjutan dan latihan teknis." };
const speedrunResource = { label: "AI Engineering Speedrun (opsional)", url: "https://youtu.be/JV3pL1_mn2M", note: "Peta cepat untuk orientasi atau mengulang; bukan pengganti pembahasan utama dari PDF." };

const seeds: LessonSeed[] = [
  { id: 100, chapter: 1, title: "AI Engineering: Membawa Model ke Masalah Nyata", level: "Pemula", minutes: 11, focus: "AI engineering adalah proses mengubah kemampuan foundation model menjadi aplikasi yang berguna, dapat diuji, dan dapat dirawat—bukan sekadar membuat demo yang terlihat pintar.", story: "Dira punya demo chatbot yang keren di depan teman-temannya. Begitu dipakai tim support, jawabannya tidak konsisten dan tidak ada cara mengecek penyebabnya. Dari situ ia sadar: demo adalah awal, sistem yang bisa dipercaya adalah pekerjaan sebenarnya.", practice: "Pilih satu ide AI-mu lalu tulis siapa penggunanya, keputusan apa yang terbantu, dan apa yang terjadi kalau jawabannya salah.", caution: "Jangan menganggap model sebagai fitur ajaib; ia tetap bagian dari sistem dengan data, UI, batasan, biaya, dan pengguna.", check: "menghubungkan kemampuan model dengan masalah pengguna yang nyata" },
  { id: 101, chapter: 1, title: "Apakah Masalah Ini Benar-Benar Perlu AI?", level: "Pemula", minutes: 10, focus: "Sebelum memilih model, kamu perlu memastikan masalahnya memang membutuhkan penalaran atau generasi AI, bukan cukup diperbaiki dengan aturan, pencarian, data yang rapi, atau UX yang lebih jelas.", story: "Tim Raka ingin chatbot untuk menjawab pertanyaan jam operasional. Setelah melihat tiket, ternyata satu halaman FAQ yang rapi menyelesaikan mayoritas pertanyaan lebih cepat dan lebih murah.", practice: "Bandingkan tiga solusi untuk satu masalah: aturan sederhana, pencarian dokumen, dan AI generatif. Tulis kelebihan serta risikonya.", caution: "Jangan memaksakan AI hanya karena terdengar modern; solusi sederhana sering lebih mudah diaudit.", check: "menguji apakah AI adalah pilihan yang tepat untuk masalahnya" },
  { id: 102, chapter: 1, title: "Demo, Produk, dan Sistem: Tiga Level yang Berbeda", level: "Pemula", minutes: 11, focus: "Demo membuktikan kemungkinan, produk membantu pengguna menyelesaikan tugas, dan sistem produksi harus menangani kegagalan, perubahan data, keamanan, serta biaya.", story: "Nadia berhasil membuat ringkasan artikel dalam satu malam. Saat artikel berisi tabel panjang atau bahasa campuran, hasilnya mulai aneh. Ia lalu menambahkan batas input, pesan gagal yang jujur, dan evaluasi contoh sulit.", practice: "Ambil prototipe sederhana lalu tulis tiga hal yang harus ditambah agar layak dipakai pengguna sungguhan.", caution: "Jangan menyamakan satu hasil bagus dengan reliabilitas; lihat variasi kasus dan kondisi gagal.", check: "membedakan bukti demo dari kesiapan produk" },
  { id: 103, chapter: 1, title: "Memilih Use Case dari Nilai, Frekuensi, dan Risiko", level: "Pemula", minutes: 12, focus: "Use case yang baik punya manfaat yang jelas, cukup sering terjadi, data atau konteks yang memadai, serta risiko yang bisa dikendalikan ketika AI keliru.", story: "Bima ingin mengotomatisasi semua email. Setelah memetakan dampak, ia mulai dari merangkum tiket internal—berguna, sering dilakukan, dan masih diperiksa manusia.", practice: "Nilai satu use case dari dampak pengguna, frekuensi, data yang tersedia, kemungkinan salah, dan reversibilitas tindakan.", caution: "Mulai dari tindakan yang mudah dibatalkan sebelum memberi sistem akses untuk bertindak besar.", check: "memilih use case dengan nilai dan risiko yang seimbang" },
  { id: 104, chapter: 1, title: "Pakai API, Model Terbuka, atau Bangun Sendiri?", level: "Menengah", minutes: 13, focus: "Pilihan model dan cara hosting perlu mempertimbangkan kualitas, data, privasi, latency, biaya, kontrol, serta kemampuan tim untuk mengoperasikannya.", story: "Untuk asisten dokumen publik, tim Sita memakai API agar cepat belajar. Untuk data internal yang ketat, mereka menguji opsi lain dengan persetujuan keamanan, bukan langsung memindahkan semua beban ke server sendiri.", practice: "Buat matriks sederhana: API komersial, model terbuka ter-host, dan model mandiri; isi kualitas, kontrol, biaya, dan beban operasi.", caution: "Model yang paling murah di awal bisa mahal jika butuh infrastruktur dan tim operasi yang belum siap.", check: "membandingkan cara memakai model berdasarkan trade-off" },
  { id: 105, chapter: 1, title: "Peta Stakeholder, Data, dan Definisi Sukses", level: "Menengah", minutes: 13, focus: "Aplikasi AI perlu kesepakatan tentang siapa pengguna, siapa pemilik risiko, data apa yang boleh dipakai, dan bukti apa yang menunjukkan fitur benar-benar membantu.", story: "Sebelum membuat copilot untuk sales, Maya mengajak sales, legal, security, dan ops. Mereka sepakat sumber data yang boleh dipakai serta kapan jawaban harus berubah menjadi draf, bukan aksi otomatis.", practice: "Tulis satu halaman berisi pengguna, owner, data yang diizinkan, larangan, metrik sukses, dan cara menghentikan fitur jika ada masalah.", caution: "Tidak ada definisi sukses yang berguna jika hanya berbunyi ‘jawabannya harus bagus’.", check: "menetapkan batas dan bukti sukses sejak awal" },

  { id: 106, chapter: 2, title: "Token dan Probabilitas: Kenapa Jawaban Bisa Berbeda", level: "Pemula", minutes: 12, focus: "Model bahasa menghasilkan token berdasarkan probabilitas; karena itu keluaran dapat berubah dan terdengar meyakinkan tanpa otomatis benar.", story: "Saat Niko bertanya dua kali dengan pertanyaan sama, jawabannya mirip tetapi tidak persis sama. Ia belajar bahwa model memilih kelanjutan yang mungkin, bukan membuka laci fakta.", practice: "Coba satu prompt pada pengaturan yang berbeda bila tersedia; catat bagian yang stabil, berubah, dan perlu diverifikasi.", caution: "Nada percaya diri bukan bukti kebenaran. Tetap cek sumber untuk klaim penting.", check: "memahami keluaran model sebagai prediksi probabilistik" },
  { id: 107, chapter: 2, title: "Context Window dan Batas Ingatan Kerja", level: "Pemula", minutes: 12, focus: "Context window menentukan banyaknya informasi yang dapat dipertimbangkan model dalam satu interaksi, tetapi kapasitas besar tidak otomatis membuat konteks relevan atau akurat.", story: "Rafi menempelkan dokumen panjang ke chat dan berharap jawaban sempurna. Beberapa bagian penting justru terlewat karena ia tidak memberi struktur, pertanyaan, atau prioritas konteks.", practice: "Ambil satu dokumen dan buat ringkasan tujuan, bagian penting, serta pertanyaan yang ingin dijawab sebelum mengirimnya ke model.", caution: "Jangan mengirim semua data hanya karena muat; pilih konteks yang relevan dan aman.", check: "menyiapkan konteks yang terarah sebelum meminta jawaban" },
  { id: 108, chapter: 2, title: "Transformer untuk Builder: Intuisi yang Cukup", level: "Menengah", minutes: 14, focus: "Kamu tidak harus menghitung seluruh matematika Transformer untuk membangun aplikasi, tetapi perlu memahami attention, urutan token, dan mengapa model peka terhadap cara konteks disusun.", story: "Lina melihat model gagal menghubungkan aturan di awal dengan pertanyaan di akhir. Setelah memahami bahwa perhatian dan posisi konteks memengaruhi hasil, ia mulai menyusun instruksi lebih jelas.", practice: "Tulis ulang satu prompt panjang menjadi bagian: peran, aturan, konteks, contoh, dan tugas pengguna.", caution: "Penjelasan arsitektur tidak menggantikan pengujian pada kasus pengguna sebenarnya.", check: "menghubungkan susunan konteks dengan perilaku model" },
  { id: 109, chapter: 2, title: "Pretraining, Post-Training, dan Preferensi Manusia", level: "Menengah", minutes: 14, focus: "Pretraining memberi pola umum, sedangkan post-training dan optimasi preferensi membantu model mengikuti instruksi, percakapan, serta harapan keamanan dengan lebih baik.", story: "Karin bertanya mengapa model yang sama bisa baik untuk kode tetapi canggung saat diberi instruksi ambigu. Ia memahami bahwa kemampuan dasar dan perilaku percakapan dibentuk oleh tahap berbeda.", practice: "Untuk fiturmu, pisahkan kemampuan yang dibutuhkan: pengetahuan umum, mengikuti format, gaya respons, dan batasan keamanan.", caution: "Post-training bukan jaminan model akan selalu mengikuti aturan, terutama pada input yang berlawanan atau tidak jelas.", check: "membedakan kemampuan dasar model dan perilaku yang diarahkan" },
  { id: 110, chapter: 2, title: "Parameter Generation: Mengatur Ragam tanpa Menebak", level: "Menengah", minutes: 13, focus: "Parameter seperti temperature, sampling, panjang keluaran, dan stop condition mengubah karakter generasi; pilihannya perlu diuji terhadap tugas, bukan disetel berdasarkan perasaan.", story: "Tim Adi menaikkan creativity untuk ringkasan faktual dan justru melihat detail makin melenceng. Mereka membuat preset berbeda untuk ringkasan, ideasi, dan ekstraksi.", practice: "Buat tiga set pengujian untuk tugas faktual, kreatif, dan format ketat; catat parameter serta hasilnya.", caution: "Menaikkan variasi bukan cara memperbaiki konteks atau data yang kurang.", check: "menghubungkan parameter generasi dengan kebutuhan tugas" },
  { id: 111, chapter: 2, title: "Hallucination sebagai Masalah Sistem, Bukan Sifat Ajaib", level: "Menengah", minutes: 15, focus: "Hallucination perlu dipahami dari kombinasi model, instruksi, konteks, tugas, dan cara aplikasi menampilkan hasil; mitigasinya biasanya berlapis.", story: "Chatbot Fira memberi nomor kebijakan yang tidak ada. Tim tidak hanya menyuruh model ‘jangan mengarang’, tetapi menambahkan sumber, jawaban tidak tahu, evaluasi groundedness, dan review kasus sensitif.", practice: "Ambil satu contoh jawaban salah lalu tandai kemungkinan sumbernya: prompt, konteks, retrieval, model, atau UI.", caution: "Jangan menyalahkan model saja; aplikasi yang tidak menunjukkan ketidakpastian juga ikut memperbesar risiko.", check: "menganalisis kegagalan faktual secara berlapis" },

  { id: 112, chapter: 3, title: "Evaluation Datang Sebelum Kamu Terlalu Jatuh Cinta pada Demo", level: "Pemula", minutes: 12, focus: "Evaluasi membuat tim menyepakati seperti apa respons yang berguna, aman, dan cukup baik sebelum perubahan model atau prompt semakin banyak.", story: "Tim Wulan senang dengan demo pertama. Ketika diminta menjelaskan ‘bagus itu seperti apa’, tiap orang memberi jawaban berbeda. Mereka lalu menulis rubrik kecil agar diskusinya punya pegangan.", practice: "Tulis tiga dimensi kualitas untuk fiturmu, misalnya benar, relevan, dan aman; beri contoh lulus serta gagal.", caution: "Jangan menunggu rilis untuk mulai evaluasi; biaya belajar dari kegagalan akan lebih mahal.", check: "mendefinisikan kualitas sebelum mengubah sistem" },
  { id: 113, chapter: 3, title: "Menyusun Dataset Evaluasi yang Representatif", level: "Pemula", minutes: 14, focus: "Dataset evaluasi harus mewakili tugas, variasi pengguna, kasus sulit, dan risiko penting—bukan hanya contoh yang membuat sistem tampak bagus.", story: "Ari menguji chatbot dengan pertanyaan yang ia tulis sendiri dan nilainya tinggi. Setelah memasukkan typo, bahasa campuran, dan pertanyaan ambigu dari pengguna, kelemahan sebenarnya mulai terlihat.", practice: "Kumpulkan sepuluh contoh: normal, sulit, ambigu, out-of-scope, dan berisiko; beri label alasan tiap contoh masuk.", caution: "Pisahkan data evaluasi dari contoh yang dipakai untuk mengarahkan sistem agar hasil uji tidak menipu.", check: "memilih contoh uji yang mewakili dunia nyata" },
  { id: 114, chapter: 3, title: "Metrik: Apa yang Bisa Diukur dan Apa yang Harus Dinilai", level: "Menengah", minutes: 14, focus: "Metrik otomatis berguna untuk pola tertentu, tetapi tugas terbuka sering membutuhkan rubrik atau penilaian manusia agar kualitas tidak direduksi menjadi satu angka palsu.", story: "Tim Juno memakai similarity score untuk menilai ringkasan. Angkanya naik, tetapi pengguna tetap bingung karena struktur jawabannya buruk. Mereka menambah rubrik keterbacaan dan kelengkapan.", practice: "Untuk satu output, pilih mana yang dapat dihitung otomatis dan mana yang perlu rubrik manusia atau penilai AI.", caution: "Metrik nyaman belum tentu metrik yang benar-benar mewakili manfaat.", check: "memilih cara ukur sesuai jenis kualitas" },
  { id: 115, chapter: 3, title: "Human Evaluation: Menilai Tanpa Membuat Rubrik Kabur", level: "Menengah", minutes: 14, focus: "Penilaian manusia menjadi lebih berguna ketika tugas, rubrik, contoh batas, dan proses perbedaan penilai dirancang dengan jelas.", story: "Dua reviewer memberi nilai berbeda untuk jawaban yang sama. Bukan karena salah satu malas, tetapi karena kata ‘berguna’ tidak pernah didefinisikan. Tim lalu membuat contoh skor 1 sampai 4.", practice: "Buat rubrik empat tingkat untuk satu dimensi kualitas dan tulis satu contoh perilaku untuk tiap tingkat.", caution: "Jangan membebani reviewer dengan instruksi panjang yang tidak menghasilkan keputusan konsisten.", check: "membuat rubrik yang bisa dipakai lebih dari satu orang" },
  { id: 116, chapter: 3, title: "AI as Judge: Membantu Skala, Bukan Menghapus Skeptis", level: "Menengah", minutes: 15, focus: "Model dapat membantu menilai output dalam skala besar jika rubrik, prompt penilai, bias, dan perbandingan dengan penilaian manusia terus diperiksa.", story: "Maya memakai AI judge untuk ribuan jawaban. Ia tidak menelan skor mentah; ia mengambil sampel, membandingkannya dengan reviewer manusia, dan menelusuri jenis kasus ketika mereka tidak sepakat.", practice: "Tulis rubrik penilai AI untuk satu tugas, lalu pilih lima contoh yang wajib diperiksa manusia sebagai kontrol.", caution: "Penilai AI dapat membawa bias model dan mudah dipengaruhi format prompt bila tidak divalidasi.", check: "menggunakan AI judge dengan baseline dan audit manusia" },
  { id: 117, chapter: 3, title: "Error Analysis: Belajar dari Pola Gagal", level: "Menengah", minutes: 15, focus: "Error analysis mengubah tumpukan output buruk menjadi kategori kegagalan yang dapat diprioritaskan, diuji, dan diperbaiki satu per satu.", story: "Daripada berkata ‘chatbot sering salah’, Tim Kiki membuat label: konteks hilang, sumber salah, format rusak, menolak terlalu banyak, dan tidak tahu tapi tetap menjawab.", practice: "Ambil lima kegagalan lalu kelompokkan berdasarkan penyebab yang mungkin; pilih satu pola paling sering atau paling berisiko untuk diperbaiki dahulu.", caution: "Jangan memperbaiki satu contoh secara manual tanpa memeriksa apakah pola itu muncul lagi pada set evaluasi.", check: "mengubah kegagalan individual menjadi hipotesis sistem" },

  { id: 118, chapter: 4, title: "Dari Notebook ke Evaluation Pipeline", level: "Menengah", minutes: 14, focus: "Evaluation pipeline menyatukan dataset, konfigurasi, eksekusi, metrik, artefak, dan laporan agar perubahan dapat dibandingkan secara konsisten.", story: "Sebelumnya hasil uji tersimpan di chat dan spreadsheet berbeda. Saat prompt berubah, tidak ada yang yakin versi mana lebih baik. Pipeline kecil membuat eksperimen dapat diulang.", practice: "Gambar alur: dataset → versi prompt/model → run → skor/rubrik → contoh gagal → keputusan.", caution: "Pipeline yang rapi tidak perlu rumit; mulai dari artefak yang benar-benar membantu membandingkan perubahan.", check: "mencatat evaluasi sebagai proses yang dapat diulang" },
  { id: 119, chapter: 4, title: "Versioning Dataset, Prompt, Model, dan Konfigurasi", level: "Menengah", minutes: 14, focus: "Kamu perlu tahu kombinasi data, prompt, model, dan parameter mana yang menghasilkan suatu hasil agar perbaikan bisa dipercaya dan dikembalikan bila perlu.", story: "Hasil minggu ini memburuk, tetapi tim tidak tahu apa yang berubah. Setelah memberi nama versi prompt dan menyimpan parameter, mereka menemukan satu contoh few-shot terhapus.", practice: "Buat format nama run yang memuat tanggal, dataset, prompt, model, dan tujuan eksperimen.", caution: "Jangan menyimpan secret di metadata eksperimen atau log.", check: "menelusuri hasil ke konfigurasi yang menghasilkan" },
  { id: 120, chapter: 4, title: "Offline dan Online Evaluation: Dua Kacamata yang Saling Melengkapi", level: "Menengah", minutes: 15, focus: "Offline evaluation memberi kontrol sebelum rilis, sedangkan sinyal online menunjukkan apa yang benar-benar terjadi pada pengguna dan data aktual.", story: "Sistem Lala lulus set offline, tetapi pengguna nyata memakai istilah lokal yang tidak muncul di dataset. Tim kemudian menambahkan sampling log yang aman dan feedback di produk.", practice: "Tulis satu sinyal sebelum rilis dan satu sinyal setelah rilis untuk fiturmu; jelaskan kapan masing-masing dipakai.", caution: "Sinyal online harus mengutamakan privasi, persetujuan, dan minimisasi data.", check: "membedakan validasi sebelum dan sesudah pengguna nyata" },
  { id: 121, chapter: 4, title: "Threshold Rilis dan Keputusan Go/No-Go", level: "Menengah", minutes: 13, focus: "Keputusan rilis perlu ambang kualitas, daftar risiko yang tidak boleh lolos, owner keputusan, dan rencana rollback—bukan hanya rata-rata skor yang cantik.", story: "Skor keseluruhan assistant naik, tetapi satu kategori keamanan turun. Karena sudah ada threshold per risiko, tim menunda rilis dan memperbaiki bagian itu.", practice: "Tentukan tiga syarat rilis: kualitas minimum, kegagalan terlarang, dan sinyal teknis yang harus sehat.", caution: "Rata-rata dapat menyembunyikan kegagalan serius pada kelompok kecil tetapi penting.", check: "membuat keputusan rilis berdasarkan kriteria eksplisit" },
  { id: 122, chapter: 4, title: "Regression Test untuk Perubahan Kecil yang Berdampak", level: "Menengah", minutes: 14, focus: "Regression test menjaga kasus penting agar tidak rusak saat kamu mengubah prompt, retrieval, model, atau UI untuk memperbaiki bagian lain.", story: "Setelah menambah gaya ramah, assistant jadi gagal mengikuti format JSON. Tim menambahkan kasus format ketat ke suite regresi agar kegagalan itu muncul sebelum deploy.", practice: "Pilih lima kasus yang tidak boleh rusak dan jadikan mereka tes wajib setiap kali konfigurasi berubah.", caution: "Suite yang terlalu besar tetapi tidak dipelihara bisa menjadi alarm bising; utamakan kasus bernilai tinggi.", check: "melindungi perilaku penting dari perubahan berikutnya" },
  { id: 123, chapter: 4, title: "Checkpoint Speedrun: Loop Eksperimen yang Sehat", level: "Menengah", minutes: 12, focus: "Sebagai recap cepat, eksperimen yang sehat mengubah satu hal, menjalankan evaluasi, membaca contoh gagal, lalu memutuskan langkah berikutnya berdasarkan bukti.", story: "Jangan mengubah model, prompt, dan chunking sekaligus. Jika hasilnya berubah, tim tidak dapat mengetahui sumber perbaikannya.", practice: "Rancang satu eksperimen kecil: hipotesis, satu perubahan, metrik, contoh yang dibaca manual, dan keputusan jika hasil tidak naik.", caution: "Video speedrun berguna untuk mengingat peta, tetapi keputusan produksi tetap membutuhkan evaluasi yang lebih dalam.", check: "mengubah satu variabel dan belajar dari hasilnya", speedrun: true },

  { id: 124, chapter: 5, title: "Prompt sebagai Kontrak Kerja, Bukan Mantra", level: "Pemula", minutes: 12, focus: "Prompt yang baik menjelaskan tugas, batas, konteks, format, dan cara menangani ketidakpastian sehingga aplikasi memiliki perilaku yang lebih dapat diprediksi.", story: "Dion hanya menulis ‘buat ringkasan bagus’. Ketika hasil tidak konsisten, ia memperjelas pembaca, panjang, struktur, sumber, dan apa yang harus dilakukan saat informasi tidak cukup.", practice: "Ambil prompt pendekmu lalu tambahkan tujuan, audiens, format keluaran, batasan, dan contoh kasus tidak cukup data.", caution: "Tidak ada prompt sakti; kualitas tetap bergantung pada model, konteks, dan evaluasi.", check: "menulis instruksi yang dapat diuji" },
  { id: 125, chapter: 5, title: "System Instruction, User Input, dan Batas Peran", level: "Menengah", minutes: 13, focus: "Memisahkan instruksi sistem, input pengguna, konteks dokumen, dan hasil tool membantu aplikasi memahami apa yang harus diprioritaskan dan apa yang perlu diperlakukan sebagai data.", story: "Saat dokumen RAG memuat kalimat menyuruh model mengabaikan aturan, aplikasi Fano tetap memperlakukannya sebagai isi dokumen, bukan instruksi aplikasi.", practice: "Petakan empat zona pada prompt-mu: aturan sistem, input pengguna, konteks tepercaya, dan data tidak tepercaya.", caution: "Pemisahan teks membantu, tetapi keputusan sensitif tetap harus divalidasi kode aplikasi.", check: "membedakan instruksi aplikasi dari data eksternal" },
  { id: 126, chapter: 5, title: "Zero-Shot, Few-Shot, dan Contoh yang Tidak Menjebak", level: "Menengah", minutes: 14, focus: "Contoh dapat mengarahkan format dan gaya, tetapi contoh yang sempit atau terlalu mirip evaluasi dapat membuat sistem tampak lebih baik daripada kemampuan sebenarnya.", story: "Untuk ekstraksi invoice, Lia menambahkan tiga contoh dengan format berbeda. Hasilnya membaik, tetapi ia tetap menyimpan contoh uji lain agar tidak hanya menghafal pola.", practice: "Buat dua contoh representatif dan satu contoh batas; pisahkan contoh prompt dari set evaluasi.", caution: "Few-shot bukan alasan untuk memasukkan data rahasia atau contoh pengguna tanpa izin.", check: "memakai contoh untuk memperjelas tugas tanpa mencemari evaluasi" },
  { id: 127, chapter: 5, title: "Structured Output dan Validasi di Aplikasi", level: "Menengah", minutes: 14, focus: "Meminta schema keluaran membantu integrasi, tetapi aplikasi tetap wajib memvalidasi field, tipe, izin, dan dampak sebelum melakukan aksi.", story: "Model mengusulkan function call untuk refund. Server tidak langsung menjalankan: ia memeriksa ID, status order, batas nilai, dan hak pengguna terlebih dahulu.", practice: "Tentukan schema sederhana untuk satu keluaran lalu tulis validasi server yang harus lolos sebelum aksi dijalankan.", caution: "JSON yang valid secara bentuk belum tentu aman atau benar secara bisnis.", check: "membedakan format keluaran dan otorisasi tindakan" },
  { id: 128, chapter: 5, title: "Prompt Versioning dan Experiment Tracking", level: "Menengah", minutes: 13, focus: "Prompt adalah artefak produk yang perlu diberi versi, diuji, direview, dan dihubungkan dengan hasil evaluasi seperti perubahan kode lain.", story: "Satu kalimat instruksi berubah di malam hari dan kualitas pagi berikutnya turun. Karena prompt diberi versi, tim dapat melihat diff dan kembali ke konfigurasi stabil.", practice: "Simpan prompt dalam file atau penyimpanan terkelola; beri nama, tujuan, owner, tanggal, dan link ke hasil evaluasi.", caution: "Jangan menyimpan API key atau data pengguna mentah dalam prompt yang ikut masuk version control.", check: "memperlakukan prompt sebagai artefak yang dapat ditelusuri" },
  { id: 129, chapter: 5, title: "Prompt Injection dan Defense in Depth", level: "Lanjut", minutes: 16, focus: "Prompt injection muncul ketika data tidak tepercaya mencoba memengaruhi perilaku model; pertahanannya memerlukan izin minimum, isolasi tool, validasi, dan approval—bukan hanya instruksi tambahan.", story: "Satu halaman web memerintahkan agent untuk mengirim semua catatan. Karena tool email dibatasi dan tindakan kirim memerlukan approval, percobaan itu tidak berubah menjadi kebocoran.", practice: "Buat tabel: sumber input, apakah tepercaya, tool yang bisa terkena dampak, validasi, dan apakah approval dibutuhkan.", caution: "Jangan menjadikan model sebagai penjaga terakhir untuk tindakan berisiko.", check: "membuat pertahanan berlapis terhadap input berbahaya" },

  { id: 130, chapter: 6, title: "Context Engineering: Memberi Model Bahan yang Tepat", level: "Pemula", minutes: 13, focus: "Context engineering memilih, menyusun, menyaring, dan memperbarui informasi yang diberikan ke model agar respons lebih berguna tanpa membanjiri konteks.", story: "Menempelkan seluruh folder ke prompt bukan context engineering. Tim Yani memilih kebijakan yang relevan, memberi tanggal dokumen, dan menyisakan ruang untuk pertanyaan pengguna.", practice: "Untuk satu pertanyaan, tulis informasi apa yang wajib ada, bermanfaat bila ada, dan sebaiknya tidak dikirim.", caution: "Konteks lebih banyak tidak selalu lebih baik; relevansi, kualitas, dan keamanan tetap utama.", check: "memilih konteks berdasarkan tugas dan risiko" },
  { id: 131, chapter: 6, title: "RAG: Kapan Retrieval Lebih Masuk Akal daripada Mengubah Model", level: "Menengah", minutes: 14, focus: "RAG cocok saat jawaban perlu memakai pengetahuan eksternal yang sering berubah, dapat dikutip, atau tidak layak ditanam permanen ke parameter model.", story: "Kebijakan HR berubah tiap bulan. Daripada melatih ulang model, tim mengambil dokumen terbaru, menunjukkan sumber, dan menjawab ‘belum ada rujukan’ bila retrieval gagal.", practice: "Pilih satu use case dan jawab: apakah pengetahuannya berubah, perlu sumber, memiliki izin akses, dan bisa dicari sebagai dokumen?", caution: "RAG bukan jaminan fakta; retrieval, dokumen, dan jawaban tetap perlu dievaluasi.", check: "memilih RAG ketika pengetahuan perlu diperbarui atau dikutip" },
  { id: 132, chapter: 6, title: "Chunking: Memecah Dokumen tanpa Memecah Makna", level: "Menengah", minutes: 14, focus: "Chunking menentukan unit informasi yang dicari dan diberikan ke model; potongan perlu cukup kecil untuk relevan tetapi cukup utuh untuk membawa konteks.", story: "Tim Sasa memecah PDF tiap 1.000 karakter. Jawaban sering kehilangan aturan yang ada tepat sebelum atau sesudah potongan. Mereka lalu mencoba batas berbasis bagian, overlap, dan metadata judul.", practice: "Ambil satu dokumen dan bandingkan potongan berdasarkan paragraf, heading, dan ukuran tetap; tulis risiko tiap cara.", caution: "Jangan memilih ukuran chunk dari contoh tunggal; ukur pada pertanyaan nyata.", check: "menilai trade-off antara detail dan konteks chunk" },
  { id: 133, chapter: 6, title: "Retrieval, Reranking, dan Metadata", level: "Menengah", minutes: 15, focus: "Kualitas RAG bergantung pada kemampuan menemukan konteks yang tepat, menyaring akses, memberi metadata, dan memilih bukti terbaik sebelum generasi.", story: "Hasil pencarian tim Rio sering mengambil dokumen lama. Mereka menambahkan tanggal, status dokumen, hak akses, dan reranking sehingga konteks lebih relevan sebelum dikirim ke model.", practice: "Buat skema metadata untuk tiga dokumen: sumber, tanggal, owner, audience, status, dan izin akses.", caution: "Jangan membiarkan retrieval melewati batas akses hanya agar jawaban terlihat lengkap.", check: "menggunakan metadata untuk meningkatkan relevansi dan kontrol" },
  { id: 134, chapter: 6, title: "Agentic Pattern: Kapan Loop dan Tool Memang Dibutuhkan", level: "Menengah", minutes: 15, focus: "Pola agentic berguna saat tugas membutuhkan langkah, observasi, atau tool yang berubah, tetapi kompleksitasnya harus lebih kecil daripada nilai yang diberikan.", story: "Untuk mencari satu kebijakan, RAG sudah cukup. Untuk membandingkan kalender, stok, dan dokumen lalu membuat draf rencana, tim melihat nilai pada loop ber-tool—dengan batas yang ketat.", practice: "Pilih tugas lalu tandai apakah cukup satu jawaban, retrieval, workflow deterministik, atau loop agent dengan tool.", caution: "Agent bukan upgrade otomatis; lebih banyak langkah juga berarti lebih banyak titik gagal.", check: "memilih pola agentic hanya saat nilainya jelas" },
  { id: 135, chapter: 6, title: "Memory, State, dan Batas Tool Agent", level: "Lanjut", minutes: 16, focus: "Agent perlu memisahkan konteks sesi, memory jangka panjang, hasil tool, dan izin agar ia tidak menyimpan terlalu banyak atau bertindak di luar tujuan.", story: "Asisten proyek dapat mengingat preferensi format, tetapi tidak perlu menyimpan semua isi percakapan selamanya. Tim membuat masa simpan, kontrol lihat-hapus, dan daftar tool yang boleh dipakai.", practice: "Buat tabel untuk agent: jenis state, alasan disimpan, masa simpan, siapa yang dapat mengakses, dan cara menghapusnya.", caution: "Memory bukan fitur gratis; ia membawa risiko privasi, biaya, dan konteks yang salah.", check: "mendesain state dan tool agent dengan batas eksplisit" },

  { id: 136, chapter: 7, title: "Kapan Finetuning Layak Dicoba?", level: "Menengah", minutes: 14, focus: "Finetuning layak dievaluasi ketika prompt dan context construction belum memenuhi pola perilaku yang stabil, sementara data berkualitas dan cara mengukurnya sudah tersedia.", story: "Setelah berulang kali gagal menjaga gaya klasifikasi yang spesifik, tim Han mengumpulkan contoh berkualitas dan membandingkan biaya finetuning dengan perbaikan prompt serta retrieval.", practice: "Tulis alasan mengapa prompt atau RAG belum cukup, data apa yang tersedia, dan metrik apa yang akan membuktikan finetuning membantu.", caution: "Jangan melakukan finetuning hanya karena model terasa kurang pintar tanpa mendiagnosis jenis kegagalannya.", check: "menentukan prasyarat sebelum eksperimen finetuning" },
  { id: 137, chapter: 7, title: "Data Readiness untuk Adaptasi Model", level: "Menengah", minutes: 14, focus: "Data untuk adaptasi model perlu relevan, legal digunakan, konsisten, cukup bervariasi, dan dipisahkan agar kemampuan baru dapat diuji dengan jujur.", story: "Tim Dini punya ribuan contoh, tetapi banyak duplikat dan aturan lama. Mereka lebih dulu membersihkan, mengecek izin, serta menyisihkan set uji sebelum mengubah model.", practice: "Audit satu kumpulan contoh dari asal, izin, format, kualitas, duplikasi, sampai pemisahan train dan evaluasi.", caution: "Jumlah data tidak memperbaiki data yang salah arah atau tidak punya hak penggunaan.", check: "menilai kesiapan data sebelum adaptasi" },
  { id: 138, chapter: 7, title: "Supervised Finetuning dengan Target Perilaku Jelas", level: "Menengah", minutes: 15, focus: "Supervised finetuning mengarahkan model melalui contoh input-output yang berkualitas, sehingga definisi target dan variasi contoh menjadi lebih penting daripada sekadar menjalankan framework.", story: "Untuk membuat asisten mengubah catatan menjadi format tertentu, tim memakai contoh yang memperlihatkan variasi input, kasus kosong, dan batas jawaban—bukan hanya contoh ideal.", practice: "Buat lima pasangan input-output yang mewakili kasus normal, variasi, batas, dan penolakan yang benar.", caution: "Contoh yang saling bertentangan akan mengajari perilaku yang membingungkan.", check: "menuliskan contoh pelatihan yang menargetkan perilaku spesifik" },
  { id: 139, chapter: 7, title: "Preference Optimization: Mengajar Pilihan yang Lebih Baik", level: "Lanjut", minutes: 15, focus: "Optimasi preferensi membandingkan respons yang lebih dan kurang diinginkan untuk memperkuat keputusan kualitas, tetapi kualitas label dan tujuan penilaian tetap kritis.", story: "Dua jawaban sama-sama faktual, tetapi satu lebih jelas menyatakan batas informasi. Reviewer memilih yang lebih aman dan menjelaskan alasannya agar sinyal preferensi tidak sekadar selera.", practice: "Buat tiga pasangan respons dan tulis alasan terukur mengapa salah satunya lebih baik menurut rubrik.", caution: "Preferensi manusia dapat bias; dokumentasikan siapa yang menilai dan dimensi apa yang dipakai.", check: "mengubah preferensi kualitas menjadi sinyal yang dapat diperiksa" },
  { id: 140, chapter: 7, title: "PEFT dan LoRA: Adaptasi dengan Sumber Daya Lebih Ringan", level: "Lanjut", minutes: 16, focus: "Teknik adaptasi parameter-efisien berusaha mengubah bagian kecil dari model untuk menekan kebutuhan memori dan komputasi dibanding mengubah seluruh parameter.", story: "Model besar terlalu berat untuk perangkat tim. Mereka mempelajari opsi adaptasi yang lebih ringan sambil tetap mengukur apakah hasilnya cukup untuk use case, bukan hanya kagum pada istilahnya.", practice: "Buat catatan trade-off antara kualitas target, memori, biaya eksperimen, waktu, dan kemampuan rollback.", caution: "Lebih ringan bukan otomatis lebih baik; evaluasi masih memutuskan apakah pendekatan layak.", check: "menghubungkan teknik adaptasi dengan batas sumber daya" },
  { id: 141, chapter: 7, title: "Model Merging dan Eksperimen yang Harus Dipagari", level: "Lanjut", minutes: 15, focus: "Menggabungkan model atau adaptasi dapat menjadi eksperimen menarik, tetapi perilakunya perlu diuji secara disiplin karena hasil gabungan tidak selalu intuitif.", story: "Tim mencoba menggabungkan dua adaptasi: satu untuk format dan satu untuk bahasa. Hasilnya membaik pada satu set tetapi gagal pada instruksi panjang, sehingga mereka kembali ke evaluasi per kategori.", practice: "Sebelum eksperimen gabungan, tetapkan baseline, set evaluasi, kriteria rollback, dan catatan konfigurasi.", caution: "Jangan mempromosikan hasil eksperimen ke produksi tanpa bukti lintas kasus penting.", check: "membuat eksperimen adaptasi yang dapat dibandingkan dan dibatalkan" },

  { id: 142, chapter: 8, title: "Peta Data: Asal, Izin, dan Aliran", level: "Pemula", minutes: 13, focus: "Data engineering dimulai dengan mengetahui data berasal dari mana, siapa pemiliknya, hak penggunaannya, bagaimana ia bergerak, dan kapan ia harus dihapus.", story: "Sebelum mengumpulkan dokumen untuk asisten, Fia menggambar sumber, owner, klasifikasi, izin, dan tujuan. Peta itu mengungkap satu folder pribadi yang seharusnya tidak masuk pipeline.", practice: "Gambar aliran data dari sumber ke aplikasi; beri label owner, sensitivitas, dan aturan retensi.", caution: "Data yang mudah diakses belum tentu boleh dipakai untuk aplikasi AI.", check: "memetakan provenance dan izin data" },
  { id: 143, chapter: 8, title: "Data Acquisition: Mengumpulkan Tanpa Mengumpulkan Sembarangan", level: "Menengah", minutes: 14, focus: "Akuisisi data perlu tujuan, metode, dokumentasi, dan pemeriksaan legal atau privasi agar koleksi tidak berubah menjadi gudang data yang tak dapat dipertanggungjawabkan.", story: "Tim Aji ingin menyalin seluruh knowledge base. Mereka memulai dari koleksi kecil yang disetujui, mencatat versi, lalu memperluas hanya setelah melihat bukti kebutuhan.", practice: "Untuk satu sumber, tulis tujuan, owner, izin, frekuensi pembaruan, risiko, dan kondisi penghentian pengambilan data.", caution: "Jangan mengambil data personal atau berlisensi dengan asumsi nanti bisa dibereskan.", check: "mengumpulkan data dengan tujuan dan akuntabilitas" },
  { id: 144, chapter: 8, title: "Annotation: Mengubah Contoh Menjadi Sinyal yang Konsisten", level: "Menengah", minutes: 14, focus: "Annotation yang baik memiliki definisi label, panduan, contoh ambigu, dan proses pemeriksaan agar beberapa orang dapat memberi sinyal yang cukup konsisten.", story: "Tiga annotator memberi label berbeda pada jawaban ‘aman’. Setelah membahas contoh batas dan memperjelas definisi, kesepakatan mereka meningkat.", practice: "Tulis panduan label satu halaman: tujuan, kelas, contoh positif-negatif, kasus ambigu, dan jalur eskalasi.", caution: "Label yang tampak mudah tetap membawa asumsi; uji panduan pada sampel sebelum memberi tugas besar.", check: "mendesain annotation guideline yang dapat digunakan ulang" },
  { id: 145, chapter: 8, title: "Data Synthesis: Membantu Variasi dengan Audit", level: "Menengah", minutes: 15, focus: "Data sintetis dapat membantu menambah variasi atau menutup celah, tetapi perlu ditinjau agar tidak mengulang bias, kesalahan, atau contoh yang terlalu mirip satu sama lain.", story: "Untuk kasus edge, tim memakai model membuat kandidat contoh lalu reviewer memeriksa label, fakta, dan keberagaman sebelum menambahkannya ke dataset.", practice: "Buat proses empat langkah: kebutuhan data, generasi kandidat, pemeriksaan manusia atau aturan, dan evaluasi dampaknya.", caution: "Data sintetis bukan jalan pintas untuk tidak memahami domain atau kualitas data asli.", check: "menggunakan sintesis data dengan review dan tujuan jelas" },
  { id: 146, chapter: 8, title: "Processing, Deduplication, dan Pemisahan Dataset", level: "Menengah", minutes: 15, focus: "Pemrosesan data mencakup normalisasi, deduplikasi, filtering, dan pemisahan train-eval agar dataset dapat dipakai tanpa kebocoran yang membuat evaluasi tampak palsu.", story: "Saat contoh hampir sama muncul di train dan eval, model tampak hebat. Setelah duplikat dibersihkan dan data dipisah berdasarkan sumber atau waktu, hasilnya lebih jujur.", practice: "Tulis checklist processing: format, bahasa, duplikasi, PII, kualitas, split, dan catatan perubahan.", caution: "Jangan menghapus data tanpa jejak; simpan alasan transformasi dan versi input.", check: "mencegah kebocoran serta duplikasi pada dataset" },
  { id: 147, chapter: 8, title: "Kualitas Data dan Kontaminasi Evaluasi", level: "Lanjut", minutes: 16, focus: "Kualitas data perlu dinilai dari relevansi, kebenaran, keberagaman, kebaruan, dan risiko kontaminasi—terutama ketika contoh uji mungkin sudah pernah dilihat model atau masuk data latihan.", story: "Tim menemukan skor eval tinggi tetapi contoh uji banyak berasal dari sumber publik populer. Mereka menambah contoh privat yang diizinkan dan memeriksa kemiripan agar hasil lebih dapat dipercaya.", practice: "Pilih satu dataset evaluasi lalu nilai relevansi, kualitas label, kebaruan, duplikasi, akses, dan risiko kontaminasinya.", caution: "Skor tinggi pada set yang tercemar tidak membuktikan sistem siap menghadapi kasus baru.", check: "menilai kualitas dan kejujuran set evaluasi" },

  { id: 148, chapter: 9, title: "Latency, Throughput, dan Biaya: Tiga Angka yang Harus Berteman", level: "Pemula", minutes: 14, focus: "Pengalaman aplikasi AI dipengaruhi waktu respons, kapasitas menangani request, dan biaya; mengoptimalkan satu angka dapat memperburuk angka lain.", story: "Asisten cepat saat sepi tetapi lambat saat banyak pengguna. Tim melihat bukan hanya waktu rata-rata, melainkan antrian, p95 latency, dan biaya per tugas.", practice: "Tulis target untuk satu fitur: waktu respons wajar, volume request, dan batas biaya; jelaskan trade-off jika satu target diutamakan.", caution: "Rata-rata latency dapat menyembunyikan pengalaman buruk pengguna paling lambat.", check: "menilai trade-off performa dan biaya" },
  { id: 149, chapter: 9, title: "Model Routing: Memakai Kemampuan Secukupnya", level: "Menengah", minutes: 14, focus: "Model routing mengarahkan tugas ke model atau konfigurasi yang sesuai kualitas, risiko, latency, dan biaya alih-alih memakai satu model paling mahal untuk semuanya.", story: "Tim memilih model ringan untuk klasifikasi sederhana dan jalur eskalasi ke model lebih kuat ketika keyakinan rendah atau tugas kompleks.", practice: "Kelompokkan tiga tugas menurut dampak, kompleksitas, kebutuhan kualitas, dan model yang masuk akal untuk diuji.", caution: "Router sendiri perlu dievaluasi; salah rute dapat merusak kualitas atau membuat biaya melonjak.", check: "mencocokkan kemampuan model dengan kelas tugas" },
  { id: 150, chapter: 9, title: "Caching: Menghindari Kerja Ulang dengan Aman", level: "Menengah", minutes: 13, focus: "Caching dapat mengurangi latency dan biaya untuk hasil yang dapat dipakai ulang, tetapi key cache, masa berlaku, personalisasi, dan data sensitif harus dirancang hati-hati.", story: "Pertanyaan kebijakan umum bisa di-cache sebentar, tetapi ringkasan data pengguna tidak boleh dibagikan ke request lain. Tim membedakan cache publik dan cache per pengguna.", practice: "Untuk satu endpoint, tulis apa yang boleh di-cache, key-nya, TTL, kondisi invalidasi, dan risiko privasinya.", caution: "Cache yang salah dapat memberi informasi lama atau data orang lain.", check: "menentukan cache berdasarkan keamanan dan kebaruan" },
  { id: 151, chapter: 9, title: "Batching, Parallelism, dan Antrean", level: "Menengah", minutes: 15, focus: "Batching dan parallelism dapat meningkatkan utilisasi, tetapi perlu antrean, batas konkurensi, timeout, dan prioritas agar sistem tidak runtuh ketika beban naik.", story: "Saat semua request diproses bersamaan, layanan gagal total. Tim membuat antrean, batas concurrency, dan jalur prioritas untuk tugas interaktif.", practice: "Gambar alur request masuk, antrean, worker, timeout, retry, dan respons pengguna untuk satu layanan.", caution: "Lebih banyak paralelisme bukan selalu lebih cepat jika bottleneck berada pada model atau layanan eksternal.", check: "merancang kapasitas dengan batas kerja yang jelas" },
  { id: 152, chapter: 9, title: "Quantization dan Optimasi Model: Harga dari Penghematan", level: "Lanjut", minutes: 16, focus: "Optimasi seperti quantization dapat mengurangi kebutuhan memori dan biaya, tetapi kualitas, kompatibilitas, latency, serta stabilitas harus dibandingkan pada tugas target.", story: "Model yang lebih kecil membuat biaya turun, tetapi kualitas bahasa Indonesia pada dokumen teknis menurun. Tim tidak menganggap penghematan berhasil sebelum menguji set evaluasi yang relevan.", practice: "Buat tabel baseline dan kandidat: kualitas, latency, memori, biaya, error, dan keputusan penggunaan.", caution: "Jangan menerima penghematan jika ia melewati threshold kualitas atau keamanan.", check: "mengukur optimasi model terhadap kebutuhan aplikasi" },
  { id: 153, chapter: 9, title: "Budget Guardrail dan Capacity Planning", level: "Lanjut", minutes: 15, focus: "Aplikasi AI perlu batas biaya, quota, fallback, monitoring pemakaian, dan rencana kapasitas agar pertumbuhan penggunaan tidak berubah menjadi kejutan tagihan atau outage.", story: "Kampanye membuat traffic asisten naik tajam. Karena ada quota pengguna, alarm biaya, dan fallback, tim bisa menyesuaikan tanpa mematikan semua layanan.", practice: "Tentukan budget harian, quota, sinyal alarm, fallback saat batas mendekat, dan owner yang mengambil keputusan.", caution: "Jangan menyembunyikan biaya AI dalam satu angka bulanan; pecah per fitur dan per pola penggunaan.", check: "membuat pagar biaya serta kapasitas yang dapat dioperasikan" },

  { id: 154, chapter: 10, title: "Arsitektur Aplikasi AI: Komponen dan Kontraknya", level: "Pemula", minutes: 14, focus: "Aplikasi AI produksi biasanya memisahkan UI, API, orchestrator, model gateway, retrieval, data, evaluasi, observability, dan kontrol akses agar setiap bagian dapat diuji serta dirawat.", story: "Nina awalnya menaruh semua di satu script. Setelah pengguna bertambah, ia memisahkan jalur request, storage dokumen, logging, dan service model sehingga masalah dapat dilacak tanpa membongkar semuanya.", practice: "Gambar arsitektur minimal fiturmu: pengguna, API, model, data/konteks, log, evaluasi, dan batas akses.", caution: "Lebih banyak komponen bukan tujuan; setiap komponen harus punya alasan, owner, dan kontrak jelas.", check: "memetakan sistem AI sebagai komponen yang dapat dirawat" },
  { id: 155, chapter: 10, title: "Observability: Melihat Input, Langkah, dan Dampak", level: "Menengah", minutes: 15, focus: "Observability membantu tim menelusuri request, versi konfigurasi, retrieval, tool call, latency, biaya, dan error tanpa menyimpan lebih banyak data sensitif daripada yang diperlukan.", story: "Ketika jawaban salah, log terstruktur menunjukkan model benar-benar tidak menerima dokumen penting. Tim memperbaiki retrieval, bukan mengganti model secara membabi buta.", practice: "Pilih event yang perlu dicatat: request ID, versi prompt, model, status retrieval, latency, biaya, dan error; tandai field sensitif yang harus disamarkan.", caution: "Logging yang kaya tetap wajib tunduk pada privasi, retensi, dan kontrol akses.", check: "mendesain observability untuk diagnosis yang aman" },
  { id: 156, chapter: 10, title: "User Feedback yang Benar-Benar Bisa Dipakai", level: "Menengah", minutes: 14, focus: "Feedback berguna ketika pengguna tahu apa yang sedang dinilai, dapat memberi konteks, dan tim memiliki proses untuk menghubungkan sinyal tersebut ke perbaikan nyata.", story: "Tombol thumbs-down tanpa alasan menghasilkan sedikit pembelajaran. Tim menambahkan pilihan sebab, tempat komentar singkat, dan link request anonim ke contoh evaluasi setelah ditinjau.", practice: "Rancang satu mekanisme feedback: pertanyaan yang diajukan, data minimum, privasi, owner review, dan keputusan yang mungkin diambil.", caution: "Jangan menjadikan pengguna tenaga label gratis tanpa menjelaskan tujuan dan perlakuan data mereka.", check: "mengumpulkan feedback yang dapat berubah menjadi tindakan" },
  { id: 157, chapter: 10, title: "Monitoring Kualitas, Drift, dan Perubahan Dunia Nyata", level: "Menengah", minutes: 15, focus: "Sistem AI dapat memburuk ketika data, model provider, dokumen, pengguna, atau konteks bisnis berubah; monitoring perlu melihat kualitas, bukan hanya uptime.", story: "Asisten tetap online, tetapi jawaban HR makin sering salah setelah kebijakan baru ditambah. Tim memantau coverage dokumen, feedback, dan sampel evaluasi berkala untuk menangkap drift.", practice: "Tentukan tiga perubahan yang mungkin terjadi pada sistemmu dan sinyal yang memberi tahu bahwa kualitas perlu diperiksa lagi.", caution: "Uptime hijau tidak berarti pengguna menerima jawaban yang benar atau berguna.", check: "memantau perubahan yang memengaruhi kualitas sistem" },
  { id: 158, chapter: 10, title: "Incident Response dan Kill Switch", level: "Lanjut", minutes: 15, focus: "Aplikasi AI perlu rencana saat perilaku berisiko muncul: siapa yang diberi tahu, bagaimana fitur dibatasi, cara rollback, cara menyimpan bukti aman, dan cara mengabari pengguna.", story: "Agent tiba-tiba membuat draf yang tidak sesuai. Karena ada feature flag dan owner on-call, tim menghentikan tool write tanpa mematikan seluruh aplikasi, lalu memeriksa konfigurasi yang berubah.", practice: "Tulis runbook insiden dengan pemicu, tindakan awal, kill switch, owner, komunikasi, bukti yang disimpan, dan langkah pemulihan.", caution: "Jangan menunggu insiden pertama untuk menemukan bahwa tidak ada yang tahu cara mematikan fitur.", check: "menyiapkan respons ketika perilaku sistem melampaui batas" },
  { id: 159, chapter: 10, title: "Capstone: Blueprint Aplikasi AI yang Dapat Dipercaya", level: "Lanjut", minutes: 22, focus: "Capstone menyatukan keputusan use case, model, evaluasi, prompt, context, data, performa, arsitektur, dan feedback menjadi blueprint yang siap dikritisi serta dibangun bertahap.", story: "Ini bukan lomba membuat diagram paling rumit. Bima memilih satu asisten dokumen kecil, menentukan apa yang boleh dilakukan, cara mengukurnya, kapan berhenti, dan langkah rilis pertamanya.", practice: "Gunakan PRD Maker untuk membuat blueprint: masalah, pengguna, data, arsitektur, evaluasi, guardrail, budget, observability, feedback, dan rencana rollout kecil.", caution: "Blueprint yang baik juga menuliskan apa yang belum diketahui dan eksperimen apa yang harus dilakukan sebelum janji besar dibuat.", check: "menghubungkan seluruh keputusan AI engineering menjadi rencana yang dapat dibangun" },
];

function makeQuiz(seed: LessonSeed): Material["quiz"] {
  return [
      { question: `Apa hal terpenting dari “${seed.title}”?`, options: [seed.check, "Menghafal tool tanpa memahami konteks", "Menambah fitur tanpa menguji"], answer: 0, explanation: `Benar. Fokusnya adalah ${seed.check.toLowerCase()}.` },
    { question: "Langkah praktik yang paling sehat adalah…", options: [seed.practice, "Menyalin konfigurasi tanpa bukti", "Melewati pemeriksaan risiko"], answer: 0, explanation: "Mulai kecil, cek hasilnya, lalu perbaiki berdasarkan bukti dan batas risiko." },
  ];
}

export const aiEngineeringPdfMaterials: Material[] = seeds.map((seed) => {
  const chapterName = chapterNames[seed.chapter];
  const lessonNumber = ((seed.id - 100) % 6) + 1;
  const teaching = aiEngineeringTeachingContent[seed.id];
  if (!teaching) throw new Error(`Missing substantive teaching content for AI Engineering lesson ${seed.id}`);
  return {
    id: seed.id,
    displayNumber: seed.id - 99,
    title: `Bab ${seed.chapter}.${lessonNumber} · ${seed.title}`,
    category: `AI Engineering · Bab ${seed.chapter} — ${chapterName}`,
    specialization: "ai-engineering",
    level: seed.level,
    minutes: Math.max(seed.minutes, 18),
    emoji: "✦",
    summary: `${seed.focus} Materi ini membahas cara kerja konsep, contoh penerapannya, dan keputusan yang perlu dibuat ketika konsep tersebut digunakan dalam produk AI.`,
    analogy: `Bab ini seperti peta kerja: ${seed.title.toLowerCase()} membantu kamu memilih langkah yang masuk akal sebelum menambah kerumitan.`,
    chapterLecture: lessonNumber === 1 ? aiEngineeringChapterLectures[seed.chapter] : undefined,
    caseStudy: employeePolicyAssistantCaseStudy[seed.id],
    sections: [
      { heading: "Konsep yang perlu dipahami", body: `${seed.focus}\n\nDalam alur buku, konsep ini ditempatkan sebagai bagian dari Bab ${seed.chapter} karena keputusan pada tahap ini memengaruhi kualitas sistem pada tahap berikutnya.` },
      { heading: "Bagaimana konsep ini bekerja", body: teaching.mechanism },
      { heading: "Kasus di dunia kerja", body: teaching.caseStudy },
      { heading: "Contoh langkah demi langkah", body: teaching.workedExample },
      { heading: "Aturan pengambilan keputusan", body: teaching.decisionRule },
      { heading: "Latihan terarah", body: `${seed.practice} Catat asumsi, bukti yang digunakan, dan hasilnya agar percobaan berikutnya dapat dibandingkan secara objektif.` },
      { heading: "Batasan dan risiko", body: seed.caution },
    ],
    resources: seed.speedrun ? [bookResource, companionResource, speedrunResource] : [bookResource, companionResource],
    quiz: makeQuiz(seed),
  };
});
