import { checkpoint, defineIntensiveCourse } from "./intensiveCourseBlueprint";
import { createIntensiveCourseMaterials } from "./intensiveCourseFactory";
import { intensiveSources } from "./intensiveCourseSources";

const s = intensiveSources.product;
const safe = "Gunakan persona fiktif atau data riset yang telah diizinkan. Jangan menjadikan AI pengambil keputusan final pada konteks berdampak tinggi tanpa owner, evaluasi, dan kontrol manusia yang sesuai.";

const productCourse = defineIntensiveCourse({
  specialization: "ai-product",
  label: "AI Product Builder",
  emoji: "▱",
  baseId: 7000,
  prologue: checkpoint({
    title: "Sebelum Masuk Course Inti",
    level: "Pemula",
    focus: "membedakan demo model dari produk AI yang berguna, dapat dipercaya, dan dapat dioperasikan",
    artifact: "product intent map dan kontrak belajar",
    guardrail: safe,
    sources: [s.pair, s.nistVideo, s.video],
    topics: ["Apa yang Dilakukan AI Product Builder", "Demo, Fitur, Produk, dan Sistem", "Masalah Pengguna Sebelum Model", "Nilai, Risiko, dan Reversibilitas", "Siapa yang Memiliki Keputusan", "Data, Model, dan UX sebagai Satu Sistem", "Kepercayaan Bukan Fitur Tambahan", "Kontrol Pengguna dan Ekspektasi", "Safety, Privacy, dan IP dalam Produk", "Cara Membaca Course Ini", "Artefak yang Akan Kamu Bangun", "Peta Jalan dari Prolog ke Product Capstone"],
    opening: "Produk AI tidak selesai ketika model menghasilkan jawaban yang mengesankan. Ia mulai ketika tim mampu menjelaskan masalah pengguna, batas perilaku, cara mengevaluasi nilai, dan siapa yang bertanggung jawab saat hasilnya salah.",
    caseTitle: "Tim Sapa ingin membuat copilot untuk staf layanan",
    caseNarrative: "Tim sudah punya prompt yang membuat draf jawaban cepat. Namun mereka belum tahu kapan draf membantu, kapan perlu sumber, siapa menyetujui balasan, dan bagaimana mengukur bahwa staf benar-benar terbantu. Mereka memulai dari product intent map.",
    teachingPoint: "Model hanyalah salah satu komponen; produk AI adalah kesepakatan antara pengguna, workflow, batas, dan bukti nilai.",
    questions: ["Masalah pengguna apa yang ingin dibantu?", "Dampak apa yang terjadi bila AI salah?", "Kontrol apa yang harus tetap berada di tangan pengguna?"],
  }),
  chapters: [
    checkpoint({
      title: "Discovery dan Masalah yang Layak Dibantu AI",
      level: "Pemula",
      focus: "mencari masalah pengguna bernilai sebelum mengunci solusi AI",
      artifact: "opportunity brief dan evidence log",
      guardrail: safe,
      sources: [s.pair, s.video],
      topics: ["Membedakan Pain, Need, dan Request", "Jobs to Be Done untuk AI", "Frekuensi, Friction, dan Dampak", "Workflow Saat Ini", "Task yang Deterministik versus Bernuansa", "Kapan Aturan Lebih Baik dari AI", "Nilai Pengguna dan Nilai Bisnis", "Risiko Salah dan Reversibilitas", "Opportunity Solution Tree", "Evidence Log", "Membuat Prioritas Opportunity", "Review Opportunity Brief"],
      opening: "Discovery membuat tim jatuh cinta pada masalah, bukan pada demo. Kamu akan mengumpulkan bukti workflow dan memilih opportunity berdasarkan nilai serta risiko, bukan hype model terbaru.",
      caseTitle: "Permintaan 'buat chatbot' datang dari tiga department",
      caseNarrative: "Semua department meminta chatbot, tetapi masalahnya berbeda: satu butuh pencarian kebijakan, satu butuh routing tiket, dan satu hanya butuh FAQ lebih rapi. Tim memetakan jobs, frekuensi, dampak, dan alternatif non-AI.",
      teachingPoint: "Use case AI yang baik punya manfaat jelas, bukti workflow, dan risiko yang dapat dikendalikan.",
      questions: ["Apa job pengguna yang belum terbantu?", "Alternatif paling sederhana apa yang perlu diuji?", "Apa risiko bila sistem salah?"],
    }),
    checkpoint({
      title: "Problem Framing dan Outcome",
      level: "Pemula",
      focus: "menyusun problem statement, target outcome, non-goal, dan asumsi yang dapat diuji",
      artifact: "problem framing canvas",
      guardrail: safe,
      sources: [s.pair, s.nist],
      topics: ["Problem Statement yang Tidak Mengunci Solusi", "User, Context, Need, Outcome", "Outcome versus Output", "Non-Goal sebagai Pelindung Scope", "Assumption Mapping", "Risiko dan Stakeholder", "Success dan Failure State", "Counterfactual: Jika Tidak Ada AI", "Definisi Nilai", "Decision Owner", "Framing Review", "Review Problem Canvas"],
      opening: "Framing yang baik memberi tim ruang untuk belajar. Ia mengikat pengguna, konteks, hasil yang diinginkan, serta hal yang sengaja belum akan dilakukan pada versi pertama.",
      caseTitle: "Copilot dianggap gagal karena tim menilai hal yang berbeda",
      caseNarrative: "Support mengharapkan waktu respon lebih cepat, quality mengharapkan jawaban lebih akurat, dan legal mengharapkan sumber terlihat. Tim menyatukan outcome, non-goal, dan owner keputusan sehingga scope menjadi dapat diuji.",
      teachingPoint: "Outcome yang jelas membantu tim memilih trade-off tanpa menyembunyikan siapa yang terdampak.",
      questions: ["Outcome apa yang berubah untuk pengguna?", "Apa non-goal versi pertama?", "Asumsi mana paling berisiko?"],
    }),
    checkpoint({
      title: "Riset Pengguna dan Bukti Workflow",
      level: "Pemula",
      focus: "mengumpulkan bukti kebutuhan, mental model, dan konteks kerja pengguna secara etis",
      artifact: "research plan dan insight repository",
      guardrail: "Minta persetujuan yang jelas untuk riset, minimalkan data pribadi, dan jangan memasukkan rekaman/transkrip sensitif ke tool tanpa izin.",
      sources: [s.pair, s.principles],
      topics: ["Research Question", "Interview Guide yang Netral", "Observasi Workflow", "Diary Study Ringan", "Sample dan Recruitment", "Consent serta Privacy", "Mencatat Kutipan dan Perilaku", "Affinity Mapping", "Mental Model Pengguna", "Membedakan Evidence dari Interpretation", "Insight Repository", "Review Research Readout"],
      opening: "Riset pengguna pada produk AI perlu melihat lebih dari pertanyaan 'mau fitur apa'. Bab ini mencari bagaimana orang bekerja, memperbaiki hasil, membangun kepercayaan, dan bereaksi terhadap ketidakpastian.",
      caseTitle: "Staf mengatakan ingin otomatisasi penuh, tetapi selalu mengedit hasil",
      caseNarrative: "Dalam observasi, staf meminta sistem otomatis tetapi tetap membaca dan mengubah draf sebelum mengirim. Tim menemukan bahwa kontrol dan tone lebih penting daripada menghilangkan semua langkah manusia.",
      teachingPoint: "Perilaku dalam workflow sering lebih jujur daripada jawaban preferensi di awal wawancara.",
      questions: ["Apa yang benar-benar dilakukan pengguna?", "Di titik mana kepercayaan turun?", "Evidence apa yang mendukung insight ini?"],
    }),
    checkpoint({
      title: "UX AI, Flow, dan Ekspektasi Pengguna",
      level: "Menengah",
      focus: "mendesain alur AI yang menjelaskan kemampuan, batas, kontrol, feedback, dan graceful failure",
      artifact: "AI user flow dan interaction contract",
      guardrail: safe,
      sources: [s.pair, s.principles],
      topics: ["Mental Model dan Onboarding", "Input yang Membantu Sistem", "Progress dan Status Sementara", "Confidence Tanpa Angka Palsu", "Source, Citation, dan Evidence", "Edit, Retry, dan Undo", "Clarification dan Ambiguity", "Out-of-Scope Response", "Graceful Failure", "Accessibility dan Language", "Feedback Loop di UI", "Review Interaction Contract"],
      opening: "UX AI yang baik tidak menyamar sebagai manusia serba tahu. Ia memberi pengguna gambaran apa yang sedang dilakukan, apa yang bisa diperbaiki, dan kapan hasil perlu diverifikasi.",
      caseTitle: "Pengguna percaya penuh pada ringkasan yang tidak punya sumber",
      caseNarrative: "Copilot menulis ringkasan dengan nada yakin. Saat ada detail salah, pengguna sulit menelusuri asalnya. Tim menambahkan sumber, status ketidakpastian, edit, dan jalur 'tidak cukup informasi'.",
      teachingPoint: "Transparansi yang berguna membantu pengguna membuat keputusan, bukan sekadar menambah disclaimer.",
      questions: ["Apa kontrol yang dapat dipakai pengguna?", "Bagaimana sistem menyatakan ketidakpastian?", "Apa fallback untuk input ambigu?"],
    }),
    checkpoint({
      title: "PRD AI, Scope, dan Kontrak Build",
      level: "Menengah",
      focus: "mengubah discovery menjadi kontrak build yang memuat requirement, data, batas, acceptance criteria, dan ownership",
      artifact: "PRD AI dan release criteria",
      guardrail: safe,
      sources: [s.pair, s.nist, s.video],
      topics: ["PRD untuk Sistem Probabilistik", "User Story dan Job", "Functional Requirement", "Non-Functional Requirement", "Data Permission dan Source", "Model Capability serta Limitation", "Acceptance Criteria", "Risk Register", "Dependencies dan Timeline", "Owner serta RACI", "Release Criteria", "Review PRD AI"],
      opening: "PRD AI yang kuat membuat ketidakpastian dapat dibahas secara eksplisit. Ia menyebut apa yang dibangun, apa yang tidak, data yang diizinkan, contoh lulus-gagal, dan pihak yang harus menyetujui rilis.",
      caseTitle: "Engineer membangun tool call yang tidak pernah diminta product",
      caseNarrative: "Tanpa PRD jelas, engineer menambahkan aksi otomatis karena terlihat keren. User research ternyata meminta draf dan approval, bukan eksekusi langsung. Tim memperbaiki requirement, non-goal, dan acceptance criteria.",
      teachingPoint: "Scope yang tepat melindungi pengguna dan tim dari fitur yang tidak punya bukti kebutuhan.",
      questions: ["Apa acceptance criteria yang terukur?", "Data apa yang memang boleh dipakai?", "Aksi mana yang termasuk non-goal?"],
    }),
    checkpoint({
      title: "Data, Policy, dan Risiko Produk AI",
      level: "Menengah",
      focus: "memetakan data, policy, safety, privacy, security, dan IP sebagai keputusan product lifecycle",
      artifact: "AI risk and policy map",
      guardrail: "Materi ini memberi kerangka kerja product; ikuti kebijakan organisasi dan minta ahli yang tepat untuk keputusan legal, keamanan, atau compliance yang spesifik.",
      sources: [s.nist, s.principles, s.nistVideo],
      topics: ["Map, Measure, Manage, Govern", "Data Classification", "Purpose Limitation", "Risk Scenario", "Harm dan Affected Group", "Misuse serta Abuse Case", "Privacy by Design", "Security Boundary", "Intellectual Property", "Policy UX", "Escalation Path", "Review Risk Map"],
      opening: "Risiko AI tidak hidup di dokumen compliance terpisah. Ia muncul dalam pilihan data, UX, model, feedback, dan siapa yang bisa bertindak. Bab ini membuatnya menjadi bagian product decision sehari-hari.",
      caseTitle: "Fitur rekrutmen diminta memberi rekomendasi kandidat otomatis",
      caseNarrative: "Tim melihat potensi efisiensi, tetapi dampaknya tinggi dan bukti model belum cukup. Mereka memetakan affected groups, data, error mode, human review, policy, dan keputusan untuk membatasi versi pertama pada bantuan ringkasan terstruktur.",
      teachingPoint: "Makin besar dampak keputusan, makin kuat bukti, kontrol, dan governance yang dibutuhkan.",
      questions: ["Siapa yang bisa terdampak negatif?", "Kontrol apa yang wajib sebelum aksi?", "Kapan fitur harus dihentikan atau dieskalasi?"],
    }),
    checkpoint({
      title: "Prototype dan Eksperimen Nilai",
      level: "Menengah",
      focus: "menguji asumsi produk melalui prototype yang cukup realistis tanpa berpura-pura sudah siap produksi",
      artifact: "prototype test plan dan experiment log",
      guardrail: safe,
      sources: [s.pair, s.video],
      topics: ["Prototype Fidelity", "Wizard of Oz", "Concierge Test", "Happy Path dan Edge Case", "Prompt Prototype", "Synthetic Scenario", "Task Success", "Think Aloud", "Feedback Prompt", "Prototype Limitation", "Learning Log", "Review Prototype Evidence"],
      opening: "Prototype bukan mini-production. Ia adalah cara murah untuk mengecek apakah flow, value proposition, dan control user masuk akal sebelum tim mengunci biaya teknis yang besar.",
      caseTitle: "Tim ingin membangun RAG penuh sebelum tahu pengguna akan membaca sumber",
      caseNarrative: "Mereka membuat prototype dengan tiga dokumen contoh dan link sumber. Saat testing, pengguna ternyata lebih peduli bisa memperbaiki draf dibanding mencari semua dokumen. Roadmap berubah berdasarkan bukti.",
      teachingPoint: "Eksperimen produk yang baik mengurangi ketidakpastian paling berisiko, bukan memvalidasi apa yang sudah ingin dipercaya tim.",
      questions: ["Asumsi apa yang sedang diuji?", "Bukti apa yang dikumpulkan?", "Apa limitation prototype yang harus jujur disampaikan?"],
    }),
    checkpoint({
      title: "Evaluasi Kualitas, Safety, dan Kepercayaan",
      level: "Menengah",
      focus: "menyusun evaluasi AI yang menggabungkan dataset, rubrik, human review, safety check, dan threshold rilis",
      artifact: "evaluation plan dan scorecard",
      guardrail: safe,
      sources: [s.pair, s.nist, s.video],
      topics: ["Definisi Kualitas untuk Use Case", "Evaluation Dataset", "Representative dan Edge Case", "Rubrik Human Review", "Automated Check", "Groundedness dan Citation", "Safety Scenario", "Bias dan Fairness Check", "AI Judge dengan Skeptis", "Threshold Rilis", "Error Taxonomy", "Review Evaluation Scorecard"],
      opening: "Jika product AI tidak dapat menjelaskan seperti apa hasil yang cukup baik dan cukup aman, maka ia belum punya dasar kuat untuk rilis. Bab ini mengubah kata 'bagus' menjadi bukti dan threshold.",
      caseTitle: "Demo dianggap bagus, tetapi gagal pada pertanyaan ambigu dan sensitif",
      caseNarrative: "Tim hanya menguji pertanyaan bersih. Saat dimasukkan typo, bahasa campur, data kurang, dan permintaan berisiko, kualitas runtuh. Mereka membangun eval set, rubrik, error taxonomy, dan gate rilis.",
      teachingPoint: "Evaluasi bukan pagar terakhir; ia adalah cara product belajar secara terukur.",
      questions: ["Kasus apa yang harus ada di eval set?", "Siapa melakukan human review?", "Kegagalan apa yang tidak boleh lolos?"],
    }),
    checkpoint({
      title: "Metrik Produk, Eksperimen, dan Pembelajaran",
      level: "Menengah",
      focus: "menghubungkan kualitas model ke perilaku pengguna, outcome, biaya, dan eksperimen yang dapat dipercaya",
      artifact: "product metric tree dan experiment readout",
      guardrail: safe,
      sources: [s.pair, s.nist],
      topics: ["Model Metric versus Product Metric", "Task Completion", "Time Saved dan Quality", "Adoption serta Retention", "Trust Signal", "Cost per Successful Task", "Guardrail Metric", "Instrumentation Plan", "A/B Test untuk AI", "Qualitative Feedback", "Metric Review Cadence", "Review Product Metric Tree"],
      opening: "Skor eval tinggi tidak otomatis berarti produk membantu. Bab ini menghubungkan kualitas dengan workflow pengguna, keberhasilan tugas, biaya, trust, dan sinyal yang membuat tim tahu kapan iterasi diperlukan.",
      caseTitle: "Pengguna mencoba fitur sekali tetapi tidak pernah kembali",
      caseNarrative: "Dashboard menunjukkan high satisfaction pada demo, tetapi retention rendah. Wawancara menemukan pengguna tidak tahu kapan memakai fitur dan tidak percaya hasil tanpa source. Tim mengubah onboarding, control, dan metric tree.",
      teachingPoint: "Metrik produk menilai perubahan perilaku dan outcome, bukan hanya kemampuan model di laboratorium.",
      questions: ["Metrik mana mewakili value pengguna?", "Apa guardrail yang tidak boleh turun?", "Sinyal kualitatif apa yang perlu dibaca?"],
    }),
    checkpoint({
      title: "Human-in-the-Loop dan Operasi Kepercayaan",
      level: "Menengah",
      focus: "menentukan level autonomy, review, escalation, feedback, dan audit sesuai dampak tindakan AI",
      artifact: "autonomy matrix dan human review playbook",
      guardrail: safe,
      sources: [s.pair, s.principles, s.nist],
      topics: ["Level of Autonomy", "Draft, Suggest, Act", "Approval UX", "Confidence dan Escalation", "Queue untuk Review", "Reviewer Guideline", "Override dan Undo", "Feedback as Data", "Disagreement Handling", "Audit Trail", "Reviewer Load", "Review Human Control Plan"],
      opening: "Human-in-the-loop bukan tombol approval yang ditempel setelah fitur selesai. Ia adalah desain kerja: siapa meninjau apa, dengan konteks apa, kapan bisa membatalkan, dan bagaimana feedback memperbaiki sistem.",
      caseTitle: "Reviewer kewalahan karena semua output dikirim untuk dicek",
      caseNarrative: "Tim ingin aman lalu mengirim seluruh output ke satu reviewer. Antrean bertambah dan pengguna menunggu. Mereka membedakan dampak, membuat triage, memberi reviewer konteks sumber, serta meninjau beban review.",
      teachingPoint: "Kontrol manusia yang baik menjaga kualitas tanpa memindahkan seluruh kerja kembali menjadi manual.",
      questions: ["Aksi mana yang boleh draft saja?", "Kapan escalation diperlukan?", "Bagaimana override dicatat dan dipelajari?"],
    }),
    checkpoint({
      title: "Launch, Monitoring, dan Product Operations",
      level: "Lanjut",
      focus: "merilis produk AI bertahap dengan owner, monitoring, support, incident path, dan iterasi berbasis bukti",
      artifact: "launch plan dan product operations dashboard",
      guardrail: safe,
      sources: [s.nist, s.principles, s.video],
      topics: ["Limited Launch", "Eligibility dan Access", "User Education", "Support Playbook", "Monitoring Quality in Production", "Feedback Triage", "Incident Response Product", "Model and Prompt Change", "Rollback Feature", "Changelog dan Transparency", "Review Launch Readiness", "Post-Launch Learning"],
      opening: "Launch adalah awal hubungan produk dengan pengguna nyata. Bab ini membuat rencana untuk merilis terbatas, memantau kualitas, menerima feedback, mengurangi dampak, dan mengubah sistem tanpa membuat pengguna bingung.",
      caseTitle: "Rilis luas membuat tim support menerima keluhan yang belum punya jalur eskalasi",
      caseNarrative: "Fitur Sapa dirilis untuk semua orang sekaligus. Ketika hasil salah, support tidak tahu apakah ini bug, data, policy, atau UX. Tim membuat limited launch, taxonomy ticket, owner rotation, monitoring, dan rollback plan.",
      teachingPoint: "Operasi produk AI membutuhkan jalur respons yang menghubungkan pengguna, product, engineering, safety, dan support.",
      questions: ["Siapa owner sinyal kualitas?", "Bagaimana pengguna melaporkan masalah?", "Kapan feature rollback dilakukan?"],
    }),
    checkpoint({
      title: "AI Product Capstone: Dari Bukti ke Launch",
      level: "Lanjut",
      focus: "menyatukan discovery, framing, UX, PRD, risk, prototype, evaluation, metrics, human control, dan launch plan",
      artifact: "AI product dossier",
      guardrail: safe,
      sources: [s.pair, s.nist, s.principles, s.nistVideo, s.video],
      topics: ["Memilih Problem Capstone", "Menyusun Evidence Log", "Menulis Problem dan Outcome", "Mendesain AI User Flow", "Menyelesaikan PRD", "Membuat Risk Map", "Merencanakan Prototype", "Membuat Evaluation Scorecard", "Mendesain Metric Tree", "Membuat Autonomy Matrix", "Menulis Launch Plan", "Presentasi dan Retrospektif Product"],
      opening: "Capstone menguji kemampuanmu menyatukan keputusan product AI dalam satu dossier yang dapat dibaca stakeholder. Yang dinilai adalah ketajaman masalah, bukti, batas, dan rencana belajar—bukan seberapa banyak jargon model.",
      caseTitle: "Sapa menyiapkan copilot layanan pelanggan versi terbatas",
      caseNarrative: "Tim Sapa menyatukan research, PRD, flow sumber, risk map, evaluation, metric, human approval, dan launch plan. Mereka memilih versi yang lebih sempit tetapi dapat dipercaya daripada otomatisasi penuh yang belum punya bukti cukup.",
      teachingPoint: "Produk AI yang siap launch memiliki cerita keputusan dari kebutuhan pengguna sampai operasi setelah rilis.",
      questions: ["Bukti apa yang mendukung scope capstone?", "Risiko apa yang paling perlu dikontrol?", "Apa yang dipelajari setelah launch terbatas?"],
    }),
  ],
});

export const aiProductIntensiveMaterials = createIntensiveCourseMaterials(productCourse);
