import { checkpoint, defineIntensiveCourse } from "./intensiveCourseBlueprint";
import { createIntensiveCourseMaterials } from "./intensiveCourseFactory";
import { intensiveSources } from "./intensiveCourseSources";

const s = intensiveSources.automation;
const safe = "Bangun workflow pada akun sandbox atau aplikasi yang kamu miliki/diizinkan. Jangan menyimpan token di node teks, membagikan URL webhook privat, atau mengotomatisasi tindakan berdampak tanpa approval dan audit.";

const automationCourse = defineIntensiveCourse({
  specialization: "automation",
  label: "Automation Specialist",
  emoji: "↻",
  baseId: 8000,
  prologue: checkpoint({
    title: "Sebelum Masuk Course Inti",
    level: "Pemula",
    focus: "memahami otomasi sebagai desain workflow, keputusan, data, dan accountability—bukan sekadar menghubungkan aplikasi",
    artifact: "workflow intent map dan kontrak belajar",
    guardrail: safe,
    sources: [s.n8n, s.zapier, s.video],
    topics: ["Apa yang Dilakukan Automation Specialist", "Workflow, Sistem, dan Proses", "Otomasi Bukan Tujuan Itu Sendiri", "Nilai, Frekuensi, dan Risiko", "Siapa Owner Workflow", "Event, Data, dan Tindakan", "Apa yang Boleh Otomatis", "Titik Review Manusia", "Credential dan Tanggung Jawab", "Cara Membaca Course Ini", "Artefak yang Akan Dibangun", "Peta Jalan dari Prolog ke Capstone"],
    opening: "Otomasi yang baik membuat kerja berulang menjadi lebih jelas, bukan sekadar lebih cepat. Ia membutuhkan pemahaman proses, data yang masuk, kondisi pengecualian, owner, dan cara menghentikan alur dengan aman.",
    caseTitle: "Tim Rapi ingin mengotomatisasi intake permintaan internal",
    caseNarrative: "Saat ini semua permintaan masuk dari chat, sebagian hilang, dan beberapa berisi informasi yang tidak lengkap. Tim ingin membuat workflow, tetapi perlu memutuskan data wajib, siapa pemilik, kapan alur berhenti, dan apa yang tidak boleh dilakukan otomatis.",
    teachingPoint: "Workflow yang sehat lahir dari proses yang dipahami, bukan dari trigger pertama yang berhasil menyala.",
    questions: ["Tugas apa yang benar-benar repetitif?", "Kesalahan apa yang paling berbahaya?", "Siapa owner keputusan di setiap tahap?"],
  }),
  chapters: [
    checkpoint({
      title: "Process Discovery dan Kandidat Otomasi",
      level: "Pemula",
      focus: "memilih proses yang layak diotomasi berdasarkan nilai, variasi, risiko, dan kesiapan data",
      artifact: "automation opportunity map",
      guardrail: safe,
      sources: [s.n8n, s.zapier, s.video],
      topics: ["Process Map As-Is", "Frequency dan Volume", "Happy Path serta Exception", "Manual Handoff", "Bottleneck dan Rework", "Rule Clarity", "Data Readiness", "Error Impact", "Reversibility", "Opportunity Scoring", "Prioritas MVP", "Review Opportunity Map"],
      opening: "Tidak semua proses harus diotomasi. Bab ini membantu kamu memilih kandidat yang punya aturan cukup jelas, dampak salah yang dapat dikelola, dan manfaat yang bisa diukur.",
      caseTitle: "Semua inbox ingin diautomasi sekaligus",
      caseNarrative: "Tim Rapi ingin membuat agent menjawab semua pesan. Saat dipetakan, sebagian pesan membutuhkan empati dan keputusan kebijakan. Mereka memilih MVP untuk mengubah form lengkap menjadi ticket dengan routing yang dapat ditinjau.",
      teachingPoint: "Mulai dari proses sempit dengan value jelas membuat pembelajaran dan keamanan jauh lebih baik.",
      questions: ["Bagian mana paling repetitif?", "Exception apa yang paling umum?", "Apa risiko jika workflow salah?"],
    }),
    checkpoint({
      title: "Event, Trigger, dan Desain Flow",
      level: "Pemula",
      focus: "menentukan kapan workflow dimulai, data apa yang diperlukan, dan bagaimana alur dibaca oleh pemiliknya",
      artifact: "event contract dan flow diagram",
      guardrail: safe,
      sources: [s.n8n, s.n8nBuild, s.zapier],
      topics: ["Event sebagai Fakta", "Schedule versus Webhook", "Trigger Contract", "Payload Minimal", "Idempotency Key", "Workflow State", "Branch dan Condition", "Delay serta Wait", "Timeout", "Correlation ID", "Flow Diagram", "Review Event Contract"],
      opening: "Trigger bukan sekadar tombol mulai. Ia adalah kontrak bahwa sebuah peristiwa terjadi, data tertentu tersedia, dan workflow boleh mengambil langkah berikutnya tanpa menciptakan duplikasi.",
      caseTitle: "Form yang dikirim dua kali membuat dua ticket",
      caseNarrative: "Pengguna mengklik submit ulang karena koneksi lambat. Workflow membuat dua ticket dan dua notifikasi. Tim menambahkan idempotency key, correlation ID, dan status agar event dapat dikenali tanpa menghapus data penting.",
      teachingPoint: "Event design yang baik menghindari kerja ganda dan memudahkan diagnosis lintas aplikasi.",
      questions: ["Fakta apa yang memicu alur?", "Bagaimana mencegah duplikasi?", "ID apa yang menghubungkan seluruh langkah?"],
    }),
    checkpoint({
      title: "Data Mapping dan Kontrak Antaraplikasi",
      level: "Pemula",
      focus: "memetakan field, validasi, transformasi, dan ownership data saat berpindah antar tool",
      artifact: "mapping table dan validation rules",
      guardrail: safe,
      sources: [s.n8n, s.zapier, s.make],
      topics: ["Source Field dan Target Field", "Required versus Optional", "Format dan Normalization", "Lookup dan Enrichment", "Default Value", "Null dan Missing Value", "Validation Rule", "Enum Mapping", "Timezone dan Date", "PII Minimization", "Sample Payload", "Review Mapping Table"],
      opening: "Banyak workflow gagal bukan karena trigger, tetapi karena data kehilangan makna ketika pindah tool. Bab ini membuat mapping dapat dibaca, diuji, dan diperbaiki tanpa mengandalkan tebakan.",
      caseTitle: "Email pengguna masuk ke field nama karena header form berubah",
      caseNarrative: "Workflow tetap sukses secara teknis, tetapi CRM berisi data salah. Tim membuat mapping table, validasi format email, missing-value branch, dan sample payload yang aman untuk regression test.",
      teachingPoint: "Data mapping adalah kontrak semantik, bukan sekadar mengisi kolom tujuan.",
      questions: ["Field mana wajib?", "Validasi apa yang diperlukan?", "Data apa yang tidak perlu diteruskan?"],
    }),
    checkpoint({
      title: "API, Webhook, dan Credential Hygiene",
      level: "Menengah",
      focus: "menghubungkan aplikasi melalui API dengan credential, scope, rate limit, dan observability yang aman",
      artifact: "integration contract dan credential register",
      guardrail: "Gunakan token sandbox/placeholder. Jangan menyimpan atau memperlihatkan API key, password, maupun refresh token pada materi, log, atau screenshot.",
      sources: [s.n8n, s.zapier, s.githubActions],
      topics: ["HTTP Request Intuisi", "REST dan Resource", "Webhook Verification", "Authentication Type", "Credential Store", "Scope dan Least Privilege", "Rate Limit", "Pagination", "Retry-After", "Request/Response Logging", "Credential Rotation", "Review Integration Contract"],
      opening: "Integrasi API yang aman menyeimbangkan kebutuhan workflow dengan batas akses. Credential bukan data biasa, dan endpoint yang berhasil sekali belum tentu tahan rate limit, perubahan schema, atau rotasi token.",
      caseTitle: "Token admin dipakai semua workflow agar cepat",
      caseNarrative: "Saat satu workflow debugging bocor ke screenshot, seluruh integrasi berisiko. Tim mengganti token menjadi scope minimum, memakai credential store, mencatat owner, dan membuat prosedur rotasi tanpa mematikan seluruh automasi.",
      teachingPoint: "Credential yang baik memberi cukup akses untuk satu tugas dan tetap dapat diputar serta diaudit.",
      questions: ["Scope minimum apa yang dibutuhkan?", "Bagaimana token disimpan?", "Apa yang dilakukan saat rotasi?"],
    }),
    checkpoint({
      title: "Error Handling, Retry, dan Recovery",
      level: "Menengah",
      focus: "membuat workflow mengelola kegagalan dengan batas, bukti, dan jalur pemulihan yang tidak menggandakan tindakan",
      artifact: "failure mode table dan recovery runbook",
      guardrail: safe,
      sources: [s.n8n, s.zapier, s.make],
      topics: ["Failure Mode", "Transient versus Permanent Error", "Retry dan Backoff", "Dead Letter Queue Intuisi", "Compensating Action", "Idempotent Action", "Timeout Boundary", "Fallback Path", "Alert dan Escalation", "Manual Replay", "Incident Note", "Review Recovery Runbook"],
      opening: "Workflow production perlu menganggap error sebagai bagian normal dari sistem. Bab ini merancang retry yang berhenti, replay yang aman, dan komunikasi ketika manusia perlu mengambil alih.",
      caseTitle: "Notifikasi pengiriman terkirim berulang setelah API lambat",
      caseNarrative: "Workflow mengulang request karena timeout, padahal provider sebenarnya memproses tindakan pertama. Tim memisahkan acknowledgement, idempotency, retry window, dan manual replay untuk mencegah pesan ganda.",
      teachingPoint: "Recovery yang aman membedakan antara 'belum tahu hasilnya' dan 'tindakan pasti gagal'.",
      questions: ["Error mana boleh retry?", "Bagaimana mencegah aksi ganda?", "Kapan manusia perlu direquest?"],
    }),
    checkpoint({
      title: "Human-in-the-Loop dan Approval Flow",
      level: "Menengah",
      focus: "menempatkan review manusia pada keputusan berdampak tanpa membuat workflow kehilangan manfaat",
      artifact: "approval matrix dan review queue design",
      guardrail: safe,
      sources: [s.hitl, s.n8n, s.zapier],
      topics: ["Dampak dan Autonomy", "Draft versus Send", "Approval Request", "Context untuk Reviewer", "SLA Review", "Escalation", "Reject dan Feedback", "Undo serta Cancellation", "Audit Trail", "Queue Prioritization", "Reviewer Load", "Review Approval Matrix"],
      opening: "Approval bukan klik setuju tanpa konteks. Bab ini mendesain titik review yang memberi manusia informasi, pilihan, waktu, dan bukti tanpa memperlambat seluruh alur secara membabi buta.",
      caseTitle: "Asisten meeting mengirim ringkasan sensitif ke channel umum",
      caseNarrative: "Tim ingin distribusi otomatis, tetapi beberapa meeting berisi keputusan personal atau komersial. Mereka membuat classification, draft destination, approval, escalation, dan audit trail sebelum ringkasan dibagikan.",
      teachingPoint: "Semakin besar dampak, semakin jelas konteks dan kontrol yang dibutuhkan sebelum workflow bertindak.",
      questions: ["Tindakan mana perlu approval?", "Informasi apa harus dilihat reviewer?", "Bagaimana reject menjadi feedback?"],
    }),
    checkpoint({
      title: "Dokumentasi, Observability, dan Ownership",
      level: "Menengah",
      focus: "membuat workflow dapat ditemukan, dipahami, dipantau, dan dirawat oleh lebih dari pembuat pertamanya",
      artifact: "workflow catalog dan operations dashboard",
      guardrail: safe,
      sources: [s.n8n, s.githubActions, s.video],
      topics: ["Workflow Naming", "Purpose dan Non-Goal", "Owner serta Backup Owner", "Input/Output Contract", "Execution History", "Structured Log", "Success dan Failure Metric", "Alert Routing", "Runbook Link", "Change Log", "Deprecation Plan", "Review Workflow Catalog"],
      opening: "Automasi yang tidak punya owner akan menjadi utang tersembunyi. Bab ini membuat catalog dan observability agar seseorang dapat menjawab workflow ini untuk apa, memakai apa, sehat atau tidak, dan siapa yang mengubahnya.",
      caseTitle: "Workflow penting berhenti setelah pembuatnya pindah tim",
      caseNarrative: "Tidak ada deskripsi, credential owner, atau runbook. Tim baru hanya tahu hasil akhir menghilang. Mereka membangun catalog, backup owner, log, alert routing, dan changelog sederhana.",
      teachingPoint: "Sistem yang dapat dirawat tidak bergantung pada ingatan satu orang.",
      questions: ["Siapa owner dan backup?", "Sinyal apa yang dipantau?", "Dokumen apa yang dibutuhkan saat handoff?"],
    }),
    checkpoint({
      title: "Testing, Versioning, dan Perubahan Aman",
      level: "Menengah",
      focus: "menguji workflow dengan sample data dan mempromosikan perubahan secara bertahap agar regresi tidak langsung mengenai pengguna",
      artifact: "workflow test suite dan release checklist",
      guardrail: safe,
      sources: [s.n8nBuild, s.githubActions, s.zapier],
      topics: ["Test Data Sintetis", "Happy Path Test", "Edge Case Test", "Contract Test", "Sandbox Environment", "Version Naming", "Diff Workflow", "Review dan Approval Change", "Feature Toggle", "Canary Workflow", "Rollback", "Review Release Checklist"],
      opening: "Workflow visual tetap software yang dapat berubah dan rusak. Bab ini memperlakukan perubahan sebagai release: ada data uji, scenario gagal, review, environment, dan jalan kembali.",
      caseTitle: "Perubahan satu node membuat semua ticket tidak ter-route",
      caseNarrative: "Tim mengedit workflow langsung di production untuk memperbaiki label. Karena tidak ada test sample atau diff, kondisi lama hilang. Mereka membuat sandbox, version naming, regression cases, dan rollback point.",
      teachingPoint: "Kecepatan perubahan yang sehat datang dari kemampuan membuktikan dan memulihkan, bukan dari langsung mengedit production.",
      questions: ["Kasus apa yang diuji sebelum release?", "Bagaimana perubahan direview?", "Apa rollback point-nya?"],
    }),
    checkpoint({
      title: "Agentic Automation dan Batas Tool",
      level: "Lanjut",
      focus: "menetapkan capability, tool scope, budget, context, verifikasi, dan kill switch ketika workflow memakai AI agent",
      artifact: "agent capability policy dan tool matrix",
      guardrail: "Jangan memberi agent akses global atau tindakan irreversible pada data nyata. Mulai dari read-only/draft dengan approval eksplisit dan lingkungan terisolasi.",
      sources: [s.hitl, s.n8n, s.video],
      topics: ["Agent versus Workflow Deterministik", "Task Scope", "Tool Allowlist", "Read, Draft, Act", "Context Boundary", "Prompt sebagai Data", "Budget dan Rate Limit", "Verification Step", "Approval Gate", "Kill Switch", "Agent Evaluation", "Review Tool Matrix"],
      opening: "Agent dapat memilih langkah, tetapi itu bukan alasan untuk memberi kebebasan tanpa batas. Bab ini membuat capability policy supaya otonomi meningkat seiring bukti, bukan karena prompt tampak meyakinkan.",
      caseTitle: "Agent diminta 'rapikan CRM' tanpa definisi tindakan",
      caseNarrative: "Permintaan terdengar sederhana, tetapi dapat berarti mengubah, menghapus, atau menggabungkan data pelanggan. Tim membatasi agent pada rekomendasi dan draft merge, menambah tool allowlist, approval, serta audit sebelum aksi.",
      teachingPoint: "Agent yang aman memiliki batas tugas, batas tool, batas biaya, dan cara berhenti yang nyata.",
      questions: ["Tool apa yang benar-benar perlu?", "Aksi mana hanya boleh draf?", "Bagaimana agent dievaluasi sebelum scope naik?"],
    }),
    checkpoint({
      title: "Scale, Governance, dan Portfolio Workflow",
      level: "Lanjut",
      focus: "mengelola banyak workflow sebagai portfolio dengan standar security, cost, reliability, ownership, dan lifecycle",
      artifact: "automation governance playbook",
      guardrail: safe,
      sources: [s.n8n, s.githubActions, s.make],
      topics: ["Automation Portfolio", "Shared Component", "Credential Governance", "Environment Separation", "Rate dan Cost Budget", "Usage Review", "Risk Tier", "Compliance Evidence", "Vendor Dependency", "Sunset Workflow", "Quarterly Review", "Review Governance Playbook"],
      opening: "Satu workflow dapat mudah dirawat; puluhan workflow membutuhkan governance. Bab ini menyusun standar yang membuat tim tetap cepat tanpa membiarkan credential, biaya, dan ownership berubah menjadi kabut.",
      caseTitle: "Setelah sukses, tiap team membuat workflow sendiri tanpa standar",
      caseNarrative: "Beberapa workflow memakai credential personal, beberapa tidak punya owner, dan biaya meningkat tanpa label. Tim membuat tier risiko, catalog, credential policy, lifecycle, dan review cadence tanpa mematikan eksperimen tim.",
      teachingPoint: "Governance yang baik membuat eksperimen lebih aman dan lebih mudah diwariskan, bukan hanya lebih birokratis.",
      questions: ["Workflow mana paling kritis?", "Standar apa yang wajib lintas team?", "Kapan workflow harus disunset?"],
    }),
    checkpoint({
      title: "Security, Privacy, dan Audit Workflow",
      level: "Lanjut",
      focus: "menetapkan minimisasi data, batas credential, auditability, incident path, dan review berkala untuk workflow yang menyentuh informasi penting",
      artifact: "workflow security review dan audit checklist",
      guardrail: "Gunakan data sintetis dan credential sandbox. Materi ini bukan izin untuk mengakses data, akun, atau integrasi yang tidak kamu miliki/diizinkan.",
      sources: [s.n8n, s.githubActions, s.hitl],
      topics: ["Data Flow Review", "Data Minimization", "Secret Exposure Check", "Credential Scope Review", "Webhook Access Boundary", "Log Redaction", "Retention dan Deletion", "Audit Evidence", "Security Incident Path", "Privacy Request Handling", "Periodic Access Review", "Review Audit Checklist"],
      opening: "Workflow dapat menyentuh banyak aplikasi dan data sekaligus, sehingga keamanan serta privacy perlu menjadi bagian dari desain dan operasi—bukan checklist yang baru dibaca setelah sesuatu bocor.",
      caseTitle: "Workflow intake menyimpan payload lengkap di log debugging",
      caseNarrative: "Tim ingin cepat memperbaiki error, tetapi log memuat email, komentar, dan token sementara. Mereka mengubah logging menjadi terstruktur dan redacted, memberi retention, meninjau scope credential, serta membuat jalur incident yang bisa diikuti.",
      teachingPoint: "Audit yang berguna memberi bukti secukupnya untuk memahami tindakan tanpa menyimpan lebih banyak data daripada yang diperlukan.",
      questions: ["Data apa yang harus tidak masuk log?", "Bagaimana access review dilakukan?", "Siapa dihubungi bila ada paparan credential?"],
    }),
    checkpoint({
      title: "Automation Capstone: Workflow yang Dapat Dipercaya",
      level: "Lanjut",
      focus: "menyatukan process discovery, flow, mapping, integration, recovery, review, operations, testing, dan governance menjadi workflow end-to-end",
      artifact: "automation dossier dan demo operasional",
      guardrail: safe,
      sources: [s.n8n, s.n8nBuild, s.zapier, s.make, s.githubActions, s.hitl, s.video],
      topics: ["Memilih Process Capstone", "Membuat Opportunity Map", "Menulis Event Contract", "Menyusun Mapping Table", "Menentukan Credential Scope", "Membuat Failure Mode Table", "Mendesain Approval Flow", "Menulis Catalog dan Runbook", "Membuat Test Plan", "Menyusun Agent Tool Policy", "Menyiapkan Governance Review", "Presentasi dan Retrospektif Automation"],
      opening: "Capstone menilai apakah workflow kamu dapat dijelaskan, diuji, dipantau, dan diserahkan. Bukan sekadar apakah satu integrasi bekerja saat demo, tetapi apakah ia tetap aman ketika data kurang, API lambat, atau owner berganti.",
      caseTitle: "Tim Rapi membuat intake-to-ticket workflow yang siap dipakai",
      caseNarrative: "Tim menyusun event contract, mapping, credential scope, error handling, review untuk permintaan sensitif, dashboard execution, test cases, dan ownership. Mereka memilih fitur lebih sempit tetapi dapat dipulihkan dan dijelaskan.",
      teachingPoint: "Otomasi yang dipercaya menyatukan kecepatan dengan bukti, kontrol, dan jalan pemulihan.",
      questions: ["Apa bukti workflow siap dipakai?", "Kegagalan apa yang sudah dirancang?", "Siapa owner setelah capstone?"],
    }),
  ],
});

export const automationIntensiveMaterials = createIntensiveCourseMaterials(automationCourse);
