import { checkpoint, defineIntensiveCourse } from "./intensiveCourseBlueprint";
import { createIntensiveCourseMaterials } from "./intensiveCourseFactory";
import { intensiveSources } from "./intensiveCourseSources";

const s = intensiveSources.cloud;
const safe = "Gunakan akun sandbox, repository latihan, dan infrastruktur yang kamu miliki atau telah diizinkan. Jangan menaruh secret nyata di contoh, log, atau repository publik.";

const cloudCourse = defineIntensiveCourse({
  specialization: "cloud-devops",
  label: "Cloud Computing AI",
  emoji: "☁",
  baseId: 5000,
  prologue: checkpoint({
    title: "Sebelum Masuk Course Inti",
    level: "Pemula",
    focus: "menerjemahkan kebutuhan produk menjadi keputusan cloud yang dapat dipertanggungjawabkan",
    artifact: "peta awal sistem cloud dan kontrak belajar",
    guardrail: safe,
    sources: [s.aws, s.video],
    topics: ["Apa yang Dimaksud Cloud Computing", "Kenapa Sistem AI Butuh Rumah yang Terukur", "Akun, Region, dan Batas Lingkungan", "Shared Responsibility Tanpa Salah Paham", "Dari Laptop ke Layanan yang Dipakai Orang", "Peta Komponen: Compute, Storage, Network, Identity", "Kualitas Bukan Cuma Server Menyala", "Biaya sebagai Sinyal Desain", "Keamanan dan Izin dari Hari Pertama", "Apa yang Boleh Dilakukan di Lab", "Cara Membaca Course Ini", "Peta Jalan dari Prolog ke Capstone"],
    opening: "Cloud bukan kumpulan layanan yang perlu dihafal. Ia adalah cara memilih sumber daya, batas akses, dan cara operasi agar aplikasi AI dapat tumbuh tanpa menjadi misteri mahal yang hanya dipahami satu orang.",
    caseTitle: "Tim Orbis ingin memindahkan demo asisten dokumen ke cloud",
    caseNarrative: "Demo Orbis berhasil di laptop, tetapi tim belum tahu data mana yang boleh keluar, siapa yang dapat mengubah konfigurasi, berapa biaya wajar, dan bagaimana cara memulihkan layanan. Mereka memulai dari peta sistem, bukan dari tombol deploy.",
    teachingPoint: "Kesiapan cloud dimulai dari konteks, ownership, dan batas; tool datang setelah itu.",
    questions: ["Masalah apa yang ingin diselesaikan sistem cloud ini?", "Data dan tindakan apa yang harus dibatasi sejak awal?", "Bukti apa yang menunjukkan desain awal dapat ditinjau ulang?"],
  }),
  chapters: [
    checkpoint({
      title: "Peta Sistem dan Keputusan Arsitektur",
      level: "Pemula",
      focus: "mengubah use case AI menjadi peta komponen, risiko, dan keputusan arsitektur",
      artifact: "diagram konteks dan decision log arsitektur",
      guardrail: safe,
      sources: [s.aws, s.video],
      topics: ["Membaca Use Case Sebelum Memilih Layanan", "Context Diagram untuk Builder", "Request, Data, Model, dan Jawaban", "Synchronous atau Asynchronous Work", "Stateless dan State yang Perlu Dijaga", "Single Point of Failure yang Sering Tidak Terlihat", "Batas Antar Komponen", "Kontrak API dan Asumsi", "Memilih Managed Service dengan Jujur", "Membandingkan Cepat, Murah, dan Terkendali", "Architecture Decision Record", "Review Arsitektur Pertama"],
      opening: "Bab pertama menahan dorongan untuk langsung memilih layanan. Kamu akan belajar menyusun diagram yang membuat keputusan teknologi bisa dipertanyakan, bukan hanya dipamerkan.",
      caseTitle: "Asisten dokumen lambat ketika laporan masuk bersamaan",
      caseNarrative: "Orbis menaruh seluruh proses upload, ekstraksi, model call, dan penyimpanan dalam satu service. Saat tiga pengguna mengunggah dokumen, semua menunggu. Tim perlu memisahkan aliran kerja tanpa kehilangan konteks dan kontrol biaya.",
      teachingPoint: "Arsitektur yang baik mengungkap aliran data, kegagalan, dan owner sebelum masalahnya menjadi insiden.",
      questions: ["Komponen mana yang perlu dipisahkan lebih dulu?", "Apa yang harus terjadi bila satu komponen lambat?", "Keputusan mana yang wajib dicatat di ADR?"],
    }),
    checkpoint({
      title: "Environment, Runtime, dan Konfigurasi",
      level: "Pemula",
      focus: "membuat lingkungan development, staging, dan production dapat dibedakan serta dilacak",
      artifact: "environment contract dan konfigurasi runtime",
      guardrail: safe,
      sources: [s.aws, s.docker, s.githubActions],
      topics: ["Development, Staging, Production Bukan Sekadar Nama", "Configuration versus Code", "Environment Variables dengan Konteks", "Feature Flag dan Perubahan Bertahap", "Version Runtime dan Dependency", "Seed Data yang Aman", "Konfigurasi Per Region", "Immutable Artifact", "Twelve-Factor Intuisi untuk Builder", "Drift Konfigurasi", "Checklist Promosi Environment", "Review Environment Contract"],
      opening: "Lingkungan yang berbeda membantu tim belajar sebelum pengguna terdampak. Namun perbedaan yang tidak terdokumentasi justru membuat bug terasa gaib; bab ini memecahnya menjadi kontrak yang dapat dicek.",
      caseTitle: "Bug hanya muncul di production karena konfigurasi tersembunyi",
      caseNarrative: "Orbis memakai variabel lokal yang tidak pernah dicatat. Saat rilis, parser dokumen memakai model dan batas ukuran berbeda. Tim perlu membuat konfigurasi dapat dibandingkan tanpa menyalin secret ke chat.",
      teachingPoint: "Perubahan aman memerlukan artifact yang sama bergerak melalui environment dengan konfigurasi yang terkontrol.",
      questions: ["Apa yang harus sama antar environment?", "Apa yang boleh berubah dan harus dicatat?", "Bagaimana menguji konfigurasi tanpa membocorkan secret?"],
    }),
    checkpoint({
      title: "Container dan Workload yang Dapat Dipindah",
      level: "Menengah",
      focus: "membungkus workload secara reproducible tanpa mengabaikan image, resource, dan lifecycle",
      artifact: "container contract dan manifest workload",
      guardrail: safe,
      sources: [s.docker, s.kubernetes, s.video],
      topics: ["Image, Container, dan Runtime", "Dockerfile yang Dapat Dibaca", "Build Context dan Dependency", "Tag, Digest, dan Reproducibility", "Local Development dengan Container", "Health Check Bukan Dekorasi", "Resource Request dan Limit", "Pod, Deployment, dan Replica", "Readiness, Liveness, Startup", "Rollout dan Rollback Workload", "Image Registry dan Provenance", "Review Container Contract"],
      opening: "Container membantu menyamakan cara aplikasi dijalankan, tetapi tidak otomatis membuatnya siap produksi. Bab ini menghubungkan image yang rapi dengan lifecycle, resource, dan rollback yang nyata.",
      caseTitle: "Worker ekstraksi dokumen mati saat file besar diproses",
      caseNarrative: "Worker Orbis berjalan baik untuk file kecil, lalu berhenti tanpa diagnosis ketika dokumen besar masuk. Tim perlu membedakan health, resource limit, retry, dan ukuran kerja agar perbaikan tidak sekadar menaikkan mesin.",
      teachingPoint: "Portable bukan berarti tak terbatas; workload perlu kontrak resource dan sinyal kesehatan.",
      questions: ["Sinyal apa yang membedakan siap menerima traffic dari masih hidup?", "Bagaimana limit resource melindungi sistem lain?", "Artifact apa yang memungkinkan rollback cepat?"],
    }),
    checkpoint({
      title: "Network, Edge, dan Jalur Request",
      level: "Menengah",
      focus: "memahami bagaimana request masuk, diarahkan, dibatasi, dan dapat diamati tanpa membongkar keamanan",
      artifact: "peta request path dan kebijakan edge",
      guardrail: safe,
      sources: [s.kubernetes, s.aws],
      topics: ["DNS sebagai Kontrak Nama", "Load Balancer dan Pembagian Beban", "Service Discovery", "Ingress, Gateway, dan Routing", "TLS dan Batas Terminasi", "Timeout, Retry, dan Backoff", "Rate Limit dengan Tujuan", "CORS dan Kontrak Browser", "Network Policy sebagai Batas", "Egress dan Dependency Eksternal", "Membaca Jalur Request Saat Gagal", "Review Edge Policy"],
      opening: "Saat pengguna berkata 'aplikasinya lambat', masalahnya dapat berada di mana pun sepanjang jalur request. Bab ini membantu kamu menggambar jalur tersebut dan memilih batas yang masuk akal.",
      caseTitle: "Pengguna mendapat timeout, tetapi service terlihat sehat",
      caseNarrative: "Dashboard Orbis menunjukkan container hidup. Ternyata request tersangkut pada dependency eksternal yang tidak punya timeout eksplisit. Tim perlu membuat jalur request dan policy retry yang tidak memperbesar antrean.",
      teachingPoint: "Network yang sehat bukan hanya bisa terkoneksi; ia juga punya batas, timeout, dan bukti diagnosis.",
      questions: ["Di titik mana timeout perlu ditempatkan?", "Kapan retry memperbaiki dan kapan memperburuk?", "Bagaimana membuktikan jalur request yang dipakai?"],
    }),
    checkpoint({
      title: "Identity, Secret, dan Akses Minimum",
      level: "Menengah",
      focus: "menetapkan siapa atau apa yang boleh melakukan tindakan tertentu dengan bukti dan masa berlaku",
      artifact: "access matrix dan secret lifecycle",
      guardrail: "Gunakan contoh credential palsu dan akun lab. Jangan meminta, menyimpan, atau membagikan secret siapa pun.",
      sources: [s.aws, s.kubernetes, s.githubActions],
      topics: ["Identity untuk Manusia dan Workload", "Authentication versus Authorization", "Principle of Least Privilege", "Role, Policy, dan Scope", "Secret Bukan Environment Variable Biasa", "Rotasi dan Masa Berlaku Credential", "Service Account dan Workload Identity", "Approval untuk Aksi Sensitif", "Audit Trail yang Berguna", "Break-Glass dengan Batas", "Mereview Permission Drift", "Review Access Matrix"],
      opening: "Akses adalah desain produk juga: terlalu longgar merusak kepercayaan, terlalu sempit menghambat kerja. Bab ini membangun kebiasaan menghubungkan tindakan ke identity, scope, dan jejak audit.",
      caseTitle: "Worker AI diberi akses penuh agar integrasi cepat selesai",
      caseNarrative: "Orbis memberi satu credential yang bisa membaca semua bucket dan mengubah konfigurasi. Saat kebutuhan bertambah, tidak ada yang tahu aksi mana yang benar-benar dibutuhkan. Tim mengurangi scope berdasarkan alur kerja nyata.",
      teachingPoint: "Permission yang baik lahir dari daftar tindakan sah, bukan dari harapan bahwa credential tidak akan disalahgunakan.",
      questions: ["Tindakan minimum apa yang benar-benar dibutuhkan worker?", "Apa jejak audit yang perlu tersedia?", "Bagaimana rotasi dilakukan tanpa downtime?"],
    }),
    checkpoint({
      title: "Infrastructure as Code dan Perubahan Terkendali",
      level: "Menengah",
      focus: "mendeskripsikan infrastruktur sebagai perubahan yang dapat direview, dibandingkan, dan dipulihkan",
      artifact: "repository IaC dan change plan",
      guardrail: safe,
      sources: [s.terraform, s.githubActions, s.aws],
      topics: ["Kenapa Klik Manual Menjadi Masalah", "State dan Sumber Kebenaran", "Resource, Module, dan Reuse", "Input, Output, dan Contract", "Plan sebagai Bahan Review", "Apply dengan Approval", "Remote State dan Akses", "Drift Detection", "Import Resource Lama dengan Hati-Hati", "Policy as Code Intuisi", "Rollback versus Forward Fix", "Review Change Plan"],
      opening: "Infrastructure as Code bukan kompetisi menulis file. Ia adalah cara memperlakukan perubahan infrastruktur seperti perubahan produk: ada review, bukti dampak, approval, dan catatan rollback.",
      caseTitle: "Konfigurasi storage berubah lewat console dan tidak ada yang tahu",
      caseNarrative: "Saat biaya naik, Orbis menemukan lifecycle storage pernah diubah manual. Tidak ada diff, owner, atau cara tahu environment mana yang ikut berubah. Tim memindahkan keputusan ke perubahan yang dapat direview.",
      teachingPoint: "Perubahan aman dapat dibaca sebelum diterapkan dan dapat ditelusuri setelah terjadi.",
      questions: ["Apa yang harus terlihat di plan?", "Siapa berhak menyetujui apply?", "Bagaimana mendeteksi drift tanpa membuat panik?"],
    }),
    checkpoint({
      title: "CI/CD, Release, dan Rollback",
      level: "Menengah",
      focus: "membuat jalur perubahan dari commit ke release memiliki pemeriksaan, artifact, dan jalan mundur",
      artifact: "release pipeline dan rollback playbook",
      guardrail: safe,
      sources: [s.githubActions, s.docker, s.video],
      topics: ["Commit sebagai Awal Bukti", "Build yang Reproducible", "Unit Test dan Contract Test", "Security Check yang Proporsional", "Artifact, Version, dan Traceability", "Promotion Staging ke Production", "Canary dan Bertahap", "Feature Flag saat Release", "Database Change yang Aman", "Observasi Setelah Deploy", "Rollback tanpa Menebak", "Review Release Playbook"],
      opening: "Rilis yang baik bukan menekan tombol deploy dengan berani. Ia mengurangi ketidakpastian sedikit demi sedikit dan membuat tim tahu tanda kapan harus berhenti atau kembali.",
      caseTitle: "Model baru menaikkan kualitas tetapi menggandakan biaya",
      caseNarrative: "Orbis mengganti model di production sekaligus. Quality naik, p95 latency dan biaya juga melonjak. Tim tidak punya canary, baseline, atau tombol rollback yang jelas sehingga perbaikan terlambat.",
      teachingPoint: "Release harus memiliki hipotesis, scope kecil, indikator, owner, dan keputusan rollback sebelum ia dimulai.",
      questions: ["Metrik apa yang dilihat setelah deploy?", "Bagaimana membatasi dampak awal?", "Apa syarat rollback yang eksplisit?"],
    }),
    checkpoint({
      title: "Data, Storage, dan Lifecycle",
      level: "Menengah",
      focus: "mengelola data aplikasi dan AI berdasarkan klasifikasi, akses, retensi, biaya, dan pemulihan",
      artifact: "data inventory dan storage lifecycle policy",
      guardrail: "Gunakan data sintetis atau yang sudah dianonimkan. Jangan memindahkan data pribadi/rahasia ke storage latihan.",
      sources: [s.aws, s.kubernetes],
      topics: ["Membedakan Object, Block, File, dan Database", "Klasifikasi Data sebelum Menyimpan", "Encryption dan Kunci", "Retention serta Deletion", "Versioning dan Recovery", "Backup Bukan Sekadar Salinan", "Lifecycle Policy dan Biaya", "Metadata untuk Discovery", "Akses Data Berdasarkan Peran", "Data Residency dan Region", "Mengukur Storage Growth", "Review Data Inventory"],
      opening: "Storage tampak sederhana sampai data perlu dipulihkan, dibatasi, dihapus, atau dibayar. Bab ini memandang data sebagai aset dengan lifecycle, bukan sebagai folder tanpa owner.",
      caseTitle: "Bucket log tumbuh tanpa batas dan memuat dokumen mentah",
      caseNarrative: "Untuk debugging, Orbis menyimpan payload lengkap selamanya. Biaya naik dan data sensitif ikut tersimpan. Tim perlu meninjau tujuan log, minimisasi, retensi, dan cara investigasi tanpa membuka isi yang tidak perlu.",
      teachingPoint: "Data yang disimpan harus punya alasan, owner, batas akses, dan waktu berakhir.",
      questions: ["Apa yang perlu disimpan untuk diagnosis?", "Apa yang harus dihapus atau dimask?", "Bagaimana membuktikan recovery berjalan?"],
    }),
    checkpoint({
      title: "Observability dan Sinyal Operasi",
      level: "Menengah",
      focus: "memilih log, metrics, traces, dashboard, dan alert yang membantu keputusan operasi",
      artifact: "observability map dan dashboard contract",
      guardrail: "Mask data sensitif pada log dan gunakan environment latihan untuk eksperimen telemetry.",
      sources: [s.prometheus, s.kubernetes, s.aws],
      topics: ["Tiga Sinyal: Log, Metric, Trace", "Golden Signals dengan Konteks", "SLI dan SLO untuk Pengguna", "Cardinality dan Biaya Telemetry", "Structured Logging", "Trace Context Antar Service", "Dashboard untuk Pertanyaan Nyata", "Alert yang Bisa Ditindak", "Noise, Fatigue, dan Eskalasi", "Synthetic Check", "Runbook dan Link Bukti", "Review Observability Map"],
      opening: "Observability bukan mengumpulkan semua angka. Tujuannya adalah membantu manusia menjawab 'apa yang berubah, siapa terdampak, dan langkah aman apa berikutnya' saat waktu terbatas.",
      caseTitle: "Alert berbunyi terus, tetapi tim tetap tidak tahu penyebabnya",
      caseNarrative: "Orbis memasang banyak alert berdasarkan CPU. Saat pengguna mengeluh, tim harus membuka lima dashboard dan tidak bisa menghubungkan request dengan worker. Mereka menyusun sinyal berdasarkan perjalanan pengguna dan runbook.",
      teachingPoint: "Sinyal yang berguna memiliki pertanyaan, owner, threshold, dan tindakan yang jelas.",
      questions: ["Pertanyaan apa yang dijawab dashboard ini?", "Siapa menerima alert dan apa tindakannya?", "Data sensitif apa yang harus dimask?"],
    }),
    checkpoint({
      title: "Reliability dan Incident Response",
      level: "Lanjut",
      focus: "membuat sistem dan tim siap menghadapi kegagalan tanpa menyalahkan orang atau memperbesar dampak",
      artifact: "reliability plan, runbook, dan post-incident review",
      guardrail: safe,
      sources: [s.aws, s.prometheus, s.kubernetes],
      topics: ["Failure Mode Sebelum Insiden", "Dependency dan Blast Radius", "Timeout, Circuit Breaker, Bulkhead", "Queue dan Backpressure", "Health, Degradation, dan Fallback", "Backup serta Restore Drill", "Incident Role dan Komunikasi", "Triage dengan Bukti", "Runbook yang Bisa Dipakai Jam 2 Pagi", "Blameless Postmortem", "Action Item yang Dimiliki", "Review Reliability Plan"],
      opening: "Reliability bukan janji tidak pernah gagal. Ia adalah kemampuan mengurangi dampak, memulihkan dengan jelas, dan belajar tanpa mengubah insiden menjadi permainan mencari kambing hitam.",
      caseTitle: "Provider model eksternal lambat selama satu jam",
      caseNarrative: "Saat provider model lambat, request menumpuk dan worker memakan memori. Tim Orbis perlu memilih fallback yang jujur, membatasi antrean, memberi pesan pengguna yang tepat, dan mencatat fakta untuk perbaikan setelah stabil.",
      teachingPoint: "Rencana insiden yang baik melindungi pengguna dan orang yang sedang memperbaiki sistem sekaligus.",
      questions: ["Apa fallback yang tetap jujur bagi pengguna?", "Bagaimana mengurangi blast radius?", "Action item mana yang benar-benar mencegah pengulangan?"],
    }),
    checkpoint({
      title: "FinOps, Kapasitas, dan Keputusan Biaya",
      level: "Menengah",
      focus: "menghubungkan biaya cloud dengan value, unit economics, kapasitas, dan keputusan produk",
      artifact: "cost model dan review kapasitas",
      guardrail: safe,
      sources: [s.aws, s.prometheus],
      topics: ["Biaya sebagai Feedback Desain", "Tagging dan Cost Allocation", "Unit Cost per Tugas", "Fixed versus Variable Cost", "Capacity Planning", "Autoscaling dengan Batas", "Right-Sizing", "Storage dan Egress Surprise", "Model AI dan Cost per Request", "Budget, Forecast, dan Alert", "Menghindari Optimasi Palsu", "Review Cost Model"],
      opening: "Menghemat cloud bukan berburu diskon buta. Bab ini mengajak kamu melihat biaya sebagai akibat dari keputusan arsitektur dan product behavior yang bisa diukur serta dibicarakan lintas tim.",
      caseTitle: "Biaya asisten AI naik tiga kali lipat tanpa pertumbuhan pengguna",
      caseNarrative: "Orbis hanya melihat tagihan akhir bulan. Setelah memetakan biaya per request, mereka menemukan retry yang berulang, context terlalu panjang, dan storage log tidak punya lifecycle. Tim memperbaiki akar masalah, bukan sekadar mematikan fitur.",
      teachingPoint: "Cost visibility yang baik menghubungkan pengeluaran dengan unit kerja dan keputusan yang dapat diubah.",
      questions: ["Unit biaya apa yang paling bermakna bagi produk?", "Komponen mana yang paling tidak transparan?", "Optimasi apa yang berisiko merusak pengalaman pengguna?"],
    }),
    checkpoint({
      title: "Production Capstone: Menjalankan Layanan AI",
      level: "Lanjut",
      focus: "menyatukan arsitektur, environment, security, delivery, data, observability, reliability, dan biaya menjadi layanan yang dapat dioperasikan",
      artifact: "production readiness dossier",
      guardrail: safe,
      sources: [s.aws, s.docker, s.kubernetes, s.terraform, s.githubActions, s.prometheus, s.video],
      topics: ["Menyusun Production Readiness Review", "Scope Capstone dan Non-Goal", "Arsitektur Final yang Bisa Dibaca", "Environment dan Config Evidence", "Permission serta Secret Review", "Release Pipeline Evidence", "Data Lifecycle Evidence", "Dashboard dan SLO Evidence", "Incident Drill Mini", "Cost Model Evidence", "Handoff ke Owner Operasi", "Presentasi dan Retrospektif Capstone"],
      opening: "Capstone bukan lomba membuat arsitektur paling rumit. Kamu akan merakit bukti bahwa layanan AI kecil dapat dipahami, dirilis, diukur, dipulihkan, dan diserahkan ke tim berikutnya.",
      caseTitle: "Orbis menyiapkan launch terbatas untuk pelanggan pertama",
      caseNarrative: "Tim memiliki banyak potongan bagus tetapi belum satu cerita operasi: siapa owner layanan, bagaimana rilis, apa yang diukur, kapan mematikan fitur, dan bagaimana merespons data yang tak terduga. Mereka menyusun dossier sebagai kontrak launch.",
      teachingPoint: "Kesiapan produksi terlihat dari bukti lintas keputusan, bukan dari satu demo yang berjalan sekali.",
      questions: ["Bukti apa yang masih hilang sebelum launch?", "Siapa owner keputusan saat insiden?", "Apa yang dipelajari untuk iterasi berikutnya?"],
    }),
  ],
});

export const cloudIntensiveMaterials = createIntensiveCourseMaterials(cloudCourse);
