import { checkpoint, defineIntensiveCourse } from "./intensiveCourseBlueprint";
import { createIntensiveCourseMaterials } from "./intensiveCourseFactory";
import { intensiveSources } from "./intensiveCourseSources";

const s = intensiveSources.creative;
const safe = "Gunakan brief, aset, wajah, suara, dan referensi yang kamu miliki/diizinkan. Jangan membuat ulasan/testimoni palsu, meniru identitas seniman hidup, memakai kemiripan orang tanpa izin, atau menganggap materi ini sebagai nasihat hukum.";

const creativeCourse = defineIntensiveCourse({
  specialization: "creative-ai",
  label: "Creative AI & Content Systems",
  emoji: "✺",
  baseId: 9000,
  prologue: checkpoint({
    title: "Sebelum Masuk Course Inti",
    level: "Pemula",
    focus: "memahami AI kreatif sebagai sistem keputusan editorial, bukan mesin konten tanpa owner",
    artifact: "creative intent map dan kontrak belajar",
    guardrail: safe,
    sources: [s.adobe, s.wipo, s.adobeVideo],
    topics: ["Apa yang Dilakukan Creative AI Builder", "Ide, Brief, Aset, dan Publikasi", "Konten Bukan Sekadar Output", "Audience dan Tujuan", "Human Taste dan AI Assistance", "Transparansi Proses", "Hak, Consent, dan Attribution", "Brand Safety dan Trust", "Sistem Konten versus Konten Acak", "Cara Membaca Course Ini", "Artefak yang Akan Dibangun", "Peta Jalan dari Prolog ke Capstone"],
    opening: "AI kreatif dapat mempercepat eksplorasi, tetapi karya yang dipercaya tetap membutuhkan tujuan, editorial judgment, hak penggunaan, accessibility, dan cara menjelaskan prosesnya kepada audiens.",
    caseTitle: "Studio Rasa ingin memakai AI untuk kampanye peluncuran",
    caseNarrative: "Tim ingin membuat banyak visual dan caption cepat, tetapi belum punya audience, voice, permission, review, atau disclosure. Mereka memulai dari creative intent map agar tiap aset punya alasan dan batas yang jelas.",
    teachingPoint: "Output kreatif yang kuat lahir dari sistem yang jelas, bukan dari prompt paling panjang.",
    questions: ["Untuk siapa konten dibuat?", "Keputusan apa yang tetap manusia pegang?", "Hak dan konteks apa yang harus jelas sebelum publikasi?"],
  }),
  chapters: [
    checkpoint({
      title: "Strategi Konten, Audience, dan Nilai",
      level: "Pemula",
      focus: "menentukan audience, tujuan, pesan, format, dan bukti nilai sebelum memproduksi aset",
      artifact: "content strategy one-pager",
      guardrail: safe,
      sources: [s.adobe, s.wipo],
      topics: ["Audience Segment", "Job Konten", "Content Goal", "Message Hierarchy", "Channel Context", "Format Fit", "Content Pillar", "Funnel dan Journey", "Editorial KPI", "Value Proposition", "Content Calendar Intuisi", "Review Strategy One-Pager"],
      opening: "Strategi konten membuat kamu tahu mengapa sebuah aset dibuat, untuk siapa, di kanal apa, dan sinyal apa yang menunjukkan konten membantu. AI dapat mempercepat eksekusi, bukan menggantikan arah.",
      caseTitle: "Kampanye menghasilkan banyak post tetapi tidak ada yang saling terhubung",
      caseNarrative: "Studio Rasa memiliki ide visual bagus, namun setiap channel berbicara berbeda. Tim mendefinisikan audience, content pillar, hierarchy pesan, format, dan KPI sehingga produksi berikutnya punya kompas bersama.",
      teachingPoint: "Kuantitas tidak menggantikan koherensi; content system dimulai dari tujuan dan audience.",
      questions: ["Audience mana yang diprioritaskan?", "Tujuan apa yang diukur?", "Pesan apa yang harus konsisten lintas format?"],
    }),
    checkpoint({
      title: "Brand Voice dan Sistem Editorial",
      level: "Pemula",
      focus: "menerjemahkan identitas brand menjadi keputusan bahasa, tone, claim, dan review yang dapat diulang",
      artifact: "voice guide dan editorial checklist",
      guardrail: safe,
      sources: [s.adobe, s.adobeVideo],
      topics: ["Brand Promise", "Voice versus Tone", "Vocabulary dan Forbidden Word", "Reading Level", "Claim dan Evidence", "Inclusive Language", "Editorial Rule", "Format Template", "Approval Role", "Version History", "Voice Test", "Review Editorial Guide"],
      opening: "Brand voice bukan daftar kata keren. Ia adalah keputusan konsisten tentang bagaimana brand berbicara, klaim apa yang boleh dibuat, dan siapa yang menjaga konteks ketika AI menghasilkan banyak variasi.",
      caseTitle: "Caption AI terdengar rapi tetapi tidak seperti brand",
      caseNarrative: "Output memakai klaim berlebihan dan gaya yang berubah-ubah. Tim menulis voice guide dengan promise, tone per konteks, forbidden wording, evidence rule, serta proses review sebelum caption dipublikasikan.",
      teachingPoint: "Voice guide memberi AI dan manusia batas yang membuat variasi tetap terasa satu sistem.",
      questions: ["Apa perbedaan voice dan tone?", "Klaim mana perlu bukti?", "Siapa menyetujui konten sebelum tayang?"],
    }),
    checkpoint({
      title: "Riset, Fakta, dan Narrative Brief",
      level: "Pemula",
      focus: "mengumpulkan sumber, memeriksa klaim, dan menyusun narrative brief sebelum menghasilkan draft kreatif",
      artifact: "research pack dan narrative brief",
      guardrail: "Jangan menjadikan AI sebagai sumber fakta tunggal. Simpan tautan sumber, tanggal akses, dan bedakan fakta terverifikasi dari opini atau konsep kreatif.",
      sources: [s.wipo, s.copyright],
      topics: ["Research Question", "Primary dan Secondary Source", "Source Credibility", "Claim Inventory", "Fact Check Matrix", "Quote dan Attribution", "Context Window", "Narrative Angle", "Evidence versus Opinion", "Sensitive Topic Review", "Research Archive", "Review Narrative Brief"],
      opening: "Konten yang meyakinkan tetap membutuhkan fakta yang dapat ditelusuri. Bab ini membuat research pack agar ide kreatif tidak berubah menjadi klaim lancar tanpa sumber.",
      caseTitle: "Artikel kampanye memakai statistik viral tanpa sumber",
      caseNarrative: "AI menghasilkan angka menarik dari ingatan model. Tim menghentikan draft, mencari sumber primer, menandai yang belum terverifikasi, dan mengubah narrative brief agar klaim sepadan dengan bukti.",
      teachingPoint: "Kreativitas dapat memperkuat cerita, tetapi tidak menggantikan kewajiban memeriksa fakta.",
      questions: ["Klaim mana paling penting untuk diverifikasi?", "Sumber apa yang paling kuat?", "Apa yang harus ditulis sebagai opini, bukan fakta?"],
    }),
    checkpoint({
      title: "Ideation, Prompt System, dan Versioning",
      level: "Menengah",
      focus: "membuat eksplorasi ide dan prompt dapat dibandingkan, diulang, serta dijelaskan tanpa mengunci kreativitas",
      artifact: "prompt library dan ideation log",
      guardrail: safe,
      sources: [s.adobe, s.adobeVideo],
      topics: ["Creative Brief sebagai Input", "Diverge dan Converge", "Prompt Block", "Constraint Kreatif", "Reference yang Sah", "Negative Constraint", "Variable dan Version", "Seed serta Reproducibility", "Prompt Log", "Selection Criteria", "Experiment Batch", "Review Prompt Library"],
      opening: "Prompt yang dapat dirawat bukan mantra sekali pakai. Ia menyimpan tujuan, constraint, referensi yang sah, variabel, versi, dan alasan mengapa satu hasil dipilih dibanding variasi lain.",
      caseTitle: "Tim tidak bisa mengulang visual yang disukai klien",
      caseNarrative: "Prompt disimpan di chat tanpa versi atau brief. Ketika klien meminta adaptasi, tim menebak ulang. Mereka membuat prompt library, variabel yang jelas, log eksperimen, dan selection criteria.",
      teachingPoint: "Versioning memberi ruang eksplorasi sekaligus membuat keputusan kreatif dapat dibicarakan.",
      questions: ["Constraint apa yang menjaga brief?", "Apa yang berubah antar versi?", "Mengapa hasil ini dipilih?"],
    }),
    checkpoint({
      title: "Writing System: Outline, Draft, dan Edit",
      level: "Menengah",
      focus: "mendesain workflow tulisan yang memisahkan ide, struktur, draft, verifikasi, edit, dan approval",
      artifact: "writing workflow dan editorial draft pack",
      guardrail: safe,
      sources: [s.adobe, s.wipo],
      topics: ["Angle dan Thesis", "Outline before Draft", "Opening Hook", "Structure dan Rhythm", "AI Draft dengan Context", "Fact Check Pass", "Voice Edit", "Clarity Edit", "Accessibility Edit", "Citation dan Credit", "Final Approval", "Review Writing Workflow"],
      opening: "AI dapat membantu menghasilkan alternatif, tetapi tulisan yang bertanggung jawab masih membutuhkan struktur, sumber, editor, dan keputusan apa yang tidak boleh diklaim. Bab ini memisahkan tahap agar setiapnya punya tujuan.",
      caseTitle: "Draft cepat tetapi kehilangan sumber dan perspektif audience",
      caseNarrative: "Artikel hasil AI terasa lengkap, tetapi pembuka tidak relevan dan klaim tidak punya bukti. Tim menambahkan outline, source pass, voice edit, accessibility pass, dan final approval sebagai workflow baku.",
      teachingPoint: "Draft adalah bahan kerja, bukan produk akhir; setiap pass menjaga kualitas yang berbeda.",
      questions: ["Apa thesis konten?", "Klaim mana perlu source?", "Pass edit apa yang belum dilakukan?"],
    }),
    checkpoint({
      title: "Visual Direction, Design System, dan Accessibility",
      level: "Menengah",
      focus: "menerjemahkan pesan menjadi direction visual yang konsisten, mudah dipahami, dan dapat diakses",
      artifact: "visual brief dan accessibility checklist",
      guardrail: "Gunakan aset dan referensi yang kamu punya haknya. Hindari meniru seniman hidup, memakai wajah/kemiripan orang tanpa izin, atau menyembunyikan penggunaan AI bila konteksnya menuntut disclosure.",
      sources: [s.adobe, s.c2pa],
      topics: ["Visual Objective", "Hierarchy dan Scan Path", "Color dan Contrast", "Typography", "Composition", "Format serta Aspect Ratio", "Image Alt Text", "Colorblind Consideration", "Mobile Readability", "Brand Asset", "Visual QA", "Review Visual Brief"],
      opening: "Direction visual yang baik mengubah rasa abstrak menjadi keputusan tentang hierarki, komposisi, format, kontras, dan aksesibilitas. AI membantu variasi, tetapi brief menjaga komunikasi tetap utuh.",
      caseTitle: "Visual kampanye cantik tetapi teks tidak terbaca di ponsel",
      caseNarrative: "Tim fokus pada mood dan melupakan hierarchy. Setelah diuji di layar kecil, CTA hilang dalam gambar. Mereka memperbaiki visual brief dengan contrast, safe area, alt text, dan mobile QA.",
      teachingPoint: "Estetika dan aksesibilitas bukan trade-off; keduanya bagian dari komunikasi yang berhasil.",
      questions: ["Pesan apa yang dibaca pertama?", "Kontras apa yang perlu diuji?", "Bagaimana visual dijelaskan lewat alt text?"],
    }),
    checkpoint({
      title: "Audio, Video, dan Storyboard",
      level: "Menengah",
      focus: "memecah cerita multimedia menjadi beat, scene, narasi, visual, suara, durasi, dan titik review",
      artifact: "storyboard dan production brief",
      guardrail: safe,
      sources: [s.adobe, s.adobeVideo],
      topics: ["Story Arc", "Audience Attention", "Beat Sheet", "Scene Purpose", "Shot dan Composition", "Narration Script", "Music serta Sound", "Timing", "Subtitle dan Caption", "Disclosure", "Review Gate", "Review Storyboard"],
      opening: "Video atau audio AI yang baik tetap membutuhkan storyboard. Bab ini menguji cerita saat masih murah untuk diubah, sebelum tim menghabiskan waktu membuat aset yang tidak membawa audience ke pesan utama.",
      caseTitle: "Video promosi terasa mengilap tetapi tidak punya cerita",
      caseNarrative: "Tim membuat banyak klip visual tanpa tujuan per scene. Penonton tidak tahu masalah atau ajakan tindakannya. Mereka menulis beat sheet, scene purpose, narration, caption, timing, dan review gate.",
      teachingPoint: "Storyboard membuat kreativitas multimedia punya ritme, arah, dan ruang untuk review.",
      questions: ["Apa fungsi setiap scene?", "Apakah narasi dan visual selaras?", "Bagaimana konten dapat diakses tanpa suara?"],
    }),
    checkpoint({
      title: "Quality Review, Brand Safety, dan Moderation",
      level: "Menengah",
      focus: "meninjau kualitas, fakta, tone, safety, harm, dan kesesuaian brand sebelum konten dipublikasikan",
      artifact: "creative QA rubric dan review queue",
      guardrail: safe,
      sources: [s.adobe, s.copyright, s.wipo],
      topics: ["Quality Rubric", "Brand Safety", "Harmful Stereotype Check", "Factuality Check", "Sensitive Content", "Context Collapse", "Audience Appropriateness", "Moderation Escalation", "Reviewer Roles", "Disagreement Resolution", "Publish Hold", "Review QA Rubric"],
      opening: "Quality review menjaga konten sebelum ia bertemu audience nyata. Bab ini mengubah rasa 'kayaknya sudah aman' menjadi rubric, owner, escalation, dan keputusan publish/hold yang dapat dipertanggungjawabkan.",
      caseTitle: "Visual humor dipuji internal tetapi menyinggung komunitas tertentu",
      caseNarrative: "Review awal hanya melihat estetika. Setelah ada rubric context, stereotype, audience, dan escalation, tim memahami mengapa perspective beragam diperlukan sebelum konten tayang.",
      teachingPoint: "Brand safety adalah proses mendengar dampak potensial, bukan sekadar memblokir kata tertentu.",
      questions: ["Dampak apa yang mungkin tidak terlihat tim?", "Siapa perlu mereview konten ini?", "Kapan publish harus ditahan?"],
    }),
    checkpoint({
      title: "Rights, Consent, dan Intellectual Property",
      level: "Menengah",
      focus: "membuat kebiasaan memeriksa lisensi, attribution, consent, likeness, trademark, dan batas penggunaan sebelum publikasi",
      artifact: "rights clearance log dan consent checklist",
      guardrail: "Materi ini untuk literasi dan kebiasaan proses, bukan nasihat hukum. Untuk keputusan berisiko atau komersial, ikuti kebijakan organisasi dan cari nasihat profesional yang sesuai.",
      sources: [s.wipo, s.copyright],
      topics: ["Copyright Basics", "License dan Terms", "Public Domain Bukan Bebas Tanpa Konteks", "Attribution", "Trademark", "Likeness dan Personality", "Consent", "Training Data Question", "Output Similarity", "Client Asset", "Rights Escalation", "Review Clearance Log"],
      opening: "Mengakses aset atau menghasilkan gambar tidak otomatis memberi hak untuk memakainya. Bab ini mengajarkan cara menyimpan pertanyaan rights sebagai log dan kapan harus berhenti serta meminta review yang tepat.",
      caseTitle: "Klien meminta visual 'persis seperti' kreator terkenal",
      caseNarrative: "Tim menolak meniru identitas kreator hidup dan mengarahkan brief ke atribut komunikasi yang lebih umum: mood, contrast, material, audience, dan referensi berlisensi. Mereka mencatat keputusan dan alternatif.",
      teachingPoint: "Rights-aware creativity mencari cara baru mencapai tujuan tanpa mengambil identitas atau kerja orang lain secara tidak pantas.",
      questions: ["Aset ini berasal dari mana?", "Izin apa yang dibutuhkan?", "Kapan perlu escalation?"],
    }),
    checkpoint({
      title: "Provenance, Content Credentials, dan Transparency",
      level: "Menengah",
      focus: "mencatat asal, perubahan, kontribusi AI/manusia, dan disclosure yang membantu audience memahami konteks konten",
      artifact: "provenance record dan transparency note",
      guardrail: safe,
      sources: [s.adobe, s.c2pa, s.adobeVideo, s.c2paVideo],
      topics: ["Apa Itu Provenance", "Content Credentials", "Asset Origin", "Edit History", "Human Contribution", "AI Assistance Disclosure", "Metadata", "C2PA Intuisi", "Transparency Note", "Tamper dan Limitation", "Archive Strategy", "Review Provenance Record"],
      opening: "Provenance tidak menghakimi apakah konten baik atau buruk. Ia membantu audience dan tim memahami dari mana aset datang, perubahan besar apa yang terjadi, dan bagaimana AI berperan dalam proses.",
      caseTitle: "Klien menanyakan apakah visual dibuat sepenuhnya AI",
      caseNarrative: "Tim tidak punya catatan prompt, asset asal, atau edit manual. Mereka membuat provenance record, disclosure yang proporsional, dan folder versioned agar pertanyaan seperti ini dapat dijawab jujur.",
      teachingPoint: "Transparansi yang baik menambah konteks tanpa mengurangi apresiasi terhadap proses kreatif manusia.",
      questions: ["Kontribusi apa yang perlu dicatat?", "Disclosure apa yang relevan bagi audience?", "Batas apa yang tetap dimiliki provenance?"],
    }),
    checkpoint({
      title: "Distribusi, Community, dan Content Learning Loop",
      level: "Menengah",
      focus: "mendistribusikan konten dengan konteks kanal, moderasi, feedback, metric, dan iterasi yang tidak mengorbankan kepercayaan",
      artifact: "distribution plan dan learning loop dashboard",
      guardrail: safe,
      sources: [s.adobe, s.wipo],
      topics: ["Channel-Native Adaptation", "Distribution Timing", "Caption dan Context", "Community Guideline", "Comment Moderation", "Feedback Tagging", "Reach versus Value", "Qualitative Signal", "Content Experiment", "Repurpose with Context", "Archive dan Update", "Review Distribution Plan"],
      opening: "Konten selesai diproduksi bukan berarti selesai bekerja. Bab ini menghubungkan distribusi dengan context kanal, community care, feedback, metrik yang bermakna, dan keputusan iterasi yang tidak hanya mengejar angka dangkal.",
      caseTitle: "Konten viral membawa komentar yang salah paham",
      caseNarrative: "Tim merayakan reach, tetapi caption kurang konteks dan komentar membutuhkan moderasi. Mereka menyiapkan community guideline, response path, qualitative tagging, dan rencana update untuk konten yang berkembang.",
      teachingPoint: "Distribusi yang bertanggung jawab mempertimbangkan apa yang terjadi setelah konten mencapai orang lain.",
      questions: ["Konteks apa yang diperlukan tiap kanal?", "Feedback mana yang perlu ditindaklanjuti?", "Metrik apa yang benar-benar bermakna?"],
    }),
    checkpoint({
      title: "Creative Systems Capstone: Paket Konten Transparan",
      level: "Lanjut",
      focus: "menyatukan strategi, brief, riset, prompt system, produksi, QA, rights, provenance, dan distribution menjadi paket konten yang dapat direview",
      artifact: "creative campaign dossier",
      guardrail: safe,
      sources: [s.adobe, s.c2pa, s.wipo, s.copyright, s.adobeVideo, s.c2paVideo],
      topics: ["Memilih Tema Capstone", "Menyusun Strategy One-Pager", "Membuat Voice Guide", "Membuat Research Pack", "Membuat Prompt Library", "Menulis Editorial Draft", "Menyusun Visual atau Storyboard", "Menjalankan Quality Review", "Melengkapi Rights Log", "Membuat Provenance Record", "Menyusun Distribution Plan", "Presentasi dan Retrospektif Creative"],
      opening: "Capstone adalah paket bukti bahwa sebuah kampanye dapat dibuat dengan imajinasi sekaligus tanggung jawab. Kamu akan menunjukkan alasan audience, proses editorial, quality, rights, provenance, dan cara belajar setelah publikasi.",
      caseTitle: "Studio Rasa menyiapkan kampanye peluncuran yang dapat dipercaya",
      caseNarrative: "Tim menyatukan brief, sumber, visual, copy, caption, accessibility, review, rights log, disclosure, Content Credentials, dan distribution plan. Mereka memilih transparansi yang relevan daripada menyembunyikan proses AI.",
      teachingPoint: "Creative system yang matang membuat karya lebih mudah dikembangkan, direview, dan dipercaya.",
      questions: ["Apa bukti paket ini siap dipublikasikan?", "Rights atau disclosure apa yang masih perlu dicek?", "Apa yang akan dipelajari dari respons audience?"],
    }),
  ],
});

export const creativeIntensiveMaterials = createIntensiveCourseMaterials(creativeCourse);
