import type { Material, MaterialLevel, QuizQuestion } from "./materials";

type SourceKey = keyof typeof sources;

const sources = {
  cs50: { label: "CS50: Intro to Cybersecurity — Full Course", url: "https://youtu.be/9HOpanT0GRs", note: "Fondasi keamanan akun, data, sistem, perangkat lunak, dan trade-off risiko." },
  handsOn: { label: "Hands-On Cybersecurity & Ethical Hacking — Full Course", url: "https://youtu.be/ug8W0sFiVJo", note: "Kali/Linux, observabilitas jaringan, dan pemahaman lab berizin dari sumber asli." },
  ethicalOne: { label: "Ethical Hacking in 15 Hours — Part 1", url: "https://youtu.be/3FNYvj2U0HM", note: "Networking, Linux, Python, metode kerja, dan passive recon dalam konteks legal." },
  ethicalTwo: { label: "Ethical Hacking in 15 Hours — Part 2", url: "https://youtu.be/sH4JCwjybGs", note: "Inventory layanan, research risiko, dokumentasi temuan, dan capstone lab." },
  webSecurity: { label: "Hacking Web Applications", url: "https://youtu.be/1GJ_LwNw6sc", note: "Pola keamanan aplikasi web dari sudut pencegahan dan perbaikan." },
  ethicalTwelve: { label: "Ethical Hacking in 12 Hours", url: "https://youtu.be/fNzpcB7ODxQ", note: "Peta skill, lab legal, dan kebiasaan dokumentasi." },
  osint: { label: "Open-Source Intelligence (OSINT) in 5 Hours", url: "https://youtu.be/qwA6MmbeGNo", note: "OSINT beretika, verifikasi, dan batas privasi." },
  webBeginner: { label: "Beginner Web Application Hacking", url: "https://youtu.be/24fHLWXGS-M", note: "Konsep keamanan aplikasi web untuk pemula." },
  memory: { label: "Buffer Overflows Made Easy", url: "https://youtu.be/ncBblM920jw", note: "Kesadaran batas memori dan coding defensif; bukan panduan eksploit." },
  kali: { label: "Linux for Ethical Hackers — Kali Linux Course", url: "https://youtu.be/U1w4T03B30I", note: "Linux/Kali sebagai lingkungan lab legal." },
  python: { label: "Python for Beginners — Full Course", url: "https://youtu.be/7utwZYKweho", note: "Fondasi otomatisasi defensif dan pembacaan data." },
  linuxPrivilege: { label: "Linux Privilege Escalation for Beginners", url: "https://youtu.be/ZTnwg3qCdVM", note: "Audit permission dan konfigurasi Linux pada aset berizin." },
  windowsPrivilege: { label: "Windows Privilege Escalation for Beginners", url: "https://youtu.be/uTcrbNBcoxQ", note: "Audit konfigurasi dan hak akses Windows pada lingkungan berizin." },
  activeDirectory: { label: "Hacking Active Directory for Beginners", url: "https://youtu.be/VXxH4n684HE", note: "Identity, directory, grup, perangkat, dan kebijakan organisasi." },
  bugBounty: { label: "Practical Bug Bounty", url: "https://youtu.be/wS2z5lt34Cc", note: "Scope, bukti minimum, disclosure, dan laporan yang bertanggung jawab." },
  rust: { label: "Rust Programming 101", url: "https://youtu.be/RU7BYxmSBNg", note: "Perspektif coding modern yang sadar memori." },
  soc: { label: "Security Operations (SOC) 101", url: "https://youtu.be/56NDgBOSpUg", note: "Log, alert, triage, eskalasi, dan operasi keamanan sehari-hari." },
  powershell: { label: "Intro to PowerShell", url: "https://youtu.be/GyvEMcMh3rc", note: "Otomasi administrasi yang dapat diaudit." },
  ai: { label: "Learn AI Fundamentals", url: "https://youtu.be/VdWqEd56HTQ", note: "Fondasi AI untuk membahas tool, agent, data, dan kontrol." },
  helpDesk: { label: "Practical Help Desk", url: "https://youtu.be/2MvT63eZfp0", note: "Endpoint hygiene, ticketing, eskalasi, dan operasi defensif." },
  iot: { label: "IoT & Hardware Hacking for Beginners", url: "https://youtu.be/j8SqZLr64NA", note: "Inventaris perangkat terhubung, firmware, jaringan, dan lifecycle." },
  career: { label: "Full-Length Hacking Courses — Soft Skills & Career", url: "https://youtube.com/playlist?list=PLLKT__MCUeixqHJ1TRqrHsEd6_EdEvo47", note: "Dua video soft skill playlist: melamar kerja dan membangun pembeda yang jujur." },
};

type Chapter = {
  title: string;
  level: MaterialLevel;
  focus: string;
  artifact: string;
  guardrail: string;
  sources: SourceKey[];
  units: readonly string[];
};

const chapters: readonly Chapter[] = [
  { title: "Kontrak Belajar, Etika, dan Cara Berpikir Risiko", level: "Pemula", focus: "keputusan keamanan selalu dimulai dari izin, aset yang bernilai, dampak ke manusia, dan kontrol yang proporsional", artifact: "worksheet scope–aset–dampak–kontrol untuk proyek atau lab milik sendiri", guardrail: "Jangan memindai, menguji, atau mengumpulkan data dari sistem lain tanpa izin tertulis dan batas aset yang jelas.", sources: ["cs50", "ethicalOne", "ethicalTwelve", "handsOn"], units: ["Tujuan pembela vs rasa penasaran tanpa scope", "Izin tertulis dan batas aset", "Data fiktif, snapshot, dan rollback", "Dampak pada orang, layanan, dan reputasi", "CIA sebagai bahasa awal", "Threat model satu halaman", "Aset, actor, dan jalur dampak", "Kontrol preventif, detektif, korektif", "Risiko, likelihood, dan prioritas", "Evidence minimum", "Catatan yang bisa diaudit", "Refleksi keputusan aman pertama"] },
  { title: "Peta Profesi, Catatan, dan Metodologi Kerja", level: "Pemula", focus: "kualitas kerja security lahir dari scope yang presisi, observasi yang terpisah dari asumsi, dan dokumentasi yang bisa diteruskan tim", artifact: "notebook investigasi fiktif dengan timeline, asumsi, bukti, dan keputusan", guardrail: "Catatan tidak boleh memuat password, token, data pribadi, atau temuan sensitif di kanal terbuka.", sources: ["ethicalOne", "ethicalTwo", "soc", "helpDesk", "career"], units: ["Hari kerja keamanan yang realistis", "Peran blue team, appsec, dan pentest berizin", "Mengubah pertanyaan kabur menjadi scope", "Struktur notebook investigasi", "Timebox dan decision log", "Menulis asumsi", "Membedakan observasi dan inferensi", "Membuat bukti yang bisa diulang", "Prioritas berdasarkan dampak", "Handoff antartim", "Bahasa laporan tanpa drama", "Retrospektif tanpa menyalahkan"] },
  { title: "Jaringan dari Paket ke Keputusan", level: "Pemula", focus: "jaringan dipahami sebagai jalur komunikasi dengan identitas, aturan, batas kepercayaan, dan titik diagnosis", artifact: "diagram perangkat–DNS–gateway–layanan untuk aplikasi yang kamu kontrol", guardrail: "Gunakan trafik, perangkat, dan jaringan lab sendiri; jangan membaca komunikasi orang lain.", sources: ["ethicalOne", "handsOn", "soc"], units: ["Model mental paket", "IPv4 dan alamat privat", "Gateway dan segmentasi", "MAC sebagai konteks lokal", "DNS dan nama layanan", "TCP sebagai percakapan", "UDP dan trade-off", "Port sebagai kontrak layanan", "HTTPS dan boundary trust", "OSI untuk diagnosis", "Subnet sebagai kontrol blast radius", "Diagram jalur aplikasi sendiri"] },
  { title: "Lab Linux/Kali yang Bersih dan Terpulihkan", level: "Pemula", focus: "lingkungan belajar yang baik dipisahkan dari perangkat kerja, terdokumentasi, mudah direset, dan tidak memberi dampak ke pihak lain", artifact: "rancangan VM lab berisi host, snapshot, jaringan, data fiktif, dan tombol rollback", guardrail: "Tool security bukan izin. Semua eksperimen dibatasi pada VM, aplikasi latihan, atau aset yang kamu miliki.", sources: ["ethicalOne", "handsOn", "kali"], units: ["Host vs VM", "Memilih hypervisor", "Snapshot sebelum eksperimen", "Isolasi jaringan lab", "Instalasi sebagai supply-chain decision", "Update dan catatan versi", "Orientasi Kali tanpa fetish tool", "Terminal sebagai alat observasi", "Struktur filesystem", "Service lifecycle", "Paket dan provenance", "Reset lab dan review bukti"] },
  { title: "Linux Praktis untuk Administrasi Aman", level: "Pemula", focus: "perintah terminal adalah cara membaca keadaan, mengubah dengan sengaja, dan menyisakan jejak perubahan yang bisa direview", artifact: "checklist perubahan aman untuk file dan konfigurasi di VM sendiri", guardrail: "Jangan menyalin perintah yang tidak dipahami ke perangkat produksi atau akun yang bukan milikmu.", sources: ["handsOn", "kali", "helpDesk"], units: ["ls sebagai pembacaan inventory", "cd dan konteks lokasi", "File dan metadata", "Nano serta perubahan terkontrol", "cat untuk membaca, bukan membocorkan", "Directory sebagai boundary", "grep untuk pencarian bukti", "wc untuk baseline", "Redirection dan risiko log", "Pipe sebagai alur review", "Copy, remove, dan rollback", "Checklist perubahan aman"] },
  { title: "Akun, Hak Akses, dan Hygiene Endpoint", level: "Pemula", focus: "identitas yang sehat memakai autentikasi kuat, hak minimum, recovery yang aman, serta lifecycle akses yang memiliki owner", artifact: "matriks akun, perangkat, faktor MFA, owner, dan jadwal review", guardrail: "Jangan meminta atau menyimpan credential orang lain; latihan hanya menggunakan akun pribadi atau fiktif.", sources: ["cs50", "handsOn", "linuxPrivilege", "windowsPrivilege", "activeDirectory", "helpDesk"], units: ["Jenis user", "Root sebagai tanggung jawab", "sudo dan audit trail", "Password unik", "MFA dan fatigue", "Recovery tanpa kebocoran", "Sesi dan perangkat tepercaya", "Joiner–mover–leaver", "Least privilege", "Permission review", "Offboarding", "Audit akun triwulanan"] },
  { title: "Observabilitas Jaringan dan Inventaris Aset", level: "Menengah", focus: "inventaris dan baseline memungkinkan tim mengurangi paparan layanan sebelum mereka berburu masalah yang belum tentu ada", artifact: "register aset lab berisi owner, fungsi layanan, paparan, baseline, dan tindakan pengurangan risiko", guardrail: "Observasi layanan dilakukan hanya pada aset berizin; tidak ada pemetaan target publik atau organisasi tanpa scope.", sources: ["handsOn", "ethicalOne", "ethicalTwo", "soc"], units: ["Mengapa inventory mendahului pemindaian", "Pemilik aset", "Port sebagai paparan layanan", "Baseline layanan lab", "Membaca hasil inventory", "Nmap sebagai konsep pemetaan aset berizin", "False positive dan false negative", "Layanan HTTP", "Layanan SMB", "Layanan SSH", "Exposure review", "Rencana pengurangan attack surface"] },
  { title: "Wi-Fi dan Traffic sebagai Permukaan Keamanan", level: "Menengah", focus: "jaringan nirkabel diperlakukan sebagai aset bersama yang perlu konfigurasi, segmentasi, pembaruan, dan observabilitas", artifact: "rencana hardening Wi-Fi rumah atau lab yang hanya menggunakan perangkat sendiri", guardrail: "Tidak ada penangkapan trafik, gangguan koneksi, atau pemulihan kata sandi pada jaringan yang tidak kamu miliki.", sources: ["handsOn", "ethicalTwelve", "iot"], units: ["SSID bukan identitas", "Router sebagai aset", "Band 2.4 vs 5 GHz", "Mode jaringan sebagai konsep", "Handshake sebagai proses protokol", "Risiko password default", "Segmentasi tamu", "Update firmware", "WPA dan keputusan konfigurasi", "Indikator gangguan koneksi", "Membaca PCAP latihan", "Runbook anomali Wi-Fi"] },
  { title: "Web: Input, Session, dan Otorisasi", level: "Menengah", focus: "aplikasi aman memperlakukan data eksternal sebagai tidak tepercaya dan memutuskan akses di server, bukan pada tampilan semata", artifact: "matriks input–validasi–otorisasi–log untuk aplikasi milik sendiri", guardrail: "Bahas pola desain dan pengujian lokal; jangan mencoba mengakses akun, data, atau peran yang bukan milikmu.", sources: ["webSecurity", "webBeginner", "cs50"], units: ["Request dan response", "Input tidak tepercaya", "Validasi format", "Validasi konteks", "Encoding output", "Authentication", "Authorization", "Session lifecycle", "Cookie boundary", "Error tanpa kebocoran", "Rate limit sebagai kontrol", "Uji desain pada aplikasi sendiri"] },
  { title: "Asset Discovery dan OSINT yang Beretika", level: "Menengah", focus: "informasi publik hanya dikumpulkan jika relevan dengan tujuan defensif, memiliki batas privasi, dan menghasilkan tindakan perbaikan yang sah", artifact: "laporan exposure organisasi fiktif berisi sumber, tanggal, tingkat keyakinan, owner, dan jalur disclosure", guardrail: "Informasi publik bukan izin untuk doxxing, stalking, impersonasi, atau penelitian terhadap kehidupan pribadi.", sources: ["ethicalTwo", "osint", "bugBounty"], units: ["Tujuan discovery defensif", "Domain dan subdomain", "Ownership dan approval", "Identifikasi teknologi untuk patching", "Public exposure review", "Mesin pencari sebagai sumber primer", "Social media tanpa doxxing", "Membedakan klaim dan bukti", "Tanggal, provenance, dan konteks", "Secret exposure response", "Disclosure channel", "Laporan exposure minimal"] },
  { title: "Vulnerability Management Tanpa Sensasionalisme", level: "Menengah", focus: "sinyal kerentanan harus diikat ke aset, dampak, bukti minimum, owner, prioritas remediasi, dan retest", artifact: "backlog risiko fiktif dengan severity, alasan prioritas, compensating control, dan tanggal review", guardrail: "Jangan memvalidasi temuan dengan mengakses data atau membuat dampak pada sistem pihak lain.", sources: ["ethicalTwo", "handsOn", "soc", "bugBounty"], units: ["CVE sebagai bahasa bersama", "Aset sebelum severity", "Dampak vs skor", "Scanner sebagai sinyal", "Validasi tanpa menyentuh data", "False positive", "Evidence minimum", "Patch window", "Compensating control", "Exception berumur", "Retest dan closure", "Dashboard risiko yang jujur"] },
  { title: "Konfigurasi Sistem dan Identity Organisasi", level: "Menengah", focus: "konfigurasi dan identity adalah graph kepercayaan yang perlu baseline, owner, review perubahan, serta pembatasan hak", artifact: "diagram organisasi fiktif berisi user, grup, perangkat, service account, owner, dan review cadence", guardrail: "Latihan hanya memakai contoh fiktif atau directory lab; jangan mengubah kebijakan organisasi tanpa persetujuan change management.", sources: ["linuxPrivilege", "windowsPrivilege", "activeDirectory", "powershell", "helpDesk"], units: ["Configuration drift", "Baseline hardening", "Permission di Linux", "Permission di Windows", "Service account", "Local admin", "Active Directory sebagai trust graph", "Group membership", "GPO sebagai kebijakan", "Endpoint onboarding", "Change approval", "Audit akses berbasis risiko"] },
  { title: "Rahasia, Dependency, dan Supply Chain", level: "Menengah", focus: "rahasia dan software pihak ketiga harus memiliki provenance, scope minimum, rotasi, review versi, staging, dan rencana pemulihan", artifact: "inventory secret dan dependency untuk proyek contoh lengkap dengan owner serta langkah rotasi", guardrail: "Jangan menempelkan key asli, token, konfigurasi rahasia, atau bukti sensitif ke tugas maupun repo.", sources: ["cs50", "webSecurity", "rust", "python", "ethicalTwo"], units: ["Apa yang disebut secret", "Scope key", "Secret storage", "Rotasi", "Revocation", "Log redaction", "Dependency inventory", "Versi dan patch", "Provenance package", "Staging update", "Rollback", "Postmortem secret leak"] },
  { title: "Python, PowerShell, dan Automasi Read-Only", level: "Menengah", focus: "otomasi defensif yang baik membaca data terkontrol, menghasilkan ringkasan yang dapat dicek, dan tidak menyimpan credential atau memodifikasi sistem", artifact: "skrip analisis CSV/log fiktif dan catatan asumsi input–outputnya", guardrail: "Gunakan data fiktif dan mode read-only; jangan membuat skrip yang menyentuh target tanpa authorization eksplisit.", sources: ["ethicalOne", "python", "powershell", "soc"], units: ["Data fiktif dulu", "String dan normalisasi", "Variable sebagai kontrak", "Function kecil", "Boolean dan guard", "List dan batch review", "Dictionary sebagai event", "File I/O aman", "Import dan dependency", "Socket sebagai konsep observasi", "PowerShell untuk inventaris", "Automasi yang bisa diaudit"] },
  { title: "Kode Aman dan Kesadaran Memori", level: "Menengah", focus: "kesalahan batas, tipe, dan lifecycle data dikurangi melalui desain, validasi, test, patch, serta code review yang memahami trade-off", artifact: "memo secure code review untuk fungsi fiktif berisi boundary, test, failure mode, dan rekomendasi", guardrail: "Materi mempelajari pencegahan dan analisis kualitas; tidak mengajarkan eksploitasi crash atau eksekusi kode.", sources: ["memory", "rust", "ethicalTwo"], units: ["Boundary input", "Panjang dan tipe", "Error handling", "Unsafe pattern review", "Memory safety sebagai desain", "Fuzzing sebagai konsep quality assurance", "Crash evidence", "Patch priority", "Rust ownership sebagai konteks", "Dependency isolation", "Regression test", "Secure code review memo"] },
  { title: "Logs, Telemetry, dan SOC Triage", level: "Menengah", focus: "telemetry yang berguna memisahkan sinyal dari noise, menjaga privasi, memberi owner, dan mendukung keputusan triage yang dapat diaudit", artifact: "playbook alert fiktif berisi event, severity, pertanyaan triage, owner, SLA, dan eskalasi", guardrail: "Jangan mengumpulkan lebih banyak data daripada tujuan keamanan yang jelas dan disetujui.", sources: ["soc", "helpDesk", "powershell"], units: ["Event vs log", "Authentication telemetry", "Endpoint telemetry", "Network telemetry", "Data minimization", "Alert threshold", "Severity", "Triage question", "Timeline", "Escalation", "Ticket hygiene", "False positive learning loop"] },
  { title: "Incident Response dan Responsible Disclosure", level: "Lanjut", focus: "respons insiden yang matang memprioritaskan keselamatan, containment proporsional, bukti, komunikasi, remediasi, dan pembelajaran tanpa kambing hitam", artifact: "runbook insiden fiktif untuk secret leak atau account compromise beserta owner dan jalur komunikasi", guardrail: "Jika ada risiko nyata, ikuti prosedur organisasi atau kanal disclosure; jangan menghapus bukti atau menyebarkan detail sensitif.", sources: ["soc", "bugBounty", "ethicalTwo", "cs50"], units: ["Trigger insiden", "Containment tanpa panik", "Preservasi bukti", "Komunikasi internal", "Owner keputusan", "Secret exposure response", "Account compromise response", "Malware suspicion response", "Pelaporan kerentanan", "Safe harbor", "Remediasi dan retest", "Postmortem tanpa kambing hitam"] },
  { title: "AI, Agent, dan Input yang Tidak Tepercaya", level: "Lanjut", focus: "AI dan agent harus diperlakukan sebagai komponen probabilistik dengan data boundary, izin teknis, validasi server, approval manusia, dan jejak audit", artifact: "matriks kemampuan agent: baca, draf, rekomendasi, approval, aksi, serta kill switch", guardrail: "Jangan menguji prompt injection atau tool abuse pada layanan pihak lain; gunakan contoh sendiri dan environment yang diizinkan.", sources: ["ai", "cs50", "webSecurity"], units: ["Model bukan policy engine", "Data classification", "Prompt sebagai input", "Prompt injection sebagai boundary failure", "Tool permission", "Human approval", "Retrieval trust", "Output validation", "Auditability", "Cost and rate limits", "Agent kill switch", "Evaluasi abuse case"] },
  { title: "IoT, Perangkat Kecil, dan Aset Fisik", level: "Lanjut", focus: "perangkat terhubung memiliki identitas, firmware, jaringan, owner, lifecycle, dan risiko fisik yang tidak boleh hilang dari inventory", artifact: "register perangkat rumah atau kantor fiktif dengan owner, update, jaringan, vendor, dan jadwal review", guardrail: "Jangan mengakses perangkat tetangga, publik, atau organisasi tanpa izin eksplisit, termasuk untuk 'sekadar mengecek'.", sources: ["iot", "helpDesk", "handsOn"], units: ["Inventory perangkat", "Owner dan lifecycle", "Default credential risk", "Firmware", "Segmentasi", "Remote administration", "Physical access", "Telemetry perangkat", "Consumer vs enterprise IoT", "Disposal", "Vendor risk", "Household/office hardening plan"] },
  { title: "Capstone: Rencana Security yang Bisa Dipertanggungjawabkan", level: "Lanjut", focus: "seluruh konsep disatukan menjadi rencana perbaikan yang memiliki aset, owner, bukti, prioritas, batas biaya, komunikasi, dan review berkala", artifact: "roadmap 30–60–90 hari untuk proyek milik sendiri atau organisasi fiktif", guardrail: "Capstone bukan penetration test. Bila ada temuan nyata, gunakan jalur eskalasi yang sah dan jangan membuat klaim yang tidak dapat dibuktikan.", sources: ["cs50", "handsOn", "ethicalOne", "ethicalTwo", "webSecurity", "osint", "memory", "kali", "python", "activeDirectory", "bugBounty", "soc", "ai", "iot", "career"], units: ["Memilih aset berizin", "Inventaris dan owner", "Threat model", "Access review", "Exposure review", "Logging plan", "Vulnerability backlog", "Incident runbook", "Secret and dependency plan", "AI/IoT scope bila relevan", "Executive-friendly report", "Roadmap 30–60–90 hari"] },
];

const chapterMoves: readonly (readonly string[])[] = [
  ["Bandingkan rasa ingin tahu dengan mandat kerja tertulis.", "Tandai tiga batas yang tidak boleh dilampaui.", "Rancang data contoh yang aman dibuang.", "Tuliskan siapa yang terdampak bila layanan terganggu.", "Klasifikasikan satu aset menurut confidentiality, integrity, dan availability.", "Buat peta ancaman satu halaman untuk aplikasi catatan pribadi.", "Hubungkan aset, pelaku, dan dampak dengan panah.", "Pasangkan risiko ke kontrol preventif, detektif, serta korektif.", "Urutkan tiga risiko berdasarkan dampak dan peluang.", "Pilih bukti terkecil yang cukup mendukung keputusan.", "Pisahkan fakta, sumber, dan keputusan pada catatanmu.", "Tulis satu keputusan aman yang akan kamu ulang minggu depan."],
  ["Buat peta peran keamanan tanpa menyebut jabatan keren semata.", "Bedakan mandat blue team, appsec, dan assessment berizin.", "Ubah permintaan 'cek aman tidak' menjadi tiga pertanyaan scope.", "Buat template notebook: waktu, fakta, asumsi, keputusan.", "Timebox sebuah review agar tidak berubah menjadi browsing tanpa tujuan.", "Catat asumsi yang perlu dikonfirmasi owner.", "Warnai mana observasi dan mana interpretasi.", "Tulis langkah reproduksi yang aman untuk temuan fiktif.", "Pilih prioritas berdasarkan dampak operasional.", "Serahkan catatan ke teman dan ukur apakah ia paham konteksnya.", "Ringkas temuan dalam bahasa yang tidak memalukan pihak lain.", "Tulis retrospektif dengan fokus proses, bukan orang."],
  ["Gambar perjalanan satu request dari perangkat ke layanan.", "Beri alamat privat pada perangkat lab imajiner.", "Tentukan peran gateway pada dua segmen rumah.", "Jelaskan mengapa MAC tidak menggantikan identitas aplikasi.", "Buat catatan resolusi nama untuk satu domain contoh.", "Urutkan pembukaan dan penutupan koneksi TCP secara konsep.", "Pilih kapan UDP masuk akal tanpa menganggapnya kurang aman otomatis.", "Hubungkan port ke owner dan fungsi layanannya.", "Tandai titik yang memberi jaminan HTTPS dan titik yang tidak.", "Gunakan OSI untuk mengelompokkan tiga gejala gangguan.", "Bagi lab kecil menjadi dua subnet menurut fungsi.", "Review diagram bersama teman dan cari trust boundary yang hilang."],
  ["Pilih tugas yang tetap di host dan yang pantas di VM.", "Tulis alasan memilih hypervisor, bukan hanya mengikuti tutorial.", "Beri nama snapshot sebelum perubahan dan alasan rollbacknya.", "Pilih mode jaringan lab berdasarkan dampak yang diizinkan.", "Catat asal image dan hash/versi yang diverifikasi.", "Buat log update berisi waktu, paket, dan hasil.", "Kelompokkan tool berdasarkan tujuan defensifnya, bukan popularitasnya.", "Gunakan terminal untuk inventaris konfigurasi lokal.", "Temukan lokasi konfigurasi tanpa mengubah file.", "Tuliskan service yang boleh aktif di lab dan alasannya.", "Periksa asal paket sebelum memasangnya.", "Latih reset VM dan buktikan artefak tes sudah hilang."],
  ["Baca daftar file sebagai inventaris, bukan sekadar daftar nama.", "Nyatakan lokasi kerja sebelum berpindah direktori.", "Bandingkan nama file, pemilik, ukuran, dan waktu modifikasi.", "Rancang perubahan kecil yang bisa dibatalkan lewat editor.", "Baca file contoh tanpa memasukkan secret ke terminal history.", "Buat struktur folder berdasarkan boundary data.", "Cari indikator pada log fiktif dengan pola yang dapat dijelaskan.", "Gunakan hitungan baris sebagai baseline sebelum menyimpulkan anomali.", "Jelaskan ke mana output diarahkan dan siapa bisa membacanya.", "Sketsa alur pipe sebagai tahapan review data.", "Buat salinan aman sebelum menghapus data contoh.", "Tulis checklist peer review untuk perubahan konfigurasi."],
  ["Kelompokkan akun manusia, layanan, dan darurat secara terpisah.", "Jelaskan mengapa root bukan akun kerja harian.", "Catat aksi admin yang perlu audit trail.", "Susun kebijakan password unik tanpa meminta password asli.", "Rancang respons saat MFA memunculkan prompt mencurigakan.", "Tulis recovery flow yang tidak membuka bypass permanen.", "Review perangkat yang masih punya sesi aktif.", "Petakan perubahan akses saat seseorang pindah tim.", "Hapus satu hak yang tidak diperlukan dari persona fiktif.", "Tentukan bukti untuk review permission.", "Rancang offboarding yang mempertimbangkan data dan token.", "Buat kalender review akun berdasarkan risiko."],
  ["Jelaskan mengapa nama aset datang sebelum tool pemetaan.", "Tetapkan owner yang bisa menyetujui perubahan exposure.", "Buat daftar port yang memang diharapkan pada VM lab.", "Bandingkan baseline layanan dengan kondisi hari ini.", "Tuliskan arti setiap kolom hasil inventaris.", "Dokumentasikan scope lab sebelum memakai konsep Nmap.", "Tandai sinyal yang masih butuh validasi.", "Hubungkan layanan web ke patch owner.", "Bedakan file sharing sah dari exposure yang tak dimaksudkan.", "Tinjau akses remote dan kebutuhan authentication-nya.", "Pilih satu layanan yang bisa dipersempit paparan-nya.", "Susun rencana pengurangan attack surface yang dapat diukur."],
  ["Buktikan bahwa nama Wi-Fi tidak cukup untuk identitas perangkat.", "Masukkan router ke inventory beserta owner dan lokasi.", "Bandingkan kebutuhan 2.4 GHz dan 5 GHz tanpa mitos.", "Jelaskan mode jaringan sebagai perubahan kemampuan perangkat.", "Gambar handshake sebagai pertukaran protokol, bukan trik.", "Audit password default pada perangkat yang kamu miliki.", "Pisahkan perangkat tamu dari perangkat utama.", "Jadwalkan update firmware dan catat hasilnya.", "Pilih konfigurasi WPA yang didukung perangkatmu.", "Buat daftar gejala gangguan koneksi yang perlu dicatat.", "Baca sampel PCAP aman untuk mengenali struktur paket.", "Tulis runbook ketika pola gangguan muncul kembali."],
  ["Gambar request dan response untuk satu form sendiri.", "Tandai semua input yang berasal dari pengguna atau pihak ketiga.", "Buat aturan format sebelum data masuk proses bisnis.", "Tambahkan aturan konteks yang tidak bisa diperiksa oleh format saja.", "Pilih lokasi encoding yang sesuai dengan output.", "Bedakan bukti identitas dan bukti hak akses.", "Uji matriks peran pada data fiktif.", "Tuliskan kapan sesi dibuat, diperbarui, dan berakhir.", "Review atribut cookie tanpa menyalin token nyata.", "Ganti error bocor dengan pesan aman dan log internal.", "Pilih limit berdasar dampak, bukan angka asal.", "Review aplikasi sendiri dengan checklist input–authz–log."],
  ["Tuliskan satu tujuan discovery yang bisa dijelaskan ke owner.", "Buat daftar domain lab beserta kepemilikannya.", "Cari bukti approval sebelum menambahkan aset ke scope.", "Hubungkan teknologi yang terdeteksi dengan owner patch.", "Review exposure publik untuk aset yang memang kamu kelola.", "Simpan URL dan tanggal saat memakai mesin pencari.", "Pisahkan profil profesional dari detail personal yang tidak relevan.", "Beri label fakta, klaim, dan hipotesis.", "Catat provenance serta tanggal kedaluwarsa informasi.", "Buat respons aman untuk secret contoh yang tidak sengaja muncul.", "Pilih kanal disclosure sebelum menulis detail.", "Buat laporan exposure yang tidak memperbesar risiko."],
  ["Jelaskan mengapa identitas CVE belum menjawab risiko organisasi.", "Hubungkan setiap isu dengan aset dan owner nyata/fiktif.", "Bandingkan skor teknis dengan dampak bisnis.", "Perlakukan hasil scanner sebagai antrean validasi.", "Buat cara validasi yang tidak membaca atau mengubah data.", "Catat alasan mengapa sinyal bisa false positive.", "Pilih bukti yang cukup untuk ticket tanpa mempublikasikan detail.", "Tetapkan window patch beserta alasan urutan.", "Tulis kontrol sementara yang bisa dipantau.", "Beri expiry date pada exception.", "Definisikan arti retest lulus.", "Buat dashboard yang menunjukkan risiko tersisa, bukan angka cantik."],
  ["Cari satu contoh drift konfigurasi pada mesin lab.", "Tulis baseline yang bisa dibandingkan, bukan slogan hardening.", "Bedakan file permission Linux dengan ownership.", "Buat matriks permission Windows sederhana.", "Berikan owner, scope, dan expiry untuk service account fiktif.", "Review alasan local admin pada satu persona.", "Gambar AD sebagai relasi trust, bukan daftar server.", "Uji kejelasan tujuan sebuah group.", "Tulis perubahan GPO dalam bahasa dampak bisnis.", "Buat checklist onboarding endpoint.", "Simulasikan approval perubahan yang butuh dua pihak.", "Jadwalkan audit akses berdasarkan risiko tertinggi."],
  ["Klasifikasikan secret dan data biasa pada proyek contoh.", "Kecilkan scope key sampai hanya punya fungsi perlu.", "Pilih lokasi penyimpanan yang tidak ikut terkirim ke repo.", "Rancang rotasi tanpa membuat layanan berhenti.", "Tentukan kapan credential harus dicabut segera.", "Cari jalur log yang perlu redaction.", "Buat bill of materials dependency sederhana.", "Catat versi, update, dan alasan menunda patch.", "Nilai asal package sebelum memasukkan dependency baru.", "Buat staging check sebelum update produksi.", "Tulis jalur rollback yang sudah diuji.", "Jalankan postmortem secret leak fiktif tanpa menyalahkan."],
  ["Buat dataset CSV fiktif yang tidak mengandung PII.", "Normalisasi string sebelum membandingkan event.", "Pilih nama variable yang menjelaskan keputusan.", "Pecah automasi menjadi function yang bisa dites.", "Tambahkan guard sebelum aksi yang berisiko.", "Buat batch kecil dan periksa hasilnya.", "Modelkan satu event sebagai dictionary yang jelas.", "Tangani file input yang kosong atau formatnya salah.", "Audit asal library yang diimpor.", "Jelaskan konsep socket tanpa menghubungi target luar.", "Gunakan PowerShell untuk inventory lokal read-only.", "Tulis readme yang menjelaskan input, output, dan batas skrip."],
  ["Tandai boundary yang wajib dicek dari satu fungsi contoh.", "Tetapkan batas panjang dan tipe sebelum data diproses.", "Pisahkan error pengguna dari error yang perlu log internal.", "Kenali pola unsafe tanpa mereproduksi exploit.", "Jelaskan mengapa memory safety adalah pilihan desain.", "Buat daftar properti yang ingin diuji secara acak.", "Simpan crash evidence dari program latihan tanpa payload.", "Prioritaskan patch menurut dampak dan exposure.", "Gunakan ownership Rust untuk menjelaskan lifecycle data.", "Isolasi dependency yang memiliki fungsi berbeda.", "Tambahkan test regresi untuk kesalahan yang pernah ditemukan.", "Tulis memo code review yang bisa ditindaklanjuti."],
  ["Bedakan fakta event dengan baris log mentah.", "Pilih field autentikasi yang perlu dikorelasikan.", "Hubungkan endpoint event dengan owner perangkat.", "Tentukan sinyal network yang relevan dengan scope.", "Hapus field tidak perlu dari contoh telemetry.", "Tulis alasan threshold dan risiko noise.", "Petakan severity ke dampak dan SLA.", "Buat tiga pertanyaan triage sebelum eskalasi.", "Susun timeline tanpa melompati bukti.", "Tentukan kondisi kapan owner lain perlu dilibatkan.", "Jaga ticket agar konteks dapat diteruskan shift berikutnya.", "Catat false positive sebagai bahan tuning, bukan kegagalan memalukan."],
  ["Tentukan kondisi yang benar-benar memicu proses insiden.", "Pilih containment paling kecil yang melindungi layanan.", "Simpan bukti sebelum membuat perubahan besar.", "Buat pesan internal yang jujur dan tidak spekulatif.", "Tentukan owner keputusan dan pengganti bila tidak tersedia.", "Latih respons secret leak pada token contoh.", "Latih pemulihan akun fiktif dengan catatan waktu.", "Tulis langkah awal saat ada dugaan malware tanpa menjalankan sample.", "Buat laporan kerentanan yang fokus dampak dan remediasi.", "Cari kebijakan safe harbor yang berlaku sebelum disclosure.", "Definisikan bukti bahwa perbaikan benar-benar menutup risiko.", "Tulis postmortem dengan action item dan due date."],
  ["Bedakan jawaban model dari aturan aplikasi.", "Tentukan klasifikasi data yang boleh masuk konteks.", "Perlakukan prompt pengguna seperti input biasa.", "Buat contoh boundary failure tanpa menyerang layanan luar.", "Beri izin tool sekecil mungkin dan terukur.", "Tetapkan momen approval manusia yang tidak boleh dilewati.", "Nilai asal dan kebaruan dokumen retrieval.", "Validasi struktur output sebelum dipakai sistem lain.", "Tentukan event audit yang perlu disimpan.", "Buat batas biaya dan rate limit yang memicu review.", "Desain kill switch dan owner-nya.", "Tambahkan abuse case ke evaluasi sebelum rilis."],
  ["Masukkan perangkat kecil ke inventaris, bukan hanya laptop.", "Tentukan owner dari pembelian sampai disposal.", "Ganti credential default pada perangkat yang memang kamu miliki.", "Catat versi firmware dan jadwal update.", "Letakkan IoT pada segmen sesuai kebutuhannya.", "Review remote admin dan alasan masih diperlukan.", "Tambahkan risiko akses fisik ke threat model.", "Pilih telemetry minimum yang mendukung perawatan.", "Bedakan kompromi kenyamanan consumer dan kebutuhan enterprise.", "Rencanakan penghapusan data saat perangkat dibuang.", "Tanya vendor tentang update dan akhir dukungan.", "Buat rencana hardening rumah/kantor yang realistis."],
  ["Pilih aset capstone yang benar-benar berada dalam izinmu.", "Konfirmasi owner dan data yang boleh dicatat.", "Buat threat model yang dapat dibaca non-teknis.", "Review akses berdasarkan persona dan kebutuhan.", "Tulis exposure yang bisa dikurangi tanpa proyek besar.", "Pilih log yang membantu pertanyaan incident paling mungkin.", "Ubah temuan menjadi backlog ber-owner.", "Rancang incident runbook dengan jalur komunikasi.", "Gabungkan secret dan dependency review ke rencana kerja.", "Nyatakan kapan AI atau IoT termasuk scope.", "Tulis ringkasan eksekutif yang tidak menyembunyikan risiko.", "Bagi roadmap menjadi 30, 60, dan 90 hari dengan indikator selesai."],
];

const caseStudies = [
  { phase: "Kasus Bab 1 · Scope sebelum tool", title: "Toko Rintis dan tautan admin yang dibagikan di grup", narrative: "Toko Rintis memakai satu akun admin bersama untuk mengelola katalog. Seorang anggota tim ingin ‘mengecek seberapa aman’ tautan itu dengan tool dari internet. Pemilik toko belum memberi scope, dan data pelanggan masih ada di sistem. Tim memilih berhenti, menggambar aset yang terlibat, lalu meminta pemilik menetapkan lingkungan staging dengan data fiktif.", artifactTitle: "Artefak: scope card", artifact: "Aset yang diizinkan: staging toko, data sintetis, jam uji, owner, tindakan terlarang, dan jalur berhenti bila layanan tidak stabil.", teachingPoint: "Kebiasaan profesional pertama adalah membatasi dampak sebelum mencari temuan.", guidedQuestions: ["Apa yang membuat staging lebih aman?", "Data apa yang tidak boleh masuk lab?", "Siapa yang berhak mengubah scope?"] },
  { phase: "Kasus Bab 2 · Membuat pekerjaan bisa diteruskan", title: "Handoff yang gagal pada tiket login", narrative: "Dua anggota tim menerima keluhan login. Catatan pertama hanya berbunyi ‘sepertinya error MFA’. Saat shift berganti, anggota kedua tidak tahu akun mana, waktu mana, atau bukti apa yang sudah diperiksa. Mereka mengganti kebiasaan itu dengan notebook kecil yang memisahkan observasi, asumsi, keputusan, serta pemilik langkah berikutnya.", artifactTitle: "Artefak: template handoff", artifact: "Waktu, dampak, fakta terverifikasi, hipotesis, bukti aman, keputusan, owner, dan batas eskalasi.", teachingPoint: "Dokumentasi bukan administrasi tambahan; ia adalah kontrol terhadap kehilangan konteks.", guidedQuestions: ["Kalimat mana yang merupakan observasi?", "Apa yang masih asumsi?", "Apa yang harus diketahui shift berikutnya?"] },
  { phase: "Kasus Bab 3 · DNS yang mengarah ke tempat salah", title: "Landing page kampanye tidak bisa dibuka", narrative: "Sebuah tim kampanye melihat domain mereka kadang membuka halaman lama. Tidak ada bukti serangan. Mereka menggambar jalur perangkat, resolver DNS, CDN, dan origin; lalu membandingkan record yang diharapkan dengan record yang sedang aktif. Ternyata perubahan belum terdokumentasi dan TTL masih mengarah ke konfigurasi lama.", artifactTitle: "Artefak: diagram jalur request", artifact: "Nama domain, resolver, record, TTL, CDN, origin, owner perubahan, dan titik bukti.", teachingPoint: "Model jaringan yang jelas mencegah tim menebak di lapisan yang salah.", guidedQuestions: ["Di mana nama diterjemahkan menjadi alamat?", "Apa bukti perubahan DNS?", "Owner mana yang perlu dilibatkan?"] },
  { phase: "Kasus Bab 4 · Lab yang bisa dibatalkan", title: "VM latihan terkena konfigurasi yang keliru", narrative: "Peserta mengubah konfigurasi jaringan VM dan tidak lagi dapat mengakses aplikasi latihan. Karena snapshot dibuat sebelum eksperimen dan jaringan VM terisolasi, ia dapat memulihkan keadaan tanpa menyentuh laptop utama atau router rumah. Catatan perubahan membantu ia memahami apa yang berbeda.", artifactTitle: "Artefak: kartu pemulihan lab", artifact: "Nama snapshot, tujuan eksperimen, perubahan yang direncanakan, jaringan VM, langkah rollback, dan bukti reset.", teachingPoint: "Lab yang baik dirancang untuk gagal dengan aman.", guidedQuestions: ["Kapan snapshot dibuat?", "Apa yang diisolasi?", "Bukti apa yang menunjukkan rollback berhasil?"] },
  { phase: "Kasus Bab 5 · Perubahan file yang terukur", title: "Konfigurasi web server hilang setelah bersih-bersih", narrative: "Di VM latihan, seorang peserta menghapus direktori yang namanya mirip folder cache. Ternyata folder itu berisi konfigurasi contoh. Ia memperbaiki proses: memeriksa lokasi kerja, mencatat file penting, membuat salinan sebelum penghapusan, dan meminta review pada perubahan yang tidak mudah dipulihkan.", artifactTitle: "Artefak: checklist perubahan filesystem", artifact: "Lokasi saat ini, file target, owner, backup, alasan perubahan, verifikasi, dan rollback.", teachingPoint: "Perintah sederhana tetap punya dampak bila konteksnya tidak jelas.", guidedQuestions: ["Apa bukti target sudah benar?", "Kapan backup diperlukan?", "Bagaimana mencegah pengulangan?"] },
  { phase: "Kasus Bab 6 · Akun setelah anggota tim pindah", title: "Akses proyek lama masih aktif", narrative: "Seorang desainer pindah ke tim baru, tetapi akun kolaborasinya masih punya akses admin pada proyek lama. Tidak ada insiden, namun review bulanan menemukan gap itu. Tim memperbarui proses joiner–mover–leaver: owner akses, tanggal review, dan daftar aplikasi yang harus diperiksa.", artifactTitle: "Artefak: matriks lifecycle akses", artifact: "Persona, aplikasi, peran minimum, approver, tanggal perubahan, review berikutnya, dan status pencabutan.", teachingPoint: "Least privilege hanya hidup jika perubahan peran memiliki proses yang nyata.", guidedQuestions: ["Akses mana yang perlu dicabut?", "Siapa owner review?", "Bagaimana MFA ikut diperiksa?"] },
  { phase: "Kasus Bab 7 · Layanan yang tak punya owner", title: "Server uji membuka layanan lama", narrative: "Inventory lab menemukan sebuah layanan file sharing masih aktif pada server uji. Tidak ada yang tahu apakah layanan itu dipakai. Tim tidak langsung mematikan; mereka mencari owner, melihat baseline, menilai kebutuhan, lalu menutup layanan setelah ada persetujuan dan jalur rollback.", artifactTitle: "Artefak: register layanan", artifact: "Aset, layanan, port, fungsi, owner, baseline, keputusan exposure, dan tanggal review.", teachingPoint: "Mengurangi attack surface adalah proses kepemilikan, bukan sekadar menutup sebanyak mungkin port.", guidedQuestions: ["Apa fungsi layanan?", "Apa bukti bahwa masih diperlukan?", "Apa rollback jika keputusan salah?"] },
  { phase: "Kasus Bab 8 · Wi-Fi tamu mencampur perangkat", title: "Printer kantor terlihat dari jaringan pengunjung", narrative: "Kantor kecil memberi password Wi-Fi yang sama kepada staf dan tamu. Seorang staf menyadari printer dan TV rapat tampak dari perangkat tamu. Tim membuat SSID terpisah, meninjau firmware router, mencatat perangkat yang benar-benar perlu saling bicara, dan menguji perubahan dengan perangkat sendiri.", artifactTitle: "Artefak: peta segmentasi Wi-Fi", artifact: "SSID, perangkat, owner, kebutuhan komunikasi, firmware, kebijakan tamu, dan indikator gangguan.", teachingPoint: "Segmentasi adalah cara mengurangi dampak salah satu perangkat tanpa mengganggu semuanya.", guidedQuestions: ["Perangkat mana perlu berada bersama?", "Apa batas jaringan tamu?", "Bagaimana menguji tanpa membaca trafik pihak lain?"] },
  { phase: "Kasus Bab 9 · Tombol edit yang hanya disembunyikan", title: "Peran viewer hampir mendapat akses editor", narrative: "Aplikasi catatan menyembunyikan tombol edit untuk viewer, tetapi aturan server belum memeriksa peran saat menerima perubahan. Saat code review lokal, tim melihat boundary ini dan menambahkan authorization di sisi server, test matriks peran, serta log penolakan yang tidak membocorkan data.", artifactTitle: "Artefak: matriks authz", artifact: "Persona, aksi, resource, keputusan server, kondisi penolakan, test, dan owner kebijakan.", teachingPoint: "Tampilan bukan kontrol keamanan; keputusan akses harus ditegakkan pada boundary yang dipercaya.", guidedQuestions: ["Di mana authz perlu terjadi?", "Apa beda auth dan authz?", "Test apa yang menangkap regresi?"] },
  { phase: "Kasus Bab 10 · Dokumen publik yang mengandung secret contoh", title: "Token demo muncul di dokumentasi", narrative: "Tim menemukan token demo lama di dokumentasi publik milik proyek mereka sendiri. Mereka tidak menyebarkan tautan atau menilai dampak secara dramatis. Mereka memverifikasi owner, mencabut token, memperbarui dokumen, memeriksa log seperlunya, dan mencatat bagaimana secret itu lolos review.", artifactTitle: "Artefak: laporan disclosure internal", artifact: "Sumber, waktu, tingkat keyakinan, owner, tindakan penahanan, jalur komunikasi, dan follow-up.", teachingPoint: "OSINT defensif bertujuan mengurangi paparan, bukan menambah penonton pada paparan itu.", guidedQuestions: ["Apa yang harus direvokasi?", "Siapa yang perlu tahu?", "Detail mana tidak perlu disebarkan?"] },
  { phase: "Kasus Bab 11 · Scanner memberi daftar panjang", title: "Seratus temuan, nol prioritas", narrative: "Sebuah scan berizin pada staging menghasilkan seratus temuan. Tim awalnya ingin mengejar skor tertinggi, tetapi beberapa aset tidak aktif dan sebagian sinyal false positive. Mereka menghubungkan tiap isu ke aset, owner, exposure, dampak, dan bukti minimum sebelum membuat backlog remediasi.", artifactTitle: "Artefak: backlog kerentanan", artifact: "Aset, status aktif, sinyal, validasi aman, dampak, owner, deadline, compensating control, dan retest.", teachingPoint: "Kerentanan adalah pekerjaan keputusan, bukan kompetisi mengumpulkan angka.", guidedQuestions: ["Apa yang membuat isu prioritas?", "Bagaimana menangani false positive?", "Kapan exception berakhir?"] },
  { phase: "Kasus Bab 12 · Group akses tanpa makna", title: "Akun baru mewarisi terlalu banyak izin", narrative: "Onboarding otomasi memasukkan karyawan baru ke group besar yang secara historis dipakai untuk banyak aplikasi. Audit menemukan group itu memberi akses jauh lebih luas dari tugas awal. Tim mendefinisikan group berdasarkan fungsi, menamai owner, dan merencanakan migrasi bertahap agar layanan tidak putus.", artifactTitle: "Artefak: peta group dan trust", artifact: "Group, tujuan, owner, anggota, aplikasi, hak, review cadence, dan rencana migrasi.", teachingPoint: "Identity organisasi adalah graph keputusan; nama group yang rapi tidak cukup tanpa owner dan tujuan.", guidedQuestions: ["Hak mana yang tidak dibutuhkan?", "Bagaimana perubahan disetujui?", "Apa risiko migrasi?"] },
  { phase: "Kasus Bab 13 · API key tersimpan di repo latihan", title: "Key test ikut ter-push", narrative: "Key test yang scope-nya terlalu luas ikut masuk ke repository latihan. Tim langsung mencabut key, mengganti dengan secret manager, mempersempit scope key berikutnya, dan menambah pre-commit review. Mereka tidak memperlakukan penghapusan commit sebagai satu-satunya perbaikan karena salinan bisa sudah tersebar.", artifactTitle: "Artefak: secret lifecycle record", artifact: "Jenis secret, scope, lokasi simpan, owner, rotasi, revoke, log redaction, dan pembelajaran.", teachingPoint: "Secret yang pernah terpapar diperlakukan sebagai tidak lagi rahasia.", guidedQuestions: ["Mengapa revoke lebih penting daripada delete?", "Scope apa yang dikurangi?", "Kontrol proses apa ditambah?"] },
  { phase: "Kasus Bab 14 · Skrip laporan mengubah file sumber", title: "Automasi yang seharusnya read-only", narrative: "Skrip pembersih log fiktif ternyata menulis ulang file input ketika dijalankan dua kali. Tim memisahkan input dan output, menambahkan mode dry-run, membuat data contoh, serta menulis README yang menjelaskan batas penggunaan. Fokusnya bukan membuat skrip paling pintar, melainkan paling mudah diaudit.", artifactTitle: "Artefak: kontrak skrip", artifact: "Input, output, mode read-only, dry-run, data contoh, dependency, error behavior, dan owner.", teachingPoint: "Automasi defensif harus membuat perubahan terlihat sebelum perubahan terjadi.", guidedQuestions: ["Apa yang boleh ditulis skrip?", "Bagaimana data contoh dipakai?", "Apa hasil saat input salah?"] },
  { phase: "Kasus Bab 15 · Error yang bocor ke pengguna", title: "Upload gagal dan menampilkan detail internal", narrative: "Aplikasi upload latihan menampilkan stack trace lengkap ketika file tidak sesuai format. Tim memperlakukan ini sebagai masalah boundary: pengguna perlu pesan yang jelas, sementara detail teknis masuk ke log internal terproteksi. Mereka menambah validasi tipe dan ukuran, test regresi, serta review dependency parser.", artifactTitle: "Artefak: memo secure code review", artifact: "Input, boundary, failure mode, pesan pengguna, log internal, test, dependency, dan rekomendasi patch.", teachingPoint: "Error handling adalah bagian dari desain keamanan dan pengalaman pengguna sekaligus.", guidedQuestions: ["Detail mana boleh ke pengguna?", "Apa yang perlu dicatat internal?", "Test apa yang mencegah bocor ulang?"] },
  { phase: "Kasus Bab 16 · Alert login yang terlalu bising", title: "SOC lelah oleh notifikasi", narrative: "Aturan alert mengirim notifikasi untuk setiap login gagal, termasuk salah ketik password biasa. Tim meninjau telemetry dengan data sintetis, menambahkan konteks perangkat dan waktu, mendefinisikan severity, serta membuat pertanyaan triage sebelum eskalasi. Mereka menjaga agar tuning tidak menyembunyikan kejadian penting.", artifactTitle: "Artefak: playbook alert", artifact: "Event, konteks, threshold, severity, pertanyaan triage, owner, SLA, eskalasi, dan review false positive.", teachingPoint: "Alert yang berguna membantu manusia membuat keputusan; alert yang bising mengalihkan perhatian dari risiko.", guidedQuestions: ["Konteks apa yang mengurangi noise?", "Apa yang memicu eskalasi?", "Bagaimana false positive dipelajari?"] },
  { phase: "Kasus Bab 17 · Token karyawan dikirim ke kanal umum", title: "Insiden kecil yang perlu respons tenang", narrative: "Seorang karyawan tanpa sengaja menempelkan token aplikasi internal ke kanal chat. Tim tidak mempermalukan orangnya. Mereka meminta penghapusan, mencabut token, memeriksa scope dan penggunaan dengan owner, memperbarui panduan, lalu melakukan postmortem yang fokus pada desain proses serta tooling.", artifactTitle: "Artefak: runbook secret exposure", artifact: "Trigger, containment, bukti, owner, komunikasi, revocation, verifikasi, postmortem, dan action item.", teachingPoint: "Respons yang baik menutup risiko, menjaga orang, dan mengubah proses agar kesalahan tidak mudah terulang.", guidedQuestions: ["Apa tindakan penahanan pertama?", "Siapa owner keputusan?", "Apa yang diperbaiki selain token?"] },
  { phase: "Kasus Bab 18 · Agent ingin mengirim email", title: "Asisten AI melampaui kewenangan", narrative: "Sebuah agent internal dapat membaca dokumen dan merangkum, lalu proposal fitur baru memberi akses mengirim email ke pelanggan. Tim memisahkan kemampuan baca, draf, rekomendasi, approval manusia, dan aksi. Mereka menambahkan permission per tool, audit trail, serta kill switch sebelum fitur diuji dengan data sintetis.", artifactTitle: "Artefak: matriks kemampuan agent", artifact: "Tool, data, izin, aksi yang diizinkan, approval, audit event, batas biaya, dan kill switch owner.", teachingPoint: "Kemampuan bahasa tidak memberi agent otoritas untuk bertindak.", guidedQuestions: ["Aksi mana perlu approval?", "Apa data yang boleh dibaca?", "Bagaimana kill switch diuji?"] },
  { phase: "Kasus Bab 19 · Kamera pintar tidak pernah di-update", title: "Perangkat kecil yang terlupakan", narrative: "Kamera pintar di kantor kecil masih memakai firmware lama dan dibeli tanpa register aset. Tim tidak mencoba mengakses perangkat lain; mereka menginventaris perangkat milik kantor, menghubungi vendor, menjadwalkan update, memisahkan jaringan, dan menetapkan owner serta tanggal review.", artifactTitle: "Artefak: register IoT", artifact: "Perangkat, lokasi, owner, firmware, network segment, remote admin, vendor support, dan disposal plan.", teachingPoint: "Aset fisik tetap bagian dari sistem keamanan meskipun ukurannya kecil dan tidak dikelola tim software.", guidedQuestions: ["Siapa owner update?", "Mengapa segmentasi dibutuhkan?", "Apa yang terjadi saat support berakhir?"] },
  { phase: "Kasus Bab 20 · Roadmap yang dapat dipertanggungjawabkan", title: "Capstone untuk aplikasi komunitas", narrative: "Aplikasi komunitas kecil ingin meningkatkan keamanan tanpa proyek raksasa. Tim memilih aset berizin, membuat inventory, access review, logging plan, backlog risiko, dan runbook. Mereka menyusun roadmap 30–60–90 hari dengan owner, bukti selesai, serta komunikasi agar perbaikan tidak berhenti di presentasi.", artifactTitle: "Artefak: roadmap 30–60–90", artifact: "Prioritas, owner, tindakan, bukti selesai, dependency, risiko residu, tanggal review, dan jalur eskalasi.", teachingPoint: "Security maturity adalah kebiasaan keputusan yang berulang, bukan satu audit besar.", guidedQuestions: ["Apa yang realistis selesai 30 hari?", "Apa indikator selesai?", "Risiko mana tetap diterima dan mengapa?"] },
];

function introduction(chapter: Chapter, chapterNumber: number) {
  return {
    title: `Sebelum gas: Bab ${chapterNumber} · ${chapter.title}`,
    body: `Oke bro, bab ini ngebahas ${chapter.focus}. Kita nggak lagi lomba hafal tool atau jargon. Yang kita cari: sebenarnya apa yang lagi dijaga, bukti apa yang masuk akal, siapa yang pegang tanggung jawab, dan keputusan kecil mana yang beneran bisa nurunin risiko. Semua contoh tetap di aplikasi sendiri, data fiktif, atau lab berizin—skill boleh naik, tapi jangan sampai ninggalin jejak buruk.\n\nDua belas subbab ini adalah rute kerja, bukan target maraton: mulai dari model mental, lanjut ke bukti dan artefak, lalu tutup dengan keputusan yang bisa direview teman tim. Kalau ada yang belum pasti, catat saja; orang security yang dewasa nggak pura-pura tahu semuanya. ${chapter.guardrail}`,
    questions: ["Sebenarnya aset atau keputusan apa yang lagi dijaga?", "Bukti minimum apa yang perlu ada sebelum bikin klaim?", "Siapa yang pegang perbaikan, dan kapan perlu dicek lagi?"],
  };
}

function sections(chapter: Chapter, unit: string, chapterNumber: number, unitNumber: number) {
  const label = `${chapterNumber}.${unitNumber} · ${unit}`;
  const move = chapterMoves[chapterNumber - 1]?.[unitNumber - 1] ?? "Tuliskan keputusan, bukti, owner, dan batas aman untuk topik ini.";
  return [
    { heading: "Bedah konsepnya", body: `Santai dulu, ${label} bukan cuma istilah keren. Ini bagian dari rantai keputusan saat ${chapter.focus}. Kalau salah nangkep, tim bisa sibuk ngurus gejala sementara sumber risiko atau owner masalahnya nggak pernah disentuh. Jadi mulai dari tiga pertanyaan: asumsinya apa, datanya ada apa, dan dampak mana yang mau dicegah?` },
    { heading: "Mekanisme dan trade-off", body: `Jangan berhenti di definisi. Untuk ${unit.toLowerCase()}, pecah masalah menjadi boundary, identitas, perubahan, bukti, dan pemulihan. Kontrol yang terlalu longgar meningkatkan paparan; kontrol yang terlalu ketat bisa menghambat operasi. Keputusan yang baik menjelaskan trade-off itu, menetapkan owner, dan mempunyai jalan mundur bila asumsi awal ternyata keliru. Fokus teknis subbab ini: ${move}` },
    { heading: "Skenario tim", body: `Bayangkan tim kecil menerima sinyal yang tampak sederhana terkait ${unit.toLowerCase()}. Mereka tidak langsung menuduh atau menekan tombol besar. Mereka membuka ${chapter.artifact}, memisahkan fakta dari dugaan, menandai dampak potensial, lalu memilih langkah paling kecil yang menurunkan risiko tanpa merusak layanan. Dalam skenario ini, tindakan yang membedakan subbab ini adalah: ${move}` },
    { heading: "Latihan lab berizin", body: `Bikin atau perbarui ${chapter.artifact}. Kerjakan fokus ini pakai data fiktif atau aset sendiri: ${move} Tambahkan dua kolom: “apa yang belum diketahui” dan “bukti apa yang aman buat dicari”. Targetnya bukan ngejalanin tool sebanyak mungkin, tapi bikin artefak yang bisa dipahami dan dikritik orang lain.` },
    { heading: "Batas aman dan pemeriksaan", body: `${chapter.guardrail} Kalau ada langkah yang butuh izin tapi kamu belum punya, berhenti di rencana saja lalu tulis pertanyaan buat owner. Di dunia profesional, punya rem di batas yang benar itu tanda kompeten, bukan kurang jago.` },
  ];
}

function makeQuiz(chapter: Chapter, unit: string): QuizQuestion[] {
  return [
    { question: `Dalam subbab “${unit}”, kebiasaan kerja yang paling kuat adalah…`, options: ["menentukan aset, bukti, owner, dan langkah aman sebelum bertindak", "langsung memakai tool pada target yang tidak jelas", "menganggap satu sinyal sebagai bukti final"], answer: 0, explanation: `Benar. ${chapter.focus.charAt(0).toUpperCase()}${chapter.focus.slice(1)}.` },
    { question: "Saat scope atau izin belum jelas, tindakan paling profesional adalah…", options: ["berhenti, dokumentasikan kebutuhan, lalu gunakan lab atau minta persetujuan", "melanjutkan karena data mungkin menarik", "membagikan dugaan ke publik agar cepat ramai"], answer: 0, explanation: "Scope dan izin selalu datang sebelum eksperimen keamanan." },
  ];
}

const prologueLessons = [
  { title: "Selamat datang: security itu sebenarnya apa?", premise: "Cyber Security adalah cara menjaga sistem digital tetap berguna dan dapat dipercaya saat ada kesalahan, gangguan, atau pihak yang berniat buruk. Ia bukan sekadar dunia 'hacker versus hacker', melainkan kebiasaan membuat keputusan yang mengurangi dampak buruk.", decision: "Tuliskan tiga hal digital yang kamu andalkan hari ini—akun, data, atau layanan—lalu jelaskan apa yang membuat masing-masing tetap layak dipercaya.", exercise: "Buat daftar aset digital pribadi tanpa menulis password, token, atau detail sensitif." },
  { title: "Bukan soal terlihat jago, tapi mengurangi risiko", premise: "Tool bisa membantu, tetapi tool bukan tujuan. Keamanan yang matang terlihat dari scope yang jelas, bukti yang cukup, dan perbaikan yang dapat dijaga setelah rasa penasaran selesai.", decision: "Bandingkan dua tujuan: 'mencari celah' dan 'mencegah kerugian'. Pilih bukti apa yang diperlukan oleh tujuan kedua.", exercise: "Tulis satu contoh keputusan aman yang tidak membutuhkan tool apa pun." },
  { title: "Kenapa masalah kecil bisa jadi besar?", premise: "Password yang dipakai ulang, update yang tertunda, folder terbuka, atau alert yang diabaikan sering menjadi awal masalah. Security dibutuhkan karena sistem nyata saling terhubung dan dampaknya sering mengenai orang lain juga.", decision: "Petakan satu kesalahan kecil ke dampak yang mungkin menjalar: pengguna, layanan, reputasi, dan waktu pemulihan.", exercise: "Gunakan skenario fiktif 'akun email lupa logout' untuk membuat rantai dampak tiga langkah." },
  { title: "Contoh kasus: link invoice palsu di tim kecil", premise: "Bayangkan admin menerima invoice yang tampak normal dan hampir meneruskannya ke keuangan. Yang menyelamatkan tim bukan intuisi magis, melainkan kebiasaan verifikasi lewat kanal kedua, tidak buru-buru, dan mencatat sinyal yang muncul.", decision: "Pisahkan sinyal, asumsi, dan tindakan yang aman dari kasus invoice fiktif tersebut.", exercise: "Buat checklist verifikasi tiga langkah untuk pesan yang meminta tindakan mendesak." },
  { title: "Security, privacy, dan safety: berteman tapi beda", premise: "Security berfokus pada menjaga sistem dan akses; privacy berfokus pada penggunaan data yang tepat; safety berfokus pada mencegah bahaya. Ketiganya sering bertemu, tetapi keputusan yang baik tidak menyamakan semuanya.", decision: "Untuk aplikasi catatan, jelaskan satu risiko security, satu risiko privacy, dan satu risiko safety.", exercise: "Buat tabel tiga kolom memakai contoh data fiktif." },
  { title: "Siapa saja yang ikut menjaga?", premise: "Security bukan tugas satu orang atau satu tim. Developer, admin, pemilik produk, help desk, legal, dan pengguna punya keputusan yang berbeda. Owner yang jelas membuat masalah tidak berputar tanpa arah.", decision: "Ambil kasus update aplikasi fiktif dan tentukan siapa pemilik keputusan, siapa pelaksana, dan siapa yang perlu diberi tahu.", exercise: "Buat daftar peran tanpa memakai nama orang asli." },
  { title: "Cara berpikir risiko sebelum panik", premise: "Tidak semua temuan harus diperlakukan sama. Risiko membantu menghubungkan aset, kemungkinan kejadian, dampak, kontrol, dan prioritas. Tujuannya bukan memprediksi masa depan dengan sempurna, tetapi memilih langkah berikutnya dengan sadar.", decision: "Nilai dua risiko fiktif berdasarkan dampak dan kemungkinan, lalu jelaskan mengapa urutannya demikian.", exercise: "Gunakan matriks sederhana rendah–sedang–tinggi untuk proyek latihanmu." },
  { title: "Batas legal: rasa ingin tahu punya rem", premise: "Memahami risiko tidak memberi izin untuk menyentuh sistem orang lain. Izin tertulis, aset yang jelas, data fiktif, dan lab terisolasi adalah dasar belajar yang bertanggung jawab—bukan formalitas yang bisa dilewati.", decision: "Ubah permintaan kabur 'cek situs ini aman tidak' menjadi scope lab yang sah dan terbatas.", exercise: "Tulis scope card untuk VM atau aplikasi milik sendiri, termasuk batas berhenti." },
  { title: "Apa yang akan kamu dapat dari course ini?", premise: "Course inti bergerak dari jaringan, lab, Linux, akun, web, OSINT defensif, vulnerability management, coding, SOC, incident response, AI, IoT, hingga capstone. Urutannya sengaja dari fondasi menuju keputusan lintas sistem.", decision: "Pilih satu alasan pribadi belajar security, lalu hubungkan ke tiga checkpoint yang paling relevan.", exercise: "Tandai apakah tujuanmu lebih dekat ke aplikasi, operasi, administrasi, atau produk." },
  { title: "Cara memakai 20 checkpoint tanpa keburu tenggelam", premise: "Dua belas subbab dalam satu checkpoint bukan target maraton. Baca pembukaan, pilih satu subbab, buat artefak kecil, jawab kuis, lalu lanjut ketika konteksnya masih segar. Katalog dibuat bertahap supaya orientasi tidak hilang.", decision: "Pilih ritme realistis—misalnya dua atau tiga subbab per minggu—dan jelaskan alasanmu.", exercise: "Buat jadwal belajar dua minggu dengan satu hari untuk review, bukan hanya menambah materi." },
  { title: "Jenis latihan yang akan kamu temui", premise: "Latihan di course ini memakai data fiktif, aset sendiri, catatan keputusan, diagram, register, dan runbook. Hasil terbaik bukan 'berhasil menjalankan tool', melainkan artefak yang bisa dibaca, dikritik, dan diperbaiki tim.", decision: "Bandingkan artefak yang bisa diaudit dengan screenshot hasil tool tanpa konteks.", exercise: "Siapkan folder lokal khusus untuk catatan lab dan data contoh yang aman dibuang." },
  { title: "Sebelum masuk course inti: kontrak belajarmu", premise: "Sekarang kamu punya konteks: security dibutuhkan karena sistem, data, dan manusia saling bergantung; praktik yang dewasa dimulai dari scope, bukti, dan dampak. Bab berikutnya baru masuk ke cara berpikir risiko dan lingkungan belajar secara lebih teknis.", decision: "Tulis satu komitmen: aset apa yang akan kamu gunakan, batas apa yang tidak akan kamu lewati, dan siapa yang akan kamu tanya bila scope tidak jelas.", exercise: "Simpan kontrak belajar satu halaman sebagai artefak pertama sebelum membuka Bab 1 course inti." },
] as const;

const prologueCaseStudy = {
  phase: "Bab Prolog · Mengapa course ini dimulai dari konteks",
  title: "Kasus pembuka: akun komunitas yang hampir diambil alih",
  narrative: "Sebuah komunitas kecil memakai satu akun media sosial bersama. Saat salah satu admin menerima pesan yang mendesak untuk 'verifikasi akun', ia hampir memasukkan credential di halaman yang salah. Masalahnya bukan karena ia kurang pintar; desain kerja tim belum punya password manager, MFA, kanal verifikasi, owner akun, atau aturan saat menerima pesan darurat. Mereka berhenti, memeriksa lewat kanal resmi, lalu menyusun perbaikan sederhana. Kasus ini menunjukkan alasan security dibutuhkan sebelum kita bicara tool: keputusan kecil yang tertata dapat mencegah dampak besar pada orang dan layanan.",
  artifactTitle: "Artefak prolog: peta perlindungan akun komunitas",
  artifact: "Akun yang dilindungi, owner, MFA, recovery, kanal verifikasi, perangkat tepercaya, jalur pelaporan, dan tanggal review.",
  teachingPoint: "Security tidak dimulai dari menyerang sistem; ia dimulai dari memahami apa yang perlu dijaga, siapa yang terdampak, dan kebiasaan paling kecil yang mengurangi risiko.",
  guidedQuestions: ["Apa sinyal yang membuat pesan perlu diverifikasi?", "Kontrol kecil apa yang mencegah dampak berulang?", "Siapa yang bertanggung jawab atas akses dan recovery?"],
};

function prologueSections(lesson: typeof prologueLessons[number], unitNumber: number) {
  return [
    { heading: "Ngobrol dulu", body: lesson.premise },
    { heading: "Kenapa ini penting sebelum teknis", body: `Sebelum menyentuh materi inti, ${lesson.title.toLowerCase()} memberi bahasa untuk membaca masalah dengan tenang. Tanpa konteks ini, networking, Linux, web, dan log hanya berubah menjadi daftar istilah yang mudah dihafal tetapi sulit dipakai membuat keputusan.` },
    { heading: "Contoh kasus yang aman", body: `Gunakan contoh akun komunitas dan aplikasi catatan fiktif. Fokusnya bukan mencari kelemahan pihak lain, melainkan memahami keputusan, owner, serta langkah verifikasi yang menjaga orang dan layanan.` },
    { heading: "Latihan kecil", body: `${lesson.exercise} Simpan hasilnya sebagai catatan singkat yang bisa kamu tinjau lagi saat masuk ke checkpoint inti.` },
    { heading: "Jembatan ke course inti", body: `${lesson.decision} Setelah itu, lanjutkan ke Bab 1 course inti untuk mengubah konteks ini menjadi cara berpikir risiko, scope, aset, bukti, dan kontrol.` },
  ];
}

export const cyberSecurityPrologueMaterials: Material[] = prologueLessons.map((lesson, unitIndex) => ({
  id: 180 + unitIndex,
  displayNumber: unitIndex + 1,
  title: `Prolog.${unitIndex + 1} · ${lesson.title}`,
  category: "Cyber Security Intensif · Bab Prolog — Sebelum Masuk Course Inti",
  specialization: "ai-security" as const,
  level: "Pemula" as const,
  minutes: 10 + (unitIndex % 4),
  emoji: "◌",
  summary: lesson.premise,
  analogy: "Anggap Prolog sebagai papan peta sebelum perjalanan: kamu belum perlu menghafal semua jalan, tetapi perlu tahu kenapa perjalanan ini dilakukan dan batas mana yang tidak boleh dilewati.",
  sections: prologueSections(lesson, unitIndex + 1),
  chapterLecture: unitIndex === 0 ? { title: "Mulai dari konteks, bukan dari tool", body: "Bab Prolog menjawab pertanyaan yang sering dilewati: apa itu Cyber Security, siapa yang dilindungi, mengapa masalah kecil dapat meluas, dan bagaimana belajar tanpa mengubah rasa ingin tahu menjadi risiko bagi orang lain. Selesaikan prolog ini sebelum membuka course inti agar 20 checkpoint berikutnya terasa sebagai satu perjalanan, bukan daftar topik acak.", questions: ["Aset apa yang ingin kamu lindungi?", "Dampak siapa yang perlu dipertimbangkan?", "Apa batas praktikmu sebelum masuk lab?"] } : undefined,
  caseStudy: unitIndex === 0 ? prologueCaseStudy : undefined,
  resources: [sources.cs50, sources.handsOn, sources.ethicalOne, sources.ethicalTwelve],
  quiz: [
    { question: `Pada ${lesson.title}, kebiasaan yang paling tepat adalah…`, options: ["menentukan konteks, aset, dampak, dan batas aman sebelum bertindak", "langsung mencoba tool pada target yang tidak jelas", "menganggap semua masalah harus direspons sama"], answer: 0, explanation: "Security yang matang dimulai dari konteks dan tanggung jawab." },
    { question: "Jika scope belum jelas, langkah profesional pertama adalah…", options: ["berhenti, gunakan lab atau minta persetujuan", "melanjutkan agar cepat belajar", "mengumpulkan data sebanyak mungkin"], answer: 0, explanation: "Izin dan batas aset selalu datang sebelum eksperimen." },
  ],
}));

export const cyberSecurityMaterials: Material[] = [...cyberSecurityPrologueMaterials, ...chapters.flatMap((chapter, chapterIndex) => chapter.units.map((unit, unitIndex) => {
  const chapterNumber = chapterIndex + 1;
  const unitNumber = unitIndex + 1;
  const title = `${chapterNumber}.${unitNumber} · ${unit}`;
  return {
    id: 200 + (chapterIndex * 12) + unitIndex,
    displayNumber: (chapterIndex * 12) + unitIndex + 13,
    title,
    category: `Cyber Security Intensif · Bab ${chapterNumber} — ${chapter.title}`,
    specialization: "ai-security" as const,
    level: chapter.level,
    minutes: 18 + ((chapterIndex + unitIndex) % 9),
    emoji: "◆",
    summary: `${unit} dibahas sebagai keputusan nyata dalam ${chapter.focus}. Kamu akan meninggalkan subbab ini dengan artefak, pertanyaan review, dan batas praktik yang jelas.`,
    analogy: `Bayangkan ${unit.toLowerCase()} sebagai titik pemeriksaan dalam jalur yang sama: bukan satu tombol ajaib, tetapi cara mencegah masalah kecil melebar ke seluruh sistem.`,
    sections: sections(chapter, unit, chapterNumber, unitNumber),
    chapterLecture: unitIndex === 0 ? introduction(chapter, chapterNumber) : undefined,
    caseStudy: unitIndex === 0 ? caseStudies[chapterIndex] : undefined,
    resources: chapter.sources.map((key) => sources[key]),
    quiz: makeQuiz(chapter, unit),
  };
}))];

export const cyberSecurityCurriculumStats = { chapters: chapters.length + 1, subchaptersPerChapter: 12, totalSubchapters: (chapters.length + 1) * 12 } as const;
