import type { Material, MaterialLevel, QuizQuestion } from "./materials";

type SourceKey = keyof typeof sources;

const sources = {
  cs50: { label: "CS50: Intro to Cybersecurity — Full Course", url: "https://youtu.be/9HOpanT0GRs", note: "Fondasi keamanan akun, data, sistem, perangkat lunak, dan trade-off risiko." },
  handsOn: { label: "Hands-On Cybersecurity & Ethical Hacking — Full Course", url: "https://youtu.be/ug8W0sFiVJo", note: "Konteks Kali Linux, network security, vulnerability assessment, dan lab legal." },
  ethicalOne: { label: "Ethical Hacking in 15 Hours — Part 1", url: "https://youtu.be/3FNYvj2U0HM", note: "Pola pikir ethical hacking, catatan, scope, dan fondasi lab." },
  ethicalTwo: { label: "Ethical Hacking in 15 Hours — Part 2", url: "https://youtu.be/sH4JCwjybGs", note: "Pendalaman metodologi dan pelaporan temuan dalam ruang lingkup yang diizinkan." },
  webSecurity: { label: "Hacking Web Applications", url: "https://youtu.be/1GJ_LwNw6sc", note: "Memahami kelas risiko aplikasi web dari sudut pandang perbaikan." },
  ethicalTwelve: { label: "Ethical Hacking in 12 Hours", url: "https://youtu.be/fNzpcB7ODxQ", note: "Peta pembelajaran keamanan, lab, scope, dan dokumentasi." },
  osint: { label: "Open-Source Intelligence (OSINT) in 5 Hours", url: "https://youtu.be/qwA6MmbeGNo", note: "Jejak digital, informasi publik, validasi, serta batas etika OSINT." },
  webBeginner: { label: "Beginner Web Application Hacking", url: "https://youtu.be/24fHLWXGS-M", note: "Konsep keamanan aplikasi web untuk pemula." },
  memory: { label: "Buffer Overflows Made Easy", url: "https://youtu.be/ncBblM920jw", note: "Kesadaran risiko memori dan pentingnya coding defensif; bukan panduan eksploit." },
  kali: { label: "Linux for Ethical Hackers — Kali Linux Course", url: "https://youtu.be/U1w4T03B30I", note: "Konteks Linux/Kali sebagai lingkungan lab yang harus dipakai secara legal." },
  python: { label: "Python for Beginners — Full Course", url: "https://youtu.be/7utwZYKweho", note: "Fondasi otomatisasi dan pembacaan data untuk pekerjaan defensif." },
  linuxPrivilege: { label: "Linux Privilege Escalation for Beginners", url: "https://youtu.be/ZTnwg3qCdVM", note: "Mengapa permission dan konfigurasi Linux perlu diaudit pada aset berizin." },
  windowsPrivilege: { label: "Windows Privilege Escalation for Beginners", url: "https://youtu.be/uTcrbNBcoxQ", note: "Kesadaran konfigurasi dan hak akses Windows pada lingkungan yang diizinkan." },
  activeDirectory: { label: "Hacking Active Directory for Beginners", url: "https://youtu.be/VXxH4n684HE", note: "Konteks identity, directory, dan konfigurasi organisasi yang perlu dijaga." },
  bugBounty: { label: "Practical Bug Bounty", url: "https://youtu.be/wS2z5lt34Cc", note: "Responsible disclosure, bukti minimal, dan komunikasi temuan." },
  rust: { label: "Rust Programming 101", url: "https://youtu.be/RU7BYxmSBNg", note: "Perspektif bahasa modern dan kebiasaan coding yang sadar memori." },
  soc: { label: "Security Operations (SOC) 101", url: "https://youtu.be/56NDgBOSpUg", note: "Triage, alert, log, eskalasi, dan operasi keamanan sehari-hari." },
  powershell: { label: "Intro to PowerShell", url: "https://youtu.be/GyvEMcMh3rc", note: "Otomasi administrasi yang dapat diaudit di lingkungan yang diizinkan." },
  ai: { label: "Learn AI Fundamentals", url: "https://youtu.be/VdWqEd56HTQ", note: "Konteks fondasi AI untuk memahami risiko tool, agent, dan data." },
  helpDesk: { label: "Practical Help Desk", url: "https://youtu.be/2MvT63eZfp0", note: "Fondasi endpoint, ticketing, eskalasi, dan komunikasi operasional." },
  iot: { label: "IoT & Hardware Hacking for Beginners", url: "https://youtu.be/j8SqZLr64NA", note: "Kesadaran aset perangkat terhubung, firmware, jaringan, dan inventaris." },
  career: { label: "Full-Length Hacking Courses — Soft Skills & Career", url: "https://youtube.com/playlist?list=PLLKT__MCUeixqHJ1TRqrHsEd6_EdEvo47", note: "Dua video soft skill dalam playlist: melamar kerja dan membangun pembeda yang jujur." },
};

type LessonSeed = {
  chapter: string;
  title: string;
  level: MaterialLevel;
  minutes: number;
  explain: string;
  analogy: string;
  story: string;
  practice: string;
  guardrail: string;
  check: string;
  sourceKeys: SourceKey[];
};

const course: LessonSeed[] = [
  { chapter: "Bab 1 — Mulai dengan Kepala Dingin", title: "Kenapa Keamanan Itu Bukan Sekadar “Jangan Di-hack”", level: "Pemula", minutes: 14, explain: "Cyber security itu seni mengurangi peluang hal buruk dan memperkecil dampaknya kalau hal buruk tetap terjadi. Bukan janji hidup bakal 100% aman, tapi cara supaya kamu nggak masuk ke masalah dengan mata tertutup.", analogy: "Kayak naik motor: helm tidak menjamin kamu tidak jatuh, tapi mengubah seberapa parah akibatnya kalau sesuatu yang tidak enak terjadi.", story: "Dina mengira keamanan cuma urusan orang IT. Begitu akun toko kakaknya diambil alih, baru kelihatan: yang terdampak bukan server doang, tapi pelanggan, uang, reputasi, dan waktu tidur satu keluarga.", practice: "Pilih satu proyek atau akun milikmu. Tulis tiga hal yang paling bikin repot kalau hilang, bocor, atau diambil orang.", guardrail: "Kita belajar untuk melindungi diri dan sistem yang memang punya izin. Rasa penasaran bukan izin untuk menyentuh sistem orang lain.", check: "membedakan tujuan keamanan: mencegah, mendeteksi, merespons, dan pulih" , sourceKeys: ["cs50", "ethicalOne", "handsOn"] },
  { chapter: "Bab 1 — Mulai dengan Kepala Dingin", title: "Aset, Ancaman, Dampak: Peta Sebelum Panik", level: "Pemula", minutes: 15, explain: "Threat model itu bukan ritual formal yang cuma cocok buat perusahaan besar. Intinya sederhana: apa yang berharga, siapa atau apa yang bisa mengganggu, dampaknya apa, lalu kontrol kecil mana yang paling masuk akal dikerjakan dulu.", analogy: "Sebelum pasang gembok, kamu perlu tahu barang mana yang ada di rumah, pintu mana yang sering kebuka, dan siapa yang punya kunci cadangan.", story: "Tim aplikasi kecil punya sepuluh fitur, tetapi satu API key memberi akses ke semua data. Mereka tidak butuh diagram rumit untuk menyadari satu kunci itu adalah prioritas pertama.", practice: "Buat tabel empat kolom: aset, kejadian buruk, dampak, dan kontrol pertama. Gunakan proyek milik sendiri atau data fiktif.", guardrail: "Peta ancaman adalah alat memilih prioritas, bukan alasan untuk mengumpulkan data berlebihan tentang orang lain.", check: "menghubungkan aset, ancaman, dampak, dan kontrol" , sourceKeys: ["cs50", "ethicalTwelve", "handsOn"] },
  { chapter: "Bab 1 — Mulai dengan Kepala Dingin", title: "Lab Legal: Tempat Salah yang Aman", level: "Pemula", minutes: 13, explain: "Belajar keamanan perlu ruang bermain yang jelas: mesin virtual sendiri, aplikasi latihan, data palsu, atau platform yang memang memberi izin. Dengan begitu kamu bisa penasaran, salah, dan memperbaiki tanpa bikin masalah buat orang lain.", analogy: "Kayak belajar nyetir di lapangan latihan dulu, bukan langsung bawa mobil ke jalur busway.", story: "Reno menemukan tutorial menarik dan hampir mencoba semua langkahnya di Wi-Fi kampus. Temannya mengingatkan bahwa skill yang bagus selalu dimulai dari scope dan izin yang jelas.", practice: "Tulis aturan lab pribadimu: aset yang boleh dipakai, data yang dilarang dipakai, cara kembali ke keadaan awal, dan siapa yang dihubungi kalau ada masalah.", guardrail: "Jangan memindai, menguji, atau mencoba masuk ke jaringan, akun, perangkat, atau situs yang bukan milikmu tanpa izin tertulis.", check: "menjelaskan arti scope, izin, dan data fiktif dalam lab" , sourceKeys: ["ethicalOne", "ethicalTwo", "handsOn"] },
  { chapter: "Bab 2 — Akun dan Data Pribadi", title: "Password Unik Itu Bukan Lebay", level: "Pemula", minutes: 12, explain: "Password yang dipakai ulang membuat satu kebocoran bisa merembet ke banyak pintu. Password manager membantu karena ia menyimpan kunci unik tanpa memaksa otakmu jadi lemari arsip yang capek.", analogy: "Kalau semua pintu rumah, motor, dan loker memakai kunci yang sama, satu kunci hilang berarti semuanya ikut kebuka.", story: "Arif merasa password yang sama lebih praktis. Saat satu layanan lama bocor, notifikasi login aneh mulai muncul di email dan marketplace-nya. Praktisnya hilang, repotnya malah nambah.", practice: "Pilih dua akun penting. Pastikan password-nya unik, panjang, dan tidak dipakai ulang. Bila perlu, mulai pindah dengan password manager.", guardrail: "Jangan pernah menulis password, kode recovery, atau kode MFA di chat, screenshot, atau catatan publik.", check: "menjelaskan mengapa reuse password memperbesar dampak kebocoran" , sourceKeys: ["cs50"] },
  { chapter: "Bab 2 — Akun dan Data Pribadi", title: "MFA, Recovery, dan Sesi: Tiga Teman Sekamar", level: "Pemula", minutes: 14, explain: "Keamanan akun bukan cuma password. MFA menambah bukti kedua, recovery membantu saat kamu terkunci, dan sesi menentukan perangkat mana yang masih dipercaya setelah berhasil masuk.", analogy: "Password itu kunci pintu, MFA itu satpam yang tanya satu hal lagi, dan sesi itu gelang acara yang membuktikan kamu sudah diperiksa.", story: "Naya rajin pakai MFA, tapi lupa mengecek perangkat yang masih login dari laptop lama. Ia lalu menutup sesi yang tidak dipakai dan menyimpan recovery code di tempat aman.", practice: "Periksa satu akun penting: MFA aktif atau belum, recovery email benar atau tidak, dan apakah ada perangkat yang sudah tidak kamu pakai tapi masih masuk.", guardrail: "Kalau ada prompt login yang tidak kamu minta, jangan asal menyetujui. Periksa dulu dari aplikasi atau situs resminya.", check: "membedakan MFA, recovery, dan sesi perangkat" , sourceKeys: ["cs50", "helpDesk"] },
  { chapter: "Bab 2 — Akun dan Data Pribadi", title: "Social Engineering: Jangan Keburu Kasihan atau Panik", level: "Pemula", minutes: 15, explain: "Serangan sosial biasanya mengejar reaksi manusia: takut, buru-buru, penasaran, atau sungkan. Pertahanannya bukan jadi orang curigaan terus, tapi punya kebiasaan verifikasi lewat jalur kedua.", analogy: "Seperti ada orang mengetuk rumah sambil bilang ‘saya teknisi, cepat buka’. Kalimatnya mungkin meyakinkan, tapi identitas tetap perlu dicek lewat nomor resmi.", story: "Pesan yang mengaku dari kurir meminta OTP karena paket ‘akan dibatalkan’. Bukan teknologinya yang canggih; yang dipancing adalah rasa takut kehilangan paket.", practice: "Buat aturan berhenti 30 detik: cek pengirim, cek konteks, buka aplikasi resmi sendiri, lalu tanyakan orang tepercaya kalau masih ragu.", guardrail: "Jangan menyebarkan contoh phishing yang aktif atau mencoba mengelabui orang lain atas nama latihan.", check: "memilih langkah verifikasi sebelum menanggapi pesan mendesak" , sourceKeys: ["cs50", "helpDesk"] },
  { chapter: "Bab 3 — Sistem yang Tidak Bikin Kaget", title: "Sistem Operasi Itu Rumah, Log Itu Buku Harian", level: "Pemula", minutes: 16, explain: "Linux, Windows, dan macOS punya cara mengelola pengguna, file, proses, dan log. Kamu tidak harus hafal semua perintah untuk mulai aman; yang penting tahu apa yang berubah sebelum buru-buru memperbaiki.", analogy: "Rumah yang baik punya daftar penghuni, aturan ruangan, dan buku catatan kalau ada kejadian aneh. Sistem operasi juga begitu.", story: "Laptop tim terasa lambat. Sebelum menghapus aplikasi secara acak, mereka melihat proses aktif, ruang penyimpanan, dan log dasar. Ternyata penyebabnya backup yang macet, bukan malware.", practice: "Di perangkatmu sendiri, cari lokasi pembaruan sistem, daftar aplikasi startup, dan halaman log dasar. Catat tiga hal tanpa mengubah apa pun.", guardrail: "Jangan menjalankan perintah yang tidak kamu pahami hanya karena terlihat keren di tutorial.", check: "menjelaskan peran user, proses, permission, dan log" , sourceKeys: ["kali", "helpDesk", "powershell"] },
  { chapter: "Bab 3 — Sistem yang Tidak Bikin Kaget", title: "Kali Linux: Laboratorium, Bukan Kostum Hacker", level: "Pemula", minutes: 14, explain: "Kali Linux adalah distribusi yang sering dipakai dalam pembelajaran keamanan karena memusatkan banyak tool. Nilainya bukan pada tampilannya, tetapi pada disiplin memakai lingkungan terpisah, data latihan, dan catatan yang rapi.", analogy: "Seperti kotak perkakas bengkel. Punya banyak alat tidak otomatis membuatmu montir, apalagi memberi izin membongkar motor orang.", story: "Fahri memasang Kali hanya untuk merasa ‘serius’. Setelah itu ia sadar yang lebih penting adalah membuat VM lab, snapshot, dan catatan sebelum menyentuh tool apa pun.", practice: "Buat rencana lab di atas kertas: host, VM latihan, snapshot, data fiktif, dan tombol darurat untuk memutus koneksi lab.", guardrail: "Tool keamanan tidak boleh digunakan pada target nyata tanpa izin; fokus materi ini adalah pemahaman dan pertahanan.", check: "menjelaskan fungsi Kali sebagai lingkungan lab legal" , sourceKeys: ["kali", "handsOn", "ethicalOne"] },
  { chapter: "Bab 3 — Sistem yang Tidak Bikin Kaget", title: "Jaringan: Biar Tahu Data Lagi Jalan Lewat Mana", level: "Pemula", minutes: 17, explain: "Saat aplikasi bicara ke internet, ada perangkat, alamat, protokol, dan jalur yang ikut bekerja. Paham jalur ini membantu kamu membedakan masalah Wi-Fi biasa, konfigurasi, atau sesuatu yang memang perlu diselidiki lebih lanjut.", analogy: "Paket online tidak teleport. Ada alamat pengirim, alamat tujuan, gudang transit, dan aturan pengantaran. Data juga begitu.", story: "Aplikasi kasir tidak bisa sinkron. Tim awalnya menyalahkan server, padahal DNS di satu perangkat salah. Dengan menggambar jalur perangkat–router–internet–layanan, masalahnya jadi lebih mudah dicari.", practice: "Gambarkan jalur ketika kamu membuka satu situs: perangkat, Wi-Fi, router, DNS, HTTPS, dan layanan tujuan. Tulis titik mana yang kamu kontrol.", guardrail: "Jangan menangkap atau membaca trafik jaringan orang lain. Gunakan trafik milik sendiri atau sampel latihan yang disediakan.", check: "menggambarkan jalur dasar permintaan dari perangkat ke layanan" , sourceKeys: ["handsOn", "ethicalTwelve", "soc"] },
  { chapter: "Bab 4 — Aplikasi Web dan Rahasia", title: "Input Itu Tamu: Harus Disapa, Bukan Diberi Kunci Rumah", level: "Pemula", minutes: 16, explain: "Semua input dari form, URL, file, API, bahkan model AI perlu diperlakukan sebagai data yang belum bisa dipercaya. Aplikasi yang sehat memeriksa bentuk, batas, dan konteks sebelum input dipakai.", analogy: "Kalau ada tamu membawa tas ke rumah, kamu tidak perlu curiga berlebihan; cukup jangan langsung biarkan tas itu masuk ke lemari pribadi tanpa diperiksa.", story: "Formulir internal menerima field catatan bebas. Ketika input itu langsung dipantulkan ke halaman lain, tim baru sadar data dari pengguna bisa mengubah pengalaman pengguna lain kalau tidak diperlakukan dengan aman.", practice: "Pilih satu input aplikasi milikmu. Tulis: siapa pengirimnya, format yang diharapkan, batas panjangnya, dan apa yang harus terjadi bila data tidak cocok.", guardrail: "Latihan ini membahas desain pertahanan, bukan pengujian agresif terhadap situs pihak lain.", check: "memperlakukan input eksternal sebagai data tidak tepercaya" , sourceKeys: ["webSecurity", "webBeginner", "handsOn"] },
  { chapter: "Bab 4 — Aplikasi Web dan Rahasia", title: "Login, Otorisasi, dan “Boleh Masuk” Itu Beda", level: "Menengah", minutes: 17, explain: "Autentikasi menjawab ‘kamu siapa’, sedangkan otorisasi menjawab ‘setelah masuk, kamu boleh melakukan apa’. Banyak masalah muncul ketika aplikasi puas hanya memastikan orang sudah login tanpa membatasi aksinya.", analogy: "Masuk gedung pakai kartu adalah autentikasi. Bisa masuk ruang keuangan atau gudang adalah otorisasi. Dua hal ini jangan dicampur.", story: "Aplikasi komunitas punya admin dan anggota. Karena satu endpoint tidak memeriksa peran, anggota biasa hampir bisa melihat data pengelolaan. Perbaikannya bukan tombol UI saja, tetapi pengecekan di server.", practice: "Buat matriks kecil berisi peran dan aksi: lihat, buat, edit, hapus, ekspor. Tandai mana yang perlu approval.", guardrail: "Jangan mencoba membuka data atau peran yang bukan milikmu untuk membuktikan poin ini.", check: "membedakan autentikasi dan otorisasi" , sourceKeys: ["webSecurity", "webBeginner", "activeDirectory"] },
  { chapter: "Bab 4 — Aplikasi Web dan Rahasia", title: "Secret Hygiene: Kunci API Bukan Aksesori Repo", level: "Pemula", minutes: 15, explain: "Secret seperti API key, token, dan credential perlu disimpan terpisah, diberi scope minimum, dipantau, dan dirotasi bila ada kemungkinan bocor. Menghapus teks dari layar tidak berarti aksesnya hilang.", analogy: "Kartu debit yang sempat difoto lalu diburamkan di Instagram tetap perlu diblokir. Masalahnya bukan tampilan kartunya, tapi kemampuan yang sudah terlanjur tersebar.", story: "Key percobaan masuk ke repo publik. Tim tidak berhenti di ‘hapus commit’; mereka mencabut key, membuat key baru, mempersempit izin, dan mencari log yang mungkin ikut menyimpan nilai lama.", practice: "Audit proyek sendiri: daftar lokasi secret, pemilik, fungsi, scope, dan langkah rotasi bila nilainya terekspos.", guardrail: "Jangan menaruh secret asli pada tugas, screenshot, prompt, atau contoh kode publik.", check: "menentukan respons aman ketika secret dicurigai bocor" , sourceKeys: ["cs50", "webSecurity", "helpDesk"] },
  { chapter: "Bab 4 — Aplikasi Web dan Rahasia", title: "Bug Bounty dan Disclosure: Laporkan, Jangan Pamer", level: "Menengah", minutes: 16, explain: "Menemukan masalah keamanan bukan tiket untuk mengumumkan, mengeksploitasi, atau mengakses data. Jalur yang dewasa adalah menghormati scope, mengumpulkan bukti minimal, dan melapor lewat kanal yang disediakan.", analogy: "Kalau menemukan lantai licin di mal, kamu lapor satpam dan tunjukkan lokasinya; kamu tidak perlu membuat orang lain jatuh untuk membuktikan lantainya licin.", story: "Seseorang menemukan perilaku aneh di situs. Ia menulis waktu, dampak potensial, langkah reproduksi yang minimal, lalu mengirimkannya lewat policy disclosure—tanpa mengambil data siapa pun.", practice: "Baca satu halaman vulnerability disclosure program. Catat scope, aset terlarang, kanal laporan, dan aturan safe harbor yang tertulis.", guardrail: "Tidak semua situs punya program. Kalau tidak ada izin jelas, jangan menguji sistemnya.", check: "menjelaskan unsur laporan kerentanan yang bertanggung jawab" , sourceKeys: ["bugBounty", "ethicalTwo", "webSecurity"] },
  { chapter: "Bab 5 — Identitas dan Akses Organisasi", title: "Least Privilege: Bukan Pelit Akses, Tapi Sayang Sistem", level: "Menengah", minutes: 15, explain: "Least privilege berarti orang, service, dan bot hanya mendapat izin yang benar-benar dibutuhkan. Ini membuat kesalahan kecil tidak langsung berubah menjadi bencana besar.", analogy: "Petugas parkir boleh masuk pos parkir, tetapi tidak perlu memegang kunci ruang arsip atau akses rekening perusahaan.", story: "Bot laporan diberi akses admin database karena dianggap paling cepat. Ketika bug muncul, risikonya langsung besar. Setelah haknya jadi read-only, masalah serupa tidak lagi punya dampak seluas itu.", practice: "Buat daftar peran proyekmu. Untuk tiap peran, tulis satu izin yang dibutuhkan dan satu izin yang sebenarnya tidak perlu.", guardrail: "Akses sementara juga perlu masa berlaku serta review, bukan dibiarkan jadi permanen.", check: "menerapkan izin minimum berdasarkan tugas" , sourceKeys: ["linuxPrivilege", "windowsPrivilege", "activeDirectory"] },
  { chapter: "Bab 5 — Identitas dan Akses Organisasi", title: "Permission di Linux dan Windows: Kebiasaan Kecil, Dampak Besar", level: "Menengah", minutes: 17, explain: "Permission menentukan siapa boleh membaca, mengubah, atau menjalankan sesuatu. Banyak insiden bukan karena ‘hacker super’, melainkan folder sensitif yang terbuka, akun lama yang tidak dicabut, atau konfigurasi default yang tidak ditinjau.", analogy: "Bayangkan lemari kantor. Bukan cuma soal ada gembok atau tidak, tapi siapa punya kunci, siapa meminjam, dan kapan kunci cadangan dikembalikan.", story: "Tim pindah proyek, tetapi akun vendor lama tetap aktif. Saat audit, mereka sadar masalahnya bukan satu password lemah, melainkan proses offboarding yang tidak pernah dibuat.", practice: "Di perangkat atau lab milik sendiri, dokumentasikan tiga hal yang perlu ditinjau: akun aktif, folder sensitif, dan aplikasi dengan izin tinggi.", guardrail: "Jangan mengubah permission sistem produksi hanya untuk mencoba; lakukan di lab dan simpan rencana rollback.", check: "mengenali konfigurasi akses yang perlu ditinjau" , sourceKeys: ["linuxPrivilege", "windowsPrivilege", "kali"] },
  { chapter: "Bab 5 — Identitas dan Akses Organisasi", title: "Active Directory: Buku Alamat yang Kalau Berantakan Bikin Ribet", level: "Menengah", minutes: 18, explain: "Di banyak organisasi, directory menyatukan identitas pengguna, perangkat, grup, dan kebijakan. Karena jadi pusat kepercayaan, perubahan kecil yang tak terdokumentasi bisa berdampak ke banyak orang.", analogy: "Seperti buku alamat, daftar kunci, dan aturan ruangan kantor yang digabung jadi satu. Praktis, tapi kalau daftar itu salah, semua pintu ikut membingungkan.", story: "Divisi baru dibentuk cepat. Akun dan grup dibuat asal jalan, lalu beberapa orang mendapat akses lebih dari yang dibutuhkan. Audit grup membantu tim mengembalikan struktur ke alasan bisnis yang jelas.", practice: "Gambar organisasi fiktif dengan tiga tim. Tentukan grup akses, owner, proses joiner–mover–leaver, dan frekuensi review.", guardrail: "Gunakan contoh fiktif atau lab. Jangan mencoba mengubah directory organisasi tanpa perubahan yang disetujui.", check: "menjelaskan hubungan identitas, grup, perangkat, dan kebijakan" , sourceKeys: ["activeDirectory", "powershell", "helpDesk"] },
  { chapter: "Bab 6 — OSINT Tanpa Jadi Kepo Liar", title: "Jejak Digital: Sedikit-Sedikit Bisa Jadi Cerita Besar", level: "Pemula", minutes: 14, explain: "OSINT memakai informasi yang memang tersedia publik untuk memahami konteks. Pelajarannya bukan mengumpulkan sebanyak mungkin, melainkan menguji relevansi, asal, tanggal, dan dampak privasi sebelum memakai informasi.", analogy: "Seperti menyusun puzzle dari potongan yang ada di meja. Potongannya terbuka, tapi kamu tetap harus berpikir apakah pantas dan perlu menyusun gambar seseorang.", story: "Tim keamanan ingin tahu akun palsu yang mengatasnamakan brand. Mereka tidak mengejar kehidupan pribadi siapa pun; mereka membandingkan nama domain, kanal resmi, waktu posting, dan tanda verifikasi.", practice: "Pilih organisasi yang kamu ikuti. Buat daftar kanal resminya dari situs mereka sendiri dan catat bagaimana kamu membedakan akun resmi dari akun peniru.", guardrail: "Informasi publik bukan izin untuk doxxing, stalking, atau menyusun profil personal yang tidak relevan.", check: "membedakan OSINT defensif dari pelanggaran privasi" , sourceKeys: ["osint", "cs50"] },
  { chapter: "Bab 6 — OSINT Tanpa Jadi Kepo Liar", title: "Validasi Informasi: Jangan Ketipu Screenshot", level: "Pemula", minutes: 13, explain: "Informasi publik sering tampak meyakinkan karena desainnya rapi atau sudah dibagikan banyak orang. Validasi berarti kembali ke sumber primer, membandingkan waktu, dan menandai apa yang belum kita tahu.", analogy: "Screenshot itu seperti potongan percakapan: bisa benar, tapi kamu belum tahu siapa yang bicara, kapan, dan apa kalimat sebelum-sesudahnya.", story: "Ada unggahan soal kebocoran data yang viral. Sebelum panik, tim mengecek kanal resmi, tanggal, domain, dan apakah contoh data benar-benar baru atau daur ulang dari insiden lama.", practice: "Ambil satu klaim publik tentang produk atau layanan. Catat sumber asli, tanggal, bukti pendukung, dan satu hal yang masih belum pasti.", guardrail: "Jangan menyebarkan dugaan sebagai fakta, apalagi bila menyangkut orang atau organisasi tertentu.", check: "membedakan klaim, bukti, dan asumsi" , sourceKeys: ["osint", "soc"] },
  { chapter: "Bab 6 — OSINT Tanpa Jadi Kepo Liar", title: "Batas Etika OSINT: Tujuan Dulu, Data Belakangan", level: "Menengah", minutes: 15, explain: "Pertanyaan etika paling penting bukan ‘bisa dicari atau tidak’, tetapi ‘kenapa perlu, seberapa sedikit yang cukup, dan siapa yang bisa terdampak’. Kebiasaan ini menjaga riset tetap berguna tanpa berubah jadi pengumpulan data yang berlebihan.", analogy: "Kalau kamu meminjam senter untuk mencari kunci, arahkan ke lantai dekat pintu; jangan sekalian menyorot seluruh rumah tetangga.", story: "Tim membuat daftar risiko vendor. Mereka hanya mengumpulkan informasi yang relevan dengan kontrak dan keamanan layanan, lalu menetapkan masa simpan serta siapa yang boleh melihat catatan.", practice: "Tulis tujuan riset fiktif, tiga jenis data yang relevan, dua jenis data yang sengaja tidak dikumpulkan, dan alasan batasnya.", guardrail: "Hentikan riset kalau scope-nya mulai bergeser ke detail pribadi yang tidak berkaitan dengan tujuan defensif.", check: "menetapkan batas pengumpulan informasi yang proporsional" , sourceKeys: ["osint", "bugBounty"] },
  { chapter: "Bab 7 — Deteksi dan Respons", title: "Log Itu Bukan Sampah Digital", level: "Pemula", minutes: 16, explain: "Log adalah jejak kejadian: siapa melakukan apa, kapan, dari mana, dan hasilnya bagaimana. Log yang rapi membantu tim membedakan ‘rasanya aneh’ dari kejadian yang benar-benar bisa ditelusuri.", analogy: "Kayak CCTV dan buku tamu digabung. Kalau ada kejadian, kamu tidak cuma mengandalkan ingatan orang yang kebetulan lewat.", story: "Akun pelanggan tidak bisa masuk. Dengan log autentikasi, tim melihat beberapa percobaan gagal lalu satu reset password yang sah. Mereka tidak perlu menebak-nebak atau menyalahkan pengguna.", practice: "Pilih aplikasi atau perangkat milik sendiri. Temukan satu halaman aktivitas/log, lalu catat informasi apa yang muncul dan apa yang sebaiknya tidak disimpan.", guardrail: "Log membantu diagnosis, tetapi jangan sampai log justru menyimpan password, token, atau data pribadi yang tidak perlu.", check: "menjelaskan fungsi log dalam investigasi defensif" , sourceKeys: ["soc", "helpDesk", "powershell"] },
  { chapter: "Bab 7 — Deteksi dan Respons", title: "Alert: Bel Bukan Musik Latar", level: "Menengah", minutes: 14, explain: "Alert yang baik menjawab tiga hal: apa yang terjadi, seberapa mendesak, dan siapa yang harus melakukan apa. Kalau semua hal berbunyi terus, tim malah belajar mengabaikannya.", analogy: "Alarm rumah yang berbunyi tiap ada kucing lewat akhirnya tidak lagi dipercaya. Alarm perlu konteks supaya orang tahu kapan harus bergerak.", story: "Tim membuat alert untuk semua error kecil. Seminggu kemudian, notifikasi ratusan kali sehari dan kejadian penting tenggelam. Mereka lalu menyusun severity, owner, dan aturan eskalasi.", practice: "Rancang tiga level alert untuk layanan fiktif: informasi, perlu dicek, dan darurat. Tulis aksi pertama untuk tiap level.", guardrail: "Jangan otomatis menutup insiden hanya karena alert berhenti; cek dampak dan bukti pemulihan.", check: "membedakan sinyal informasi, warning, dan insiden" , sourceKeys: ["soc", "helpDesk"] },
  { chapter: "Bab 7 — Deteksi dan Respons", title: "Respons Insiden: Tenang, Catat, Baru Bergerak", level: "Menengah", minutes: 18, explain: "Saat ada dugaan insiden, tujuannya bukan menemukan kambing hitam. Tim perlu mengamankan keadaan, menjaga bukti, memberi tahu orang yang tepat, dan membuat keputusan yang bisa dijelaskan setelah tekanan turun.", analogy: "Seperti kebakaran kecil di dapur: matikan sumber risiko jika aman, panggil bantuan, catat apa yang terjadi, dan jangan sibuk berdebat siapa yang terakhir masak.", story: "Ada key yang tidak sengaja masuk log. Tim segera mencabut key, memeriksa penggunaan, mengganti konfigurasi, dan menulis timeline singkat supaya pembelajaran tidak hilang setelah masalah selesai.", practice: "Buat runbook satu halaman untuk skenario secret bocor: deteksi, contain, owner, komunikasi, pemeriksaan dampak, dan langkah belajar ulang.", guardrail: "Jangan menghapus bukti atau log secara panik. Ikuti prosedur organisasi dan minta bantuan bila kejadian menyentuh data sensitif.", check: "menyusun urutan respons awal yang aman" , sourceKeys: ["soc", "ethicalTwelve", "helpDesk"] },
  { chapter: "Bab 8 — Kode dan Otomasi yang Lebih Aman", title: "Python untuk Membaca Pola, Bukan Mengacak-acak Sistem", level: "Pemula", minutes: 15, explain: "Python berguna untuk pekerjaan defensif yang membosankan bila dilakukan manual: merapikan log fiktif, menghitung event, memeriksa format, atau membuat laporan kecil. Nilainya ada pada data yang lebih mudah dibaca dan keputusan yang lebih cepat.", analogy: "Seperti membuat mesin sortir surat. Mesin bukan petugas keamanan, tapi membantu petugas menemukan tumpukan yang perlu dilihat dulu.", story: "Niko punya seribu baris log latihan. Ia membuat skrip kecil untuk menghitung jenis error per hari. Hasilnya bukan ‘membobol apa pun’, tetapi pola yang lebih gampang didiskusikan tim.", practice: "Gunakan CSV fiktif. Rancang skrip yang hanya membaca data dan menghitung jumlah event per kategori; tulis dulu output yang kamu harapkan.", guardrail: "Skrip pembelajaran sebaiknya read-only, memakai data fiktif, dan tidak menyimpan credential di kode.", check: "menjelaskan peran otomatisasi defensif sederhana" , sourceKeys: ["python", "soc"] },
  { chapter: "Bab 8 — Kode dan Otomasi yang Lebih Aman", title: "Keamanan Memori: Kenapa “Sedikit Salah” Bisa Mahal", level: "Menengah", minutes: 16, explain: "Beberapa bug muncul saat program salah mengelola batas memori atau data. Kamu tidak perlu belajar mengeksploitasi bug untuk paham pelajarannya: validasi batas, gunakan library tepercaya, patch rutin, dan pilih desain yang membuat kesalahan sulit terjadi.", analogy: "Seperti memasukkan barang ke kardus. Kalau kamu terus memaksa barang melebihi ukuran kardus, yang rusak bukan cuma kardusnya; barang di sekitarnya juga bisa kena.", story: "Tim membahas bug lama di komponen rendah level. Alih-alih mengejar trik serangan, mereka fokus pada review input, pembaruan dependency, testing, dan bahasa/abstraksi yang membantu mengurangi kelas kesalahan tertentu.", practice: "Ambil fungsi fiktif yang menerima teks. Tulis pertanyaan review: batas panjang, karakter tak terduga, error handling, dan test untuk input kosong.", guardrail: "Materi ini tidak memberikan langkah exploit; gunakan hanya untuk memperkuat desain dan review kode sendiri.", check: "menghubungkan validasi batas dengan pengurangan risiko bug" , sourceKeys: ["memory", "rust"] },
  { chapter: "Bab 8 — Kode dan Otomasi yang Lebih Aman", title: "Patch, Dependency, dan Utang Keamanan", level: "Menengah", minutes: 15, explain: "Aplikasi hampir selalu memakai dependency. Karena itu, keamanan bukan sekali selesai saat kode ditulis; ada kebiasaan mengecek versi, membaca perubahan, menguji update, dan punya rencana kalau update membawa masalah baru.", analogy: "Seperti merawat motor. Suku cadang yang bagus tetap perlu dicek berkala, bukan hanya dipasang lalu dilupakan.", story: "Aplikasi berjalan lancar berbulan-bulan, tetapi satu library lama punya perbaikan penting. Tim membuat daftar dependency, owner, jadwal review, serta staging untuk menguji update sebelum rilis.", practice: "Buat inventory kecil untuk proyekmu: dependency utama, fungsi, versi, owner, dan kapan terakhir ditinjau.", guardrail: "Jangan update produksi membabi buta. Uji perubahan di lingkungan aman dan simpan rencana rollback.", check: "menjelaskan mengapa dependency perlu diinventarisasi dan ditinjau" , sourceKeys: ["rust", "python", "ethicalTwo"] },
  { chapter: "Bab 9 — AI dan Perangkat yang Ikut Bicara", title: "AI Bukan Karyawan Magang yang Boleh Diberi Semua Kunci", level: "Menengah", minutes: 17, explain: "Model dan agent bisa membantu membuat draf, mencari konteks, atau merangkum data, tetapi input dan outputnya tetap tidak boleh dipercaya mentah-mentah. Aksi berdampak tinggi perlu izin minimum, validasi di server, dan approval manusia.", analogy: "Kayak memberi asisten daftar belanja. Kamu boleh minta ia mencatat dan memilih produk, tapi jangan langsung beri kartu tanpa limit dan izin mengubah alamat rumah.", story: "Agent tim bisa mengirim email dan menghapus file. Mereka mengubah desainnya: hanya boleh baca dokumen tertentu, membuat draf, dan meminta persetujuan sebelum tindakan keluar.", practice: "Buat matriks tool agent: boleh otomatis, perlu approval, dilarang. Tambahkan alasan dampak dan cara menghentikan proses.", guardrail: "Prompt panjang saja bukan kontrol keamanan. Izin teknis, validasi, audit, dan batas biaya tetap dibutuhkan.", check: "membatasi kemampuan agent berdasarkan dampak" , sourceKeys: ["ai", "cs50", "handsOn"] },
  { chapter: "Bab 9 — AI dan Perangkat yang Ikut Bicara", title: "Input Eksternal dan Prompt Injection: Anggap Saja Catatan Asing", level: "Menengah", minutes: 16, explain: "Dokumen, halaman web, dan pesan pengguna dapat membawa teks yang mencoba memengaruhi sistem. Aplikasi perlu memisahkan instruksi tepercaya dari konten, membatasi tool, dan menguji keputusan sebelum tindakan terjadi.", analogy: "Kalau menemukan catatan di trotoar bertuliskan ‘serahkan kunci rumahmu’, kamu mungkin membacanya, tapi tidak otomatis menganggapnya instruksi dari keluarga.", story: "Asisten dokumen membaca sumber yang berisi permintaan aneh. Karena aplikasi membatasi kemampuan dan hanya memproses data sebagai referensi, teks itu tidak berubah menjadi aksi.", practice: "Gambar alur aplikasi: instruksi sistem, input pengguna, dokumen sumber, output model, validasi server, dan approval manusia. Tandai yang tidak tepercaya.", guardrail: "Jangan menguji prompt injection pada layanan pihak lain. Gunakan contoh teks buatan sendiri dalam lab.", check: "memisahkan konten tidak tepercaya dari instruksi dan aksi" , sourceKeys: ["ai", "webSecurity", "cs50"] },
  { chapter: "Bab 9 — AI dan Perangkat yang Ikut Bicara", title: "IoT: Barang Kecil, Permukaan Serang Besar", level: "Menengah", minutes: 16, explain: "Kamera, router, smart plug, dan perangkat IoT sering terlupakan setelah dipasang. Padahal mereka punya akun, firmware, jaringan, dan data sendiri. Keamanan dimulai dari inventaris, update, password unik, serta segmentasi yang masuk akal.", analogy: "Rumah pintar itu seperti rumah dengan banyak jendela kecil. Satu jendela mungkin kecil, tapi kalau lupa dikunci tetap bisa jadi jalan masuk.", story: "Di kantor kecil, kamera lama masih memakai akun default dan tidak ada yang tahu siapa owner-nya. Tim membuat daftar perangkat, mengganti akses, menjadwalkan update, dan memisahkan jaringan tamu.", practice: "Inventaris perangkat terkoneksi di rumah atau lab milikmu: nama, owner, jaringan, status update, dan apakah password default sudah diganti.", guardrail: "Jangan mengakses perangkat tetangga, perangkat umum, atau perangkat organisasi tanpa izin eksplisit.", check: "membuat inventory dasar aset IoT" , sourceKeys: ["iot", "helpDesk", "ethicalTwelve"] },
  { chapter: "Bab 10 — Kerja Profesional dan Capstone", title: "Menulis Temuan yang Bikin Orang Mau Memperbaiki", level: "Menengah", minutes: 17, explain: "Laporan keamanan yang berguna tidak pamer istilah. Ia menjelaskan konteks, dampak, bukti minimal, rekomendasi praktis, owner, dan cara memeriksa apakah perbaikan berhasil.", analogy: "Seperti laporan dokter: bukan cuma nama penyakit, tapi apa dampaknya, apa yang perlu dilakukan, kapan kontrol lagi, dan tanda bahaya yang harus diperhatikan.", story: "Laporan satu halaman menyebut ‘security lemah’ tanpa detail. Tim penerima bingung harus mulai dari mana. Versi baru menyebut aset, risiko, prioritas, pemilik, dan langkah perbaikan yang bisa diuji.", practice: "Tulis temuan fiktif tentang password reuse dengan format: ringkasan, dampak, bukti aman, rekomendasi, owner, dan cara verifikasi.", guardrail: "Hindari menyebarkan bukti sensitif atau detail yang dapat membuat orang lain menyalahgunakan temuan.", check: "menulis rekomendasi yang dapat ditindaklanjuti" , sourceKeys: ["bugBounty", "ethicalTwo", "soc"] },
  { chapter: "Bab 10 — Kerja Profesional dan Capstone", title: "Skill Teknis + Cara Ngobrol = Dipercaya Tim", level: "Pemula", minutes: 14, explain: "Keamanan hampir selalu kerja tim. Kamu perlu bisa menjelaskan risiko tanpa menakut-nakuti, mendengar konteks operasional, dan menerima bahwa solusi terbaik kadang bertahap karena waktu serta biaya terbatas.", analogy: "Kayak jadi penerjemah antara orang yang melihat asap dan orang yang bertugas menjaga gedung tetap buka. Dua-duanya perlu saling paham.", story: "Rafa menemukan konfigurasi kurang ideal, lalu mengirim pesan bernada menyalahkan. Tidak ada yang bergerak. Saat ia mengganti pendekatan menjadi dampak, pilihan perbaikan, dan bantuan yang dibutuhkan, tim mulai bekerja sama.", practice: "Ubah satu kalimat teknis menjadi pesan untuk non-teknis: risiko, dampak, pilihan, dan langkah pertama yang realistis.", guardrail: "Jujur tentang batas pengetahuanmu. Tidak tahu lalu bertanya itu lebih aman daripada mengarang kepastian.", check: "mengomunikasikan risiko dengan jelas dan tidak menghakimi" , sourceKeys: ["career", "helpDesk", "soc"] },
  { chapter: "Bab 10 — Kerja Profesional dan Capstone", title: "Capstone: Rencana Keamanan untuk Proyek yang Kamu Punya", level: "Lanjut", minutes: 25, explain: "Capstone menyatukan seluruh jalur: inventaris aset, akun, data, akses, log, respons insiden, dependency, AI atau IoT bila relevan, serta rencana perbaikan bertahap. Tujuannya bukan membuat dokumen sempurna, tetapi rencana yang benar-benar bisa dipakai.", analogy: "Seperti checklist sebelum perjalanan jauh. Kamu tidak bisa mengendalikan cuaca, tapi bisa memastikan bahan bakar, rem, kontak darurat, dan rute cadangan sudah dipikirkan.", story: "Tim belajar memilih satu aplikasi kecil, lalu menemukan lima perbaikan realistis: aktifkan MFA, rotasi key lama, batasi akses bot, tambah log tanpa token, dan buat owner untuk review bulanan.", practice: "Buat dokumen satu halaman: aset, risiko utama, kontrol yang sudah ada, tiga perbaikan 30 hari, owner, dan cara mengecek progres. Gunakan data fiktif bila proyek belum punya izin.", guardrail: "Capstone bukan penetration test dan bukan sertifikasi. Bila menemukan risiko nyata pada organisasi, ikuti kanal eskalasi yang sah.", check: "mengubah konsep keamanan menjadi rencana tindakan bertahap" , sourceKeys: ["cs50", "handsOn", "ethicalOne", "ethicalTwo", "ethicalTwelve", "webSecurity", "osint", "webBeginner", "memory", "kali", "python", "linuxPrivilege", "windowsPrivilege", "activeDirectory", "bugBounty", "rust", "soc", "powershell", "ai", "helpDesk", "iot", "career"] },
];

function makeQuiz(seed: LessonSeed): QuizQuestion[] {
  return [
    { question: `Setelah belajar “${seed.title}”, kebiasaan paling sehat adalah…`, options: [seed.check, "Mencoba semua tool pada sistem yang tidak memberi izin", "Menghafal istilah tanpa memahami dampaknya"], answer: 0, explanation: `Iya. Fokus checkpoint ini adalah ${seed.check.toLowerCase()}.` },
    { question: "Kalau kamu belum yakin suatu tindakan aman dan diizinkan, langkah pertama yang paling benar?", options: ["Berhenti, cek scope/izin, lalu gunakan lab atau minta bantuan", "Lanjut saja supaya cepat tahu", "Bagikan temuannya ke grup publik dulu"], answer: 0, explanation: "Dalam security, scope dan izin selalu datang sebelum rasa penasaran." },
  ];
}

const chapterNumbers = new Map(Array.from(new Set(course.map((seed) => seed.chapter))).map((chapter, index) => [chapter, index + 1]));
const subchapterNumbers = new Map<string, number>();

export const cyberSecurityMaterials: Material[] = course.map((seed, index) => {
  const subchapterNumber = (subchapterNumbers.get(seed.chapter) ?? 0) + 1;
  subchapterNumbers.set(seed.chapter, subchapterNumber);

  return ({
  id: 200 + index,
  displayNumber: index + 1,
  title: `${chapterNumbers.get(seed.chapter)}.${subchapterNumber} · ${seed.title}`,
  category: seed.chapter,
  specialization: "ai-security",
  level: seed.level,
  minutes: seed.minutes,
  emoji: "◆",
  summary: seed.explain,
  analogy: seed.analogy,
  sections: [
    { heading: "Ngobrol dulu", body: seed.explain },
    { heading: "Coba bayangin", body: seed.analogy },
    { heading: "Cerita teman satu tim", body: seed.story },
    { heading: "Latihan aman", body: seed.practice },
    { heading: "Jangan kelewatan", body: seed.guardrail },
  ],
  resources: seed.sourceKeys.map((key) => sources[key]),
  quiz: makeQuiz(seed),
  });
});
