import { checkpoint, defineIntensiveCourse } from "./intensiveCourseBlueprint";
import { createIntensiveCourseMaterials } from "./intensiveCourseFactory";
import { intensiveSources } from "./intensiveCourseSources";

const s = intensiveSources.data;
const safe = "Gunakan data sintetis, data publik yang sah, atau data yang telah dianonimkan. Jangan menyalin data pribadi/rahasia ke spreadsheet, notebook, dashboard, atau environment latihan.";

const dataCourse = defineIntensiveCourse({
  specialization: "data-engineering",
  label: "Data Analyst & Data Engineering",
  emoji: "▦",
  baseId: 6000,
  prologue: checkpoint({
    title: "Sebelum Masuk Course Inti",
    level: "Pemula",
    focus: "membedakan angka, keputusan, data, dan tanggung jawab sebelum membuka tool analitik",
    artifact: "kontrak pertanyaan data dan peta perjalanan course",
    guardrail: safe,
    sources: [s.pandas, s.video],
    topics: ["Apa yang Dikerjakan Analyst dan Data Engineer", "Dari Pertanyaan ke Keputusan", "Data Bukan Kebenaran Otomatis", "Siapa Pemilik Definisi Metrik", "Dataset, Tabel, Event, dan Dokumen", "Kualitas Data sebagai Kepercayaan", "Privacy dan Izin Sejak Awal", "Cara Memilih Tool Tanpa FOMO", "Notebook, SQL, Dashboard, dan Pipeline", "Eksperimen Aman dengan Data Sintetis", "Cara Membaca Course Ini", "Peta Jalan dari Prolog ke Data Product"],
    opening: "Data bukan sekadar angka atau query. Ia adalah jejak keputusan dan proses yang perlu dipahami sumbernya, dibatasi penggunaannya, dan disampaikan tanpa melebih-lebihkan kepastian.",
    caseTitle: "Tim Kawan Belajar ingin memahami kenapa peserta tidak kembali",
    caseNarrative: "Tim sudah memiliki banyak event, spreadsheet, dan komentar. Namun pertanyaan mereka masih kabur: apakah yang ingin dipahami retensi, kepuasan, error, atau kualitas konten? Mereka menyusun pertanyaan dan definisi sebelum membuat dashboard.",
    teachingPoint: "Data yang bermanfaat dimulai dari keputusan yang ingin dibantu, bukan visual yang ingin ditampilkan.",
    questions: ["Keputusan apa yang benar-benar ingin dibantu?", "Data apa yang diperlukan dan siapa pemiliknya?", "Batas interpretasi apa yang harus diketahui pembaca?"],
  }),
  chapters: [
    checkpoint({
      title: "Pertanyaan, Metrik, dan Kontrak Keputusan",
      level: "Pemula",
      focus: "menerjemahkan masalah bisnis atau produk menjadi pertanyaan yang dapat dibuktikan dengan data",
      artifact: "decision brief dan metric dictionary",
      guardrail: safe,
      sources: [s.pandas, s.postgres, s.video],
      topics: ["Masalah, Pertanyaan, dan Keputusan", "Leading versus Lagging Indicator", "North Star tanpa Menyederhanakan Berlebihan", "Definisi User Aktif", "Denominator dan Populasi", "Periode Waktu yang Tepat", "Segmentasi yang Bermakna", "Metric Tree", "Ambang dan Tindakan", "Asumsi serta Confounder", "Metric Dictionary", "Review Decision Brief"],
      opening: "Bab ini membuat kamu berhenti menulis query sebelum tahu keputusan apa yang akan berubah. Metric yang sehat memiliki definisi, owner, periode, denominator, dan tindakan ketika nilainya berubah.",
      caseTitle: "Retensi terlihat turun, tetapi tim tidak sepakat apa arti kembali",
      caseNarrative: "Satu orang menghitung login, yang lain menghitung membuka materi, dan product manager menghitung menyelesaikan quiz. Semua dashboard benar secara teknis tetapi membicarakan hal berbeda. Tim membuat metric dictionary dan decision brief.",
      teachingPoint: "Definisi yang disepakati sering memberi dampak lebih besar daripada visual yang paling cantik.",
      questions: ["Keputusan apa yang dipengaruhi metrik ini?", "Apa denominator dan periodenya?", "Siapa owner definisinya?"],
    }),
    checkpoint({
      title: "Spreadsheet dan SQL untuk Membaca Kenyataan",
      level: "Pemula",
      focus: "menyiapkan data tabular, membaca tabel, dan menyusun query read-only yang dapat ditinjau",
      artifact: "data dictionary, workbook bersih, dan query notebook",
      guardrail: "Gunakan database latihan/read-only dan dataset aman. Jangan menjalankan query mutasi atau ekspor data pribadi saat belajar.",
      sources: [s.pandas, s.postgres],
      topics: ["Grain: Satu Baris Mewakili Apa", "Data Dictionary yang Tidak Bohong", "Tipe Data dan Format Tanggal", "Nilai Kosong dan Nilai Tidak Diketahui", "Duplikasi dan Primary Key", "Select, Filter, dan Sort", "Aggregate serta Group By", "Join dan Risiko Double Count", "CTE untuk Membuat Query Terbaca", "Window Function Intuisi", "Validasi Sampel Query", "Review Workbook dan Query"],
      opening: "Spreadsheet dan SQL menjadi kuat ketika kamu tahu satu baris mewakili apa. Bab ini membangun kebiasaan memeriksa grain, key, filter, dan sampel sebelum percaya hasil agregasi.",
      caseTitle: "Jumlah peserta tampak dua kali lipat setelah menggabungkan tabel",
      caseNarrative: "Tim menggabungkan tabel peserta dan event tanpa memeriksa grain. Satu peserta dengan banyak event dihitung berulang sebagai orang baru. Mereka memperbaiki join, distinct, dan validasi sampel.",
      teachingPoint: "Query yang rapi tetap dapat salah jika grain dan join tidak dipahami.",
      questions: ["Satu baris hasil mewakili apa?", "Join mana yang dapat menggandakan angka?", "Sampel apa yang perlu diperiksa manual?"],
    }),
    checkpoint({
      title: "Statistik, Variasi, dan Eksperimen",
      level: "Menengah",
      focus: "membaca variasi data dan merancang eksperimen tanpa mengubah korelasi menjadi klaim sebab-akibat",
      artifact: "analysis plan dan experiment readout",
      guardrail: safe,
      sources: [s.pandas, s.looker],
      topics: ["Distribusi Bukan Sekadar Rata-Rata", "Mean, Median, dan Outlier", "Persentase dan Base Rate", "Sampling dan Bias Seleksi", "Correlation versus Causation", "Hipotesis yang Dapat Ditolak", "Control dan Treatment", "Randomisasi Intuisi", "Sample Size dan Durasi", "Guardrail Metric", "Membaca Hasil Eksperimen", "Review Experiment Readout"],
      opening: "Statistik membantu kamu melihat variasi, bukan memberi izin untuk mengarang kepastian. Bab ini mengajarkan cara menulis hipotesis dan menjaga eksperimen tetap dekat pada keputusan yang benar-benar bisa diubah.",
      caseTitle: "Fitur pengingat tampak menaikkan kelulusan, tetapi hanya dipakai peserta paling rajin",
      caseNarrative: "Tim melihat pengguna pengingat lebih sering selesai. Tanpa control group, mereka hampir menyimpulkan pengingat penyebabnya. Setelah merancang eksperimen, mereka melihat segmentasi dan guardrail lebih jelas.",
      teachingPoint: "Data observasional bisa memberi petunjuk, tetapi desain eksperimen memberi alasan yang lebih kuat untuk bertindak.",
      questions: ["Apa hipotesis dan metrik primary?", "Bias apa yang dapat menjelaskan hasil?", "Guardrail apa yang harus tidak memburuk?"],
    }),
    checkpoint({
      title: "Modelling Data dan Warehouse",
      level: "Menengah",
      focus: "mendesain data agar istilah bisnis dapat digunakan ulang, diuji, dan dijelaskan lintas tim",
      artifact: "model data konseptual dan warehouse map",
      guardrail: safe,
      sources: [s.postgres, s.dbt, s.video],
      topics: ["OLTP dan OLAP", "Fact, Dimension, dan Grain", "Star Schema Intuisi", "Slowly Changing Dimension", "Surrogate Key", "Event Model", "Snapshot dan Historis", "Metric Layer", "Naming Convention", "Warehouse Cost dan Partition", "Dokumentasi Model", "Review Warehouse Map"],
      opening: "Data model bukan diagram demi diagram. Ia adalah bahasa bersama supaya 'peserta aktif', 'order selesai', atau 'pendapatan' tidak dihitung berbeda oleh tiap dashboard.",
      caseTitle: "Tiga dashboard memberi angka pendapatan yang tidak sama",
      caseNarrative: "Finance menghitung refund berbeda dari product, sedangkan growth menggabungkan trial. Tim menyusun fact table, dimension, definisi status, dan model yang menjadi sumber bersama.",
      teachingPoint: "Warehouse yang berguna membuat definisi penting dapat dicari, digunakan ulang, dan diuji.",
      questions: ["Apa grain fact table ini?", "Dimensi mana yang diperlukan untuk segmentasi?", "Definisi bisnis mana yang harus disepakati?"],
    }),
    checkpoint({
      title: "Ingestion dan Kontrak Sumber Data",
      level: "Menengah",
      focus: "membawa data dari sumber ke platform dengan owner, schema, freshness, dan cara menangani perubahan",
      artifact: "source contract dan ingestion checklist",
      guardrail: safe,
      sources: [s.airflow, s.dbt, s.video],
      topics: ["Batch, Stream, dan Event", "Source of Truth", "Schema Contract", "API Pagination dan Rate Limit", "Incremental Load", "Watermark dan Late Data", "Idempotency", "Backfill dengan Batas", "Schema Evolution", "Freshness SLA", "Owner Sumber Data", "Review Source Contract"],
      opening: "Pipeline dapat berjalan hijau sambil membawa data salah atau terlambat. Bab ini menempatkan kontrak sumber—schema, owner, freshness, dan kebijakan perubahan—sebelum data mencapai warehouse.",
      caseTitle: "Kolom status berubah diam-diam dan dashboard menurun tanpa error",
      caseNarrative: "Sistem sumber mengganti nilai status tanpa memberi tahu tim data. Ingestion tidak gagal, tetapi transformasi salah memahami arti nilainya. Tim membuat schema contract dan alert perubahan.",
      teachingPoint: "Ketersediaan data tidak sama dengan kesesuaian makna data.",
      questions: ["Siapa owner source schema?", "Bagaimana mendeteksi late atau missing data?", "Apa aturan backfill yang aman?"],
    }),
    checkpoint({
      title: "Transformasi dengan dbt dan Data yang Dapat Ditelusuri",
      level: "Menengah",
      focus: "membangun transformasi modular dengan test, lineage, dokumentasi, dan proses review seperti software engineering",
      artifact: "dbt project plan dan lineage review",
      guardrail: safe,
      sources: [s.dbt, s.postgres],
      topics: ["Staging, Intermediate, Mart", "Model SQL yang Modular", "Ref dan Dependency Graph", "Materialization", "Test Not Null dan Unique", "Accepted Values dan Relationship", "Source Freshness", "Documentation dan Exposure", "Semantic Layer Intuisi", "CI untuk Transformasi", "Lineage untuk Dampak Perubahan", "Review dbt Project"],
      opening: "Transformasi analitik sering berubah menjadi SQL panjang yang hanya berani disentuh pembuatnya. Bab ini menggunakan pola modular, test, dan lineage agar perubahan kecil dapat dibaca serta dipulihkan.",
      caseTitle: "Perubahan kolom di staging merusak laporan CEO",
      caseNarrative: "Satu model SQL diubah untuk kebutuhan tim growth. Tanpa lineage dan test, laporan eksekutif ikut kosong. Setelah itu tim membuat dependency graph, test kontrak, dan review exposure.",
      teachingPoint: "Lineage membuat tim tahu siapa terdampak sebelum perubahan menjadi kejutan.",
      questions: ["Model mana yang menjadi sumber mart ini?", "Test apa yang menangkap perubahan berisiko?", "Siapa perlu tahu sebelum model diubah?"],
    }),
    checkpoint({
      title: "Orkestrasi, Scheduling, dan Operasi Pipeline",
      level: "Menengah",
      focus: "menjalankan pekerjaan data secara terjadwal dengan dependency, retry, observability, dan keputusan intervensi yang jelas",
      artifact: "DAG design dan runbook pipeline",
      guardrail: safe,
      sources: [s.airflow, s.dbt],
      topics: ["DAG sebagai Peta Dependency", "Task Boundary", "Schedule dan Data Interval", "Retry serta Backoff", "SLA dan Alert", "Parameterisasi Run", "XCom dan Handoff Data", "Backfill dengan Review", "Concurrency dan Resource", "Log yang Dapat Didiagnosis", "Runbook Gagal Pipeline", "Review DAG Design"],
      opening: "Orkestrasi bukan sekadar menjadwalkan script. Ia adalah cara menyatakan dependency, apa yang boleh dicoba ulang, siapa diberi tahu, dan kapan manusia perlu turun tangan.",
      caseTitle: "Laporan pagi terkirim dengan data kemarin karena satu task retry terlalu lama",
      caseNarrative: "Pipeline terlihat akhirnya berhasil, tetapi melewati batas freshness. Penerima laporan tidak tahu datanya terlambat. Tim menambahkan SLA, alert, status freshness, dan runbook untuk keputusan publish atau hold.",
      teachingPoint: "Pipeline sukses secara teknis belum tentu memenuhi kontrak waktu dan kualitas bagi pengguna data.",
      questions: ["Dependency mana yang kritis?", "Kapan retry harus berhenti?", "Bagaimana pengguna tahu data terlambat?"],
    }),
    checkpoint({
      title: "Kualitas Data, Lineage, dan Observability",
      level: "Menengah",
      focus: "mendeteksi masalah data melalui ekspektasi, freshness, volume, distribusi, dan lineage sebelum keputusan bisnis terdampak",
      artifact: "data quality scorecard dan incident playbook",
      guardrail: safe,
      sources: [s.gx, s.dbt, s.airflow],
      topics: ["Kualitas sebagai Dimensi", "Expectation dan Assertion", "Completeness", "Validity", "Uniqueness", "Timeliness dan Freshness", "Volume Anomaly", "Distribution Shift", "Data Incident Severity", "Lineage untuk Triage", "Komunikasi Data Incident", "Review Quality Scorecard"],
      opening: "Data quality tidak dapat diserahkan pada satu test. Bab ini menggabungkan ekspektasi data dengan sinyal operasi agar tim mengetahui apakah yang berubah adalah data, pipeline, definisi, atau perilaku pengguna.",
      caseTitle: "Konversi turun 40% karena event checkout hilang setelah perubahan aplikasi",
      caseNarrative: "Dashboard memberi alarm, tetapi tim product mengira bisnis turun. Dengan volume anomaly, lineage, dan pemeriksaan event, tim menemukan instrumentation yang hilang. Mereka memperbaiki pipeline dan menulis incident note.",
      teachingPoint: "Observability data mempercepat perbedaan antara perubahan dunia nyata dan perubahan kualitas pengukuran.",
      questions: ["Ekspektasi apa yang paling kritis?", "Lineage mana yang dipakai untuk triage?", "Siapa yang perlu tahu dan kapan?"],
    }),
    checkpoint({
      title: "Privacy, Governance, dan Akses Data",
      level: "Menengah",
      focus: "menetapkan tujuan, klasifikasi, akses, retensi, dan audit data agar analytics tidak mengorbankan kepercayaan",
      artifact: "data governance register dan access review",
      guardrail: "Gunakan data contoh/anonymized untuk lab. Materi ini bukan nasihat hukum; ikuti kebijakan organisasi dan regulasi yang berlaku.",
      sources: [s.dbt, s.postgres],
      topics: ["Purpose Limitation", "Klasifikasi Data", "PII dan Pseudonymization", "Role-Based Access", "Row dan Column Level Access", "Consent dan Dasar Penggunaan", "Retention dan Deletion", "Data Sharing Review", "Audit Access", "Dataset untuk Development", "Data Request Process", "Review Governance Register"],
      opening: "Governance bukan gerbang birokrasi di akhir project. Ia membantu tim menjawab sejak awal data ini untuk apa, siapa yang boleh melihat, kapan harus dihapus, dan siapa owner-nya.",
      caseTitle: "Tim ingin memberi dashboard lengkap ke semua department",
      caseNarrative: "Dashboard memuat email, lokasi, dan detail pembelian. Niatan awalnya transparansi, tetapi akses terlalu luas menciptakan risiko baru. Tim mendefinisikan view berdasarkan peran, tujuan, dan kebutuhan minimum.",
      teachingPoint: "Akses data yang sehat mempertemukan kegunaan dengan konteks serta tanggung jawab.",
      questions: ["Tujuan apa yang membenarkan akses ini?", "Field apa yang perlu disamarkan?", "Bagaimana access review dilakukan berkala?"],
    }),
    checkpoint({
      title: "BI, Storytelling, dan Keputusan",
      level: "Menengah",
      focus: "mengubah analisis menjadi cerita keputusan yang menunjukkan konteks, bukti, ketidakpastian, dan langkah berikutnya",
      artifact: "decision-ready dashboard dan narrative memo",
      guardrail: safe,
      sources: [s.looker, s.pandas],
      topics: ["Audience dan Pertanyaan Dashboard", "Visual yang Sesuai Tipe Data", "Baseline dan Comparison", "Annotation serta Context", "Filter yang Aman", "Dashboard Layering", "Metric Narrative", "Insight versus Observation", "Menyatakan Ketidakpastian", "Rekomendasi yang Bisa Diuji", "Review dengan Stakeholder", "Review Decision Memo"],
      opening: "Dashboard bukan tembok grafik. Bab ini mengajak kamu membuat perjalanan pembaca dari pertanyaan ke bukti hingga keputusan, sambil jujur tentang apa yang belum dapat disimpulkan.",
      caseTitle: "Eksekutif meminta 'satu slide yang menjelaskan semuanya'",
      caseNarrative: "Tim mencoba memasukkan semua angka. Hasilnya membingungkan dan setiap orang memilih grafik sendiri. Mereka kembali ke pertanyaan keputusan, baseline, segmentasi, satu insight, dan opsi tindakan yang dapat diuji.",
      teachingPoint: "Storytelling data yang baik mengurangi beban interpretasi tanpa menyembunyikan batas bukti.",
      questions: ["Siapa audiens dan keputusannya?", "Pembanding apa yang dibutuhkan?", "Apa yang belum bisa disimpulkan?"],
    }),
    checkpoint({
      title: "Performa, Biaya, dan Keberlanjutan Data",
      level: "Menengah",
      focus: "menyeimbangkan kecepatan query, biaya compute/storage, freshness, dan kebutuhan pengguna secara sadar",
      artifact: "performance review dan cost-aware data plan",
      guardrail: safe,
      sources: [s.postgres, s.dbt, s.airflow],
      topics: ["Query Plan Intuisi", "Index dan Partition", "Incremental Model", "Materialization Trade-Off", "Cache dan Pre-Aggregation", "Warehouse Workload", "Storage Lifecycle", "Job Cost Attribution", "Freshness versus Cost", "Concurrency Management", "Capacity Forecast", "Review Cost-Aware Plan"],
      opening: "Data platform yang cepat tetapi mahal, atau murah tetapi terlambat, sama-sama dapat menghambat keputusan. Bab ini membuat trade-off performa dan biaya menjadi artifact yang bisa dibahas.",
      caseTitle: "Dashboard cepat untuk satu orang, tetapi menghabiskan seluruh compute warehouse",
      caseNarrative: "Satu query tanpa filter dipakai ulang di puluhan dashboard. Biaya meningkat dan job transformasi tertunda. Tim membaca workload, membuat aggregation, membatasi query, dan menilai ulang freshness yang benar-benar dibutuhkan.",
      teachingPoint: "Optimasi terbaik dimulai dari beban kerja dan kebutuhan keputusan, bukan dari tweak acak.",
      questions: ["Workload mana paling mahal?", "Freshness apa yang benar-benar dibutuhkan?", "Perubahan apa yang menjaga makna metric?"],
    }),
    checkpoint({
      title: "Data Product Capstone: Dari Pertanyaan ke Keputusan",
      level: "Lanjut",
      focus: "menyatukan pertanyaan, model, pipeline, quality, governance, dashboard, dan narrative menjadi data product yang dapat dipercaya",
      artifact: "data product dossier",
      guardrail: safe,
      sources: [s.pandas, s.postgres, s.dbt, s.airflow, s.gx, s.looker, s.video],
      topics: ["Memilih Problem Capstone", "Menulis Decision Brief", "Mendesain Model dan Source Contract", "Membangun Transformasi serta Test", "Mendesain DAG dan Freshness", "Membuat Quality Scorecard", "Meninjau Governance", "Merancang Dashboard", "Menulis Narrative Memo", "Menguji dengan Stakeholder", "Handoff dan Ownership", "Retrospektif Data Product"],
      opening: "Capstone menguji apakah kamu dapat menyatukan data menjadi keputusan yang dapat ditelusuri. Fokusnya bukan volume tool, tetapi dossier yang membuat pengguna memahami definisi, bukti, batas, dan langkah berikutnya.",
      caseTitle: "Kawan Belajar ingin memutuskan apakah harus memperbaiki onboarding atau konten",
      caseNarrative: "Tim memiliki event dan feedback tetapi belum satu data product yang dipercaya. Mereka membangun metric dictionary, transformasi teruji, pipeline terpantau, dashboard berlapis, dan memo yang membedakan temuan dari rekomendasi.",
      teachingPoint: "Data product yang baik membuat keputusan lebih jelas sekaligus membuat batas bukti tetap terlihat.",
      questions: ["Keputusan apa yang didukung dossier ini?", "Bukti dan batas apa yang perlu dibaca stakeholder?", "Siapa owner setelah project selesai?"],
    }),
  ],
});

export const dataIntensiveMaterials = createIntensiveCourseMaterials(dataCourse);
