// Style reminder: Paper Playground — glossary entries should feel like friendly margin notes, not a dry dictionary.

export type GlossaryTerm = { term: string; definition: string; analogy: string; category: string; materialId: number };

export const glossaryTerms: GlossaryTerm[] = [
  { term: "Foundation model", definition: "Model berskala besar yang menjadi dasar untuk banyak tugas, lalu diarahkan lewat instruksi, konteks, atau adaptasi.", analogy: "Seperti dapur besar yang punya banyak bahan dasar; resep dan bahan tambahan menentukan hidangan akhirnya.", category: "Bab 02", materialId: 106 },
  { term: "Token", definition: "Unit teks yang diproses model ketika membaca atau menghasilkan bahasa.", analogy: "Seperti keping puzzle kecil yang disusun menjadi kalimat.", category: "Bab 02", materialId: 106 },
  { term: "Context window", definition: "Batas informasi yang dapat dipertimbangkan model dalam satu pekerjaan.", analogy: "Seperti luas meja belajar; terlalu banyak kertas membuat yang penting mudah tertutup.", category: "Bab 02", materialId: 107 },
  { term: "Hallucination", definition: "Respons yang terdengar yakin tetapi tidak didukung konteks atau fakta yang benar.", analogy: "Seperti teman yang menjawab dengan lancar walau sebenarnya sedang menebak.", category: "Bab 02", materialId: 111 },
  { term: "Dataset evaluasi", definition: "Kumpulan contoh yang dipakai untuk memeriksa kualitas sistem secara konsisten.", analogy: "Seperti set latihan yang mewakili jenis soal sebelum ujian sesungguhnya.", category: "Bab 03", materialId: 113 },
  { term: "Rubrik", definition: "Kriteria terstruktur untuk menilai kualitas respons.", analogy: "Seperti daftar penilaian guru yang menjelaskan kenapa jawaban mendapat nilai tertentu.", category: "Bab 03", materialId: 115 },
  { term: "Regression test", definition: "Tes untuk memastikan perilaku penting tidak rusak setelah ada perubahan.", analogy: "Seperti mengecek rem lagi setelah servis mobil, bukan hanya melihat cat barunya.", category: "Bab 04", materialId: 122 },
  { term: "Prompt injection", definition: "Upaya dari input tidak tepercaya untuk memengaruhi perilaku model atau tool secara tidak semestinya.", analogy: "Seperti catatan asing yang menyamar sebagai instruksi resmi di tengah dokumen.", category: "Bab 05", materialId: 129 },
  { term: "Structured output", definition: "Respons dalam format yang telah ditentukan agar aplikasi dapat memprosesnya lebih aman.", analogy: "Seperti formulir dengan kolom khusus, bukan surat bebas yang harus ditebak isinya.", category: "Bab 05", materialId: 127 },
  { term: "RAG", definition: "Pola yang mencari konteks eksternal relevan sebelum model menyusun jawaban.", analogy: "Seperti siswa yang membuka catatan terbaru sebelum menjawab pertanyaan.", category: "Bab 06", materialId: 131 },
  { term: "Chunking", definition: "Memecah dokumen menjadi potongan yang bisa dicari sambil menjaga makna penting.", analogy: "Seperti membuat kartu catatan dari buku tanpa memotong ide di tengah-tengah.", category: "Bab 06", materialId: 132 },
  { term: "Reranking", definition: "Menyusun ulang hasil pencarian agar bukti paling relevan diprioritaskan sebelum diberikan ke model.", analogy: "Seperti menyusun kembali daftar buku pinjaman agar yang paling cocok berada di paling atas.", category: "Bab 06", materialId: 133 },
  { term: "Finetuning", definition: "Mengadaptasi perilaku model memakai data contoh khusus untuk target yang telah didefinisikan.", analogy: "Seperti melatih koki yang sudah hebat agar mengikuti standar menu restoran tertentu.", category: "Bab 07", materialId: 136 },
  { term: "PEFT", definition: "Keluarga teknik untuk menyesuaikan model dengan perubahan parameter yang lebih efisien.", analogy: "Seperti menyetel bagian penting pada instrumen tanpa harus membongkar seluruh panggung.", category: "Bab 07", materialId: 140 },
  { term: "Annotation", definition: "Memberi label atau penilaian pada data agar data dapat menjadi sinyal yang dipahami proses berikutnya.", analogy: "Seperti memberi label pada kotak arsip agar orang lain tidak perlu menebak isinya.", category: "Bab 08", materialId: 144 },
  { term: "Data synthesis", definition: "Membuat kandidat data tambahan dengan proses yang tetap diperiksa kualitas dan risikonya.", analogy: "Seperti membuat soal latihan tambahan, lalu guru tetap memeriksa apakah jawabannya masuk akal.", category: "Bab 08", materialId: 145 },
  { term: "Model routing", definition: "Memilih model atau konfigurasi sesuai kelas tugas, kualitas, risiko, waktu, dan biaya.", analogy: "Seperti memilih kendaraan sesuai jarak dan muatan, bukan selalu memakai kendaraan terbesar.", category: "Bab 09", materialId: 149 },
  { term: "Caching", definition: "Menyimpan hasil yang aman dipakai ulang untuk mengurangi kerja, waktu, atau biaya.", analogy: "Seperti menyimpan catatan jawaban umum, tetapi bukan membagikan catatan pribadi ke semua orang.", category: "Bab 09", materialId: 150 },
  { term: "Observability", definition: "Kemampuan melihat sinyal sistem untuk memahami apa yang terjadi dan mengapa.", analogy: "Seperti panel kontrol yang menunjukkan temperatur, jalur, dan alarm sebuah mesin.", category: "Bab 10", materialId: 155 },
  { term: "Feedback loop", definition: "Proses mengumpulkan sinyal penggunaan dan mengubahnya menjadi perbaikan yang terukur.", analogy: "Seperti latihan musik: dengar rekaman, catat bagian lemah, lalu coba lagi dengan tujuan jelas.", category: "Bab 10", materialId: 156 },
  { term: "Kill switch", definition: "Kontrol untuk membatasi atau menghentikan perilaku berisiko ketika sistem perlu diamankan cepat.", analogy: "Seperti tombol darurat pada mesin: jarang dipakai, tetapi harus jelas letaknya dan benar-benar berfungsi.", category: "Bab 10", materialId: 158 },
];
