// Style reminder: Paper Playground — clear editorial hierarchy, ink-black borders, hot-pink accents, and friendly Indonesian copy.

import type { SpecializationId } from "./specializations";
import { specializationMaterials } from "./specializationMaterials";

export type MaterialLevel = "Pemula" | "Menengah" | "Lanjut";

export type QuizQuestion = {
  question: string;
  options: string[];
  answer: number;
  explanation: string;
};

export type Material = {
  id: number;
  title: string;
  category: string;
  specialization?: SpecializationId;
  level: MaterialLevel;
  minutes: number;
  emoji: string;
  summary: string;
  analogy: string;
  sections: { heading: string; body: string }[];
  diagram?: { src: string; alt: string; caption: string; note: string };
  diagramQuiz?: QuizQuestion;
  resources?: { label: string; url: string; note?: string }[];
  quiz: QuizQuestion[];
};

export const categoryMeta: Record<string, { emoji: string; level: MaterialLevel }> = {
  "Dasar-Dasar AI": { emoji: "✦", level: "Pemula" },
  "Large Language Models": { emoji: "⌁", level: "Menengah" },
  "RAG & Teknik Lanjutan": { emoji: "⌗", level: "Menengah" },
  "AI Agents & Tools": { emoji: "⚙", level: "Lanjut" },
  "Infrastruktur Agent": { emoji: "⌁", level: "Menengah" },
  "Cloud & DevOps untuk AI": { emoji: "☁", level: "Menengah" },
  "Data Analyst & Data Engineering": { emoji: "▦", level: "Menengah" },
  "AI Product Builder": { emoji: "▱", level: "Menengah" },
  "Automation Specialist": { emoji: "↻", level: "Menengah" },
  "AI Security & Safety": { emoji: "◆", level: "Menengah" },
  "Creative AI & Content Systems": { emoji: "✺", level: "Menengah" },
};

const titles: { title: string; minutes: number; category: string }[] = [
  { title: "Apa Itu Artificial Intelligence (AI)?", minutes: 5, category: "Dasar-Dasar AI" },
  { title: "Sejarah Singkat AI: Dari Turing Sampai ChatGPT", minutes: 7, category: "Dasar-Dasar AI" },
  { title: "Jenis-Jenis AI: Narrow, General, dan Super AI", minutes: 6, category: "Dasar-Dasar AI" },
  { title: "Machine Learning vs Deep Learning vs AI — Apa Bedanya?", minutes: 8, category: "Dasar-Dasar AI" },
  { title: "Bagaimana AI Belajar? Konsep Training Data", minutes: 6, category: "Dasar-Dasar AI" },
  { title: "Neural Network: Otak Buatan yang Meniru Manusia", minutes: 7, category: "Dasar-Dasar AI" },
  { title: "Supervised vs Unsupervised vs Reinforcement Learning", minutes: 8, category: "Dasar-Dasar AI" },
  { title: "Dataset dan Labeling: Makanan Utama AI", minutes: 5, category: "Dasar-Dasar AI" },
  { title: "Overfitting dan Underfitting", minutes: 6, category: "Dasar-Dasar AI" },
  { title: "AI dalam Kehidupan Sehari-hari: Contoh Nyata", minutes: 5, category: "Dasar-Dasar AI" },
  { title: "Apa Itu Large Language Model (LLM)?", minutes: 7, category: "Large Language Models" },
  { title: "Transformer Architecture: Fondasi di Balik ChatGPT", minutes: 10, category: "Large Language Models" },
  { title: "Tokenisasi: Bagaimana AI Membaca Teks", minutes: 6, category: "Large Language Models" },
  { title: "Attention Mechanism: Perhatian yang Bikin AI Pintar", minutes: 8, category: "Large Language Models" },
  { title: "Pre-training vs Fine-tuning: Dua Fase Belajar LLM", minutes: 7, category: "Large Language Models" },
  { title: "Prompt Engineering: Seni Berbicara dengan AI", minutes: 8, category: "Large Language Models" },
  { title: "Temperature, Top-K, Top-P: Mengatur Kreativitas AI", minutes: 6, category: "Large Language Models" },
  { title: "Hallucination pada AI: Ketika AI Ngarang", minutes: 5, category: "Large Language Models" },
  { title: "Open Source vs Closed Source LLM", minutes: 7, category: "Large Language Models" },
  { title: "Context Window: Batas Memori AI", minutes: 5, category: "Large Language Models" },
  { title: "Apa Itu RAG (Retrieval-Augmented Generation)?", minutes: 8, category: "RAG & Teknik Lanjutan" },
  { title: "Vector Database: Gudang Pengetahuan AI", minutes: 7, category: "RAG & Teknik Lanjutan" },
  { title: "Embedding: Mengubah Teks Jadi Angka", minutes: 8, category: "RAG & Teknik Lanjutan" },
  { title: "Chunking Strategy: Memotong Dokumen untuk AI", minutes: 6, category: "RAG & Teknik Lanjutan" },
  { title: "Semantic Search vs Keyword Search", minutes: 6, category: "RAG & Teknik Lanjutan" },
  { title: "RAG Pipeline: Dari Dokumen Sampai Jawaban", minutes: 9, category: "RAG & Teknik Lanjutan" },
  { title: "Evaluasi RAG: Faithfulness, Relevancy, dan Recall", minutes: 7, category: "RAG & Teknik Lanjutan" },
  { title: "Apa Itu AI Agent? Dari Chatbot ke Asisten Pintar", minutes: 7, category: "AI Agents & Tools" },
  { title: "Function Calling: Ketika AI Bisa Pakai Tools", minutes: 8, category: "AI Agents & Tools" },
  { title: "Multi-Agent System: Tim AI yang Bekerja Bareng", minutes: 8, category: "AI Agents & Tools" },
  { title: "Memory pada AI Agent: Short-term vs Long-term", minutes: 6, category: "AI Agents & Tools" },
  { title: "AI Safety dan Alignment: Menjaga AI Tetap Aman", minutes: 7, category: "AI Agents & Tools" },
  { title: "Masa Depan AI: AGI, Regulasi, dan Dampak Sosial", minutes: 8, category: "AI Agents & Tools" },
];

const infrastructureMaterials: Material[] = [
  { id: 34, title: "Hermes Agent Lokal: Dari Install sampai Chat Pertama", category: "Infrastruktur Agent", level: "Menengah", minutes: 16, emoji: "⌁", summary: "Setup Hermes Agent secara lokal dari instalasi, pemilihan provider, hingga chat pertama yang dapat diverifikasi.", analogy: "Hermes seperti bengkel agent pribadi: nyalakan mesin dasar dan pastikan berjalan lurus sebelum memasang banyak alat.", sections: [
    { heading: "Prasyarat yang realistis", body: "Gunakan Linux, macOS, atau WSL2, lalu siapkan satu provider model. Dokumentasi resmi menyediakan installer dan setup wizard. Mulailah pada folder kerja khusus; jangan menyalin API key ke chat, screenshot, atau repository." },
    { heading: "Urutan setup aman", body: "Pasang Hermes dari installer resmi, buka shell baru, lalu jalankan `hermes setup` atau `hermes model`. Pilih satu provider dan satu model, lalu jalankan `hermes` untuk satu percakapan sederhana. Jangan menambah gateway, cron, atau MCP sebelum jalur ini stabil." },
    { heading: "Verifikasi dan diagnosis", body: "Keberhasilan minimum adalah provider/model terbaca, Hermes menjawab, dan sesi dapat dilanjutkan. Jika gagal, gunakan urutan diagnosis resmi: `hermes doctor`, `hermes model`, lalu `hermes setup`. Untuk custom endpoint, periksa base URL, nama model, dan kompatibilitasnya." },
  ], diagram: { src: "/manus-storage/hermes-dashboard-reference_a585039e.png", alt: "Dashboard Hermes Agent yang menampilkan daftar sesi dan navigasi model, log, cron, skills, plugins, MCP, pairing, profil, konfigurasi, dan keys", caption: "Referensi antarmuka resmi Hermes Agent", note: "Tampilan dapat berubah per versi. Gunakan sebagai orientasi dan selalu ikuti dokumentasi resmi untuk perintah terbaru." }, resources: [
    { label: "Hermes Agent GitHub (resmi)", url: "https://github.com/nousresearch/hermes-agent", note: "Kode sumber, installer, dan README." }, { label: "Hermes Quickstart (resmi)", url: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart", note: "Setup, model, chat pertama, dan diagnosis." },
  ], quiz: [{ question: "Apa yang harus berhasil sebelum memasang gateway pesan?", options: ["Satu chat dasar dengan provider/model terverifikasi", "Mengaktifkan semua tool", "Membagikan token"], answer: 0, explanation: "Pastikan fondasi chat bekerja sebelum menambahkan lapisan baru." }, { question: "Jika custom endpoint bermasalah, apa yang diperiksa?", options: ["Base URL, nama model, dan kompatibilitas", "Warna terminal", "Jumlah emoji"], answer: 0, explanation: "Ketiganya menentukan apakah endpoint dapat digunakan dengan benar." }] },
  { id: 35, title: "Hermes Agent di VPS: Gateway yang Tetap Menyala", category: "Infrastruktur Agent", level: "Menengah", minutes: 18, emoji: "⌁", summary: "Rencana menjalankan Hermes pada VPS dengan akses minimum, rahasia terlindungi, dan jalur pemulihan yang jelas.", analogy: "VPS adalah rumah kecil yang selalu menyala untuk agent; karena pintunya tidak lagi di laptopmu, kuncinya harus lebih ketat.", sections: [
    { heading: "Kapan VPS diperlukan", body: "Gunakan VPS bila agent atau gateway pesan harus tersedia ketika laptop mati. Mulai dari satu environment yang mudah dipulihkan. Uji chat dari terminal VPS sebelum mengaktifkan gateway agar sumber error tidak bercampur." },
    { heading: "Keamanan minimum", body: "Simpan rahasia pada environment atau secret store server, gunakan SSH key dan akun non-root, update sistem, batasi port dengan firewall, dan pisahkan workspace sensitif. Jangan menaruh API key di command history atau file yang dikomit." },
    { heading: "Uji operasional", body: "Uji restart layanan, log gateway, satu pesan masuk, dan proses shutdown. Pantau budget provider, kurangi izin tool, serta pertahankan approval untuk tindakan yang dapat mengubah sistem." },
  ], resources: [{ label: "Hermes Quickstart (resmi)", url: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart" }, { label: "Hermes Agent GitHub (resmi)", url: "https://github.com/nousresearch/hermes-agent" }], quiz: [{ question: "Urutan aman di VPS adalah…", options: ["Uji chat dasar lalu konfigurasi gateway", "Buka semua port lalu memilih model", "Hubungkan semua akun pribadi dulu"], answer: 0, explanation: "Chat/provider perlu terbukti bekerja sebelum gateway ditambahkan." }, { question: "Di mana API key disimpan?", options: ["Environment atau secret store terlindungi", "Commit Git", "Screenshot terminal"], answer: 0, explanation: "Rahasia harus dipisahkan dari kode dan materi publik." }] },
  { id: 36, title: "Menghubungkan Hermes ke Telegram dan WhatsApp dengan Aman", category: "Infrastruktur Agent", level: "Menengah", minutes: 20, emoji: "⌁", summary: "Integrasi pesan yang berfokus pada token, allowlist, pairing, dan batas aman WhatsApp bridge.", analogy: "Gateway pesan adalah bel rumah agent. Tentukan siapa yang boleh menekan bel dan apa yang boleh mereka minta.", sections: [
    { heading: "Telegram: token dan allowlist", body: "Buat bot melalui @BotFather, simpan token sebagai rahasia, lalu gunakan `hermes gateway setup` untuk Telegram. Masukkan numeric user ID yang diizinkan; username bukan pengganti user ID. Pahami privacy mode bila bot ditempatkan dalam grup." },
    { heading: "WhatsApp: pilih jalur dengan sadar", body: "Dokumentasi Hermes membedakan bridge Baileys dan WhatsApp Business Cloud API. Baileys berbasis sesi WhatsApp Web dan lebih cepat untuk eksperimen, tetapi bukan API resmi serta memiliki risiko pembatasan akun. Untuk bisnis yang stabil, pertimbangkan Cloud API Meta." },
    { heading: "Pengujian minimum", body: "Mulai dari DM pribadi, kirim satu pesan, lalu cek status/log gateway. Gunakan nomor khusus bot dan jangan melakukan bulk/spam. Jika token atau sesi pairing bocor, rotasi token atau unlink perangkat secepatnya." },
  ], resources: [{ label: "Hermes Telegram Setup (resmi)", url: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/telegram" }, { label: "Hermes WhatsApp Setup (resmi)", url: "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/whatsapp", note: "Termasuk risiko bridge Baileys dan sesi pairing." }], quiz: [{ question: "Mengapa numeric user ID penting di Telegram?", options: ["Untuk allowlist akses", "Untuk menentukan warna bot", "Agar token tidak dijaga"], answer: 0, explanation: "User ID dipakai untuk membatasi pengirim yang dapat memicu bot." }, { question: "Langkah aman untuk bridge WhatsApp eksperimen?", options: ["Nomor khusus dan tanpa bulk messaging", "Spam dari nomor pribadi", "Commit folder sesi"], answer: 0, explanation: "Lindungi sesi dan hindari perilaku yang berisiko pada akun." }] },
  { id: 37, title: "Setup 9Router: Satu Endpoint untuk Banyak Provider", category: "Infrastruktur Agent", level: "Menengah", minutes: 17, emoji: "⌁", summary: "Memahami 9Router sebagai gateway lokal OpenAI-compatible: provider, endpoint, model, dan batas logging.", analogy: "9Router seperti meja resepsionis: aplikasi bicara ke satu alamat, router meneruskan ke provider yang kamu hubungkan.", sections: [
    { heading: "Apa yang dirutekan", body: "9Router mendokumentasikan dirinya sebagai gateway lokal dengan endpoint OpenAI-compatible di `/v1/*`. Dashboard mengelola provider, alias model, fallback, key lokal, dan usage. Router bukan provider model; tetap pahami biaya dan kebijakan upstream provider." },
    { heading: "Setup minimum", body: "Pasang sesuai README resmi, buka dashboard, hubungkan satu provider, lalu catat endpoint dan key yang dibuat dashboard. Uji daftar model atau permintaan sederhana sebelum memasukkan endpoint ke tool lain. Jangan langsung menambah fallback dan banyak akun." },
    { heading: "Logging dan data", body: "Dokumentasi arsitektur menjelaskan bahwa logging mendalam dapat mencatat header/body. Lindungi data lokal dan jangan menyalakan logging detail untuk data sensitif. Jangan mengekspos dashboard atau endpoint lokal ke internet tanpa autentikasi serta jaringan yang benar." },
  ], diagram: { src: "/manus-storage/9router-providers-reference_eee8471d.webp", alt: "Dashboard provider 9Router dengan kategori OAuth, free provider, API key provider, dan opsi provider kompatibel OpenAI atau Anthropic", caption: "9Router: provider dikelola dari dashboard lokal", note: "Nama provider dan tampilan dapat berubah. Periksa README/release resmi sebelum menyalin konfigurasi." }, resources: [{ label: "9Router GitHub (resmi)", url: "https://github.com/decolua/9router", note: "Repository, README, instalasi, dan release." }, { label: "9Router Architecture (resmi)", url: "https://github.com/decolua/9router/blob/master/docs/ARCHITECTURE.md", note: "Endpoint, persistence, routing, dan batas keamanan." }], quiz: [{ question: "Peran utama 9Router adalah…", options: ["Gateway lokal ke provider", "Model AI tunggal", "Penyimpan token publik"], answer: 0, explanation: "Ia menyediakan endpoint tunggal lalu merutekan ke koneksi provider." }, { question: "Mengapa logging penuh perlu hati-hati?", options: ["Dapat mencatat data sensitif", "Membuat model lebih kreatif", "Menghapus autentikasi"], answer: 0, explanation: "Request log dapat memuat header dan body yang tidak seharusnya tersebar." }] },
  { id: 38, title: "Menghubungkan 9Router ke Hermes Agent", category: "Infrastruktur Agent", level: "Lanjut", minutes: 18, emoji: "⌁", summary: "Menghubungkan Hermes ke endpoint 9Router dengan pengujian berlapis dan pemahaman localhost/deployment.", analogy: "Hermes adalah pekerja di meja; 9Router operator telepon yang memilih provider di belakangnya.", sections: [
    { heading: "Uji tiap tautan", body: "Alurnya adalah Hermes → endpoint 9Router → provider upstream. Pastikan 9Router dapat menjawab request sederhana sebelum mengubah konfigurasi Hermes. Pastikan Hermes dapat chat dengan provider dasar sebelum menambah router." },
    { heading: "Konfigurasi tanpa menebak", body: "Di dashboard 9Router, sambungkan provider lalu ambil endpoint dan key milikmu. Di Hermes, pilih custom endpoint lewat setup/model, masukkan base URL dan key dalam konfigurasi rahasia, lalu gunakan model yang benar-benar muncul dari router. Uji satu chat dasar." },
    { heading: "Localhost bukan selalu mesin yang sama", body: "`http://localhost:20128/v1` menunjuk pada mesin/proses yang menjalankan perintah. Pada container atau VPS terpisah, ia dapat menunjuk ke tempat yang salah. Gunakan jaringan privat atau bind address yang tepat dan jangan membuka endpoint ke publik sembarangan." },
  ], resources: [{ label: "Hermes Quickstart — custom endpoint", url: "https://hermes-agent.nousresearch.com/docs/getting-started/quickstart" }, { label: "9Router Architecture — endpoint /v1", url: "https://github.com/decolua/9router/blob/master/docs/ARCHITECTURE.md" }, { label: "9Router GitHub (resmi)", url: "https://github.com/decolua/9router" }], quiz: [{ question: "Apa yang diuji sebelum menyambungkan Hermes ke 9Router?", options: ["Request sederhana langsung ke 9Router", "Semua fallback sekaligus", "Endpoint publik tanpa auth"], answer: 0, explanation: "Pengujian berlapis membuat sumber error lebih mudah diketahui." }, { question: "Mengapa localhost perlu dipahami?", options: ["Ia menunjuk ke proses lokal tempat perintah berjalan", "Ia selalu tersedia di internet", "Ia mengganti API key"], answer: 0, explanation: "Di deployment terpisah, localhost tidak otomatis mengarah ke layanan yang diinginkan." }] },
  { id: 39, title: "AWS Cloud Architecture: Merancang Sistem yang Tahan Tumbuh", category: "Infrastruktur Agent", level: "Menengah", minutes: 19, emoji: "⌁", summary: "Membaca arsitektur AWS sebagai trade-off keamanan, keandalan, performa, biaya, operasi, dan keberlanjutan.", analogy: "Arsitektur cloud seperti merancang kota: ada jalan masuk, rumah, gudang, penjaga, dan rencana saat salah satu bagian gagal.", sections: [
    { heading: "Mulai dari kebutuhan", body: "AWS Well-Architected Framework membantu mengevaluasi keputusan berdasarkan trade-off. Mulai dari pengguna, data, jalur request, target ketersediaan, biaya, dan risiko—baru pilih compute, database, storage, jaringan, observability, dan identity." },
    { heading: "Enam perspektif", body: "Gunakan operational excellence, security, reliability, performance efficiency, cost optimization, dan sustainability. Redundansi dapat menaikkan reliabilitas sekaligus biaya; keputusan yang baik harus memiliki alasan dan ukuran keberhasilan." },
    { heading: "Pola web-app sederhana", body: "Pikirkan jalur pengguna → edge/load balancer → aplikasi → database/storage, dengan identity, logging, backup, dan alert. Terapkan least privilege dan rencanakan kegagalan sebelum terjadi. Visual arsitektur membantu komunikasi, bukan bukti konfigurasi sudah aman." },
  ], resources: [{ label: "AWS Well-Architected Framework (resmi)", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html" }, { label: "AWS Architecture Center (resmi)", url: "https://aws.amazon.com/architecture/" }, { label: "AWS Architecture Icons (resmi)", url: "https://aws.amazon.com/architecture/icons/", note: "Sumber visual resmi untuk diagram yang teratribusi." }], quiz: [{ question: "Well-Architected Framework digunakan untuk…", options: ["Mengevaluasi trade-off arsitektur", "Memilih logo", "Menghapus pengujian"], answer: 0, explanation: "Framework memberi perspektif untuk menilai kualitas desain dan trade-off." }, { question: "Langkah pertama desain cloud yang sehat?", options: ["Memahami kebutuhan dan risiko", "Memilih semua layanan", "Membuka akses publik"], answer: 0, explanation: "Kebutuhan dan risiko harus membimbing pemilihan layanan." }] },
];

const quickSummaries = [
  "Peta pertama untuk memahami apa yang sebenarnya dilakukan AI di balik aplikasi yang kamu pakai setiap hari.",
  "Perjalanan AI dari ide di atas kertas sampai jadi teman ngobrol yang ada di ponsel kita.",
  "Kenalan dengan tiga level kemampuan AI—dan kenapa kebanyakan AI hari ini masih sangat spesifik.",
  "Bedah tiga istilah yang sering tertukar, pakai contoh belajar yang gampang dibayangkan.",
  "Lihat cara model menemukan pola dari contoh, seperti anak magang yang terus menerima feedback.",
  "Intip ‘otak’ buatan yang tersusun dari lapisan-lapisan kecil untuk membaca pola.",
  "Tiga cara belajar yang berbeda: dengan kunci jawaban, tanpa kunci, atau lewat hadiah dan konsekuensi.",
  "Kenapa dataset itu seperti bahan masakan—dan labeling bisa menentukan rasa akhirnya.",
  "Saat model terlalu hafal latihan atau justru belum menangkap polanya, di sinilah masalahnya.",
  "Contoh AI yang mungkin sudah membantu memilih lagu, foto, rute, dan tulisanmu hari ini.",
  "Bahasa sederhana untuk memahami mesin yang memprediksi kata berikutnya dengan skala sangat besar.",
  "Arsitektur yang membuat model bisa melihat hubungan antarbagian kalimat tanpa membaca satu-satu.",
  "Cara kalimat dipecah menjadi potongan kecil sebelum bisa diproses oleh model bahasa.",
  "Mekanisme yang membantu model memutuskan bagian mana dari konteks yang paling perlu diperhatikan.",
  "Kenapa model perlu belajar umum dulu, lalu dilatih lebih spesifik untuk kebutuhan tertentu.",
  "Cara menulis instruksi yang lebih jelas supaya AI terasa seperti rekan satu tim, bukan mesin tebak-tebakan.",
  "Kenalan dengan knop kecil yang mengatur apakah jawaban AI terasa fokus atau lebih eksploratif.",
  "Kenapa AI kadang terdengar meyakinkan padahal sedang mengisi celah dengan jawaban yang salah.",
  "Membandingkan model terbuka dan tertutup tanpa terjebak perang istilah atau fanboy.",
  "Batas seberapa banyak konteks yang bisa ‘diingat’ model dalam satu percakapan.",
  "Cara memberi model catatan yang relevan sebelum ia menyusun jawaban untuk kita.",
  "Kenapa pencarian biasa belum cukup ketika aplikasi perlu menemukan makna, bukan hanya kata.",
  "Jembatan yang mengubah kalimat menjadi posisi angka agar komputer bisa membandingkan kemiripan.",
  "Seni memotong dokumen menjadi potongan yang pas: tidak terlalu pendek, tidak terlalu berantakan.",
  "Bedakan pencarian berdasarkan kata yang sama dengan pencarian berdasarkan maksud yang mirip.",
  "Ikuti perjalanan lengkap RAG dari dokumen mentah sampai jawaban yang bisa dicek.",
  "Cara mengecek apakah jawaban RAG setia pada sumber, relevan, dan benar-benar menemukan yang dibutuhkan.",
  "Dari chatbot yang menunggu perintah menjadi asisten yang bisa merencanakan langkah berikutnya.",
  "Saat model bisa memanggil kalkulator, database, atau API untuk menyelesaikan tugas nyata.",
  "Bayangkan beberapa agen AI dengan peran berbeda yang bekerja seperti tim kecil.",
  "Apa yang perlu disimpan oleh agent agar percakapan terasa nyambung tanpa mengingat semuanya.",
  "Prinsip agar sistem AI tetap bisa diawasi, dipahami, dan diarahkan ke dampak yang baik.",
  "Membaca masa depan AI dengan rasa penasaran, tapi tetap membawa kacamata kritis dan manusiawi.",
];

const specialContent: Record<number, Pick<Material, "summary" | "analogy" | "sections" | "quiz">> = {
  1: {
    summary: "AI adalah cara membuat komputer melakukan tugas yang biasanya membutuhkan kecerdasan manusia: mengenali pola, memahami bahasa, belajar dari contoh, lalu mengambil keputusan.",
    analogy: "Bayangkan AI seperti anak magang super cepat. Ia tidak otomatis tahu segalanya, tetapi bisa belajar dari banyak contoh dan aturan yang kita berikan.",
    sections: [
      { heading: "AI bukan robot yang punya pikiran sendiri", body: "AI adalah kumpulan metode, data, dan komputer yang bekerja bersama untuk menemukan pola. Saat aplikasi mengenali wajah, merekomendasikan lagu, atau membantu menulis, biasanya ada model AI di belakangnya." },
      { heading: "Tiga bahan utama", body: "Model adalah resepnya, data adalah contoh makanannya, dan komputasi adalah dapurnya. Semakin tepat ketiganya dipadukan, semakin berguna hasil AI—tetapi hasilnya tetap perlu diperiksa manusia." },
      { heading: "Mulai dari pertanyaan sederhana", body: "Saat mempelajari AI, jangan mulai dari rumus. Mulailah dari pertanyaan: pola apa yang ingin ditemukan, contoh apa yang tersedia, dan keputusan apa yang ingin dibantu?" },
    ],
    quiz: [
      { question: "AI biasanya belajar dengan cara…", options: ["Menerka tanpa contoh", "Mengenali pola dari data", "Membaca pikiran manusia"], answer: 1, explanation: "Betul. Data membantu model menemukan pola untuk menghasilkan prediksi atau keputusan." },
      { question: "Mana yang termasuk contoh AI?", options: ["Rekomendasi lagu", "Kabel charger", "Meja belajar"], answer: 0, explanation: "Rekomendasi lagu menggunakan pola dari kebiasaan dan preferensi pengguna." },
    ],
  },
  5: {
    summary: "Training data adalah kumpulan contoh yang dipakai model untuk menemukan pola. Kualitas dan keberagaman contoh sangat memengaruhi perilaku AI.",
    analogy: "Kalau kamu ingin belajar membedakan kucing dan anjing, kamu butuh banyak foto dengan jawaban yang jelas. Itulah peran training data.",
    sections: [
      { heading: "Contoh adalah guru model", body: "Model tidak membaca maksud manusia seperti kita. Ia memproses contoh, mencari pola, lalu menyesuaikan parameter internalnya agar prediksi berikutnya lebih tepat." },
      { heading: "Data yang bias menghasilkan AI yang bias", body: "Jika contoh latihan hanya mewakili satu kelompok, model bisa bekerja baik di situ tetapi keliru di situasi lain. Karena itu, data perlu relevan, cukup beragam, dan diperiksa." },
      { heading: "Training bukan sulap", body: "Proses training adalah eksperimen berulang: model memprediksi, dibandingkan dengan jawaban, lalu diperbaiki sedikit demi sedikit. Setelah itu, model diuji dengan contoh yang belum pernah dilihat." },
    ],
    quiz: [
      { question: "Fungsi utama training data adalah…", options: ["Menghias tampilan aplikasi", "Memberi contoh untuk menemukan pola", "Mematikan model"], answer: 1, explanation: "Training data memberi model contoh sehingga ia bisa belajar pola." },
      { question: "Kenapa data perlu beragam?", options: ["Agar file lebih besar", "Agar model tidak hanya jago di satu situasi", "Agar warna layar berubah"], answer: 1, explanation: "Data beragam membantu model menghadapi variasi nyata dengan lebih adil." },
    ],
  },
  16: {
    summary: "Prompt engineering adalah seni menyusun instruksi yang jelas, kontekstual, dan punya tujuan agar AI bisa membantu dengan lebih konsisten.",
    analogy: "Prompt itu seperti brief untuk teman satu tim. Semakin jelas tujuan, format, dan batasannya, semakin kecil kemungkinan hasilnya melenceng.",
    sections: [
      { heading: "Prompt yang baik punya konteks", body: "Jelaskan siapa pembacanya, apa tujuan akhirnya, dan informasi apa yang boleh digunakan. Konteks membuat AI memahami situasi sebelum menjawab." },
      { heading: "Minta format yang bisa dicek", body: "Daripada hanya berkata ‘buatkan ide’, minta lima ide dalam tabel dengan kolom masalah, solusi, dan alasan. Format membantu kamu membandingkan hasil." },
      { heading: "Iterasi adalah bagian dari proses", body: "Prompt pertama tidak harus sempurna. Tinjau hasilnya, cari bagian yang kurang, lalu perbaiki instruksi secara bertahap seperti mengedit brief." },
    ],
    quiz: [
      { question: "Prompt yang lebih membantu biasanya memiliki…", options: ["Tujuan dan konteks", "Kata-kata acak", "Instruksi yang sengaja kabur"], answer: 0, explanation: "Tujuan dan konteks memberi arah yang lebih jelas untuk model." },
      { question: "Kenapa format output penting?", options: ["Supaya hasil lebih mudah dicek", "Supaya AI lupa konteks", "Supaya jawaban selalu pendek"], answer: 0, explanation: "Format yang diminta membuat hasil lebih mudah dipakai dan dibandingkan." },
    ],
  },
  21: {
    summary: "RAG menggabungkan pencarian dokumen dengan generasi jawaban agar model bisa menjawab berdasarkan sumber yang relevan, bukan hanya mengandalkan ingatan parameternya.",
    analogy: "RAG seperti siswa yang membuka catatan sebelum menjawab ujian. Ia mencari halaman yang relevan, lalu merangkumnya menjadi jawaban.",
    sections: [
      { heading: "Kenapa RAG dibutuhkan?", body: "Model bahasa bisa terdengar yakin walau informasinya tidak tepat. RAG memberi model konteks dari dokumen yang lebih segar atau lebih spesifik." },
      { heading: "Empat langkah ringkas", body: "Dokumen dipecah menjadi potongan, diubah menjadi embedding, dicari potongan yang paling dekat dengan pertanyaan, lalu disisipkan ke prompt sebelum model menjawab." },
      { heading: "RAG bukan jaminan otomatis", body: "Jawaban masih perlu dievaluasi. Jika potongan dokumennya salah, terlalu pendek, atau tidak relevan, jawaban akhir juga dapat meleset." },
    ],
    quiz: [
      { question: "RAG menggabungkan…", options: ["Pencarian dan generasi", "Kamera dan speaker", "Game dan musik"], answer: 0, explanation: "Retrieval mengambil konteks, generation menyusun jawaban dari konteks tersebut." },
      { question: "RAG membantu mengurangi…", options: ["Ukuran layar", "Jawaban tanpa sumber yang relevan", "Kecepatan mengetik"], answer: 1, explanation: "RAG memberikan konteks tambahan agar jawaban lebih grounded." },
    ],
  },
};

const expandedContent: Record<number, Pick<Material, "summary" | "analogy" | "sections" | "quiz">> = {
  1: { summary: "AI adalah cara membuat komputer mengenali pola, memahami masukan, dan membantu mengambil keputusan dari contoh yang diberikan.", analogy: "Bayangkan AI seperti anak magang super cepat: ia bisa mempelajari banyak contoh, tetapi tetap perlu brief yang jelas dan hasilnya perlu diperiksa manusia.", sections: [{ heading: "Penjelasan pelan-pelan", body: "Artificial Intelligence atau AI bukan satu aplikasi tunggal. AI adalah payung besar untuk berbagai cara membuat komputer melakukan tugas yang biasanya terasa membutuhkan kecerdasan manusia, seperti mengenali gambar, memahami bahasa, menemukan pola, atau memprediksi sesuatu. Model AI tidak berpikir seperti manusia; model menghitung pola dari data lalu menghasilkan kemungkinan jawaban." }, { heading: "Cerita kecil: playlist hari Senin", body: "Bayangkan aplikasi musik yang tahu kamu sering mendengarkan lagu santai saat berangkat sekolah. Aplikasi itu tidak membaca pikiranmu. Ia melihat pola dari lagu yang kamu putar, kapan kamu memutarnya, dan lagu apa yang sering kamu lewati. Dari pola itu, AI membuat tebakan tentang lagu berikutnya yang mungkin kamu suka." }, { heading: "Contoh yang dekat", body: "Rekomendasi video, filter kamera, penerjemah otomatis, navigasi, deteksi spam, dan chatbot adalah contoh penggunaan AI. Di baliknya ada data, model, dan komputer yang bekerja bersama. Karena AI membuat prediksi, jawabannya bisa keliru dan tetap perlu dinilai dengan akal sehat." }, { heading: "Ringkasnya", body: "AI adalah mesin pencari pola, bukan penyihir. Agar berguna, AI membutuhkan tujuan yang jelas, data yang relevan, proses pengujian, dan manusia yang memahami batasnya." }], quiz: [{ question: "AI terutama bekerja dengan cara…", options: ["Menemukan pola dari data", "Menebak tanpa contoh", "Membaca pikiran manusia"], answer: 0, explanation: "Model AI mempelajari pola dari data untuk membuat prediksi atau keputusan." }, { question: "Mengapa hasil AI tetap perlu diperiksa?", options: ["Karena AI bisa keliru", "Karena AI tidak pernah memakai data", "Karena AI selalu acak"], answer: 0, explanation: "AI membuat prediksi berdasarkan pola, sehingga hasilnya tidak selalu benar." }] },
  2: { summary: "Perjalanan AI melewati beberapa gelombang: dari aturan sederhana, musim optimisme, masa sulit, hingga model bahasa modern.", analogy: "Sejarah AI mirip perjalanan seorang penemu: beberapa kali menemukan jalan buntu, lalu kembali dengan alat dan data yang lebih kuat.", sections: [{ heading: "Dari aturan ke pembelajaran", body: "Pada masa awal, banyak sistem AI dibuat dengan aturan yang ditulis manusia. Sistem tersebut bisa hebat dalam satu permainan atau tugas tertentu, tetapi mudah bingung ketika situasinya berubah. Perlahan, peneliti lebih banyak memakai machine learning, yaitu pendekatan yang membiarkan model mempelajari pola dari contoh." }, { heading: "Cerita kecil: komputer yang belajar bermain", body: "Bayangkan kamu mengajari komputer bermain catur. Versi pertama mungkin berisi ribuan aturan seperti jika lawan melakukan ini, lakukan itu. Versi berikutnya dapat mempelajari banyak pertandingan dan menilai langkah mana yang sering membawa kemenangan. Perubahan cara belajar inilah yang membuat AI berkembang." }, { heading: "Kenapa ChatGPT terasa seperti lompatan", body: "Model bahasa modern memanfaatkan data teks dalam jumlah besar, arsitektur neural network yang lebih kuat, dan komputasi yang jauh lebih besar. Itu bukan berarti semua masalah AI sudah selesai. Model masih dapat salah, bias, atau tidak memahami konteks seperti manusia." }, { heading: "Ringkasnya", body: "Sejarah AI bukan garis lurus menuju kesempurnaan. Kemajuan biasanya muncul ketika ide lama bertemu data yang lebih baik, perangkat keras yang lebih kuat, dan cara evaluasi yang lebih matang." }], quiz: [{ question: "Sistem AI awal banyak mengandalkan…", options: ["Aturan yang ditulis manusia", "Video pendek", "Sensor perasaan"], answer: 0, explanation: "Banyak sistem awal menggunakan aturan eksplisit sebelum machine learning berkembang luas." }, { question: "Salah satu pendorong AI modern adalah…", options: ["Data dan komputasi yang lebih besar", "Menghapus proses pengujian", "Mengurangi semua contoh"], answer: 0, explanation: "Data, arsitektur, dan komputasi yang lebih kuat membantu model belajar pola yang lebih kompleks." }] },
  3: { summary: "Narrow AI, General AI, dan Super AI menggambarkan tingkat keluasan kemampuan, bukan tiga aplikasi yang bisa langsung dipilih dari menu.", analogy: "Narrow AI seperti atlet yang sangat jago satu cabang; General AI seperti orang yang bisa belajar banyak cabang; Super AI adalah gagasan hipotetis tentang kemampuan yang melampaui manusia.", sections: [{ heading: "Narrow AI adalah yang kita pakai hari ini", body: "Narrow AI atau weak AI dirancang untuk tujuan tertentu. Sistem rekomendasi, pengenal wajah, dan filter spam bisa bekerja sangat baik dalam ruang tugasnya, tetapi tidak otomatis dapat berpindah menjadi guru, koki, atau mekanik tanpa pelatihan dan desain tambahan." }, { heading: "Cerita kecil: juara satu cabang", body: "Bayangkan robot yang sangat hebat membedakan kucing dan anjing. Ia dapat memproses ribuan foto dengan cepat, tetapi jika kamu memintanya merencanakan perjalanan, ia belum tentu tahu harus mulai dari mana. Kehebatan dalam satu tugas tidak sama dengan kecerdasan umum." }, { heading: "General dan Super AI masih berupa gagasan", body: "General AI biasanya berarti sistem yang dapat belajar dan beradaptasi di banyak jenis tugas seperti manusia. Super AI merujuk pada kemampuan yang melampaui manusia di hampir semua bidang. Keduanya sering dibahas dalam riset dan fiksi, tetapi jangan menyamakan konsep dengan teknologi yang sudah tersedia." }, { heading: "Ringkasnya", body: "Saat melihat klaim tentang AI, tanya dulu: kemampuan ini berlaku di tugas apa, pada kondisi apa, dan seberapa baik ketika situasinya berubah?" }], quiz: [{ question: "AI yang kita temui pada rekomendasi lagu biasanya termasuk…", options: ["Narrow AI", "Super AI", "Manusia digital"], answer: 0, explanation: "Sistem rekomendasi dibuat untuk tugas spesifik, sehingga termasuk Narrow AI." }, { question: "General AI menggambarkan sistem yang…", options: ["Mampu beradaptasi di banyak tugas", "Hanya mengenali satu jenis gambar", "Tidak membutuhkan data"], answer: 0, explanation: "General AI adalah gagasan tentang kemampuan yang lebih luas dan fleksibel." }] },
  4: { summary: "AI adalah payung besarnya, machine learning adalah cara belajar dari data, dan deep learning adalah machine learning dengan neural network berlapis banyak.", analogy: "AI adalah kendaraan, machine learning adalah cara kendaraan belajar rute, dan deep learning adalah sistem navigasi yang memakai banyak lapisan peta serta sinyal.", sections: [{ heading: "Hubungan ketiganya", body: "AI mencakup aturan, pencarian, logika, machine learning, dan banyak pendekatan lain. Machine learning membuat model belajar dari contoh, bukan hanya aturan manual. Deep learning memakai jaringan saraf dengan banyak lapisan untuk memproses pola yang lebih rumit, terutama pada gambar, suara, dan bahasa." }, { heading: "Cerita kecil: mengenali foto kucing", body: "Dengan aturan manual, kamu harus menulis ciri seperti ada telinga, kumis, dan empat kaki. Dengan machine learning, kamu memberi banyak contoh foto kucing dan bukan kucing. Dengan deep learning, model belajar sendiri kombinasi pola visual dari piksel hingga bentuk yang lebih kompleks." }, { heading: "Memilih pendekatan", body: "Deep learning tidak selalu menjadi pilihan terbaik. Jika datanya sedikit dan aturan masalahnya jelas, metode sederhana bisa lebih mudah dijelaskan dan dirawat. Pilihan teknologi sebaiknya mengikuti tujuan, kualitas data, biaya, dan risiko kesalahan." }, { heading: "Ringkasnya", body: "Ketiga istilah ini berada dalam hubungan bertingkat: AI adalah payung, machine learning adalah salah satu pendekatan, dan deep learning adalah salah satu keluarga metode machine learning." }], quiz: [{ question: "Machine learning membedakan diri dari aturan manual karena…", options: ["Belajar dari contoh", "Tidak membutuhkan tujuan", "Selalu benar"], answer: 0, explanation: "Machine learning menyesuaikan pola dari data contoh yang diberikan." }, { question: "Deep learning biasanya menggunakan…", options: ["Neural network berlapis", "Satu aturan if saja", "Kertas catatan"], answer: 0, explanation: "Deep learning memakai neural network dengan banyak lapisan pemrosesan." }] },
  5: { summary: "Training data adalah kumpulan contoh yang dipakai model untuk menemukan pola; kualitas, keberagaman, dan labelnya memengaruhi perilaku AI.", analogy: "Kalau kamu belajar membedakan kucing dan anjing, kamu butuh banyak foto dengan jawaban yang jelas. Itulah peran training data.", sections: [{ heading: "Contoh adalah guru model", body: "Model tidak membaca maksud manusia seperti kita. Ia memproses contoh, membuat prediksi, membandingkan prediksi dengan jawaban, lalu memperbaiki parameter internalnya. Siklus ini diulang berkali-kali sampai pola yang dipelajari cukup berguna." }, { heading: "Cerita kecil: belajar dari kartu gambar", body: "Bayangkan ada kartu bergambar buah. Setiap kali model menebak apel padahal gambarnya pisang, ia mendapat sinyal bahwa tebakan itu perlu diperbaiki. Setelah melihat banyak variasi warna, ukuran, dan sudut foto, model lebih siap menghadapi gambar baru." }, { heading: "Data yang bias menghasilkan AI yang bias", body: "Jika contoh latihan hanya mewakili satu kelompok atau satu kondisi, model bisa bekerja baik di situ tetapi keliru di situasi lain. Karena itu, data perlu relevan, cukup beragam, memiliki izin yang tepat, dan diperiksa kualitasnya." }, { heading: "Ringkasnya", body: "Training bukan sulap. Model belajar dari contoh, melakukan kesalahan, menerima sinyal perbaikan, lalu diuji dengan data yang belum pernah dilihat." }], quiz: [{ question: "Fungsi utama training data adalah…", options: ["Memberi contoh untuk menemukan pola", "Menghias tampilan aplikasi", "Mematikan model"], answer: 0, explanation: "Training data memberi model contoh agar ia dapat belajar pola." }, { question: "Kenapa data perlu beragam?", options: ["Agar model tidak hanya jago di satu situasi", "Agar file terlihat besar", "Agar warna layar berubah"], answer: 0, explanation: "Keberagaman membantu model menghadapi variasi yang muncul di dunia nyata." }] },
  6: { summary: "Neural network adalah model yang tersusun dari lapisan unit kecil untuk mengubah masukan menjadi prediksi melalui banyak kombinasi pola.", analogy: "Bayangkan sekelompok teman menyaring foto: satu mencari garis, satu mencari bentuk, satu mengenali objek, lalu semuanya menggabungkan petunjuk.", sections: [{ heading: "Dari piksel ke pola", body: "Neural network menerima angka sebagai masukan. Lapisan awal dapat menangkap pola sederhana seperti garis atau warna, lapisan berikutnya menggabungkan pola itu menjadi bentuk, dan lapisan lebih dalam menyusun pemahaman yang lebih kompleks." }, { heading: "Cerita kecil: tim detektif", body: "Satu detektif tidak harus menyelesaikan seluruh kasus sendirian. Ada yang memeriksa sidik jari, ada yang membaca rekaman, dan ada yang menyusun kronologi. Neural network bekerja dengan semangat serupa: tiap lapisan menyumbang petunjuk sebelum menghasilkan prediksi." }, { heading: "Parameter dan proses belajar", body: "Koneksi antarunit memiliki angka yang disebut bobot. Saat prediksi keliru, proses training menyesuaikan bobot sedikit demi sedikit. Bobot bukan fakta atau ingatan seperti buku; bobot adalah pola numerik yang membantu model membuat tebakan." }, { heading: "Ringkasnya", body: "Neural network belajar melalui lapisan, bobot, prediksi, dan koreksi. Analogi otak membantu intuisi, tetapi neural network bukan otak biologis dan tidak memiliki pengalaman sadar." }], quiz: [{ question: "Lapisan awal neural network sering menangkap…", options: ["Pola sederhana", "Niat manusia", "Kebijakan sekolah"], answer: 0, explanation: "Lapisan awal biasanya memproses ciri sederhana sebelum digabungkan menjadi pola yang lebih kompleks." }, { question: "Bobot pada neural network adalah…", options: ["Angka yang mengatur pengaruh koneksi", "Label nama pengguna", "Ukuran layar"], answer: 0, explanation: "Bobot menentukan seberapa besar pengaruh suatu sinyal dalam perhitungan model." }] },
  7: { summary: "Supervised learning memakai jawaban, unsupervised learning mencari struktur tanpa label, dan reinforcement learning belajar dari hadiah atau konsekuensi.", analogy: "Tiga cara belajar ini seperti belajar dengan guru, mengelompokkan barang sendiri, dan berlatih lewat skor permainan.", sections: [{ heading: "Supervised: ada kunci jawaban", body: "Pada supervised learning, contoh latihan memiliki label atau jawaban. Model melihat foto yang sudah diberi label, email yang sudah ditandai spam, atau harga yang sudah diketahui, lalu belajar memprediksi label untuk contoh baru." }, { heading: "Unsupervised: mencari kelompok tersembunyi", body: "Pada unsupervised learning, data tidak memiliki jawaban yang diberikan manusia. Model bisa mencari kelompok pelanggan dengan kebiasaan mirip atau pola yang tidak biasa. Hasilnya perlu ditafsirkan manusia karena kelompok yang ditemukan belum tentu langsung bermakna." }, { heading: "Reinforcement: belajar lewat konsekuensi", body: "Reinforcement learning memakai agen, lingkungan, aksi, dan reward. Bayangkan karakter game yang mencoba banyak gerakan. Gerakan yang membawa skor lebih baik cenderung diulang, sedangkan gerakan yang buruk ditinggalkan." }, { heading: "Ringkasnya", body: "Tanya apakah data punya label, apakah model hanya mencari struktur, atau apakah model belajar lewat reward. Jawaban itu membantu memilih pendekatan yang tepat." }], quiz: [{ question: "Supervised learning membutuhkan…", options: ["Contoh dengan label", "Tidak ada data", "Hadiah berupa uang"], answer: 0, explanation: "Label menjadi jawaban acuan saat model belajar dari contoh." }, { question: "Reinforcement learning belajar lewat…", options: ["Reward dan konsekuensi", "Daftar kata saja", "Foto tanpa tujuan"], answer: 0, explanation: "Agen mencoba aksi dan menerima sinyal reward dari lingkungan." }] },
  8: { summary: "Dataset adalah kumpulan data, sedangkan labeling memberi arti atau jawaban pada contoh agar model dapat belajar dengan arah yang jelas.", analogy: "Dataset seperti rak bahan makanan; labeling adalah catatan yang menjelaskan bahan apa yang ada di setiap kotak.", sections: [{ heading: "Dataset bukan sekadar kumpulan file", body: "Dataset memiliki sumber, format, ukuran, izin penggunaan, dan kualitas. Foto, teks, audio, atau angka perlu disusun agar model dapat membacanya. Data yang duplikat, rusak, atau tidak relevan dapat membuat proses belajar menjadi tidak sehat." }, { heading: "Cerita kecil: kotak bekal tanpa nama", body: "Bayangkan semua kotak bekal di kelas dikumpulkan tanpa nama. Kamu mungkin bisa menebak isinya dari bentuk, tetapi akan sering tertukar. Label membantu menghubungkan setiap contoh dengan makna yang ingin dipelajari model." }, { heading: "Label bisa memiliki tingkat kesulitan", body: "Label sederhana bisa berupa kucing atau bukan kucing. Label yang lebih rumit dapat berupa emosi, tingkat kerusakan, atau bagian-bagian objek. Semakin rumit tugasnya, semakin penting panduan labeling yang konsisten dan proses pengecekan antarlabeler." }, { heading: "Ringkasnya", body: "Data memberi bahan belajar; label memberi arah. Keduanya harus dikumpulkan secara bertanggung jawab dan diperiksa sebelum dipakai training." }], quiz: [{ question: "Label pada dataset berguna untuk…", options: ["Memberi arti atau jawaban pada contoh", "Menghapus semua variasi", "Mengubah data menjadi wallpaper"], answer: 0, explanation: "Label membantu model memahami target yang perlu dipelajari pada contoh tertentu." }, { question: "Data yang baik seharusnya…", options: ["Relevan dan diperiksa kualitasnya", "Selalu berulang", "Tidak punya sumber"], answer: 0, explanation: "Relevansi, kualitas, sumber, dan izin adalah bagian penting dari dataset." }] },
  9: { summary: "Overfitting terjadi ketika model terlalu hafal data latihan, sedangkan underfitting terjadi ketika model belum cukup menangkap pola penting.", analogy: "Siswa yang hafal jawaban latihan tetapi bingung saat soal berubah mengalami overfitting; siswa yang belum memahami konsep mengalami underfitting.", sections: [{ heading: "Mengapa overfitting terjadi", body: "Model yang terlalu kompleks atau terlalu lama dilatih dapat mengikuti detail kebetulan dalam training data. Nilai training terlihat sangat bagus, tetapi performa pada data baru turun. Model seolah-olah hafal daftar soal, bukan memahami pola di baliknya." }, { heading: "Cerita kecil: latihan soal yang sama", body: "Seorang siswa mengerjakan lembar soal yang sama setiap hari sampai hafal posisi jawabannya. Ketika guru mengubah angka dan cara bertanya, ia kesulitan. Itulah gambaran sederhana overfitting: hafal contoh, belum tentu siap menghadapi variasi." }, { heading: "Cara melihat perbedaannya", body: "Data biasanya dipisah menjadi training dan validation atau test. Jika skor training tinggi tetapi skor data baru rendah, ada tanda overfitting. Jika keduanya rendah, model mungkin underfitting, datanya kurang informatif, atau tugasnya belum dirancang dengan baik." }, { heading: "Ringkasnya", body: "Tujuan training bukan membuat model sempurna pada contoh lama, tetapi cukup kuat menghadapi contoh baru. Evaluasi pada data yang belum dilihat adalah kunci." }], quiz: [{ question: "Overfitting berarti model…", options: ["Terlalu hafal data latihan", "Tidak memakai data sama sekali", "Selalu lebih sederhana"], answer: 0, explanation: "Overfitting membuat model sangat cocok dengan data latihan tetapi kurang mampu melakukan generalisasi." }, { question: "Data test dipakai untuk…", options: ["Melihat performa pada contoh baru", "Menambah dekorasi", "Mengganti tujuan model"], answer: 0, explanation: "Data test membantu mengukur kemampuan model pada data yang tidak dipakai saat belajar." }] },
  10: { summary: "AI hadir dalam banyak aktivitas sehari-hari, dari rekomendasi dan navigasi sampai penyaringan spam dan bantuan menulis.", analogy: "AI seperti kru kecil di belakang panggung: jarang terlihat, tetapi membantu banyak hal berjalan lebih cepat.", sections: [{ heading: "AI yang kamu temui tanpa sadar", body: "Saat aplikasi memilihkan video, memperbaiki foto, menerjemahkan pesan, atau memberi rute tercepat, biasanya ada sistem prediksi atau pengenalan pola yang bekerja di belakangnya. Tidak semua otomatisasi adalah AI, tetapi banyak layanan memakai AI pada bagian yang perlu menafsirkan data." }, { heading: "Cerita kecil: perjalanan ke tempat baru", body: "Kamu memasukkan alamat kafe. Aplikasi melihat peta, kondisi jalan, pola kepadatan, dan pilihan rute. Ia lalu menyarankan jalur yang diperkirakan lebih cepat. Saat kondisi berubah, prediksi bisa berubah juga—jadi tetap perhatikan keadaan nyata." }, { heading: "Manfaat dan pertanyaan penting", body: "AI dapat menghemat waktu dan menemukan pola yang sulit dilihat manusia. Namun, kita juga perlu bertanya data apa yang dipakai, apakah ada bias, apakah keputusan bisa dijelaskan, dan apa yang terjadi jika prediksinya salah." }, { heading: "Ringkasnya", body: "Mengenali AI dalam kehidupan sehari-hari membantu kita menjadi pengguna yang lebih kritis, bukan hanya pengguna yang kagum pada hasilnya." }], quiz: [{ question: "Rekomendasi video biasanya memanfaatkan…", options: ["Pola perilaku dan konten", "Kabel listrik saja", "Hasil lempar koin"], answer: 0, explanation: "Sistem rekomendasi mempelajari pola interaksi dan karakteristik konten." }, { question: "Saat memakai AI, kita tetap perlu…", options: ["Memeriksa hasil dan konteks", "Percaya tanpa mengecek", "Menghapus semua data"], answer: 0, explanation: "Hasil AI perlu dipahami dalam konteks dan diperiksa ketika keputusan penting terlibat." }] },
  11: { summary: "Large Language Model adalah model yang belajar dari banyak teks untuk memprediksi dan menghasilkan rangkaian token yang masuk akal.", analogy: "LLM seperti pembaca yang sangat cepat: ia mengenali pola cara manusia menulis, tetapi tidak otomatis memahami dunia seperti manusia.", sections: [{ heading: "Apa yang sebenarnya diprediksi", body: "Saat kamu mengetik kalimat, LLM tidak mengambil satu jawaban utuh dari laci. Model menghitung token berikutnya yang paling mungkin berdasarkan konteks. Proses ini diulang berkali-kali sampai menjadi paragraf, kode, atau jawaban yang terlihat lengkap." }, { heading: "Cerita kecil: permainan sambung kata", body: "Bayangkan bermain sambung kata dengan teman yang sudah membaca jutaan buku. Ketika kamu berkata Hari ini cuaca…, ia dapat menebak banyak kelanjutan yang wajar. Tebakan itu terasa pintar karena ia mengenali pola bahasa, bukan karena ia mengalami cuaca hari ini." }, { heading: "Mengapa LLM bisa membantu banyak hal", body: "Pola bahasa yang dipelajari dapat dipakai untuk merangkum, menerjemahkan, mengubah gaya tulisan, menjawab pertanyaan, dan membantu membuat kode. Kualitas hasil bergantung pada konteks, instruksi, data training, serta cara model dievaluasi." }, { heading: "Ringkasnya", body: "LLM sangat kuat dalam pola bahasa, tetapi kelancaran kalimat bukan bukti bahwa semua faktanya benar. Selalu bedakan kefasihan dari ketepatan." }], quiz: [{ question: "LLM pada dasarnya memprediksi…", options: ["Token berikutnya dari konteks", "Perasaan pengguna", "Cuaca dengan kepastian"], answer: 0, explanation: "LLM menghasilkan token secara bertahap berdasarkan konteks yang tersedia." }, { question: "Jawaban LLM yang lancar berarti…", options: ["Belum tentu selalu benar", "Pasti memiliki pengalaman", "Tidak perlu diperiksa"], answer: 0, explanation: "Kefasihan bahasa dan kebenaran fakta adalah dua hal yang berbeda." }] },
  12: { summary: "Transformer adalah arsitektur yang membantu model memproses hubungan antarbagian teks secara paralel dan efisien.", analogy: "Transformer seperti pembaca yang bisa menempelkan stabilo pada banyak kata penting sekaligus, bukan hanya membaca satu kata lalu melupakan kata sebelumnya.", sections: [{ heading: "Masalah yang ingin dipecahkan", body: "Teks memiliki hubungan jarak jauh. Kata di awal paragraf bisa memengaruhi arti kata di akhir. Arsitektur lama sering kesulitan menjaga konteks panjang, sedangkan transformer memakai mekanisme attention untuk menimbang hubungan antar-token." }, { heading: "Cerita kecil: mencari siapa yang dimaksud", body: "Dalam kalimat Rani meminjam payung dari Dika karena ia lupa membawa miliknya, kata ia bisa membingungkan. Pembaca melihat konteks di sekitarnya untuk menebak siapa yang dimaksud. Attention membantu model memberi bobot pada bagian-bagian kalimat yang relevan." }, { heading: "Kenapa menjadi fondasi LLM", body: "Transformer dapat memproses banyak token secara paralel saat training. Arsitekturnya juga bisa dipakai dalam berbagai variasi untuk memahami atau menghasilkan teks. Meski kuat, transformer tetap dibatasi data, komputasi, context window, dan kualitas evaluasi." }, { heading: "Ringkasnya", body: "Transformer bukan nama lain untuk ChatGPT. Transformer adalah salah satu arsitektur penting yang memungkinkan model bahasa modern menangani konteks dengan lebih baik." }], quiz: [{ question: "Transformer terkenal karena memakai…", options: ["Attention", "Kabel analog", "Label warna"], answer: 0, explanation: "Attention membantu transformer menimbang hubungan antar-token dalam konteks." }, { question: "Salah satu kelebihan transformer saat training adalah…", options: ["Bisa memproses banyak token secara paralel", "Tidak memerlukan data", "Selalu mengingat semua hal"], answer: 0, explanation: "Pemrosesan paralel membantu efisiensi training pada data besar." }] },
  13: { summary: "Tokenisasi memecah teks menjadi unit kecil yang dapat diproses model, sehingga kalimat manusia bisa diubah menjadi rangkaian angka.", analogy: "Tokenisasi seperti memotong kalimat menjadi keping puzzle sebelum komputer menyusunnya kembali.", sections: [{ heading: "Token bukan selalu satu kata", body: "Satu token dapat berupa kata utuh, potongan kata, tanda baca, atau spasi tertentu, bergantung pada tokenizer. Kata yang sering muncul mungkin memiliki token sederhana, sedangkan kata langka bisa dipecah menjadi beberapa bagian." }, { heading: "Cerita kecil: biaya pesan", body: "Bayangkan kamu membayar ongkos kirim berdasarkan jumlah keping puzzle, bukan jumlah kalimat. Pesan yang tampak pendek bisa memiliki banyak keping jika berisi kata langka atau format rumit. Konsep ini membantu menjelaskan mengapa panjang token memengaruhi biaya dan batas konteks." }, { heading: "Dari token ke angka", body: "Setelah dipecah, setiap token dipetakan ke ID numerik. Model memproses angka tersebut lalu menghasilkan probabilitas untuk token berikutnya. Proses ini terjadi sangat cepat, tetapi tetap memiliki batas jumlah token yang bisa dimasukkan sekaligus." }, { heading: "Ringkasnya", body: "Token adalah unit kerja model bahasa. Memahami token membantu kamu memahami context window, biaya penggunaan, dan mengapa teks tidak selalu dihitung berdasarkan jumlah kata saja." }], quiz: [{ question: "Token bisa berupa…", options: ["Kata, potongan kata, atau tanda baca", "Hanya satu paragraf", "Hanya gambar"], answer: 0, explanation: "Tokenizer dapat memecah teks menjadi unit yang ukurannya tidak selalu sama dengan satu kata." }, { question: "Token diubah menjadi…", options: ["ID atau representasi numerik", "Suara manusia", "Kertas fisik"], answer: 0, explanation: "Model memproses representasi numerik dari token." }] },
  14: { summary: "Attention membantu model menentukan bagian konteks mana yang paling relevan untuk memahami atau menghasilkan token berikutnya.", analogy: "Attention seperti saat kamu membaca chat panjang dan langsung menyorot tiga pesan yang paling penting untuk menjawab pertanyaan terakhir.", sections: [{ heading: "Perhatian yang berbobot", body: "Untuk setiap token, model menghitung hubungan dengan token lain di dalam konteks. Hubungan itu menghasilkan bobot perhatian. Bobot tinggi berarti bagian tersebut lebih banyak dipertimbangkan pada langkah tertentu, bukan berarti model benar-benar memiliki perhatian sadar." }, { heading: "Cerita kecil: mencari rujukan kata", body: "Dalam kalimat Dita membawa buku ke kelas karena buku itu akan dipakai untuk presentasi, kata itu merujuk pada buku. Attention membantu model menghubungkan kata tersebut dengan rujukan yang relevan di bagian sebelumnya." }, { heading: "Attention bukan jaminan pemahaman", body: "Attention membuat pemrosesan konteks lebih kuat, tetapi tidak otomatis menjamin model memahami niat, fakta, atau nilai moral. Model masih dapat menghubungkan bagian yang salah atau menghasilkan jawaban yang terdengar meyakinkan." }, { heading: "Ringkasnya", body: "Attention adalah mekanisme pengatur fokus dalam perhitungan model. Ia membantu memilih sinyal relevan, bukan menggantikan verifikasi dan penalaran manusia." }], quiz: [{ question: "Attention digunakan untuk…", options: ["Menimbang bagian konteks yang relevan", "Menghapus semua konteks", "Mengukur volume suara"], answer: 0, explanation: "Attention memberi bobot pada hubungan antarbagian konteks." }, { question: "Attention tidak otomatis menjamin…", options: ["Kebenaran setiap jawaban", "Pemrosesan konteks", "Perhitungan bobot"], answer: 0, explanation: "Attention membantu konteks, tetapi model tetap dapat salah atau berhalusinasi." }] },
  15: { summary: "Pre-training membangun kemampuan umum dari data besar, sedangkan fine-tuning menyesuaikan model untuk kebutuhan atau gaya tugas tertentu.", analogy: "Pre-training seperti sekolah dasar yang luas; fine-tuning seperti kursus khusus untuk pekerjaan yang ingin kamu lakukan.", sections: [{ heading: "Belajar umum dulu", body: "Pada pre-training, model melihat banyak teks dan belajar pola bahasa, struktur, serta hubungan antar-konsep. Model belum tentu diarahkan untuk menjawab dengan gaya tertentu. Fokusnya membangun kemampuan dasar yang dapat dipakai dalam banyak tugas." }, { heading: "Cerita kecil: koki yang memilih spesialisasi", body: "Seorang koki belajar teknik dasar, bahan, dan keamanan dapur. Setelah itu ia mengikuti pelatihan khusus masakan pastry. Ia tidak membuang semua kemampuan lama; ia menambahkan keterampilan baru untuk konteks yang lebih spesifik." }, { heading: "Fine-tuning perlu data yang tepat", body: "Fine-tuning dapat mengajarkan format jawaban, gaya komunikasi, atau perilaku pada tugas tertentu. Data yang buruk dapat membawa bias, membuat model terlalu sempit, atau menurunkan kemampuan yang sebelumnya berguna." }, { heading: "Ringkasnya", body: "Pre-training memberi fondasi luas. Fine-tuning menambahkan spesialisasi. Keduanya berbeda dari prompt engineering, yang mengarahkan model melalui instruksi saat digunakan." }], quiz: [{ question: "Pre-training biasanya bertujuan membangun…", options: ["Kemampuan umum dari data besar", "Satu jawaban tetap", "Tampilan aplikasi"], answer: 0, explanation: "Pre-training mempelajari pola umum sebelum model diarahkan ke tugas khusus." }, { question: "Fine-tuning digunakan untuk…", options: ["Menyesuaikan model pada kebutuhan tertentu", "Menghapus semua kemampuan model", "Mengubah layar menjadi gelap"], answer: 0, explanation: "Fine-tuning dapat mengarahkan gaya atau perilaku model melalui data tugas tertentu." }] },
  16: { summary: "Prompt engineering adalah kebiasaan menyusun instruksi yang jelas, kontekstual, dan dapat diuji agar AI memberi hasil yang lebih konsisten.", analogy: "Prompt adalah brief untuk teman satu tim: semakin jelas tujuan, konteks, batasan, dan formatnya, semakin mudah pekerjaan dilakukan.", sections: [{ heading: "Prompt yang baik punya konteks", body: "Jelaskan siapa pembacanya, apa tujuan akhirnya, informasi apa yang boleh digunakan, dan hal apa yang perlu dihindari. Konteks membuat AI memahami situasi sebelum menyusun jawaban." }, { heading: "Cerita kecil: pesan ke desainer", body: "Jika kamu hanya berkata Buat poster, temanmu harus menebak ukuran, audiens, gaya, dan isi poster. Jika kamu menambahkan untuk acara sekolah, audiens remaja, format persegi, warna cerah, dan tiga informasi wajib, hasilnya jauh lebih mudah diarahkan." }, { heading: "Minta format yang bisa dicek", body: "Daripada meminta ide secara umum, minta lima ide dalam tabel dengan kolom masalah, solusi, risiko, dan alasan. Format membuat hasil lebih mudah dibandingkan dan mengurangi bagian yang terlewat." }, { heading: "Ringkasnya", body: "Prompt bukan mantra ajaib. Ia adalah proses komunikasi: tulis tujuan, beri konteks, tentukan bentuk keluaran, cek hasil, lalu iterasikan instruksi." }], quiz: [{ question: "Prompt yang lebih membantu biasanya memiliki…", options: ["Tujuan dan konteks", "Kata-kata acak", "Instruksi yang sengaja kabur"], answer: 0, explanation: "Tujuan dan konteks memberi arah yang lebih jelas untuk model." }, { question: "Kenapa format output penting?", options: ["Supaya hasil lebih mudah dicek", "Supaya AI lupa konteks", "Supaya jawaban selalu pendek"], answer: 0, explanation: "Format yang diminta membuat hasil lebih mudah dipakai dan dibandingkan." }] },
  17: { summary: "Temperature, Top-K, dan Top-P adalah pengaturan yang memengaruhi cara model memilih token berikutnya, dari lebih fokus sampai lebih eksploratif.", analogy: "Bayangkan memilih menu: temperature mengatur keberanian mencoba, Top-K membatasi jumlah pilihan teratas, dan Top-P memilih kumpulan pilihan dengan peluang gabungan tertentu.", sections: [{ heading: "Temperature bukan tombol pintar", body: "Temperature mengubah bentuk probabilitas pilihan token. Nilai lebih rendah cenderung menghasilkan jawaban yang konsisten dan fokus. Nilai lebih tinggi membuka lebih banyak variasi, tetapi juga dapat meningkatkan risiko jawaban melenceng." }, { heading: "Cerita kecil: membuat sepuluh judul", body: "Untuk merangkum laporan, kamu mungkin ingin pilihan yang stabil. Untuk mencari ide nama acara, kamu ingin lebih banyak variasi. Pengaturan sampling membantu menyesuaikan perilaku model dengan jenis tugas, bukan menentukan benar atau salahnya fakta." }, { heading: "Top-K dan Top-P", body: "Top-K menyimpan sejumlah kandidat dengan probabilitas tertinggi. Top-P memilih kandidat sampai total peluang tertentu tercapai. Keduanya bekerja sebagai pembatas pilihan. Detail perilaku dapat berbeda antarimplementasi, jadi selalu uji pada model yang digunakan." }, { heading: "Ringkasnya", body: "Gunakan pengaturan lebih fokus untuk tugas yang membutuhkan konsistensi, dan eksploratif untuk ideasi. Tetap sediakan evaluasi karena kreativitas bukan ukuran ketepatan." }], quiz: [{ question: "Temperature lebih tinggi biasanya membuat output…", options: ["Lebih bervariasi", "Pasti lebih benar", "Selalu lebih pendek"], answer: 0, explanation: "Temperature lebih tinggi biasanya membuka variasi pilihan token." }, { question: "Top-K berfungsi untuk…", options: ["Membatasi kandidat pilihan teratas", "Menghapus konteks", "Mengukur durasi membaca"], answer: 0, explanation: "Top-K membatasi sampling pada sejumlah kandidat berprobabilitas tinggi." }] },
  18: { summary: "Hallucination adalah saat AI menghasilkan informasi yang terdengar meyakinkan tetapi tidak didukung fakta atau konteks yang benar.", analogy: "Seperti teman yang tidak tahu jawaban tetapi tetap menjawab dengan percaya diri agar tidak terlihat bingung.", sections: [{ heading: "Mengapa model bisa mengarang", body: "LLM dilatih untuk menghasilkan kelanjutan teks yang masuk akal, bukan untuk selalu membuka sumber dan membuktikan fakta. Jika konteks kurang, pertanyaan ambigu, atau informasi langka, model dapat mengisi celah dengan pola yang terlihat wajar." }, { heading: "Cerita kecil: nama buku yang tidak ada", body: "Kamu meminta daftar buku tentang topik tertentu. Model menyebut judul dan nama penulis yang terdengar realistis, tetapi ketika dicari, bukunya tidak ditemukan. Masalahnya bukan model sengaja berbohong seperti manusia; model menghasilkan rangkaian teks yang probabilitasnya terlihat masuk akal." }, { heading: "Cara mengurangi risikonya", body: "Berikan sumber, minta model menyatakan ketidakpastian, gunakan RAG, pecah pertanyaan kompleks, dan verifikasi klaim penting. Untuk keputusan kesehatan, hukum, keuangan, atau keselamatan, jangan menjadikan jawaban model sebagai satu-satunya dasar." }, { heading: "Ringkasnya", body: "Semakin penting dampak jawaban, semakin kuat proses verifikasinya. Kalimat yang lancar harus diperlakukan sebagai hipotesis sampai sumbernya diperiksa." }], quiz: [{ question: "Hallucination pada AI berarti…", options: ["Informasi salah yang terdengar meyakinkan", "Model sedang tidur", "Jawaban selalu berasal dari database"], answer: 0, explanation: "Hallucination adalah keluaran yang tidak didukung fakta atau konteks tetapi terdengar percaya diri." }, { question: "Cara mengurangi risiko hallucination adalah…", options: ["Memverifikasi klaim penting", "Percaya pada semua jawaban", "Menghapus pertanyaan"], answer: 0, explanation: "Verifikasi dan sumber yang relevan membantu mengurangi risiko informasi keliru." }] },
  19: { summary: "Open source dan closed source menggambarkan perbedaan akses, transparansi, lisensi, dan cara model dikembangkan atau digunakan.", analogy: "Open source seperti resep yang bisa dipelajari sesuai lisensi; closed source seperti produk dengan dapur internal yang tidak seluruhnya dibuka.", sections: [{ heading: "Apa yang sebenarnya terbuka", body: "Istilah open source dapat merujuk pada hal berbeda: kode, bobot model, data, dokumentasi, atau lisensi. Sebuah model bisa membuka bobot tetapi tetap memiliki batas penggunaan data atau komponen tertentu. Karena itu, baca lisensi dan dokumentasi, bukan hanya labelnya." }, { heading: "Cerita kecil: memilih alat untuk klub sekolah", body: "Klub sekolah ingin membuat chatbot. Alat tertutup mungkin mudah dipakai dan memiliki layanan terkelola. Alat terbuka mungkin memberi ruang eksperimen dan kontrol lebih besar, tetapi membutuhkan kemampuan teknis, infrastruktur, dan tanggung jawab pemeliharaan." }, { heading: "Trade-off yang perlu dipikirkan", body: "Pertimbangkan biaya, privasi, kemampuan modifikasi, kualitas, keamanan, dukungan, dan kepatuhan lisensi. Tidak ada pilihan yang otomatis selalu unggul. Pilih berdasarkan kebutuhan nyata dan risiko yang sanggup dikelola." }, { heading: "Ringkasnya", body: "Open atau closed bukan label baik atau buruk. Yang penting adalah memahami apa yang benar-benar terbuka, apa yang boleh dilakukan, dan siapa yang bertanggung jawab." }], quiz: [{ question: "Saat memilih model open source, kita perlu membaca…", options: ["Lisensi dan dokumentasi", "Warna logo saja", "Jumlah emoji"], answer: 0, explanation: "Lisensi dan dokumentasi menjelaskan akses, batas penggunaan, dan tanggung jawab pengguna." }, { question: "Model closed source biasanya berarti…", options: ["Komponen internal tidak sepenuhnya dibuka", "Tidak bisa menghasilkan teks", "Selalu gratis"], answer: 0, explanation: "Closed source umumnya menyimpan sebagian komponen atau proses internal di balik layanan." }] },
  20: { summary: "Context window adalah jumlah token yang dapat diproses model dalam satu permintaan atau percakapan.", analogy: "Context window seperti meja kerja: semakin luas mejanya, semakin banyak catatan yang bisa dibentangkan sekaligus, tetapi tetap ada batas.", sections: [{ heading: "Batas memori kerja", body: "Model hanya dapat mempertimbangkan konteks yang masuk dalam window saat itu. Jika percakapan atau dokumen terlalu panjang, bagian lama dapat dipotong, diringkas, atau tidak lagi tersedia secara langsung bagi model." }, { heading: "Cerita kecil: meja penuh catatan", body: "Kamu meminta teman merangkum satu semester catatan di meja kecil. Jika semuanya ditumpuk, beberapa halaman jatuh dan tidak terlihat. Solusinya bisa memilih halaman penting, membuat ringkasan bertahap, atau membagi pekerjaan menjadi beberapa sesi." }, { heading: "Cara bekerja dengan batas ini", body: "Gunakan chunking, ringkasan bertahap, struktur heading, dan retrieval. Jangan menganggap model dapat mengingat semua percakapan selamanya. Context window juga berbeda dari memory jangka panjang yang sengaja dibangun oleh aplikasi." }, { heading: "Ringkasnya", body: "Context window adalah ruang kerja saat ini, bukan ingatan tanpa batas. Desain prompt dan pipeline harus memperhitungkan jumlah token serta informasi yang paling penting." }], quiz: [{ question: "Context window menentukan…", options: ["Seberapa banyak token yang diproses sekaligus", "Ukuran layar", "Kecepatan Wi-Fi rumah"], answer: 0, explanation: "Context window membatasi jumlah token dalam satu konteks kerja model." }, { question: "Jika dokumen terlalu panjang, kita bisa…", options: ["Membagi dan merangkum dokumen", "Memasukkan semuanya tanpa batas", "Menghapus tujuan"], answer: 0, explanation: "Chunking dan ringkasan membantu bekerja dalam batas context window." }] },
  21: { summary: "RAG menggabungkan pencarian dokumen dengan generasi jawaban agar model dapat menjawab berdasarkan konteks yang relevan.", analogy: "RAG seperti siswa yang membuka catatan sebelum menjawab ujian: ia mencari halaman yang tepat, lalu merangkum isinya.", sections: [{ heading: "Kenapa RAG dibutuhkan", body: "Model bahasa dapat terdengar yakin walau informasinya tidak tepat atau sudah tidak relevan. RAG memberi model potongan dokumen yang lebih spesifik, lebih segar, atau lebih sesuai dengan pengetahuan internal sebuah organisasi." }, { heading: "Cerita kecil: menjawab aturan perpustakaan", body: "Seorang siswa bertanya apakah boleh meminjam lima buku. Daripada mengandalkan ingatan, petugas membuka aturan terbaru perpustakaan, menemukan paragraf yang relevan, lalu menjawab dengan rujukan. Itulah intuisi RAG: cari konteks dulu, baru susun jawaban." }, { heading: "Empat langkah utama", body: "Dokumen dibersihkan dan dipecah menjadi potongan, potongan diubah menjadi embedding, sistem mencari potongan yang paling relevan, lalu potongan itu dimasukkan ke konteks model. Jawaban akhir masih perlu dievaluasi karena pencarian yang salah menghasilkan konteks yang salah." }, { heading: "Ringkasnya", body: "RAG membantu grounding, tetapi bukan jaminan otomatis. Kualitas dokumen, chunking, retrieval, prompt, dan evaluasi semuanya berpengaruh." }], quiz: [{ question: "RAG menggabungkan…", options: ["Pencarian dan generasi", "Kamera dan speaker", "Game dan musik"], answer: 0, explanation: "Retrieval mengambil konteks, generation menyusun jawaban dari konteks tersebut." }, { question: "RAG membantu mengurangi…", options: ["Jawaban tanpa sumber relevan", "Ukuran layar", "Kecepatan mengetik"], answer: 0, explanation: "RAG memberikan konteks tambahan agar jawaban lebih grounded." }] },
  22: { summary: "Vector database menyimpan representasi numerik dan membantu mencari potongan informasi yang maknanya paling dekat dengan pertanyaan.", analogy: "Vector database seperti perpustakaan yang mengelompokkan buku berdasarkan kemiripan ide, bukan hanya urutan abjad judul.", sections: [{ heading: "Mengapa database biasa belum selalu cukup", body: "Pencarian keyword cocok ketika kata pertanyaan sama dengan kata di dokumen. Namun, pertanyaan dan dokumen bisa memakai kata berbeda tetapi memiliki makna mirip. Vector database membantu melakukan pencarian berdasarkan representasi semantik." }, { heading: "Cerita kecil: mencari payung tanpa kata payung", body: "Kamu mencari informasi tentang perlindungan saat hujan, tetapi dokumen memakai kata jas hujan dan perlengkapan cuaca. Pencarian berbasis makna dapat membantu menemukan dokumen itu meskipun kata persisnya berbeda." }, { heading: "Apa yang disimpan", body: "Sistem menyimpan embedding, metadata, dan hubungan dengan sumber asli. Metadata seperti kategori, tanggal, atau akses dapat dipakai untuk memfilter hasil. Database bukan hanya gudang angka; ia bagian dari strategi retrieval yang perlu diuji." }, { heading: "Ringkasnya", body: "Vector database membantu menemukan informasi yang mirip secara makna. Kualitas hasil tetap bergantung pada embedding, data, filter, dan cara mengukur relevansi." }], quiz: [{ question: "Vector database membantu pencarian berdasarkan…", options: ["Kemiripan representasi makna", "Warna dokumen", "Urutan ukuran file saja"], answer: 0, explanation: "Embedding memungkinkan pencarian kemiripan semantik." }, { question: "Metadata berguna untuk…", options: ["Memfilter atau menjelaskan sumber", "Menghapus semua konteks", "Mengubah jawaban menjadi gambar"], answer: 0, explanation: "Metadata membantu membatasi hasil dan melacak asal informasi." }] },
  23: { summary: "Embedding mengubah teks atau objek menjadi deretan angka yang mewakili pola dan makna relatifnya.", analogy: "Embedding seperti menaruh banyak kalimat di peta; kalimat yang maknanya mirip ditempatkan berdekatan.", sections: [{ heading: "Dari kalimat ke posisi di peta", body: "Sebuah embedding bukan terjemahan kata demi kata. Ia adalah representasi numerik yang bisa dibandingkan menggunakan ukuran kemiripan. Kalimat tentang belajar memasak dapat berada lebih dekat dengan kalimat tentang resep daripada kalimat tentang mesin motor." }, { heading: "Cerita kecil: peta perpustakaan", body: "Bayangkan perpustakaan memiliki peta tema. Buku tentang kesehatan berada dekat buku olahraga, sementara buku astronomi berada di area lain. Ketika kamu meminta topik tertentu, pustakawan mencari wilayah terdekat sebelum membuka judul yang lebih spesifik." }, { heading: "Embedding punya batas", body: "Embedding tidak otomatis memahami kebenaran, kualitas, atau izin dokumen. Dua teks bisa dekat karena memakai pola bahasa mirip, padahal salah satunya keliru. Karena itu, embedding dipakai untuk menemukan kandidat, bukan menggantikan verifikasi." }, { heading: "Ringkasnya", body: "Embedding mengubah makna relatif menjadi koordinat numerik agar mesin bisa membandingkan kemiripan. Ia adalah bahan penting untuk semantic search dan RAG." }], quiz: [{ question: "Embedding biasanya menghasilkan…", options: ["Representasi numerik", "File suara manusia", "Label warna otomatis"], answer: 0, explanation: "Embedding mengubah objek menjadi vektor angka yang dapat dibandingkan." }, { question: "Embedding digunakan untuk…", options: ["Mencari kemiripan", "Menjamin fakta selalu benar", "Menghapus metadata"], answer: 0, explanation: "Embedding membantu menemukan kandidat yang mirip secara semantik." }] },
  24: { summary: "Chunking adalah proses memotong dokumen menjadi potongan yang cukup lengkap untuk dipahami dan cukup kecil untuk dicari.", analogy: "Chunking seperti memotong buku menjadi kartu catatan: terlalu besar sulit dicari, terlalu kecil kehilangan cerita.", sections: [{ heading: "Mengapa dokumen perlu dipotong", body: "RAG biasanya tidak memasukkan seluruh dokumen ke dalam prompt. Dokumen dipecah menjadi potongan agar sistem dapat mengambil bagian yang paling relevan dengan pertanyaan. Ukuran potongan harus mempertimbangkan panjang konteks dan hubungan antarparagraf." }, { heading: "Cerita kecil: resep yang terpisah", body: "Jika langkah membuat kue dipotong satu kalimat per kartu tanpa judul, kamu bisa mendapat kartu oven tetapi kehilangan suhu dan durasinya. Potongan yang baik membawa konteks secukupnya, misalnya judul bagian dan paragraf yang saling berkaitan." }, { heading: "Strategi yang bisa dicoba", body: "Potongan bisa dibuat berdasarkan heading, paragraf, jumlah token, atau jendela yang saling tumpang tindih. Overlap membantu menjaga konteks yang berada di batas potongan, tetapi menambah ukuran penyimpanan dan kandidat retrieval." }, { heading: "Ringkasnya", body: "Chunking bukan sekadar memotong berdasarkan jumlah karakter. Tujuannya adalah menjaga unit informasi tetap bermakna, mudah ditemukan, dan cocok dengan kebutuhan pertanyaan." }], quiz: [{ question: "Potongan yang terlalu kecil dapat…", options: ["Kehilangan konteks", "Selalu lebih akurat", "Menghilangkan kebutuhan retrieval"], answer: 0, explanation: "Chunk kecil dapat memisahkan detail penting dari konteksnya." }, { question: "Overlap digunakan untuk…", options: ["Menjaga konteks di batas potongan", "Membuat semua data duplikat tanpa alasan", "Mengubah teks menjadi audio"], answer: 0, explanation: "Overlap membantu informasi yang berada di perbatasan chunk tetap terbawa." }] },
  25: { summary: "Keyword search mencari kecocokan kata, sedangkan semantic search mencari kemiripan maksud atau makna.", analogy: "Keyword search mencari buku dengan judul yang sama; semantic search mencari buku yang membahas ide serupa meski judulnya berbeda.", sections: [{ heading: "Kapan keyword search berguna", body: "Keyword search cepat dan mudah dipahami. Ia cocok untuk nama produk, kode, istilah hukum, atau kata yang harus dicari persis. Jika pengguna tahu kata yang tepat, pencarian keyword sering sangat efektif." }, { heading: "Cerita kecil: pertanyaan dengan kata berbeda", body: "Seseorang mencari cara mengganti kata sandi, tetapi dokumen memakai istilah kredensial akun. Keyword search bisa gagal jika tidak ada sinonim yang disiapkan. Semantic search memiliki peluang lebih besar menemukan hubungan makna tersebut." }, { heading: "Sering kali keduanya digabung", body: "Hybrid search menggabungkan ketepatan keyword dengan keluwesan semantic search. Sistem dapat melakukan reranking agar hasil yang paling relevan muncul di atas. Pilihan terbaik bergantung pada jenis data dan pertanyaan pengguna." }, { heading: "Ringkasnya", body: "Keyword membantu menemukan kata yang tepat. Semantic membantu menemukan maksud yang mirip. Banyak aplikasi nyata membutuhkan kombinasi keduanya." }], quiz: [{ question: "Keyword search paling cocok untuk…", options: ["Kecocokan istilah yang harus presisi", "Semua pertanyaan abstrak", "Mengukur emosi"], answer: 0, explanation: "Keyword search unggul saat istilah atau kode perlu ditemukan secara tepat." }, { question: "Semantic search fokus pada…", options: ["Kemiripan makna", "Warna font", "Ukuran monitor"], answer: 0, explanation: "Semantic search menggunakan representasi untuk mencari maksud atau makna yang mirip." }] },
  26: { summary: "RAG pipeline menghubungkan ingestion dokumen, chunking, embedding, retrieval, prompt, generation, dan evaluasi menjadi satu alur.", analogy: "RAG pipeline seperti dapur restoran: bahan masuk, dipotong, disimpan, dicari saat ada pesanan, lalu disajikan setelah dicek.", sections: [{ heading: "Sebelum pertanyaan datang", body: "Dokumen dikumpulkan, dibersihkan, diberi metadata, dipecah menjadi chunk, lalu diubah menjadi embedding. Tahap ini biasanya disebut ingestion. Kesalahan di sini dapat terbawa sampai jawaban akhir." }, { heading: "Cerita kecil: petugas pusat informasi", body: "Petugas menerima tumpukan panduan, menaruhnya di rak berdasarkan topik, membuat indeks, lalu mencari halaman ketika pengunjung bertanya. Ia tidak membawa seluruh perpustakaan ke meja; ia mengambil bagian yang paling relevan." }, { heading: "Saat pengguna bertanya", body: "Pertanyaan diubah atau dipakai untuk retrieval. Sistem mengambil beberapa kandidat, mungkin memfilter metadata, lalu menyusun prompt berisi konteks dan instruksi. Model menghasilkan jawaban yang sebaiknya menyertakan sumber atau batasan bila informasi belum cukup." }, { heading: "Ringkasnya", body: "Pipeline yang baik memperhatikan setiap tahap, bukan hanya model generasinya. Debugging perlu melihat apakah masalah muncul di data, retrieval, prompt, atau jawaban." }], quiz: [{ question: "Tahap sebelum retrieval biasanya mencakup…", options: ["Chunking dan embedding", "Menghapus semua dokumen", "Menutup aplikasi"], answer: 0, explanation: "Dokumen perlu diproses dan direpresentasikan sebelum dapat dicari." }, { question: "Jika konteks retrieval salah, jawaban bisa…", options: ["Ikut meleset", "Selalu sempurna", "Tidak terpengaruh sama sekali"], answer: 0, explanation: "Model menghasilkan jawaban dari konteks yang diberikan, sehingga retrieval penting." }] },
  27: { summary: "Evaluasi RAG memeriksa apakah jawaban didukung sumber, relevan dengan pertanyaan, dan mengambil informasi yang seharusnya ditemukan.", analogy: "Evaluasi RAG seperti memeriksa tugas: bukan hanya apakah kalimatnya rapi, tetapi apakah jawabannya menjawab soal dan sesuai catatan.", sections: [{ heading: "Faithfulness", body: "Faithfulness menanyakan apakah jawaban mengikuti konteks yang diberikan dan tidak menambahkan klaim yang tidak didukung. Jawaban yang terdengar bagus tetapi bertentangan dengan dokumen mendapat sinyal buruk pada metrik ini." }, { heading: "Cerita kecil: petugas yang salah membuka map", body: "Pengunjung bertanya jadwal pendaftaran, tetapi petugas membuka map jadwal libur lalu menjawab dengan yakin. Jawabannya mungkin rapi, namun retrieval-nya tidak relevan. Evaluasi membantu memisahkan masalah pencarian dari masalah generasi." }, { heading: "Relevancy dan recall", body: "Relevancy memeriksa apakah jawaban atau konteks berkaitan dengan pertanyaan. Recall melihat apakah informasi yang diperlukan berhasil ditemukan. Dalam praktik, tim dapat memakai dataset pertanyaan dan jawaban acuan, pemeriksaan manusia, serta metrik otomatis." }, { heading: "Ringkasnya", body: "Tidak ada satu angka yang menceritakan semuanya. Evaluasi yang baik menggabungkan faithfulness, relevansi, recall, kualitas sumber, latency, dan pengalaman pengguna." }], quiz: [{ question: "Faithfulness memeriksa apakah jawaban…", options: ["Didukung konteks", "Memiliki emoji", "Selalu paling panjang"], answer: 0, explanation: "Faithfulness menilai kesetiaan jawaban terhadap konteks sumber." }, { question: "Recall pada retrieval bertanya apakah…", options: ["Informasi yang dibutuhkan berhasil ditemukan", "Warna kartu sesuai", "Prompt memiliki lima baris"], answer: 0, explanation: "Recall berkaitan dengan seberapa banyak informasi relevan yang berhasil diambil." }] },
  28: { summary: "AI Agent adalah sistem yang memakai model untuk mengamati tujuan, merencanakan langkah, menggunakan tools, dan mengecek hasil.", analogy: "Chatbot menjawab dari kursi; agent seperti asisten yang bisa membuat rencana, membuka kalender, memanggil alat, lalu kembali membawa hasil.", sections: [{ heading: "Dari respons ke tindakan", body: "Chatbot biasa mungkin menerima pesan dan menghasilkan balasan. Agent menambahkan loop kerja: memahami tujuan, memilih langkah, memanggil tool, membaca hasil, lalu menentukan langkah berikutnya. Agent tetap membutuhkan batasan, izin, dan cara menghentikan proses." }, { heading: "Cerita kecil: merencanakan acara kelas", body: "Kamu meminta bantuan mencari waktu rapat. Asisten perlu melihat kalender, menemukan slot bersama, membuat draft undangan, lalu meminta konfirmasi sebelum mengirim. Kemampuan memakai tools dan menjaga status inilah yang membuatnya terasa seperti agent." }, { heading: "Agent bukan otomatis otonom penuh", body: "Banyak sistem agent bersifat semi-otomatis. Manusia menyetujui tindakan berisiko, menetapkan tools yang boleh dipakai, dan memantau hasil. Semakin besar dampak tindakan, semakin penting guardrail dan human-in-the-loop." }, { heading: "Ringkasnya", body: "Agent menggabungkan model, state, tools, rencana, dan evaluasi. Tujuan yang jelas serta batas tindakan sama pentingnya dengan model yang dipakai." }], quiz: [{ question: "AI Agent berbeda dari chatbot biasa karena dapat…", options: ["Merencanakan dan memakai tools", "Tidak membutuhkan tujuan", "Selalu berjalan tanpa batas"], answer: 0, explanation: "Agent biasanya memiliki loop kerja dan akses terkontrol ke tools." }, { question: "Human-in-the-loop berguna untuk…", options: ["Memeriksa tindakan berisiko", "Menghapus semua keputusan", "Membuat model lupa konteks"], answer: 0, explanation: "Manusia dapat menyetujui atau meninjau tindakan yang berdampak penting." }] },
  29: { summary: "Function calling memungkinkan model memilih fungsi terstruktur, sementara aplikasi menjalankan fungsi tersebut dan mengembalikan hasilnya.", analogy: "Model adalah resepsionis yang memahami permintaan; function adalah formulir resmi yang dikirim ke bagian yang punya akses melakukan pekerjaan.", sections: [{ heading: "Model tidak menjalankan fungsi sendirian", body: "Model menghasilkan panggilan terstruktur seperti nama fungsi dan argumen. Aplikasi memvalidasi argumen, menjalankan kode atau API, lalu mengirimkan hasil kembali ke model. Pemisahan ini penting agar akses tetap berada di bawah kontrol aplikasi." }, { heading: "Cerita kecil: memesan tiket", body: "Pengguna berkata carikan tiket untuk Sabtu. Model dapat memilih fungsi searchTicket dengan tanggal dan tujuan. Aplikasi memeriksa format, memanggil layanan tiket, menampilkan pilihan, dan meminta konfirmasi sebelum pembelian. Model tidak boleh langsung membayar tanpa izin." }, { heading: "Validasi dan keamanan", body: "Schema perlu membatasi tipe data dan nilai yang diperbolehkan. Tool harus memiliki izin minimal, timeout, logging, dan penanganan error. Jangan meneruskan input pengguna ke operasi sensitif tanpa validasi atau persetujuan." }, { heading: "Ringkasnya", body: "Function calling adalah jembatan terstruktur antara bahasa dan tindakan. Model memilih, aplikasi memvalidasi dan mengeksekusi, lalu hasilnya dikembalikan dengan aman." }], quiz: [{ question: "Dalam function calling, aplikasi biasanya…", options: ["Memvalidasi dan menjalankan fungsi", "Membiarkan model membayar langsung", "Menghapus semua argumen"], answer: 0, explanation: "Aplikasi memegang kontrol eksekusi dan validasi tool." }, { question: "Mengapa schema penting?", options: ["Membatasi bentuk argumen", "Membuat hasil selalu kreatif", "Mengganti database"], answer: 0, explanation: "Schema membantu memastikan argumen memiliki bentuk dan tipe yang diharapkan." }] },
  30: { summary: "Multi-agent system membagi pekerjaan ke beberapa agent dengan peran berbeda, lalu mengatur cara mereka berkoordinasi.", analogy: "Seperti tim produksi: ada peneliti, penulis, editor, dan pemeriksa fakta yang bekerja dengan brief dan jalur komunikasi jelas.", sections: [{ heading: "Mengapa membagi agent", body: "Tugas besar sering memiliki bagian yang berbeda. Agent khusus dapat diberi tools dan instruksi yang lebih sempit, sehingga tanggung jawabnya lebih jelas. Namun, setiap agent menambah latency, biaya, dan peluang koordinasi gagal." }, { heading: "Cerita kecil: membuat laporan sekolah", body: "Agent peneliti mencari sumber, agent penyusun membuat kerangka, agent editor merapikan bahasa, dan agent pemeriksa mencari klaim yang meragukan. Seorang koordinator menentukan urutan dan memutuskan kapan pekerjaan dianggap cukup." }, { heading: "Koordinasi bukan sekadar membagi prompt", body: "Sistem perlu menentukan format pesan, siapa yang memegang state, bagaimana konflik diselesaikan, dan kapan manusia dilibatkan. Jika agent mengulang pekerjaan atau saling memberi instruksi yang bertentangan, hasilnya bisa lebih buruk daripada satu agent yang sederhana." }, { heading: "Ringkasnya", body: "Multi-agent berguna saat pembagian peran benar-benar membantu. Mulailah dari sistem sederhana, lalu tambah agent hanya ketika ada manfaat yang bisa diukur." }], quiz: [{ question: "Multi-agent system biasanya membagi…", options: ["Peran dan tanggung jawab", "Satu layar menjadi dua warna", "Semua data tanpa aturan"], answer: 0, explanation: "Beberapa agent diberi peran berbeda untuk mengerjakan bagian tugas tertentu." }, { question: "Kelemahan multi-agent adalah…", options: ["Biaya dan koordinasi lebih kompleks", "Tidak bisa memakai tools", "Selalu tanpa state"], answer: 0, explanation: "Lebih banyak agent menambah komunikasi, latency, biaya, dan potensi konflik." }] },
  31: { summary: "Memory pada AI Agent menentukan informasi apa yang disimpan agar percakapan dan tugas dapat berlanjut dengan konteks yang tepat.", analogy: "Short-term memory seperti catatan di meja hari ini; long-term memory seperti arsip yang disimpan untuk dipakai pada kesempatan lain.", sections: [{ heading: "Short-term memory", body: "Short-term memory biasanya berisi percakapan atau hasil tool dalam tugas saat ini. Ia membantu agent menjaga urutan langkah, tetapi terbatas oleh context window. Jika terlalu banyak detail, agent perlu merangkum atau memilih informasi penting." }, { heading: "Cerita kecil: teman yang mencatat", body: "Saat mengerjakan proyek kelompok, kamu menulis catatan rapat hari ini di buku kecil. Setelah proyek selesai, sebagian informasi dipindahkan ke dokumen bersama. Catatan harian membantu kerja saat ini; arsip membantu percakapan di masa depan." }, { heading: "Long-term memory perlu persetujuan", body: "Informasi preferensi atau riwayat pengguna sebaiknya disimpan dengan tujuan jelas, kontrol akses, dan pilihan untuk melihat atau menghapusnya. Jangan menyimpan semua hal hanya karena bisa. Relevansi, privasi, dan masa simpan perlu dipikirkan." }, { heading: "Ringkasnya", body: "Memory bukan sekadar menyimpan teks. Sistem harus menentukan apa yang layak disimpan, kapan dipanggil kembali, dan bagaimana pengguna mengontrolnya." }], quiz: [{ question: "Short-term memory terutama membantu…", options: ["Menjaga konteks tugas saat ini", "Menyimpan semua hal selamanya", "Mengubah teks menjadi gambar"], answer: 0, explanation: "Short-term memory membantu agent mengikuti konteks dan langkah dalam satu tugas." }, { question: "Long-term memory perlu memperhatikan…", options: ["Privasi dan kontrol pengguna", "Jumlah emoji", "Warna tombol saja"], answer: 0, explanation: "Informasi yang disimpan lintas sesi memiliki konsekuensi privasi dan keamanan." }] },
  32: { summary: "AI safety dan alignment berusaha membuat sistem tetap aman, dapat diawasi, dan selaras dengan tujuan manusia serta batas yang disepakati.", analogy: "Seperti memasang rem, sabuk pengaman, dan rambu pada kendaraan cepat: kemampuan saja tidak cukup tanpa pengendalian.", sections: [{ heading: "Safety dan alignment bukan hal yang sama persis", body: "Safety mencakup pencegahan penyalahgunaan, kegagalan, kebocoran, dan dampak berbahaya. Alignment berkaitan dengan apakah perilaku sistem mengikuti tujuan dan nilai yang dimaksud manusia. Keduanya saling berhubungan tetapi membutuhkan teknik dan evaluasi yang berbeda." }, { heading: "Cerita kecil: robot kurir", body: "Robot diminta mengantarkan paket secepat mungkin. Jika hanya mengejar kecepatan, ia mungkin menerobos area terlarang atau membahayakan orang. Tujuan yang baik perlu batasan, prioritas keselamatan, dan cara meminta bantuan saat situasi tidak jelas." }, { heading: "Lapisan perlindungan", body: "Perlindungan dapat mencakup data yang baik, model yang diuji, filter, sandbox, izin minimal, monitoring, red teaming, logging, dan human review. Tidak ada satu guardrail yang menyelesaikan semua risiko." }, { heading: "Ringkasnya", body: "Sistem AI yang hebat bukan hanya sistem yang mampu. Ia juga dapat dipahami, diarahkan, dibatasi, diuji, dan dihentikan ketika diperlukan." }], quiz: [{ question: "Alignment berhubungan dengan…", options: ["Perilaku sistem mengikuti tujuan yang dimaksud", "Kecepatan internet", "Ukuran font"], answer: 0, explanation: "Alignment berfokus pada kesesuaian perilaku sistem dengan tujuan dan nilai yang diinginkan." }, { question: "Guardrail yang baik seharusnya…", options: ["Berlapis dan dapat dipantau", "Hanya satu aturan", "Tidak pernah diuji"], answer: 0, explanation: "Risiko yang berbeda membutuhkan perlindungan dan monitoring berlapis." }] },
  33: { summary: "Masa depan AI akan dipengaruhi kemajuan model, kemungkinan AGI, regulasi, pekerjaan, pendidikan, dan cara masyarakat membagi tanggung jawab.", analogy: "Masa depan AI seperti membangun kota baru: teknologi adalah infrastrukturnya, tetapi aturan, budaya, dan keputusan warganya menentukan kota itu terasa aman atau tidak.", sections: [{ heading: "AGI bukan tombol yang sudah tersedia", body: "Artificial General Intelligence biasanya dipakai untuk menggambarkan kemampuan luas yang dapat beradaptasi pada banyak tugas. Definisinya belum seragam, sehingga klaim tentang AGI perlu dibaca hati-hati. Yang jelas, kemampuan model saat ini terus berubah dan dampaknya sudah terasa sebelum istilah tersebut selesai diperdebatkan." }, { heading: "Cerita kecil: sekolah yang memakai AI", body: "Sebuah sekolah memakai AI untuk memberi latihan yang lebih sesuai dengan kemampuan siswa. Guru tetap menentukan tujuan, memeriksa materi, dan menjaga agar siswa tidak diperlakukan hanya sebagai skor. Teknologi membantu, tetapi keputusan pendidikan tetap membutuhkan konteks manusia." }, { heading: "Regulasi dan dampak sosial", body: "Pertanyaan penting mencakup privasi, hak cipta, bias, keamanan, transparansi, dampak pekerjaan, dan akses yang adil. Regulasi mencoba membagi tanggung jawab antara pembuat, penyedia, pengguna, dan institusi yang menerapkan sistem." }, { heading: "Ringkasnya", body: "Belajar masa depan AI bukan hanya menebak teknologi berikutnya. Kita juga perlu memahami trade-off, ikut berdiskusi, dan memastikan manfaatnya dibangun dengan tanggung jawab." }], quiz: [{ question: "AGI biasanya menggambarkan…", options: ["Kemampuan luas yang dapat beradaptasi", "Satu filter foto", "Database kecil"], answer: 0, explanation: "AGI adalah istilah untuk gagasan kemampuan umum lintas tugas, bukan sekadar satu fitur." }, { question: "Diskusi masa depan AI perlu mencakup…", options: ["Privasi, bias, pekerjaan, dan regulasi", "Warna logo saja", "Kecepatan mengetik saja"], answer: 0, explanation: "Dampak AI melibatkan teknologi sekaligus aspek sosial, hukum, dan etika." }] },
};

const expandedMinutes = [8, 10, 9, 11, 10, 10, 11, 9, 10, 9, 10, 12, 9, 11, 10, 10, 9, 9, 10, 9, 11, 10, 10, 9, 9, 11, 10, 10, 11, 10, 10, 11, 12];

export const materials: Material[] = [...titles.map((item, index) => {
  const id = index + 1;
  const meta = categoryMeta[item.category];
  const content = expandedContent[id] ?? specialContent[id] ?? {
    summary: quickSummaries[id - 1],
    analogy: "Anggap konsep ini seperti toolkit: pahami fungsi tiap alat dulu, baru pilih alat yang cocok untuk masalahmu.",
    sections: [
      { heading: "Inti konsepnya", body: `Materi ini membantu kamu melihat bagaimana ${item.title.toLowerCase()} bekerja dalam ekosistem AI modern. Fokus pada hubungan antarbagian, bukan sekadar istilah.` },
      { heading: "Kenapa ini penting?", body: "Konsep yang terlihat rumit biasanya menjadi lebih ringan ketika dihubungkan dengan contoh sehari-hari. Coba cari satu situasi nyata yang mirip dengan ide di materi ini." },
      { heading: "Catatan kecil", body: "Tidak apa-apa kalau belum langsung hafal. Tandai bagian yang ingin kamu ulangi, lalu lanjutkan sedikit demi sedikit agar rasa penasaran tetap hidup." },
    ],
    quiz: [
      { question: `Apa fokus utama materi “${item.title}”?`, options: ["Memahami konsep dan kegunaannya", "Menghafal semua kode", "Menghindari semua teknologi"], answer: 0, explanation: "Pemahaman konsep membuatmu lebih siap membaca contoh dan mencoba alatnya." },
      { question: "Cara belajar yang paling sehat adalah…", options: ["Mencoba, mengecek, lalu memperbaiki", "Takut bertanya", "Menghafal tanpa memahami"], answer: 0, explanation: "Eksperimen kecil dan refleksi membantu konsep menempel lebih lama." },
    ],
  };
  const diagram = id === 6 ? { src: "/manus-storage/neural-network-belajar-ai_3438e441.png", alt: "Diagram Neural Network dari input data melewati tiga lapisan pola hingga menghasilkan prediksi, dengan loop training untuk memperbaiki bobot", caption: "Neural Network: dari input, melewati lapisan, menjadi prediksi", note: "Cara membacanya: lapisan awal menangkap pola sederhana, lapisan berikutnya menggabungkan ciri, lalu output menghasilkan prediksi. Saat training, bobot diperbaiki berdasarkan kesalahan." } : id === 12 ? { src: "/manus-storage/transformer-belajar-ai_147a79d8.png", alt: "Diagram alur Transformer dari kalimat masuk, tokenisasi, embedding, self-attention, feed forward, hingga jawaban", caption: "Transformer: dari kalimat menjadi jawaban, selangkah demi selangkah", note: "Cara membacanya: model mengubah teks menjadi token, menimbang hubungan antar-token lewat attention, mengolah pola, lalu memilih token berikutnya secara berulang." } : id === 23 ? { src: "/manus-storage/embedding-belajar-ai_492add3b.png", alt: "Diagram Embedding dari kalimat yang diubah menjadi vektor lalu ditempatkan di ruang makna untuk menemukan kalimat mirip atau jauh", caption: "Embedding: mengubah kalimat menjadi posisi di ruang makna", note: "Cara membacanya: model mengubah kalimat menjadi deretan angka, lalu memakai posisinya untuk membandingkan kemiripan makna dengan kalimat lain." } : id === 26 ? { src: "/manus-storage/rag-pipeline-belajar-ai_fa3aea09.png", alt: "Diagram RAG Pipeline dari dokumen dan pertanyaan menuju pencarian relevan, LLM, jawaban, dan sumber", caption: "RAG Pipeline: siapkan pengetahuan, cari konteks, lalu jawab", note: "Cara membacanya: dokumen disiapkan lebih dulu di vector database. Saat pertanyaan datang, sistem mencari potongan yang relevan dan memberikannya kepada LLM sebagai konteks." } : id === 28 ? { src: "/manus-storage/ai-agent-belajar-ai_5604f1f1.png", alt: "Diagram AI Agent dari tujuan pengguna, pemahaman konteks, rencana, pemilihan tool, observasi, loop keputusan, dan guardrail persetujuan manusia", caption: "AI Agent: rencanakan, pakai tool, amati, lalu putuskan", note: "Cara membacanya: agent tidak hanya menjawab. Ia membuat rencana, memakai tool, membaca hasil, lalu mengulang atau menyelesaikan tugas. Tindakan berisiko dapat membutuhkan persetujuan manusia." } : id === 29 ? { src: "/manus-storage/function-calling-belajar-ai_dc8a17e4.png", alt: "Diagram Function Calling dari permintaan pengguna, pemahaman LLM, function call, validasi aplikasi, tool API, hasil tool, dan jawaban", caption: "Function Calling: dari maksud pengguna ke tool yang tervalidasi", note: "Cara membacanya: LLM memilih fungsi dan mengisi argumen, tetapi aplikasi tetap memvalidasi dan menjalankan tool. Hasilnya kemudian dikembalikan untuk membantu menyusun jawaban." } : undefined;
  const diagramQuiz = id === 6 ? { question: "Pada diagram Neural Network, apa yang terjadi setelah input melewati beberapa layer?", options: ["Model menghasilkan prediksi", "Data langsung menjadi jawaban manusia", "Semua bobot dihapus"], answer: 0, explanation: "Benar. Setiap layer mengolah pola sebelum output menghasilkan prediksi. Saat training, bobot diperbaiki jika prediksinya meleset." } : id === 12 ? { question: "Pada alur Transformer, apa yang terjadi setelah self-attention?", options: ["Pola diolah lebih dalam lewat feed forward", "Dokumen langsung disimpan ke vector database", "Jawaban langsung dikirim tanpa memilih token"], answer: 0, explanation: "Benar. Setelah attention menimbang konteks, feed forward membantu mengolah pola sebelum model memilih token berikutnya." } : id === 23 ? { question: "Pada diagram Embedding, mengapa dua kalimat bisa berada berdekatan?", options: ["Maknanya dianggap mirip oleh model", "Jumlah hurufnya pasti sama", "Keduanya selalu berasal dari dokumen yang sama"], answer: 0, explanation: "Benar. Embedding menempatkan teks dalam ruang angka sehingga kemiripan makna dapat dibandingkan." } : id === 26 ? { question: "Pada RAG Pipeline, kapan vector database dipakai?", options: ["Saat mencari potongan konteks yang relevan", "Setelah jawaban selesai tanpa membaca pertanyaan", "Hanya ketika dokumen pertama kali ditulis"], answer: 0, explanation: "Benar. Vector database dicari ketika pertanyaan datang agar sistem bisa mengambil konteks yang paling relevan untuk LLM." } : id === 28 ? { question: "Pada diagram AI Agent, kapan agent kembali membuat rencana?", options: ["Saat hasil observasi belum cukup", "Setelah selalu selesai tanpa melihat hasil", "Sebelum memahami tujuan pengguna"], answer: 0, explanation: "Benar. Agent mengulang loop rencana dan tool ketika observasi belum cukup untuk menyelesaikan tujuan." } : id === 29 ? { question: "Dalam Function Calling, siapa yang memvalidasi dan menjalankan tool?", options: ["Aplikasi", "Model tanpa batas", "Pengguna lain yang tidak terlibat"], answer: 0, explanation: "Benar. Model mengusulkan function call, tetapi aplikasi memvalidasi argumen dan mengontrol eksekusinya." } : undefined;
  return { id, title: item.title, category: item.category, level: meta.level, minutes: expandedMinutes[id - 1] ?? item.minutes, emoji: meta.emoji, diagram, diagramQuiz, ...content };
}), ...infrastructureMaterials, ...specializationMaterials];

export const categories = ["Semua kategori", ...Object.keys(categoryMeta)];
export const levels = ["Semua level", "Pemula", "Menengah", "Lanjut"];
