export type PriorityDeepDive = { exampleTitle: string; example: string; commonMistake: string; rubric: readonly [string, string, string] };

const dive = (exampleTitle: string, example: string, commonMistake: string, rubric: readonly [string, string, string]): PriorityDeepDive => ({ exampleTitle, example, commonMistake, rubric });

export const priorityIntensiveDeepening: Record<number, PriorityDeepDive> = {
  5000: dive("Contoh kerja: demo dokumen Orbis", "Sebelum memilih layanan, tim menulis: pengguna mengunggah PDF, worker mengekstrak teks, model membuat ringkasan, dan operator melihat error. Dari situ mereka bisa menandai data sensitif dan titik biaya tanpa menyebut nama produk cloud.", "Menggambar logo layanan lebih dulu. Diagram yang cantik tetapi tidak menunjukkan data, owner, atau kegagalan tidak membantu keputusan.", ["Aktor dan tujuan terlihat", "Aliran data ditandai", "Ada owner dan batas awal"]),
  5001: dive("Contoh kerja: rumah yang terukur", "Tim mengubah kalimat 'butuh cloud' menjadi tiga kebutuhan: upload stabil, waktu ringkasan di bawah batas yang disepakati, dan biaya per dokumen yang dapat dibaca. Baru sesudah itu mereka membandingkan opsi compute.", "Menganggap server menyala berarti produk siap. Ukur juga waktu tunggu, kegagalan, biaya, dan cara pulih saat provider lambat.", ["Kebutuhan ditulis sebagai sinyal", "Trade-off dicatat", "Ukuran keberhasilan bisa dicek"]),
  5002: dive("Contoh kerja: pisahkan sandbox", "Orbis memberi tiap lingkungan nama, tag biaya, dan akun latihan berbeda. Data contoh tetap sintetis, sehingga eksperimen tidak membuat tim bingung apakah mereka sedang melihat konfigurasi production.", "Menguji dengan akun utama lalu berharap tidak ada yang salah. Pemisahan lingkungan adalah pagar proses, bukan formalitas nama folder.", ["Lingkungan punya tujuan", "Data latihan aman", "Biaya dan akses dapat dibedakan"]),
  5012: dive("Contoh kerja: mulai dari perjalanan pengguna", "Satu request ringkasan diurai menjadi upload, validasi, antrean, ekstraksi, panggilan model, penyimpanan hasil, lalu notifikasi. Komponen dipilih karena tugasnya, bukan karena sedang populer.", "Memilih layanan dari daftar fitur lalu memaksa use case masuk ke sana. Mulailah dari pekerjaan yang harus selesai dan batas waktunya.", ["Use case satu kalimat", "Aliran kerja berurutan", "Batas latency dan data disebut"]),
  5013: dive("Contoh kerja: context diagram satu halaman", "Diagram Orbis memakai lima kotak: pengguna, aplikasi, storage, worker, dan provider model. Panah diberi label 'PDF terenkripsi', 'job metadata', atau 'ringkasan' agar pembaca tahu apa yang melintas.", "Panah tanpa kata kerja atau label data. Itu membuat review keamanan dan biaya menjadi tebak-tebakan.", ["Kotak mewakili owner/tanggung jawab", "Panah punya kata kerja", "Data sensitif dibedakan"]),
  5014: dive("Contoh kerja: request yang dapat ditelusuri", "Tim memberikan request ID sejak upload. ID yang sama dibawa ke antrean, worker, dan log hasil sehingga mereka bisa membedakan dokumen gagal dari model lambat tanpa membuka isi dokumen.", "Mencatat payload mentah untuk memudahkan debug. Simpan metadata dan ID korelasi; minimalkan data yang tidak dibutuhkan.", ["Ada ID korelasi", "Status tiap tahap jelas", "Log tidak memuat rahasia"]),
  5144: dive("Contoh kerja: paket readiness", "Capstone Orbis dimulai dengan satu halaman yang menyatakan layanan, owner on-call, data yang diproses, SLO awal, dan cara rollback. Paket itu membuat diskusi production fokus pada bukti, bukan rasa percaya diri.", "Menutup capstone dengan screenshot dashboard. Screenshot tidak menjelaskan keputusan, ambang alert, atau siapa yang bertindak.", ["Scope layanan jelas", "Owner dan sinyal operasi ada", "Jalan mundur terdokumentasi"]),
  5145: dive("Contoh kerja: drill kecil sebelum launch", "Tim menjalankan simulasi aman: worker dibuat lambat di sandbox, dashboard menunjukkan antrean, dan runbook menyebut langkah pause, komunikasi, lalu pemulihan. Mereka mencatat apa yang tidak bekerja.", "Menganggap runbook selesai karena ditulis. Runbook harus dapat dipakai orang lain dalam latihan kecil.", ["Skenario aman dipilih", "Langkah dan owner eksplisit", "Temuan drill berubah menjadi action item"]),

  6000: dive("Contoh kerja: pertanyaan sebelum tabel", "Tim analitik tidak mulai dari dashboard. Mereka bertanya: 'Apakah pengguna baru berhasil sampai ringkasan pertama dalam satu sesi?' lalu mencatat siapa pemilik keputusan dan tindakan bila angka turun.", "Mengumpulkan semua kolom karena mungkin berguna. Data tanpa keputusan mengundang biaya, kebingungan, dan risiko akses.", ["Pertanyaan keputusan spesifik", "Pengguna metrik disebut", "Tindakan setelah hasil tersedia"]),
  6001: dive("Contoh kerja: angka yang bisa diperdebatkan sehat", "Untuk 'aktivasi', Orbis menulis event yang dihitung, jendela waktu, populasi, dan pengecualian. Saat angka berubah, tim bisa mengecek definisi sebelum menyalahkan pipeline.", "Menyebut metrik dengan nama populer tanpa definisi. Dua dashboard bisa sama-sama berkata 'retensi' tetapi menghitung hal yang berbeda.", ["Definisi dapat diuji", "Batas populasi ada", "Versi definisi dicatat"]),
  6012: dive("Contoh kerja: brief keputusan", "Analis menerima permintaan 'buat dashboard'. Ia membalas dengan brief: keputusan apa, siapa yang mengambilnya, frekuensi, dan perubahan perilaku yang diharapkan. Dashboard baru dibuat setelah jawaban cukup.", "Menjawab pertanyaan kabur dengan visual yang rumit. Clarifying question sering lebih bernilai daripada chart tambahan.", ["Keputusan utama tunggal", "Stakeholder dan ritme jelas", "Batas interpretasi disebut"]),
  6013: dive("Contoh kerja: metric contract", "Kontrak 'waktu ke ringkasan' berisi start event upload selesai, end event hasil tampil, median dan p95, serta pengecualian job yang dibatalkan. Engineer dan product dapat menguji kontrak yang sama.", "Mengukur rata-rata saja. Rata-rata dapat menyembunyikan pengalaman pengguna yang menunggu sangat lama.", ["Event awal/akhir eksplisit", "Agregasi tepat", "Pengecualian terdokumentasi"]),
  6014: dive("Contoh kerja: data owner bukan satu orang", "Source event dimiliki aplikasi, transformasi dimiliki data team, dan definisi metrik disetujui product. Kontrak menghubungkan ketiganya sehingga perubahan schema tidak diam-diam mematahkan keputusan.", "Menganggap warehouse otomatis sumber kebenaran. Kebenaran berasal dari kontrak dan review perubahan, bukan lokasi tabel.", ["Owner tiap lapisan", "Perubahan punya notifikasi", "Asumsi kualitas tampak"]),
  6144: dive("Contoh kerja: paket keputusan data", "Capstone berisi satu pertanyaan, metric contract, lineage ringkas, tiga quality check, dan keputusan yang akan diambil. Pembaca bisa menelusuri klaim kembali ke sumber sintetis.", "Memasukkan semua query ke portfolio tanpa narasi. Yang dinilai adalah alasan query menjawab keputusan, bukan panjang SQL.", ["Pertanyaan hingga keputusan tersambung", "Lineage dapat dibaca", "Quality check punya tindak lanjut"]),
  6145: dive("Contoh kerja: quality check yang beraksi", "Saat event upload harian tiba-tiba nol, check menahan refresh dashboard dan memberi tahu owner source. Ia tidak menghapus data atau menjalankan perbaikan otomatis tanpa bukti.", "Membuat alert 'data buruk' tanpa ambang dan owner. Alert tanpa aksi hanya menambah kebisingan.", ["Ambang masuk akal", "Owner dan aksi jelas", "Kegagalan tidak menyembunyikan data"]),

  7000: dive("Contoh kerja: masalah sebelum model", "Tim product mendengar pengguna kesulitan memeriksa dokumen panjang. Mereka menulis bukti workflow, risiko salah ringkas, dan keputusan yang tetap di tangan manusia sebelum membicarakan model.", "Menyebut produk 'AI assistant' sebagai masalah. Itu nama solusi, bukan bukti bahwa pengguna benar-benar terbantu.", ["Masalah pengguna nyata", "Kerugian bila salah disebut", "Bukti awal dapat dikumpulkan"]),
  7001: dive("Contoh kerja: outcome yang tidak menipu", "Outcome Orbis bukan 'model akurat 90%'. Mereka memilih 'reviewer menemukan bagian penting lebih cepat tanpa melewatkan kutipan sumber', lalu merencanakan cara mengukurnya.", "Mengganti outcome dengan output demo. Banyak chat selesai bukan berarti pekerjaan pengguna membaik.", ["Perubahan perilaku jelas", "Proxy metrik tidak menyesatkan", "Safety included dalam outcome"]),
  7012: dive("Contoh kerja: discovery tiga bukti", "Sebelum prototype, tim mengumpulkan tiga contoh workflow izin: satu cepat, satu gagal, satu ambigu. Mereka memetakan langkah manual dan momen ketika pengguna perlu alasan, bukan hanya jawaban.", "Mewawancarai pengguna untuk meminta fitur favorit. Amati pekerjaan dan artefak yang sudah mereka gunakan.", ["Contoh workflow nyata", "Variasi kasus dicatat", "Bukti dipisah dari asumsi"]),
  7013: dive("Contoh kerja: job-to-be-done", "Reviewer tidak 'ingin AI'. Ia ingin memutuskan apakah dokumen perlu escalated sebelum batas waktu. Kalimat ini membantu menentukan input, feedback, dan kapan sistem harus diam.", "Menulis persona tanpa tugas dan konteks. Persona cantik tidak menggantikan keadaan yang memicu pekerjaan.", ["Situasi pemicu ada", "Keputusan pengguna terlihat", "Kriteria selesai jelas"]),
  7014: dive("Contoh kerja: hipotesis bernilai", "Hipotesisnya: jika sistem memberi kutipan sumber dan tombol tandai ragu, reviewer dapat memeriksa dua kali lebih cepat tanpa menaikkan escalations salah. Tim menyatakan apa yang akan membantah hipotesis.", "Menulis 'pengguna akan suka'. Hipotesis perlu perilaku, kondisi, ukuran, dan kemungkinan gagal.", ["Ada mekanisme sebab-akibat", "Metrik dan guardrail", "Falsifier disebut"]),
  7144: dive("Contoh kerja: brief yang siap review", "Capstone menempatkan problem, bukti, scope, non-goal, UX control, evaluasi, dan launch gate dalam satu brief. Pembaca tahu apa yang sengaja belum dibangun.", "Menyatukan semua ide roadmap menjadi capstone. Scope kecil yang dapat dievaluasi lebih kredibel daripada janji besar.", ["Scope dan non-goal", "Kontrol manusia", "Launch gate terukur"]),
  7145: dive("Contoh kerja: failure log sebagai produk", "Setelah uji, tim mengelompokkan jawaban salah: sumber hilang, kutipan lemah, atau permintaan ambigu. Mereka memilih perbaikan berdasarkan dampak, bukan hanya jumlah error.", "Menganggap feedback teks sebagai sinyal bersih. Catat konteks, dampak, dan apakah pengguna benar-benar memeriksa hasil.", ["Kategori kegagalan", "Dampak pengguna", "Keputusan prioritas berikutnya"]),

  8000: dive("Contoh kerja: workflow invoice", "Tim memetakan email masuk, ekstraksi data, validasi, approval, dan posting. Mereka menandai siapa boleh menyetujui, kapan workflow berhenti, dan apa yang tidak boleh diotomasi.", "Menghubungkan aplikasi dulu lalu mencari alasan. Automasi yang tidak punya owner dan batas hanya memindahkan kekacauan lebih cepat.", ["Trigger dan hasil jelas", "Owner tiap keputusan", "Stop condition tertulis"]),
  8001: dive("Contoh kerja: nilai versus risiko", "Proses dipilih bukan karena paling sering dilakukan, tetapi karena volume cukup, aturan stabil, dampak salah dapat dibatasi, dan ada orang yang memegang exception.", "Mengotomatiskan proses paling menjengkelkan tanpa melihat variasi dan risiko. Friksi kadang merupakan kontrol penting.", ["Aturan cukup stabil", "Nilai dan risiko dibandingkan", "Exception memiliki jalur manusia"]),
  8012: dive("Contoh kerja: process walk-through", "Satu invoice diuji dari inbox sampai sistem akuntansi. Tim mencatat input hilang, kondisi duplikat, dan titik approval sebelum membuat flow diagram.", "Memetakan alur ideal saja. Workflow yang aman harus memasukkan kondisi aneh yang benar-benar terjadi.", ["Happy path dan exception", "Input/output eksplisit", "Bukti dari proses nyata"]),
  8013: dive("Contoh kerja: kandidat otomatisasi", "Dari lima langkah, hanya ekstraksi metadata dan routing yang diotomasi. Keputusan pembayaran tetap menunggu approval karena aturan dan dampaknya berbeda.", "Mengukur kandidat hanya dengan jumlah klik. Nilai juga ditentukan oleh reversibilitas dan kemampuan mendeteksi salah.", ["Tugas dipisah per risiko", "Manfaat terukur", "Approval tetap pada keputusan sensitif"]),
  8014: dive("Contoh kerja: kontrak trigger", "Workflow hanya berjalan bila email berasal dari domain yang diizinkan, memiliki lampiran tipe aman, dan metadata wajib lengkap. Kasus lain masuk antrean review, bukan diteruskan paksa.", "Menulis trigger terlalu longgar lalu memperbaikinya dengan retry. Validasi awal mengurangi beban dan kejutan downstream.", ["Kondisi masuk eksplisit", "Input invalid punya jalur", "Tidak ada secret dalam payload contoh"]),
  8144: dive("Contoh kerja: trusted workflow pack", "Capstone menyatukan intent, trigger, data contract, approval, exception, audit trail, dan runbook. Seseorang di luar pembuat flow dapat membaca kapan automation boleh bertindak.", "Mengirim screenshot kanvas workflow tanpa alasan desain. Bukti perlu menjelaskan kontrol, bukan hanya koneksi antar tool.", ["Intent dan owner", "Exception/recovery", "Audit dan batas data"]),
  8145: dive("Contoh kerja: uji exception", "Tim mengirim data contoh yang duplikat dan field kosong. Flow tidak membuat transaksi kedua; ia memberi status jelas dan mengarahkan operator ke langkah aman.", "Menganggap test sukses jika happy path jalan. Kepercayaan lahir dari perilaku saat input tidak sesuai harapan.", ["Kasus gagal diuji", "Tidak ada aksi ganda", "Pesan recovery bisa dipahami"]),

  9000: dive("Contoh kerja: editorial system kecil", "Sebuah organisasi pendidikan memilih satu audiens, tiga pertanyaan berulang, tone yang jelas, dan ritme review. AI dipakai untuk draf, bukan untuk mengarang klaim tanpa sumber.", "Menilai strategi dari banyaknya ide. Strategi terlihat dari pilihan yang sengaja tidak diambil dan cara mengukur manfaatnya.", ["Audience spesifik", "Nilai editorial", "Batas fakta dan klaim"]),
  9001: dive("Contoh kerja: tujuan konten", "Tujuan kampanye bukan 'viral'. Tim ingin calon peserta memahami syarat beasiswa dan mampu mengecek sumber resmi; maka format, CTA, dan review disusun untuk pemahaman.", "Menggunakan engagement sebagai satu-satunya sinyal. Konten ramai dapat tetap membingungkan atau menyesatkan.", ["Tujuan perilaku", "CTA sesuai konteks", "Metrik kualitas tidak hanya reach"]),
  9012: dive("Contoh kerja: audience card", "Tim membuat kartu untuk calon peserta yang membuka ponsel saat jam kerja: apa yang ia sudah tahu, apa yang membuatnya ragu, dan sumber mana yang perlu ditautkan.", "Memakai target 'semua orang'. Audience yang terlalu luas membuat bahasa, contoh, dan review tidak punya pegangan.", ["Konteks penggunaan", "Pertanyaan/rasa ragu", "Aksesibilitas dipertimbangkan"]),
  9013: dive("Contoh kerja: janji konten", "Satu artikel berjanji menjelaskan proses pendaftaran dan memberikan tautan primer. Ia tidak menjanjikan hasil penerimaan atau menyamarkan informasi yang belum terverifikasi.", "Membuat hook yang melebihkan bukti. Klaim kreatif tetap harus dapat ditelusuri dan tidak menipu pembaca.", ["Janji dapat dipenuhi", "Sumber primer", "Tidak ada klaim hasil pasti"]),
  9014: dive("Contoh kerja: constraints jadi brief", "Brief menyebut kata yang harus dihindari, batas visual, izin aset, teks alternatif, dan siapa yang menyetujui. Batas ini membuat hasil AI lebih konsisten dan aman direview.", "Memberi prompt panjang tanpa brief. Prompt tidak menggantikan keputusan editorial, rights, dan accessibility.", ["Tone dan fakta", "Hak/izin aset", "Review owner dan accessibility"]),
  9144: dive("Contoh kerja: paket transparan", "Capstone memiliki brief, kalender, draf, catatan review, daftar aset berizin, dan provenance note yang menyatakan peran AI. Pembaca dapat membedakan fakta, kreativitas, dan keputusan manusia.", "Menganggap kredit 'dibuat dengan AI' sudah cukup. Transparansi yang berguna menyebut sumber, izin, perubahan signifikan, dan cara mengoreksi.", ["Brief ke output tersambung", "Aset berizin", "Provenance dapat dibaca"]),
  9145: dive("Contoh kerja: review sebelum distribusi", "Sebelum tayang, editor memeriksa klaim faktual, alt text, consent narasumber, dan tautan. Bila fakta belum terkonfirmasi, konten ditahan atau diubah menjadi pertanyaan terbuka.", "Menunda review sampai setelah publikasi. Kecepatan bukan alasan untuk melewati consent atau menyebarkan informasi yang belum pasti.", ["Fakta dan sumber", "Consent/rights", "Jalur koreksi setelah publikasi"]),
};

export const priorityIntensiveDeepeningCount = Object.keys(priorityIntensiveDeepening).length;
