import type { Material, MaterialLevel, QuizQuestion } from "./materials";
import type { SpecializationId } from "./specializations";
import { specializationMeta } from "./specializations";
import { cloudIntensiveMaterials } from "./cloudIntensiveMaterials";
import { dataIntensiveMaterials } from "./dataIntensiveMaterials";
import { aiProductIntensiveMaterials } from "./aiProductIntensiveMaterials";
import { automationIntensiveMaterials } from "./automationIntensiveMaterials";
import { creativeIntensiveMaterials } from "./creativeIntensiveMaterials";

type Seed = { id: number; title: string; level: MaterialLevel; minutes: number; focus: string; analogy: string; story: string; practice: string; guardrail: string; check: string };

const resources: Record<SpecializationId, NonNullable<Material["resources"]>> = {
  "ai-engineering": [{ label: "O'Reilly: AI Engineering — Chip Huyen", url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/", note: "Foundation models, evaluation, prompting, RAG/agents, adaptation, inference, dan architecture." }],
  "cloud-devops": [{ label: "AWS Well-Architected (resmi)", url: "https://aws.amazon.com/architecture/well-architected/", note: "Trade-off keamanan, reliabilitas, performa, biaya, operasi, dan sustainability." }, { label: "GitHub Actions (resmi)", url: "https://docs.github.com/actions", note: "Workflow CI/CD, runner, secrets, dan deployment." }, { label: "Prometheus Overview (resmi)", url: "https://prometheus.io/docs/introduction/overview/", note: "Metrik, alerting, dan observability." }],
  "data-engineering": [{ label: "pandas Documentation (resmi)", url: "https://pandas.pydata.org/docs/", note: "Dasar analisis dan manipulasi data tabular." }, { label: "Apache Airflow Documentation (resmi)", url: "https://airflow.apache.org/docs/", note: "Workflow data yang dijadwalkan dan dipantau." }, { label: "Looker Studio Documentation (resmi)", url: "https://docs.cloud.google.com/data-studio", note: "Dashboard dan laporan data." }],
  "ai-product": [{ label: "Google PAIR Guidebook (resmi)", url: "https://pair.withgoogle.com/guidebook/", note: "Desain produk AI yang human-centered, dapat dikendalikan, dan dapat dipercaya." }, { label: "NIST AI RMF (resmi)", url: "https://www.nist.gov/itl/ai-risk-management-framework", note: "Kerangka sukarela untuk mengelola risiko AI." }],
  automation: [{ label: "n8n Workflows (resmi)", url: "https://docs.n8n.io/build/understand-workflows/", note: "Konsep node, trigger, execution, dan debugging workflow." }, { label: "Zapier Workflow Guide (resmi)", url: "https://zapier.com/blog/get-started-with-zapier/", note: "Trigger, action, mapping data, test, dan publish." }, { label: "Make Platform (resmi)", url: "https://www.make.com/en", note: "Orkestrasi visual automation dan AI agent." }],
  "ai-security": [{ label: "NIST AI RMF (resmi)", url: "https://www.nist.gov/itl/ai-risk-management-framework", note: "Govern, map, measure, dan manage risiko AI." }, { label: "OWASP GenAI LLM Top 10 (resmi)", url: "https://genai.owasp.org/resource/owasp-genai-llm-top-10-2026/", note: "Risiko dan mitigasi penting pada LLM serta aplikasi GenAI." }],
  "creative-ai": [{ label: "Adobe Content Credentials (resmi)", url: "https://helpx.adobe.com/creative-cloud/apps/adobe-content-authenticity/content-credentials/overview.html", note: "Transparansi asal dan riwayat pembuatan konten." }, { label: "WIPO: AI & Intellectual Property", url: "https://www.wipo.int/en/web/frontier-technologies/artificial-intelligence/index", note: "Hak, atribusi, dan isu IP pada AI." }, { label: "U.S. Copyright Office AI", url: "https://www.copyright.gov/ai/", note: "Sumber kebijakan dan laporan AI serta copyright." }],
};

function makeQuiz(title: string, check: string, practice: string): QuizQuestion[] {
  return [{ question: `Apa fokus utama saat mempelajari “${title}”?`, options: [check, "Menghafal tool tanpa memahami tujuan", "Melewati proses pengecekan"], answer: 0, explanation: `Benar. Materi ini menekankan ${check.toLowerCase()}.` }, { question: "Langkah praktik yang paling sehat adalah…", options: [practice, "Menyalin konfigurasi tanpa menguji", "Menambah semua fitur sekaligus"], answer: 0, explanation: "Mulai kecil, uji hasilnya, lalu perbaiki berdasarkan bukti." }];
}

function makeLessons(track: SpecializationId, seeds: Seed[]): Material[] {
  const meta = specializationMeta[track];
  return seeds.map((seed) => ({ id: seed.id, title: seed.title, category: meta.label, specialization: track, level: seed.level, minutes: seed.minutes, emoji: meta.emoji, summary: seed.focus, analogy: seed.analogy, sections: [{ heading: "Peta konsep", body: `${seed.focus} Dalam jalur ${meta.shortLabel}, tujuanmu bukan sekadar memakai istilah teknis, tetapi memahami keputusan apa yang sedang dibuat dan sinyal apa yang membuktikan keputusan itu bekerja.` }, { heading: "Cerita kecil", body: seed.story }, { heading: "Coba di dunia nyata", body: `${seed.practice}. Catat apa yang terjadi sebelum dan sesudah langkahmu agar prosesnya dapat diulang, dijelaskan, atau diperbaiki oleh orang lain.` }, { heading: "Ringkasnya", body: `${seed.title} membantu kamu membangun kebiasaan kerja yang lebih terstruktur. ${seed.guardrail}` }], resources: resources[track], quiz: makeQuiz(seed.title, seed.check, seed.practice) }));
}

const cloudLessons: Seed[] = [
  { id: 40, title: "Peta Cloud: Dari Laptop ke Layanan AI", level: "Pemula", minutes: 10, focus: "Cloud memindahkan beban aplikasi dari satu laptop ke layanan yang dapat diakses, diukur, dan dirawat oleh lebih banyak orang.", analogy: "Seperti membuka kedai dari dapur rumah: kamu perlu jalur pelanggan, meja kerja, gudang, kunci, dan aturan ketika listrik mati.", story: "Raka menjalankan chatbot di laptop dan semuanya tampak baik sampai temannya mencoba membukanya saat laptop tertutup. Ia lalu menggambar jalur pengguna, aplikasi, model, database, dan tempat rahasia disimpan sebelum memilih layanan cloud.", practice: "Gambarkan lima kotak: pengguna, pintu masuk, aplikasi, data, dan layanan AI; hubungkan panah request-nya", guardrail: "Jangan memilih layanan hanya karena namanya populer; mulai dari kebutuhan, risiko, dan biaya yang sanggup kamu pantau.", check: "memetakan komponen dan aliran request sebuah layanan" },
  { id: 41, title: "Linux & Terminal untuk Builder AI", level: "Pemula", minutes: 12, focus: "Terminal membantu kamu melihat file, proses, permission, environment, dan log tanpa harus menebak apa yang dilakukan server.", analogy: "Terminal seperti ruang kontrol stasiun: tombolnya ringkas, tetapi satu perintah yang keliru bisa mengubah banyak hal.", story: "Nia panik karena aplikasinya berhenti. Alih-alih memasang ulang semuanya, ia memeriksa folder kerja, membaca log terakhir, lalu melihat proses yang memakai port. Masalahnya ternyata satu variabel environment belum dimuat.", practice: "Buat folder proyek latihan, daftar isinya, buat file catatan, lalu biasakan membaca output perintah sebelum menekan Enter berikutnya", guardrail: "Jangan menyalin perintah destruktif dari internet tanpa memahami path, user, dan akibatnya.", check: "membaca keadaan sistem sebelum mengubahnya" },
  { id: 42, title: "Docker: Mengemas Aplikasi agar Konsisten", level: "Menengah", minutes: 13, focus: "Container membantu aplikasi berjalan dengan dependensi dan konfigurasi yang lebih konsisten dari laptop sampai server.", analogy: "Docker seperti kotak bekal berlabel: isi dan aturan penyimpanannya ikut terbawa, sehingga dapur lain tidak harus menebak resepnya.", story: "Di laptop Dita, aplikasi berjalan; di VPS, versi library berbeda dan gagal. Setelah dependensi dimasukkan ke image, ia dapat menjalankan versi yang sama sambil tetap memisahkan rahasia melalui environment.", practice: "Tulis daftar dependensi aplikasi kecilmu dan bedakan mana yang masuk image, mana yang harus menjadi environment, serta mana yang harus tetap di secret store", guardrail: "Container bukan alasan untuk memasukkan API key ke image atau membuka port tanpa kebutuhan.", check: "membedakan image, container, konfigurasi, dan rahasia" },
  { id: 43, title: "Reverse Proxy, Domain, dan HTTPS", level: "Menengah", minutes: 12, focus: "Reverse proxy mengatur jalur trafik dari domain menuju aplikasi dan membantu menempatkan HTTPS di batas yang tepat.", analogy: "Bayangkan resepsionis gedung: ia menerima tamu di satu pintu, memeriksa tujuan, lalu mengarahkan mereka ke ruangan yang benar.", story: "Saat aplikasi Lila langsung dibuka pada port internal, ia kesulitan memakai domain dan sertifikat. Dengan proxy, satu alamat publik dapat diteruskan ke aplikasi yang tepat tanpa mengekspos semua layanan internal.", practice: "Tulis alur domain → HTTPS → reverse proxy → aplikasi, lalu tandai layanan mana yang seharusnya tidak dapat diakses publik", guardrail: "HTTPS membantu melindungi trafik, tetapi tidak menggantikan autentikasi, validasi input, atau pengelolaan secret.", check: "memahami jalur trafik publik menuju aplikasi" },
  { id: 44, title: "CI/CD: Menguji Sebelum Merilis", level: "Menengah", minutes: 14, focus: "CI/CD membuat perubahan melewati langkah yang konsisten—cek kode, test, build, dan deploy—sebelum menyentuh pengguna.", analogy: "Seperti jalur pemeriksaan bandara: tiap tas melewati pemeriksaan berbeda sebelum boleh masuk pesawat.", story: "Tim Arman sering merilis manual pada Jumat malam. Setelah satu typo merusak halaman utama, mereka membuat workflow yang menjalankan test dan build pada setiap pull request sebelum perubahan dapat dipromosikan.", practice: "Buat urutan empat langkah untuk proyekmu: pemicu perubahan, pemeriksaan otomatis, artefak build, dan keputusan deploy", guardrail: "Jangan menyimpan credential deployment di file workflow atau log; gunakan secret dan akses minimum.", check: "menempatkan test sebelum tahap rilis" },
  { id: 45, title: "Observability: Log, Metrik, dan Alert", level: "Menengah", minutes: 14, focus: "Observability membuat tim dapat melihat gejala, memahami penyebab, dan merespons gangguan berdasarkan data, bukan dugaan.", analogy: "Log adalah buku harian, metrik adalah panel angka, dan alert adalah bel yang berbunyi ketika keadaan butuh perhatian.", story: "Pengguna berkata chatbot lambat. Tanpa data, tim menebak modelnya bermasalah. Setelah melihat metrik latency, mereka menemukan antrean request meningkat tepat ketika satu integrasi eksternal melambat.", practice: "Pilih tiga sinyal layanan: jumlah request, waktu respons, dan error; tulis kapan masing-masing perlu dipantau", guardrail: "Alert yang terlalu banyak membuat orang kebal; pilih alert yang memang membutuhkan tindakan.", check: "membedakan log, metrik, dan alert" },
  { id: 46, title: "Arsitektur Cloud & Batas Biaya", level: "Menengah", minutes: 15, focus: "Arsitektur sehat selalu menimbang keamanan, reliabilitas, performa, operasi, dan biaya—bukan hanya apakah aplikasi berhasil dibuka hari ini.", analogy: "Merancang cloud seperti menyusun anggaran rumah: cadangan membuat lebih aman, tetapi setiap ruang tambahan punya biaya yang harus disadari.", story: "Dua server memang membuat aplikasi lebih tahan gagal, tetapi tagihan juga bertambah. Tim Sari menuliskan target ketersediaan, batas biaya, dan rencana scale sebelum menambah komponen baru.", practice: "Buat tabel kecil berisi komponen, manfaat, risiko jika gagal, dan biaya yang harus dipantau", guardrail: "Gunakan batas budget, tagging, dan review berkala; biaya cloud yang tidak terlihat tetap biaya nyata.", check: "menilai trade-off arsitektur dan biaya" },
  { id: 47, title: "Proyek Mini: Runbook Deploy Agent yang Aman", level: "Lanjut", minutes: 18, focus: "Runbook mengubah pengetahuan deploy yang hanya ada di kepala menjadi langkah teruji untuk rilis, rollback, dan respons gangguan.", analogy: "Runbook adalah kartu prosedur dapur: saat ramai atau ada masalah, tim tidak perlu mengandalkan ingatan saja.", story: "Ketika gateway agent perlu restart, orang pertama yang panik biasanya membuka banyak terminal. Dengan runbook, tim mengikuti checklist: cek status, backup konfigurasi, deploy, smoke test, pantau, lalu rollback jika indikator memburuk.", practice: "Tulis runbook satu halaman dengan prasyarat, langkah deploy, smoke test, sinyal gagal, owner, dan langkah rollback", guardrail: "Runbook yang baik tidak menyertakan secret; ia menunjuk tempat aman untuk mengaksesnya.", check: "mendokumentasikan deploy dan rollback yang dapat diikuti ulang" },
];

const dataLessons: Seed[] = [
  { id: 48, title: "Pertanyaan Data yang Benar", level: "Pemula", minutes: 10, focus: "Analisis yang baik dimulai dari keputusan yang ingin dibantu, bukan dari dashboard yang ingin dibuat.", analogy: "Data seperti senter: ia berguna jika kamu sudah tahu bagian ruangan mana yang ingin dilihat.", story: "Mira ingin tahu mengapa peserta berhenti belajar. Alih-alih langsung membuat dua puluh grafik, ia menulis keputusan yang akan diambil, metrik pendukung, periode waktu, dan batas data yang tersedia.", practice: "Ubah satu pertanyaan kabur menjadi format: keputusan, pengguna, metrik, periode, dan tindakan jika hasilnya tinggi atau rendah", guardrail: "Metrik bukan tujuan itu sendiri; selalu tanyakan keputusan apa yang benar-benar berubah setelah melihatnya.", check: "menghubungkan pertanyaan data dengan keputusan" },
  { id: 49, title: "Membaca Tabel tanpa Tertipu Angka", level: "Pemula", minutes: 11, focus: "Angka hanya bermakna jika pembanding, denominator, periode, dan sumbernya ikut dibaca.", analogy: "Angka tanpa konteks seperti nilai ujian tanpa tahu total soalnya: terlihat jelas, tetapi bisa menyesatkan.", story: "Laporan menyebut pengguna naik 100%. Setelah diperiksa, angka itu berarti dari dua menjadi empat orang. Tim belajar membedakan perubahan persentase, jumlah absolut, dan rentang waktu.", practice: "Ambil satu tabel dan tandai kolom sumber, periode, total pembanding, data kosong, serta angka yang membutuhkan pertanyaan lanjutan", guardrail: "Jangan menyimpulkan sebab-akibat hanya karena dua angka berubah bersama.", check: "memeriksa konteks sebelum menarik kesimpulan" },
  { id: 50, title: "Spreadsheet untuk Data Bersih", level: "Pemula", minutes: 12, focus: "Data bersih memiliki format konsisten, definisi kolom yang jelas, nilai yang dapat ditelusuri, dan kesalahan yang terlihat.", analogy: "Spreadsheet seperti lemari arsip: label yang rapi membuatmu menemukan dokumen tanpa menebak-nebak.", story: "File peserta Rafi punya tanggal dalam tiga format, nama ganda, dan baris kosong. Ia tidak langsung menghitung rata-rata; ia membuat salinan, menamai kolom, menandai duplikasi, dan mencatat aturan pembersihan.", practice: "Buat data dictionary sederhana berisi nama kolom, arti, format, contoh nilai, dan siapa yang memperbarui", guardrail: "Selalu simpan data mentah terpisah dari data yang sudah dibersihkan agar perubahan bisa diperiksa.", check: "membedakan data mentah, data bersih, dan aturan transformasi" },
  { id: 51, title: "SQL: Bertanya ke Database dengan Tertib", level: "Menengah", minutes: 15, focus: "SQL adalah bahasa untuk meminta data secara terstruktur sambil tetap memeriksa filter, agregasi, join, dan hasilnya.", analogy: "SQL seperti daftar belanja yang sangat spesifik: kamu menyebut barang, rak, syarat, dan cara menghitungnya.", story: "Bimo ingin menghitung pengguna aktif. Query pertama menghitung semua baris event dan hasilnya terlalu besar. Ia belajar mendefinisikan pengguna aktif, memilih periode, lalu memakai distinct agar satu orang tidak dihitung berkali-kali.", practice: "Tulis pertanyaan lalu pecah menjadi: tabel sumber, filter waktu, unit yang dihitung, agregasi, dan cara memeriksa sampel hasil", guardrail: "Jangan menjalankan perubahan data pada database produksi saat sedang belajar query; mulailah dari read-only.", check: "menyusun pertanyaan data dengan filter dan agregasi" },
  { id: 52, title: "Statistik Ringkas untuk Keputusan", level: "Menengah", minutes: 13, focus: "Rata-rata, median, persentase, dan sebaran membantu merangkum data, tetapi masing-masing menjawab pertanyaan yang berbeda.", analogy: "Memilih statistik seperti memilih kamera: lensa yang tepat bergantung pada hal yang ingin kamu lihat.", story: "Gaji rata-rata tim terlihat tinggi karena satu nilai ekstrem. Ketika median ditampilkan, gambaran kondisi kebanyakan anggota menjadi lebih jujur.", practice: "Untuk satu kumpulan angka, bandingkan rata-rata dan median, lalu catat apakah ada nilai ekstrem yang mengubah cerita", guardrail: "Ringkasan tidak menggantikan pemeriksaan distribusi dan konteks pengumpulan data.", check: "memilih ringkasan angka sesuai pertanyaan" },
  { id: 53, title: "Dashboard yang Bercerita", level: "Menengah", minutes: 14, focus: "Dashboard yang baik memandu pembaca dari pertanyaan, sinyal utama, sampai tindakan—bukan sekadar memajang semua grafik.", analogy: "Dashboard seperti halaman depan koran: ia memilih informasi paling penting agar pembaca tahu apa yang perlu diperhatikan dulu.", story: "Tim Nara memiliki sepuluh grafik warna-warni tetapi tidak tahu mana yang penting. Mereka memilih tiga metrik inti, memberi judul berupa pertanyaan, menambahkan periode pembanding, dan menulis catatan tindakan.", practice: "Pilih satu grafik dan tulis ulang judulnya sebagai pertanyaan keputusan, lalu tambahkan pembanding waktu yang relevan", guardrail: "Hindari warna yang menyamarkan perbedaan dan grafik yang memotong sumbu tanpa penjelasan.", check: "menghubungkan visual data dengan tindakan" },
  { id: 54, title: "ETL & Orkestrasi Data", level: "Menengah", minutes: 16, focus: "ETL memindahkan dan menyiapkan data melalui tahap extract, transform, dan load; orkestrasi menjaga urutan, jadwal, dan kegagalannya.", analogy: "Seperti jalur produksi: bahan masuk, dibersihkan, dirakit, lalu ditempatkan di gudang dengan catatan jika satu tahap berhenti.", story: "Setiap pagi, laporan Dina salah karena file sumber datang terlambat. Dengan pemahaman orkestrasi, ia menentukan dependency, jadwal, retry, dan pemberitahuan ketika satu task gagal.", practice: "Gambarkan pipeline kecil: sumber, transformasi, tujuan, jadwal, dependency, dan tindakan jika proses gagal", guardrail: "Pipeline yang otomatis tetap butuh observability; kegagalan diam-diam lebih berbahaya daripada kegagalan yang terlihat.", check: "membedakan ETL dan orkestrasi workflow" },
  { id: 55, title: "Proyek Mini: Dashboard Belajar yang Bisa Dipercaya", level: "Lanjut", minutes: 18, focus: "Proyek data yang baik menunjukkan asal data, definisi metrik, langkah pembersihan, visual, dan batas interpretasi.", analogy: "Dashboard akhir seperti resep yang bisa diulang: pembaca bukan hanya melihat hasil, tetapi tahu dari mana bahan dan langkahnya datang.", story: "Reno membuat dashboard kebiasaan belajar. Ia mencatat kapan data dikumpulkan, bagaimana data kosong ditangani, apa arti pengguna aktif, lalu menjelaskan bahwa korelasi jam belajar dan nilai bukan bukti sebab-akibat.", practice: "Buat dashboard satu halaman dengan data dictionary, tiga metrik, satu insight, satu batasan, dan satu tindakan yang dapat diuji", guardrail: "Jangan menampilkan data pribadi orang lain tanpa izin dan tanpa alasan yang jelas.", check: "mendokumentasikan proses analisis dari data sampai insight" },
];

const productLessons: Seed[] = [
  { id: 56, title: "Memilih Masalah yang Layak Dibantu AI", level: "Pemula", minutes: 11, focus: "Produk AI dimulai dari masalah pengguna yang nyata; tidak semua masalah membutuhkan model atau agent.", analogy: "AI seperti alat tukang: palu berguna untuk paku, tetapi bukan alasan untuk memukul semua benda.", story: "Sebuah tim ingin memakai AI untuk semua tiket bantuan. Setelah melihat pola, mereka menemukan sebagian besar pertanyaan dapat diselesaikan dengan artikel yang lebih jelas, sedangkan AI berguna untuk merangkum kasus panjang.", practice: "Tulis masalah, siapa yang terdampak, proses saat ini, kegagalan yang terjadi, dan alasan AI mungkin atau tidak mungkin membantu", guardrail: "Jangan mulai dari model; mulai dari dampak pengguna dan pilihan paling sederhana yang aman.", check: "membedakan masalah AI dari masalah proses atau UX biasa" },
  { id: 57, title: "Riset Pengguna & Problem Statement", level: "Pemula", minutes: 12, focus: "Problem statement yang baik menyatukan pengguna, konteks, hambatan, dan hasil yang ingin dicapai tanpa langsung mengunci solusi.", analogy: "Seperti dokter yang bertanya gejala dan kebiasaan sebelum menulis resep.", story: "Tim Damar mengira pengguna ingin chatbot lebih cepat. Dari wawancara singkat, ternyata pengguna paling kesulitan mengetahui dokumen mana yang dipakai jawaban. Masalahnya bukan kecepatan, tetapi kepercayaan.", practice: "Buat problem statement dengan format: pengguna, saat sedang, membutuhkan, karena, sehingga", guardrail: "Pisahkan kutipan pengguna, asumsi tim, dan keputusan produk agar tidak tercampur.", check: "menulis masalah dari sudut pandang pengguna" },
  { id: 58, title: "User Flow untuk Fitur AI", level: "Pemula", minutes: 12, focus: "User flow AI perlu memperlihatkan input, proses, hasil, kontrol, fallback, dan apa yang terjadi ketika sistem tidak yakin.", analogy: "Seperti peta perjalanan di taman bermain: bukan hanya jalan masuk, tetapi juga jalur keluar ketika wahana ditutup.", story: "Pada fitur ringkasan, Tara menambahkan tombol edit, sumber, dan buat ulang. Ketika model tidak mendapat konteks cukup, aplikasi meminta pengguna menambahkan dokumen alih-alih membuat jawaban palsu.", practice: "Gambarkan alur dari input pengguna sampai hasil; tambahkan satu cabang untuk hasil tidak yakin atau gagal", guardrail: "Jangan menyembunyikan kegagalan AI di balik jawaban yang terdengar pasti.", check: "menyertakan fallback dan kontrol pengguna dalam user flow" },
  { id: 59, title: "PRD AI: Batasan, Data, dan Acceptance Criteria", level: "Menengah", minutes: 15, focus: "PRD AI mengubah ide menjadi ruang lingkup yang dapat dibangun, diuji, dan dievaluasi oleh tim lintas fungsi.", analogy: "PRD seperti denah renovasi: menjelaskan ruangan yang dibangun, batas pekerjaan, dan tanda bahwa hasilnya layak dipakai.", story: "Reno menulis 'buat chatbot pintar' dan tim menafsirkan berbeda. Setelah PRD diperbaiki, ada target pengguna, sumber data, batas tindakan, contoh kegagalan, dan acceptance criteria yang bisa diuji.", practice: "Gunakan PRD Maker untuk membuat problem, audience, data yang boleh dipakai, larangan, contoh sukses, dan contoh gagal", guardrail: "Acceptance criteria tidak boleh hanya 'jawaban bagus'; buat kondisi yang dapat diamati atau diukur.", check: "menuliskan batasan dan kriteria penerimaan fitur AI" },
  { id: 60, title: "Metrik Produk AI: Benar Saja Tidak Cukup", level: "Menengah", minutes: 13, focus: "Produk AI perlu menilai kualitas, waktu, biaya, keberhasilan tugas, dan kepercayaan pengguna secara bersama.", analogy: "Nilai ujian tidak cukup menggambarkan sekolah; kamu juga perlu melihat kehadiran, pemahaman, dukungan, dan pengalaman belajar.", story: "Model klasifikasi tim Eva sangat akurat, tetapi pengguna berhenti memakainya karena hasilnya datang terlalu lambat. Setelah latency dan completion rate ditambahkan, prioritas perbaikan berubah.", practice: "Pilih satu fitur lalu buat kartu metrik: kualitas, latency, biaya, completion, feedback, dan ambang yang memicu investigasi", guardrail: "Metrik yang mudah diukur belum tentu mewakili manfaat bagi pengguna.", check: "menggabungkan kualitas teknis dan dampak produk" },
  { id: 61, title: "Human-in-the-Loop & UX Kepercayaan", level: "Menengah", minutes: 14, focus: "Kontrol manusia yang tepat membuat pengguna dapat meninjau, mengoreksi, dan memahami kapan AI membantu serta kapan ia perlu berhenti.", analogy: "Seperti cruise control: kendaraan membantu mempertahankan kecepatan, tetapi pengemudi tetap memegang tanggung jawab dan dapat mengambil alih.", story: "Pada fitur kirim email otomatis, tim Farah mengubah aksi menjadi draf yang harus disetujui. Pengguna merasa lebih berani memakai fitur karena ada preview, sumber, dan tombol batalkan.", practice: "Tandai tindakan mana yang cukup dibuat draf, perlu approval, atau boleh otomatis; tulis alasan dampaknya", guardrail: "Semakin besar dampak tindakan, semakin jelas kontrol, audit, dan jalur pembatalannya.", check: "menentukan titik review manusia berdasarkan dampak" },
  { id: 62, title: "Evaluasi dan Iterasi Fitur AI", level: "Menengah", minutes: 15, focus: "Evaluasi membuat tim belajar dari contoh nyata melalui dataset uji, rubrik, feedback pengguna, dan keputusan rilis yang eksplisit.", analogy: "Seperti latihan tanding: kamu tidak cukup tahu skor akhir; kamu perlu melihat pertandingan mana yang gagal dan mengapa.", story: "Sebelum merilis assistant, tim Hafiz mengumpulkan 30 pertanyaan representatif. Mereka membuat rubrik grounded, berguna, aman, dan jelas, lalu menemukan banyak jawaban gagal ketika pertanyaan ambigu.", practice: "Kumpulkan sepuluh contoh representative, tulis rubrik 1–4, dan catat keputusan setelah melihat pola gagal", guardrail: "Jangan menggunakan data pengguna sensitif sebagai dataset uji tanpa izin dan perlindungan yang sesuai.", check: "menggunakan rubrik dan contoh representatif untuk iterasi" },
  { id: 63, title: "Proyek Mini: Product Brief AI yang Siap Dibangun", level: "Lanjut", minutes: 20, focus: "Capstone produk menyatukan masalah, user flow, data, metrik, risiko, dan eksperimen pertama dalam satu dokumen yang dapat dibicarakan tim.", analogy: "Seperti pitch proyek yang tidak hanya menjual ide, tetapi juga menunjukkan cara mengukurnya dan pagar pengamannya.", story: "Maya menyusun brief asisten riset: ia menjelaskan pengguna, sumber tepercaya, kapan jawaban harus meminta klarifikasi, metrik keberhasilan, dan bagaimana pengguna memberi feedback.", practice: "Buat satu brief menggunakan PRD Maker; sertakan satu risiko, satu fallback, tiga metrik, dan rencana evaluasi sebelum rilis", guardrail: "Brief yang baik berani menyatakan apa yang tidak akan dilakukan fitur pada versi pertama.", check: "menggabungkan kebutuhan produk, risiko, dan ukuran keberhasilan" },
];

const automationLessons: Seed[] = [
  { id: 64, title: "Memilih Tugas yang Layak Diotomasi", level: "Pemula", minutes: 10, focus: "Otomasi paling berguna untuk tugas yang berulang, punya aturan jelas, dan memiliki dampak yang aman ketika dijalankan otomatis.", analogy: "Seperti memasang rice cooker untuk nasi yang sama setiap hari, bukan menyerahkan menu pesta yang rumit tanpa pengawasan.", story: "Vino ingin mengotomasi semua inbox. Setelah dipetakan, ia memilih mulai dari memindahkan formulir yang lengkap ke spreadsheet, bukan membalas keluhan pelanggan secara otomatis.", practice: "Nilai satu tugas dari frekuensi, aturan, dampak salah, data yang diperlukan, dan apakah manusia perlu menyetujui hasil", guardrail: "Jika salah satu kesalahan bisa merugikan orang, tambahkan review manusia atau jangan otomatiskan dulu.", check: "memilih kandidat otomasi berdasarkan risiko dan nilai" },
  { id: 65, title: "Trigger, Action, dan Data Mapping", level: "Pemula", minutes: 12, focus: "Workflow biasanya dimulai dari trigger, memproses data, lalu menjalankan satu atau beberapa action yang dapat diuji.", analogy: "Seperti bel pintu dan daftar tugas: saat bel berbunyi, orang yang tepat mengambil catatan lalu melakukan tindakan yang sudah disepakati.", story: "Saat formulir masuk, workflow Sasa membaca nama dan topik, lalu membuat baris pada tabel. Ketika kolom email kosong, workflow tidak melanjutkan dan mengirim notifikasi untuk diperiksa.", practice: "Tulis satu kalimat WHEN–DO dan buat tabel data: nama field trigger, tujuan field action, dan nilai yang wajib ada", guardrail: "Tes mapping dengan data fiktif yang mudah dikenali, bukan data pribadi nyata.", check: "menghubungkan event pemicu, data, dan tindakan" },
  { id: 66, title: "API, Webhook, dan Credential dengan Aman", level: "Menengah", minutes: 14, focus: "API memberi cara aplikasi bertukar data, webhook mengirim sinyal event, dan credential menentukan siapa yang diizinkan melakukan tindakan.", analogy: "API seperti loket layanan, webhook seperti bel yang memberi tahu ada kejadian, dan credential seperti kartu akses yang harus dijaga.", story: "Workflow Rani gagal karena token ditaruh di kolom teks biasa. Setelah memakai credential store, ia dapat menghubungkan aplikasi tanpa menyebarkan key ke screenshot atau template workflow.", practice: "Gambarkan aplikasi pengirim, webhook atau API, credential, payload, dan aplikasi penerima untuk satu alur sederhana", guardrail: "Jangan pernah menempel API key di prompt, chat, URL publik, atau repository.", check: "membedakan peran API, webhook, dan credential" },
  { id: 67, title: "Kondisi, Cabang, dan Error Handling", level: "Menengah", minutes: 14, focus: "Workflow yang sehat merencanakan jalur normal, kondisi pengecualian, retry, dan pemberitahuan ketika data atau layanan tidak sesuai harapan.", analogy: "Seperti rambu jalan: jalur utama jelas, tetapi ada juga petunjuk jika jalan ditutup atau bahan bakar hampir habis.", story: "Alur Faris gagal setiap ada file tanpa judul. Ia menambahkan kondisi untuk memberi nama default, cabang review jika metadata penting kosong, dan notifikasi jika layanan tujuan sedang down.", practice: "Tambahkan pada workflow-mu: satu kondisi validasi, satu jalur review, satu aksi retry, dan satu notifikasi pemilik", guardrail: "Retry tanpa batas dapat menggandakan tindakan atau biaya; selalu tentukan batas dan idempotensi bila memungkinkan.", check: "merancang jalur gagal dan pemulihan workflow" },
  { id: 68, title: "Human Review: Titik Berhenti yang Sehat", level: "Menengah", minutes: 12, focus: "Human review menjaga otomasi tetap berguna ketika output bernuansa, tindakan berdampak, atau data tidak cukup untuk mengambil keputusan aman.", analogy: "Seperti editor koran: mesin dapat menyusun draf, tetapi publikasi tetap membutuhkan mata manusia untuk konteks dan tanggung jawab.", story: "Asisten otomatis membuat balasan pelanggan. Tim memilih agar pesan dengan sentimen negatif, permintaan refund, atau informasi sensitif berubah menjadi draft yang menunggu persetujuan.", practice: "Buat daftar tiga kondisi yang memicu review: risiko tinggi, keyakinan rendah, atau aksi yang sulit dibatalkan", guardrail: "Tombol approval harus menjelaskan tindakan dan data apa yang akan dipakai, bukan hanya meminta klik setuju.", check: "menentukan kapan workflow harus berhenti untuk manusia" },
  { id: 69, title: "Dokumentasi & Observability Workflow", level: "Menengah", minutes: 13, focus: "Workflow yang dapat dirawat mempunyai nama jelas, tujuan, owner, input-output, log execution, dan cara diagnosis ketika gagal.", analogy: "Seperti label kabel di studio: masalah jauh lebih mudah dilacak ketika setiap sambungan punya nama dan fungsi.", story: "Setelah tiga orang mengubah automation yang sama, tidak ada yang tahu mengapa pesan ganda terkirim. Mereka lalu menambahkan deskripsi, owner, changelog singkat, dan dashboard execution.", practice: "Dokumentasikan satu workflow dengan tujuan, trigger, input, output, credential yang dipakai secara nama saja, owner, dan tanda kegagalan", guardrail: "Log perlu cukup untuk diagnosis tanpa menyalin data sensitif atau token ke tempat yang tidak perlu.", check: "membuat workflow dapat ditelusuri dan dirawat" },
  { id: 70, title: "Agentic Automation tanpa Kehilangan Kontrol", level: "Lanjut", minutes: 16, focus: "Agentic automation menambah kemampuan memilih langkah, tetapi tetap memerlukan batas tool, scope tugas, budget, dan verifikasi hasil.", analogy: "Seperti memberi asisten daftar tugas dan kartu akses terbatas, bukan kunci master ke seluruh gedung.", story: "Agent Nina dapat mencari dokumen dan membuat draf, tetapi tidak boleh mengirim email atau mengubah database tanpa approval. Dengan batas ini, tim bisa menikmati bantuan tanpa menyerahkan kendali penuh.", practice: "Buat tabel tool agent: aksi yang boleh otomatis, aksi yang perlu approval, aksi yang dilarang, budget, dan cara menghentikan eksekusi", guardrail: "Jangan menganggap agent aman hanya karena prompt-nya panjang; kontrol teknis dan izin tetap diperlukan.", check: "memberi batas kemampuan agent berdasarkan dampak" },
  { id: 71, title: "Proyek Mini: Asisten Ringkasan Meeting", level: "Lanjut", minutes: 18, focus: "Capstone automation merangkai trigger, transkrip, ringkasan, review, dan distribusi menjadi alur yang transparan bagi peserta meeting.", analogy: "Seperti sekretaris rapat yang menyiapkan draf notulen, tetapi peserta tetap menyetujui keputusan sebelum catatan dibagikan.", story: "Setelah meeting selesai, workflow menaruh transkrip di folder, meminta AI membuat draf ringkasan, lalu mengirimkannya ke owner untuk diedit sebelum disebarkan.", practice: "Buat blueprint alur meeting dengan trigger, input, prompt, output draft, approval, penyimpanan, dan notifikasi", guardrail: "Pastikan peserta tahu rekaman atau transkrip digunakan, dan jangan mengirim ringkasan sensitif ke kanal terbuka.", check: "merangkai workflow AI dengan approval sebelum distribusi" },
];

const securityLessons: Seed[] = [
  { id: 72, title: "Peta Ancaman Digital untuk Builder AI", level: "Pemula", minutes: 11, focus: "Keamanan dimulai dengan mengenali aset yang ingin dilindungi, pihak yang mungkin menyalahgunakan, dan dampak jika sebuah kontrol gagal.", analogy: "Seperti menjaga rumah: sebelum membeli alat, kamu perlu tahu pintu mana, barang apa, dan risiko siapa yang sedang dipertimbangkan.", story: "Tim kecil ingin membuat bot. Mereka awalnya hanya memikirkan fitur, lalu memetakan API key, data pengguna, akun admin, dan endpoint publik. Dari peta itu, mereka melihat satu credential dapat membuka terlalu banyak akses.", practice: "Buat daftar aset, ancaman, dampak, dan kontrol sederhana untuk satu proyek belajar", guardrail: "Threat model bukan ramalan sempurna; ia alat untuk menemukan risiko lebih awal dan memilih prioritas.", check: "menghubungkan aset, ancaman, dampak, dan kontrol" },
  { id: 73, title: "Password, MFA, dan Manajemen Sesi", level: "Pemula", minutes: 12, focus: "Akun lebih aman ketika password unik, faktor tambahan, dan sesi perangkat dikelola secara sadar.", analogy: "Password adalah kunci, MFA adalah pemeriksaan kedua, dan sesi adalah kartu akses yang tetap berlaku setelah kamu masuk.", story: "Luna memakai password sama di banyak situs. Ketika satu layanan bocor, akun lain ikut berisiko. Ia lalu memakai password manager, mengaktifkan MFA, dan memeriksa perangkat yang masih memiliki sesi aktif.", practice: "Pilih satu akun penting lalu periksa password unik, MFA, opsi recovery, dan perangkat yang masih masuk", guardrail: "Jangan pernah membagikan kode MFA, password, atau recovery code melalui chat dan screenshot.", check: "membedakan password, MFA, dan sesi aktif" },
  { id: 74, title: "API Key & Secret Hygiene", level: "Pemula", minutes: 13, focus: "Secret harus disimpan, dibatasi, dirotasi, dan dipantau agar kebocoran satu nilai tidak menjadi akses tanpa batas.", analogy: "API key seperti kartu debit: ia memberi kemampuan bertindak, jadi tidak boleh ditempel di papan pengumuman atau difoto sembarangan.", story: "Key demo masuk ke repository publik. Walau cepat dihapus, log dan cache mungkin sudah menyimpan salinannya. Tim mencabut key, membuat key baru dengan scope lebih kecil, lalu memindahkan konfigurasi ke secret manager.", practice: "Audit satu proyek: cari secret pada file konfigurasi, buat daftar lokasi aman, dan tulis langkah rotasi jika nilai bocor", guardrail: "Mengganti tampilan key di UI tidak mencabut akses; rotasi dari penyedia layanan tetap diperlukan.", check: "menyimpan dan merotasi secret secara aman" },
  { id: 75, title: "Data Sensitif dan Batas Prompt", level: "Pemula", minutes: 12, focus: "Tidak semua data boleh dimasukkan ke prompt; klasifikasi data membantu menentukan apa yang boleh, perlu disamarkan, atau tidak boleh dikirim.", analogy: "Seperti memilih barang yang aman dibawa ke ruang publik: tidak semua dokumen dari laci pribadi boleh dibacakan keras-keras.", story: "Andi ingin merangkum kontrak pelanggan dengan tool umum. Ia berhenti sejenak, melihat ada alamat, nomor identitas, dan harga internal, lalu memakai contoh yang sudah disamarkan serta kebijakan yang disetujui.", practice: "Buat tiga kolom: publik, internal, sensitif; isi contoh data dari pekerjaan atau proyekmu dan pilih perlakuannya", guardrail: "Penghapusan nama saja belum tentu cukup jika detail lain masih dapat mengidentifikasi seseorang.", check: "mengklasifikasikan data sebelum memasukkannya ke AI" },
  { id: 76, title: "Prompt Injection & Output yang Tidak Tepercaya", level: "Menengah", minutes: 15, focus: "Input eksternal dan output LLM harus diperlakukan sebagai data tidak tepercaya, terutama sebelum memicu tool atau kode.", analogy: "Seperti catatan asing yang ditemukan di kotak surat: mungkin berguna, tetapi tidak boleh langsung dianggap instruksi resmi.", story: "RAG assistant membaca halaman yang berisi teks 'abaikan instruksi sebelumnya'. Karena aplikasi tidak memisahkan konten sumber dari instruksi sistem, assistant mencoba mengikuti teks tersebut. Tim lalu membatasi tool dan memvalidasi tindakan di aplikasi.", practice: "Tandai input mana yang datang dari pengguna, dokumen, atau web; tulis validasi apa yang harus dilakukan aplikasi sebelum aksi", guardrail: "Prompt yang lebih panjang bukan pertahanan tunggal; gunakan izin minimum, validasi server, dan review pada tindakan penting.", check: "memperlakukan input serta output LLM sebagai data tidak tepercaya" },
  { id: 77, title: "Hak Akses, Least Privilege, dan Audit", level: "Menengah", minutes: 13, focus: "Least privilege memberi setiap orang atau sistem hanya izin yang dibutuhkan untuk tugasnya, lalu audit membantu melihat siapa melakukan apa.", analogy: "Seperti kartu akses kantor: petugas gudang tidak memerlukan kunci ruang keuangan untuk menyelesaikan pekerjaannya.", story: "Bot laporan diberi akses admin database demi kemudahan. Ketika bug terjadi, risiko tindakan tak sengaja menjadi besar. Tim mengganti credential menjadi read-only dan mencatat perubahan akses.", practice: "Daftar peran dalam proyekmu lalu tulis aksi yang benar-benar diperlukan; hapus akses yang tidak punya alasan", guardrail: "Akses sementara tetap perlu tanggal kadaluarsa dan peninjauan, bukan dibiarkan selamanya.", check: "menerapkan izin minimum berdasarkan tugas" },
  { id: 78, title: "Risiko Agent: Excessive Agency & Tool Safety", level: "Lanjut", minutes: 16, focus: "Agent yang dapat memakai tool perlu scope, approval, budget, timeout, dan kill switch agar otonomi tidak berubah menjadi tindakan berisiko.", analogy: "Seperti memberi asisten tugas belanja dengan daftar dan batas uang, bukan kartu tanpa limit serta izin membeli apa pun.", story: "Agent proyek dapat mengirim email dan menghapus file. Alih-alih mengaktifkan semuanya, tim membatasi agent pada draft, memerlukan approval untuk send, dan melarang operasi delete sampai ada sandbox serta audit log.", practice: "Buat matriks tool: baca, tulis draft, kirim, ubah data, hapus; tentukan permission dan approval untuk masing-masing", guardrail: "Otonomi agent harus naik bertahap setelah bukti evaluasi, bukan langsung di produksi.", check: "membatasi tool agent berdasarkan dampak tindakan" },
  { id: 79, title: "Proyek Mini: Security Checklist untuk Fitur AI", level: "Lanjut", minutes: 19, focus: "Security checklist mengubah konsep risiko menjadi pemeriksaan yang dapat dilakukan sebelum dan setelah fitur AI dirilis.", analogy: "Seperti checklist sebelum pesawat lepas landas: tidak menjamin tidak ada masalah, tetapi membuat langkah penting tidak mudah terlewat.", story: "Sebelum demo, tim membuat checklist: secret tidak ada di kode, data sensitif memiliki aturan, tool berisiko punya approval, log tidak menyimpan token, dan ada contact person jika insiden terjadi.", practice: "Buat checklist sepuluh item untuk satu fitur AI; pilih satu item yang akan diuji sekarang dan satu yang perlu owner jelas", guardrail: "Checklist perlu diperbarui setelah insiden atau perubahan produk, bukan disimpan sebagai dokumen mati.", check: "mengubah threat model menjadi kontrol yang bisa diperiksa" },
];

const creativeLessons: Seed[] = [
  { id: 80, title: "Sistem Konten: Tujuan, Audiens, dan Batas Brand", level: "Pemula", minutes: 10, focus: "Sistem konten menyatukan tujuan, audiens, suara, format, dan batas agar produksi dengan AI tidak menjadi tumpukan draft acak.", analogy: "Seperti kompas dan peta perjalanan: ide bisa banyak, tetapi arah membuat semua pilihan tetap menuju tempat yang sama.", story: "Konten tim Lala terasa tidak konsisten karena setiap prompt dimulai dari nol. Mereka menulis satu halaman tentang audiens, janji brand, gaya bahasa, kata yang dihindari, dan tujuan tiap format.", practice: "Buat brand brief ringkas: audiens, tujuan, nada, tiga hal yang selalu ada, dan tiga hal yang dihindari", guardrail: "Brand guideline tidak boleh dipakai untuk meniru identitas atau gaya personal kreator lain tanpa izin.", check: "membuat batas kreatif yang konsisten" },
  { id: 81, title: "Prompt Kreatif yang Bisa Diiterasi", level: "Pemula", minutes: 12, focus: "Prompt kreatif yang baik menyimpan keputusan tentang subjek, tujuan, gaya, komposisi, batasan, dan versi agar hasil dapat dibandingkan.", analogy: "Seperti brief pemotretan: bukan hanya 'buat foto bagus', tetapi siapa subjeknya, suasananya, sudutnya, dan untuk media apa.", story: "Faris menyimpan prompt panjang yang tidak dapat diulang. Ia lalu membagi prompt menjadi blok tujuan, subjek, mood, format, negative constraint, dan nomor versi sehingga setiap iterasi jelas alasannya.", practice: "Tulis prompt dalam enam blok dan ubah hanya satu variabel pada iterasi berikutnya; catat apa yang berubah", guardrail: "Hindari meminta sistem meniru seniman hidup atau menggunakan wajah/identitas orang tanpa hak yang jelas.", check: "mengiterasi prompt melalui perubahan yang terkontrol" },
  { id: 82, title: "Editorial Workflow: Ide ke Draft", level: "Pemula", minutes: 13, focus: "Workflow editorial memisahkan ideasi, riset, outline, draft, edit, fact-check, dan persetujuan agar AI tidak melewati tanggung jawab manusia.", analogy: "Seperti dapur restoran: bahan datang, disiapkan, dimasak, dicicipi, lalu disajikan—setiap tahap punya tujuan berbeda.", story: "Artikel Bagas terdengar lancar tetapi memiliki sumber keliru. Ia mengubah alurnya: AI hanya membantu ide dan outline, sementara klaim diberi sumber, editor memeriksa fakta, dan penulis menyetujui versi akhir.", practice: "Gambarkan workflow satu konten dari ide sampai publikasi dan tandai siapa yang bertanggung jawab pada fakta serta approval", guardrail: "Jangan menganggap teks yang rapi otomatis benar atau siap dipublikasikan.", check: "memisahkan tahap kreatif, verifikasi, dan approval" },
  { id: 83, title: "Visual Direction & Brief yang Jelas", level: "Pemula", minutes: 12, focus: "Arahan visual mengubah rasa abstrak menjadi keputusan tentang pesan, hierarki, palet, komposisi, format, dan aksesibilitas.", analogy: "Seperti memberi petunjuk dekorasi ruangan: suasana saja tidak cukup tanpa ukuran, fungsi, warna, dan batas ruang.", story: "Tim meminta 'visual futuristik' dan menerima hasil yang berbeda-beda. Setelah brief memuat audiens, tujuan, rasio, warna, kontras, objek wajib, dan objek terlarang, iterasi menjadi lebih cepat.", practice: "Buat visual brief dengan tujuan, format, mood, palet, hierarki teks, elemen wajib, dan elemen yang harus dihindari", guardrail: "Pastikan teks tetap terbaca dan kontras cukup; estetika tidak boleh mengalahkan aksesibilitas.", check: "menerjemahkan tujuan komunikasi menjadi arahan visual" },
  { id: 84, title: "Audio dan Video: Storyboard sebelum Generate", level: "Menengah", minutes: 14, focus: "Storyboard memecah ide audio atau video menjadi beat, scene, narasi, visual, durasi, dan titik review sebelum aset dibuat.", analogy: "Seperti komik kasar sebelum animasi: cerita diuji lebih murah sebelum waktu habis pada produksi.", story: "Video promosi Rika terasa cantik tetapi membingungkan. Ia lalu menulis lima scene: masalah, konteks, solusi, bukti, ajakan; setiap scene punya durasi dan teks yang harus muncul.", practice: "Buat storyboard lima scene dengan tujuan, visual, suara atau teks, durasi, dan cara memeriksa apakah scene bekerja", guardrail: "Gunakan audio, wajah, atau suara sintetis dengan disclosure dan hak penggunaan yang jelas.", check: "merencanakan urutan cerita sebelum produksi aset" },
  { id: 85, title: "Hak Cipta, Likeness, dan Izin", level: "Menengah", minutes: 15, focus: "AI tidak menghapus kebutuhan untuk menghormati hak cipta, merek, kemiripan orang, izin penggunaan, serta hukum yang dapat berbeda antarwilayah.", analogy: "Seperti meminjam karya dari perpustakaan: akses terhadap sesuatu tidak otomatis memberi hak untuk menyalin atau mengakuinya milik sendiri.", story: "Seorang kreator ingin membuat iklan bergaya artis tertentu dan memakai foto pelanggan tanpa persetujuan. Tim berhenti, mengecek lisensi, meminta izin, dan memilih referensi visual yang sah serta transparan.", practice: "Untuk satu aset, tulis siapa pembuatnya, sumbernya, lisensinya, apakah ada wajah/suara orang, dan izin apa yang diperlukan", guardrail: "Materi ini adalah kebiasaan dasar, bukan nasihat hukum; konsultasikan aturan lokal untuk penggunaan berisiko tinggi.", check: "memeriksa sumber, izin, dan hak sebelum publikasi" },
  { id: 86, title: "Provenance & Content Credentials", level: "Menengah", minutes: 13, focus: "Provenance membantu orang memahami asal, perubahan, dan keterlibatan AI pada konten sehingga transparansi dapat menjadi bagian dari proses kreatif.", analogy: "Seperti label nutrisi: bukan menghakimi makanan, tetapi memberi informasi agar orang dapat mengambil keputusan dengan sadar.", story: "Portofolio Hana menggunakan aset AI dan edit manual. Ia menyimpan catatan prompt, sumber, versi edit, serta disclosure. Saat klien bertanya, ia dapat menjelaskan proses tanpa mengklaim semua dibuat dari nol.", practice: "Pilih satu karya lalu buat catatan provenance: sumber, kontribusi manusia, tool, perubahan besar, dan disclosure yang perlu dibaca audiens", guardrail: "Content Credentials dan catatan proses membantu transparansi, tetapi tidak otomatis menyelesaikan semua pertanyaan hak atau izin.", check: "mendokumentasikan asal dan perubahan konten" },
  { id: 87, title: "Proyek Mini: Paket Konten Transparan", level: "Lanjut", minutes: 19, focus: "Capstone kreatif menyatukan brief, aset, caption, disclosure, checklist hak, dan catatan provenance dalam paket yang siap direview.", analogy: "Seperti paket pameran: karya utama penting, tetapi label, kredit, dan konteks membuat orang dapat memahami serta mempercayainya.", story: "Nara membuat kampanye kecil dengan visual AI. Ia menyertakan brief, versi aset, caption, kredit sumber, catatan AI assistance, dan checklist sebelum posting. Review menjadi lebih mudah karena semua keputusan dapat dilacak.", practice: "Buat paket satu konten berisi brief, aset konsep, caption, sumber, disclosure AI, dan checklist publikasi", guardrail: "Jangan membuat testimonial, ulasan, atau bukti pengalaman pengguna yang direkayasa; gunakan konten representatif yang jelas statusnya.", check: "menyusun aset dan disclosure menjadi paket publikasi yang dapat direview" },
];

export const specializationMaterials: Material[] = [...cloudIntensiveMaterials, ...dataIntensiveMaterials, ...aiProductIntensiveMaterials, ...automationIntensiveMaterials, ...creativeIntensiveMaterials];
