import { ArrowRight, Check, Clock3, Layers3, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { materials } from "@/lib/materials";
import { specializationMeta, specializationOrder } from "@/lib/specializations";
import { useLearning } from "@/contexts/LearningContext";

const katherineJohnsonImage = "/manus-storage/katherine-johnson-nasa-1962_c6b966c1.jpg";

export default function Home() {
  const { completed, completedCount, progressPercent } = useLearning();
  const materialCount = materials.length;
  const totalHours = Math.ceil(materials.reduce((total, material) => total + material.minutes, 0) / 60);
  const tracks = specializationOrder.map((id) => ({ ...specializationMeta[id], count: materials.filter((material) => material.specialization === id).length }));
  const checkpoint = materials.find((material) => !completed.includes(material.id)) ?? materials[0];
  return <div className="page home-page simplified-landing"><div className="page-wrap">
    <header className="landing-hero"><div className="landing-hero-copy"><span className="eyebrow">WORKBOOK AI UNTUK PEMULA</span><h1>Belajar AI itu<br /><em>butuh peta.</em></h1><p>Bayangin kamu mau ke tempat yang belum pernah didatengin. Kamu buka Maps dulu, kan? Belajar juga gitu, bro. Di sini kamu tahu mulai dari mana, lanjut ke mana, dan apa yang perlu kamu bawa pulang dari tiap bab.</p><div className="landing-hero-actions"><Link href="/materi" className="brutal-button button-pink">Lihat peta belajarnya <ArrowRight size={18} /></Link><Link href={`/materi/${checkpoint.id}`} className="landing-text-link">Mulai dari titik pertama</Link></div><div className="landing-proof"><span>{materialCount} materi</span><span>·</span><span>~{totalHours} jam belajar</span><span>·</span><span>Proyek kecil per jalur</span></div></div>
      <figure className="scientist-quote-card"><img src={katherineJohnsonImage} alt="Katherine Johnson bekerja di meja NASA Langley pada 1962" width="1041" height="843" /><figcaption><span className="eyebrow">CATATAN DARI ILMUWAN</span><blockquote>“There will always, always be mathematics. Everything is physics and math.”</blockquote><p>— Katherine Johnson, matematikawan NASA</p><a href="https://www.nasa.gov/learning-resources/katherine-johnson-a-lifetime-of-stem/" target="_blank" rel="noreferrer">Kutipan & cerita di NASA ↗</a><small>Foto: NASA Langley Research Center, 1962.</small></figcaption></figure>
    </header>
    <section className="landing-explainer"><div><span className="eyebrow">KENAPA ADA URUTANNYA?</span><h2>Belajar harus tahu arahnya.</h2><p>Kalau cuma lompat-lompat materi, kamu gampang merasa paham padahal belum nyambung. Jadi tiap mata pelajaran dimulai dari dasar, lanjut pelan per bab, lalu ditutup dengan hal kecil yang bisa kamu praktekkan.</p></div><div className="landing-explainer-steps"><article><strong>01</strong><h3>Lihat petanya.</h3><p>Kenalan dulu sama tujuan dan istilah dasarnya. Biar nggak masuk materi berat sambil nebak-nebak.</p></article><article><strong>02</strong><h3>Jalan per bab.</h3><p>Satu konsep, satu contoh, satu latihan kecil. Kamu nggak perlu ngebut ke semua arah sekaligus.</p></article><article><strong>03</strong><h3>Bawa pulang hasilnya.</h3><p>Tutup dengan catatan, jawaban, atau rancangan kecil. Jadi yang kamu pelajari nggak cuma lewat di kepala.</p></article></div></section>
    <section className="landing-subjects"><div className="landing-section-heading"><div><span className="eyebrow">MULAI DARI MANA?</span><h2>Pilih satu arah dulu.</h2><p>Nggak perlu jago semuanya sekarang. Pilih yang paling dekat dengan tujuanmu, lalu ikuti petanya sampai kamu mulai nyambung.</p></div><Link href="/materi" className="landing-text-link">Lihat semua mata pelajaran <ArrowRight size={16} /></Link></div><div className="landing-subject-grid">{tracks.map((track) => <Link key={track.id} href={`/materi?jurusan=${track.id}`} className={`landing-subject-card subject-card-${track.accent}`}><span>{track.emoji}</span><div><small>{track.count} materi</small><h3>{track.label}</h3><p>{track.intro}</p></div><ArrowRight size={18} /></Link>)}</div></section>
    <section className="landing-progress-note"><div><span className="eyebrow">KALAU KAMU BALIK BESOK</span><h2>{completedCount ? `Kamu sudah menutup ${completedCount} materi.` : "Cukup mulai dari satu halaman."}</h2><p>{completedCount ? `Sekarang kamu sudah ${progressPercent}% jalan. Nggak usah lihat semua daftar lagi; buka saja checkpoint yang paling dekat dari posisi kamu.` : "Nggak ada lomba buat kelihatan pintar dalam sehari. Buka satu materi, pahami, lalu lanjut besok kalau masih penasaran."}</p></div><Link href={completedCount ? `/materi/${checkpoint.id}` : "/materi"} className="brutal-button button-black">{completedCount ? "Lihat langkah berikutnya" : "Pilih arah belajarmu"} <ArrowRight size={17} /></Link></section>
  </div></div>;
}
