// Style reminder: Paper Playground — editorial hero, generous paper whitespace, energetic pink actions, and concrete learning entry points.

import { ArrowRight, BookMarked, BookOpen, BrainCircuit, Check, Clock3, Layers3, RotateCcw, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";
import { materials } from "@/lib/materials";
import { specializationMeta, specializationOrder } from "@/lib/specializations";
import { useLearning } from "@/contexts/LearningContext";

export default function Home() {
  const [heroImageStatus, setHeroImageStatus] = useState<"loading" | "ready" | "error">("loading");
  const { bookmarkCount, completed, completedCount, current, progressPercent, weeklyActivity } = useLearning();
  const materialCount = materials.length;
  const categoryCount = new Set(materials.map((material) => material.category)).size;
  const totalHours = Math.ceil(materials.reduce((total, material) => total + material.minutes, 0) / 60);
  const tracks = specializationOrder.map((id) => ({ ...specializationMeta[id], count: materials.filter((material) => material.specialization === id).length }));
  const checkpoint = materials.find((material) => material.id === current) ?? materials.find((material) => !completed.includes(material.id)) ?? materials[0];
  const checkpointDone = completed.includes(checkpoint.id);
  return <div className="page home-page">
    <div className="page-wrap">
      <div className="top-note"><span className="eyebrow-dot" /> WORKBOOK DIGITAL UNTUK PEMULA <span className="top-note-line" /><span>dibuat supaya kamu nggak cuma ikut tren</span></div>
      <section className="hero-section">
        <div className="hero-copy reveal-on-load"><div className="sticker-label">✦ bab 01 · mulai dari nol</div><h1>Belajar AI<br /><em>jadi seru.</em></h1><p className="hero-lead">Nggak perlu jadi jenius buat paham AI. Mulai dari sini, pelan-pelan, satu materi setiap hari.</p><Link href="/materi" className="brutal-button button-pink">Buka materi pertama <ArrowRight size={19} /></Link><div className="hero-caption"><span className="scribble-arrow">↳</span> {materialCount} materi ringkas<br />yang bisa kamu cerna</div></div>
        <div className="hero-art reveal-on-load reveal-delay-2"><div className="art-sticker star-one">✦</div><div className="art-sticker star-two">✹</div><div className={`hero-image-frame hero-image-${heroImageStatus}`}><div className="hero-image-fallback" aria-hidden="true"><BrainCircuit size={76} /><span>✦</span><i /><b>AI<br />mulai<br />di sini</b></div><img src="/manus-storage/belajar-ai-hero-robot_a9d1a2ea.png" alt="Robot ramah dikelilingi kartu belajar AI" width="1200" height="800" loading="eager" fetchPriority="high" decoding="async" onLoad={() => setHeroImageStatus("ready")} onError={() => setHeroImageStatus("error")} /></div><div className="hero-tag"><span>AI<br />tanpa<br />ribet</span><strong>→</strong></div></div>
      </section>
      <section className="stat-strip reveal-on-load reveal-delay-3"><div className="stat-item"><BookOpen size={20} /><div><strong>{materialCount}</strong><span>materi terstruktur</span></div></div><div className="stat-item"><Clock3 size={20} /><div><strong>~{totalHours} jam</strong><span>total waktu belajar</span></div></div><div className="stat-item"><Layers3 size={20} /><div><strong>{categoryCount}</strong><span>kategori inti AI</span></div></div><div className="stat-progress"><span>progress kamu</span><div className="mini-progress"><i style={{ width: `${progressPercent}%` }} /></div><b>{completedCount}/{materialCount}</b></div></section>
      <section className="home-checkpoint-card"><div className="home-checkpoint-stamp"><span>CHECKPOINT</span><strong>{String(checkpoint.displayNumber ?? checkpoint.id).padStart(2, "0")}</strong></div><div className="home-checkpoint-copy"><span className="eyebrow">{checkpointDone ? "ULANGI DARI TITIK TERAKHIR" : "LANJUTKAN DARI TITIK TERAKHIR"}</span><h2>{checkpoint.title}</h2><p>{checkpointDone ? "Semua langkah inti sudah kamu tandai selesai. Buka lagi untuk menguatkan ingatan atau pilih materi berikutnya." : `${checkpoint.minutes} menit · ${checkpoint.level} · ${checkpoint.summary}`}</p></div><Link href={`/materi/${checkpoint.id}`} className="brutal-button button-black">{checkpointDone ? "Buka lagi" : "Lanjut checkpoint"} <ArrowRight size={17} /></Link></section>
      <section className="home-tools"><Link href="/review" className="home-tool home-tool-pink"><RotateCcw size={22} /><div><span className="eyebrow">ULANGI DENGAN CERDAS</span><h3>Mode Review</h3><p>Temukan konsep yang perlu dikuatkan dan langkah berikutnya.</p></div><ArrowRight size={17} /></Link><Link href="/glosarium" className="home-tool home-tool-yellow"><BookMarked size={22} /><div><span className="eyebrow">MARGIN NOTES</span><h3>Glosarium AI</h3><p>{bookmarkCount ? `${bookmarkCount} materi tersimpan · ` : ""}Cari istilah dengan bahasa yang lebih ramah.</p></div><ArrowRight size={17} /></Link><Link href="/flashcards" className="home-tool home-tool-green"><Layers3 size={22} /><div><span className="eyebrow">LATIHAN INGATAN</span><h3>Flashcard Lab</h3><p>Balik istilah glossary dan pertanyaan quiz yang pernah salah.</p></div><ArrowRight size={17} /></Link></section>
      <section className="home-grid section-space"><div className="section-intro"><span className="section-index">01 / 04</span><h2>Pilih pintu masukmu.</h2><p>Masuk lewat jurusan yang paling dekat dengan tujuanmu. Setiap pintu membuka kumpulan materi yang sudah dipilihkan, bukan daftar campuran.</p><Link href="/materi" className="text-link">Lihat peta semua jurusan <ArrowRight size={16} /></Link></div><div className="specialization-entrances">{tracks.map((track) => <Link key={track.id} href={`/materi?jurusan=${track.id}`} className={`specialization-entrance entrance-${track.accent} ${track.count === 0 ? "entrance-coming-soon" : ""}`}><span className="entrance-emoji">{track.emoji}</span><div><span className="eyebrow">{track.count ? `${track.count} MATERI` : "SEGERA HADIR"}</span><h3>{track.label}</h3><p>{track.intro}</p></div><ArrowRight size={19} /></Link>)}</div></section>
      <section className="pink-banner section-space"><div><span className="eyebrow">CATATAN KECIL HARI INI</span><h2>AI bukan sihir.<br /><span>AI adalah pola.</span></h2><p>Kalau kamu bisa menjelaskan masalahnya dengan contoh sederhana, kamu sudah punya modal pertama untuk memahami AI.</p></div><div className="banner-stamp"><Sparkles size={25} /><strong>keep<br />curious</strong><span>✦</span></div></section>
      <section className="home-grid section-space bottom-home"><div className="section-intro"><span className="section-index">02 / 04</span><h2>Belajar dengan ritme yang masuk akal.</h2><p>Setiap materi punya analogi, contoh, dan quiz mini. Selesaikan sedikit demi sedikit, progress tersimpan otomatis.</p></div><div className="habit-card"><div className="habit-card-head"><span className="sticker-label sticker-white">TARGET MINGGU INI</span><span>{weeklyActivity.activeDays.toString().padStart(2, "0")} / {weeklyActivity.goal.toString().padStart(2, "0")}</span></div><div className="habit-dashes">{weeklyActivity.days.map((day) => <span key={day.dateKey} className={day.active ? "day-done" : ""} title={day.active ? `${day.count} aktivitas belajar` : "Belum ada aktivitas"}>{day.active ? <Check size={14} /> : day.label}</span>)}</div><div className="habit-copy"><strong>{weeklyActivity.complete ? "Target mingguan tercapai!" : `${weeklyActivity.activeDays} hari aktif minggu ini.`}</strong><p>{weeklyActivity.complete ? "Pertahankan ritme kecil yang sudah kamu bangun." : `${weeklyActivity.goal - weeklyActivity.activeDays} hari aktif lagi untuk menutup target minggu ini.`}</p></div><Link href="/progress" className="brutal-button button-black">Lihat progress <ArrowRight size={17} /></Link></div></section>
    </div>
  </div>;
}
