// Style reminder: Paper Playground — reading view prioritizes calm paper space, strong article rhythm, and quiz feedback that feels encouraging.

import { ArrowLeft, ArrowRight, Check, ChevronDown, Clock3, RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import { materials } from "@/lib/materials";
import { useLearning } from "@/contexts/LearningContext";

export default function MaterialDetail() {
  const [, params] = useRoute("/materi/:id");
  const [, navigate] = useLocation();
  const id = Number(params?.id) || 1;
  const material = materials.find((item) => item.id === id) ?? materials[0];
  const { completed, scores, markComplete, markCurrent, saveQuizAttempt } = useLearning();
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const isDone = completed.includes(material.id);
  const score = useMemo(() => material.quiz.reduce((total, question, index) => total + (answers[index] === question.answer ? 1 : 0), 0), [answers, material.quiz]);
  const prev = materials.find((item) => item.id === material.id - 1);
  const next = materials.find((item) => item.id === material.id + 1);

  const chooseAnswer = (questionIndex: number, optionIndex: number) => { if (!submitted) setAnswers((prevAnswers) => ({ ...prevAnswers, [questionIndex]: optionIndex })); };
  const submitQuiz = () => { setSubmitted(true); saveQuizAttempt(material.id, score, material.quiz.length); toast(score === material.quiz.length ? "Mantap! Quiz kamu sempurna." : `Quiz selesai: ${score}/${material.quiz.length}. Coba ulang kalau mau naik skor!`); };
  const finish = () => { markComplete(material.id); markCurrent(next?.id ?? material.id); toast("Materi ditandai selesai. Nice work!"); };

  return <div className="page"><div className="detail-layout page-wrap"><aside className={`lesson-sidebar ${sidebarOpen ? "lesson-sidebar-open" : ""}`}><button className="lesson-mobile-toggle" onClick={() => setSidebarOpen(!sidebarOpen)}>Daftar materi <ChevronDown size={17} /></button><div className="lesson-sidebar-inner"><Link href="/materi" className="back-link"><ArrowLeft size={15} /> Kembali ke semua materi</Link><span className="lesson-sidebar-label">KAMU SEDANG DI</span><strong className="lesson-sidebar-title">{material.category}</strong><div className="lesson-list">{materials.filter((item) => item.category === material.category).map((item) => <Link key={item.id} href={`/materi/${item.id}`} className={item.id === material.id ? "lesson-active" : ""}><span>{String(item.id).padStart(2, "0")}</span><b>{item.title}</b>{completed.includes(item.id) && <Check size={14} />}</Link>)}</div></div></aside>
    <article className="lesson-article"><div className="article-meta"><span className="sticker-label">{material.category}</span><span><Clock3 size={15} /> {material.minutes} menit baca</span><span>·</span><span>{material.level}</span></div><div className="article-heading"><span className="article-number">{String(material.id).padStart(2, "0")}</span><h1>{material.title}</h1><p>{material.summary}</p></div><div className="analogy-box"><span className="eyebrow">ANALOGI GAMPANG</span><p>{material.analogy}</p></div>{material.sections.map((section, index) => <section className="article-section" key={section.heading}><span className="section-index">0{index + 1}</span><div><h2>{section.heading}</h2><p>{section.body}</p></div></section>)}<div className="article-callout"><span>✦</span><div><strong>Pause sebentar.</strong><p>Coba jelaskan konsep ini ke diri sendiri dengan satu contoh dari kehidupan sehari-hari.</p></div></div>
      <div className="practice-box"><div className="practice-sticker">TANTANGAN<br />2 MENIT</div><div><span className="eyebrow">WORKSHEET MINI</span><h3>Tarik konsep ini ke dunia nyata.</h3><p>Pilih satu aplikasi yang kamu pakai hari ini. Di mana kamu melihat konsep <strong>{material.title.split(":")[0]}</strong> bekerja?</p><div className="practice-lines"><span /><span /></div></div></div><section className="quiz-box"><div className="quiz-heading"><div><span className="eyebrow">CEK PEMAHAMAN</span><h2>Quiz mini, biar makin nempel.</h2></div><span className="quiz-score">{submitted ? `${score}/${material.quiz.length}` : `${material.quiz.length} soal`}</span></div>{material.quiz.map((question, questionIndex) => <div className="quiz-question" key={question.question}><div className="question-number">0{questionIndex + 1}</div><div className="question-content"><h3>{question.question}</h3><div className="quiz-options">{question.options.map((option, optionIndex) => { const chosen = answers[questionIndex] === optionIndex; const isCorrect = submitted && optionIndex === question.answer; const isWrong = submitted && chosen && !isCorrect; return <button key={option} className={`quiz-option ${chosen ? "option-chosen" : ""} ${isCorrect ? "option-correct" : ""} ${isWrong ? "option-wrong" : ""}`} onClick={() => chooseAnswer(questionIndex, optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}{isCorrect && <Check size={15} />}</button>; })}</div>{submitted && <p className={`quiz-feedback ${answers[questionIndex] === question.answer ? "feedback-good" : "feedback-bad"}`}>{answers[questionIndex] === question.answer ? "✓ " : "↗ "}{answers[questionIndex] === question.answer ? question.explanation : `Belum tepat. ${question.explanation}`}</p>}</div></div>)}<div className="quiz-actions">{submitted && <button className="text-button" onClick={() => { setSubmitted(false); setAnswers({}); }}><RotateCcw size={15} /> Ulangi quiz</button>} {!submitted && <button className="brutal-button button-pink" onClick={submitQuiz} disabled={Object.keys(answers).length !== material.quiz.length}>Cek jawaban <ArrowRight size={17} /></button>}</div></section>
      <div className="lesson-complete"><div><span className="eyebrow">SELESAI MEMBACA?</span><h2>{isDone ? "Materi ini sudah kamu taklukkan." : "Satu materi lagi masuk checklist."}</h2><p>{isDone ? `Skor terbaikmu ${scores[material.id] ?? 0}/${material.quiz.length}. Lanjutkan ke materi berikutnya.` : "Tandai selesai supaya progress dan badge kamu ikut bergerak."}</p></div><button className={`brutal-button ${isDone ? "button-white" : "button-black"}`} onClick={finish}>{isDone ? <><Check size={17} /> Sudah selesai</> : <>Tandai selesai <Check size={17} /></>}</button></div>
      <div className="prev-next">{prev ? <button className="lesson-nav prev" onClick={() => { markCurrent(prev.id); navigate(`/materi/${prev.id}`); }}><ArrowLeft size={17} /><span><small>MATERI SEBELUMNYA</small>{prev.title}</span></button> : <span />}{next ? <button className="lesson-nav next" onClick={() => { markCurrent(next.id); navigate(`/materi/${next.id}`); }}><span><small>MATERI BERIKUTNYA</small>{next.title}</span><ArrowRight size={17} /></button> : <span />}</div>
    </article></div></div>;
}
