import { Check, CircleDollarSign, Gamepad2, Gift, PawPrint, Play, Sparkles, ToggleLeft, ToggleRight, Utensils } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import NpcPetArt from "@/components/NpcPetArt";
import NpcEvolutionCelebration, { type EvolutionCelebration } from "@/components/NpcEvolutionCelebration";
import { useLearning } from "@/contexts/LearningContext";
import { DAILY_FEED_LIMIT, DAILY_PLAY_LIMIT, FEED_XP, FOOD_COST, PLAY_XP, dailyQuests, getPetStage, getPetXpProgress, petProfiles, petRewards, petStages, type PetActionResult, type PetId } from "@/lib/npcPets";

export default function NpcPets() {
  const { npc, selectNpcPet, setNpcPopupEnabled, feedNpcPet, playWithNpcPet, buyNpcFood, claimNpcDailyQuest } = useLearning();
  const [celebration, setCelebration] = useState<EvolutionCelebration | null>(null);
  const activeId = npc.activePet;
  const activeProfile = petProfiles[activeId];
  const activeXp = npc.xp[activeId];
  const progress = getPetXpProgress(activeXp);

  const handleAction = (result: PetActionResult) => { if (!result.ok) { toast.error(result.message); return; } toast.success(result.message); if (result.evolved) setCelebration({ id: Date.now(), petId: activeId, from: result.previousStage, to: result.stage }); };

  return <div className="page"><div className="page-wrap npc-page"><NpcEvolutionCelebration event={celebration} />
    <div className="page-heading npc-heading"><div><span className="eyebrow">NPC PET · TEMAN BELAJAR</span><h1>Tim kecilmu,<br /><em>naik level bareng.</em></h1><p className="npc-lead">Rawat partner pilihanmu, selesaikan quest harian, lalu bangun evolusinya lewat kebiasaan belajar yang konsisten.</p></div><div className="npc-heading-sticker"><PawPrint size={28} /><strong>4 PET</strong><span>koleksi awal</span></div></div>

    <section className="npc-main-card" aria-labelledby="active-pet-heading"><div className="npc-main-art"><NpcPetArt petId={activeId} stage={progress.stage.id} alt={`${activeProfile.name} pada tahap ${progress.stage.label}`} /></div><div className="npc-main-copy"><span className="eyebrow">PET AKTIF</span><div className="npc-name-row"><h2 id="active-pet-heading">{activeProfile.name}</h2><span>{activeProfile.species}</span></div><p>{activeProfile.personality}</p><div className="npc-level-badge">{progress.stage.label} <b>Lv.{progress.stage.level}</b></div><div className="npc-xp-track" role="progressbar" aria-label={`XP ${activeProfile.name}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percent}><i style={{ width: `${progress.percent}%` }} /></div><div className="npc-xp-meta"><strong>{activeXp} XP</strong><span>{progress.nextStage ? `${progress.remaining} XP menuju ${progress.nextStage.label}` : "Tahap akhir tercapai"}</span></div></div><div className="npc-main-quest"><Sparkles size={22} /><span>MODE EVOLUSI 10×</span><strong>Perjalanan panjang, hasil yang terasa.</strong><small>Ambang evolusi dibuat lebih menantang agar setiap tahap terasa spesial.</small><Link href="#quest-harian">Lihat quest <span>↓</span></Link></div></section>

    <section className="npc-care-zone" aria-labelledby="care-heading"><div className="npc-care-copy"><span className="section-index">RUANG INTERAKSI</span><h2 id="care-heading">Rawat {activeProfile.name} hari ini.</h2><p>Makanan memberi <b>+{FEED_XP} XP</b> dan dapat diberikan maksimal <b>{DAILY_FEED_LIMIT} kali per hari</b>. Bermain memberi <b>+{PLAY_XP} XP</b> sekali sehari.</p><div className="npc-care-actions"><button type="button" className="brutal-button button-pink" disabled={npc.foodInventory < 1 || npc.daily.feedings >= DAILY_FEED_LIMIT} onClick={() => handleAction(feedNpcPet())}><Utensils size={16} /> Beri makan <b>+{FEED_XP} XP</b></button><button type="button" className="brutal-button button-black" disabled={npc.daily.plays >= DAILY_PLAY_LIMIT} onClick={() => handleAction(playWithNpcPet())}><Play size={16} /> Ajak bermain <b>+{PLAY_XP} XP</b></button></div><div className="npc-care-limit"><span>Makan hari ini <b>{npc.daily.feedings}/{DAILY_FEED_LIMIT}</b></span><span>Main hari ini <b>{npc.daily.plays}/{DAILY_PLAY_LIMIT}</b></span></div></div><div className="npc-food-inventory"><span className="eyebrow">TAS PERAWATAN</span><div className="npc-inventory-count"><Utensils size={25} /><div><strong>{npc.foodInventory}</strong><span>Makanan pet</span></div></div><div className="npc-inventory-count npc-coins"><CircleDollarSign size={25} /><div><strong>{npc.snackCoins}</strong><span>Koin snack</span></div></div><button type="button" className="npc-buy-food" disabled={npc.snackCoins < FOOD_COST} onClick={() => handleAction(buyNpcFood())}>Tukar {FOOD_COST} koin → 1 makanan</button><small>Selesaikan quest untuk mengumpulkan koin snack.</small></div></section>

    <section className="npc-daily-quests" id="quest-harian"><div className="npc-section-heading"><div><span className="section-index">QUEST HARIAN</span><h2>Belajar untuk bekal merawat.</h2></div><p>Quest akan terbarui setiap hari. Ambil koin snack, lalu tukarkan menjadi makanan untuk pet.</p></div><div className="npc-quest-grid">{dailyQuests.map((quest) => { const current = npc.daily.questProgress[quest.progressKey]; const complete = current >= quest.target; const claimed = npc.daily.claimedQuestIds.includes(quest.id); const percent = Math.min(100, Math.round((current / quest.target) * 100)); return <article className={`npc-quest-card ${claimed ? "npc-quest-claimed" : ""}`} key={quest.id}><Gift size={19} /><span className="npc-quest-reward">+{quest.rewardCoins} koin snack</span><h3>{quest.title}</h3><p>{quest.description}</p><div className="npc-quest-progress"><i style={{ width: `${percent}%` }} /><span>{Math.min(current, quest.target)}/{quest.target}</span></div>{claimed ? <b className="npc-quest-done"><Check size={14} /> Hadiah diambil</b> : complete ? <button type="button" className="brutal-button button-pink" onClick={() => handleAction(claimNpcDailyQuest(quest.id))}>Ambil hadiah <Gift size={14} /></button> : <Link className="npc-quest-link" href={quest.href}>{quest.cta} <span>→</span></Link>}</article>; })}</div></section>

    <section className="npc-collection"><div className="npc-section-heading"><div><span className="section-index">KOLEKSI PET</span><h2>Pilih partner berikutnya.</h2></div><p>XP tiap pet disimpan terpisah. Ganti partner kapan saja dari koleksi ini.</p></div><div className="npc-pet-grid">{(Object.keys(petProfiles) as PetId[]).map((petId) => { const profile = petProfiles[petId]; const xp = npc.xp[petId]; const stage = getPetStage(xp); const active = activeId === petId; return <button type="button" key={petId} className={`npc-pet-card npc-${profile.color} ${active ? "npc-pet-card-active" : ""}`} onClick={() => selectNpcPet(petId)}><NpcPetArt petId={petId} stage={stage.id} alt={`${profile.name}, ${stage.label}`} /><span className="npc-pet-symbol">{profile.symbol}</span><div><small>{profile.species}</small><strong>{profile.name}</strong><em>{stage.label} · {xp} XP</em></div>{active && <b className="npc-active-check"><Check size={14} /> Aktif</b>}</button>; })}</div></section>

    <section className="npc-stage-section"><div className="npc-section-heading"><div><span className="section-index">JALUR EVOLUSI</span><h2>Dari bayi sampai mentor.</h2></div><p>Mode evolusi 10× membuat setiap perubahan tahap benar-benar terasa berarti.</p></div><div className="npc-stage-road">{petStages.map((stage) => { const unlocked = npc.earnedMilestones[activeId].includes(stage.id); return <div className={`npc-stage-stop ${unlocked ? "npc-stage-unlocked" : ""}`} key={stage.id}><span>{stage.level}</span><div><strong>{stage.label}</strong><small>{unlocked ? "Sudah dibuka" : `${stage.minXp} XP`}</small><p>{stage.description}</p></div></div>; })}</div></section>

    <section className="npc-rewards-settings"><div className="npc-reward-card"><Gamepad2 size={24} /><div><span className="eyebrow">CARA MENDAPAT XP</span><h2>Quest kecil, dampak besar.</h2><div className="npc-reward-list">{petRewards.map((reward) => <div key={reward.action}><span>{reward.action}</span><strong>+{reward.xp} XP</strong></div>)}</div></div></div><div className="npc-popup-setting"><div><span className="eyebrow">POPUP TEMAN</span><h2>Tampilkan pet di semua halaman?</h2><p>Default-nya mati. Saat aktif, pet muncul kecil di pojok dan bisa ditutup kapan saja.</p></div><button type="button" className={`npc-toggle ${npc.popupEnabled ? "npc-toggle-on" : ""}`} onClick={() => setNpcPopupEnabled(!npc.popupEnabled)} aria-pressed={npc.popupEnabled}>{npc.popupEnabled ? <ToggleRight size={31} /> : <ToggleLeft size={31} />}<span>{npc.popupEnabled ? "Popup aktif" : "Popup mati"}</span></button></div></section>
  </div></div>;
}
