import { ArrowRight, Check, Clock3, Flame, Target } from "lucide-react";
import { Link } from "wouter";
import { materials } from "@/lib/materials";
import { useLearning } from "@/contexts/LearningContext";
import { getSyncStatusCopy } from "@/lib/syncStatus";
import { getActivityCopy } from "@/lib/learningActivity";

export default function Progress() {
  const { completed, completedCount, progressPercent, current, streak, syncStatus, lastSyncedAt, activityHistory, weeklyActivity } = useLearning();
  const currentMaterial = materials.find((item) => item.id === current) ?? materials.find((item) => !completed.includes(item.id)) ?? materials[0];
  const activeSubjects = new Set(materials.filter((item) => completed.includes(item.id)).map((item) => item.specialization)).size;
  return <div className="page"><div className="page-wrap focus-dashboard-page">
    <header className="focus-dashboard-heading"><div><span className="eyebrow">DASHBOARD BELAJAR</span><h1>Satu langkah lagi,<br /><em>lalu istirahat.</em></h1><p>Dashboard ini hanya menyimpan yang kamu perlukan untuk kembali belajar dengan tenang.</p></div><div className="focus-dashboard-streak"><Flame size={18} fill="currentColor" /><strong>{streak}</strong><span>hari berturut</span></div></header>
    <section className="focus-progress-overview"><div className="focus-progress-ring" style={{ "--progress": `${progressPercent * 3.6}deg` } as React.CSSProperties}><div><strong>{progressPercent}<small>%</small></strong><span>selesai</span></div></div><div><span className="eyebrow">GAMBAR BESAR</span><h2>{completedCount === 0 ? "Halaman pertama menunggu." : "Kamu sudah membangun ritme."}</h2><p>{completedCount === 0 ? "Pilih satu mata pelajaran, lalu buka satu prolog. Tidak perlu memilih semuanya hari ini." : `${completedCount} dari ${materials.length} materi sudah selesai di ${activeSubjects || 1} mata pelajaran.`}</p><small>{getSyncStatusCopy(syncStatus, lastSyncedAt)}</small></div></section>
    <section className="focus-next-card"><div className="focus-next-label"><Target size={17} /><span>CHECKPOINT BERIKUTNYA</span></div><div className="focus-next-main"><div><h2>{currentMaterial.title}</h2><p>{currentMaterial.summary}</p><span><Clock3 size={14} /> {currentMaterial.minutes} menit · {currentMaterial.level}</span></div><Link href={`/materi/${currentMaterial.id}`} className="brutal-button button-pink">Buka materi <ArrowRight size={17} /></Link></div></section>
    <section className="focus-weekly-card"><div><span className="eyebrow">RITME MINGGU INI</span><h2>{weeklyActivity.complete ? "Target minggu ini sudah selesai." : `Sisa ${weeklyActivity.goal - weeklyActivity.activeDays} hari aktif lagi.`}</h2><p>Ritme kecil lebih berguna daripada daftar target yang panjang.</p></div><div className="focus-weekly-days">{weeklyActivity.days.map((day) => <div className={day.active ? "active" : ""} key={day.dateKey}><span>{day.label}</span><b>{day.active ? <Check size={15} /> : "·"}</b></div>)}</div><strong>{weeklyActivity.activeDays}/{weeklyActivity.goal} hari</strong></section>
    <section className="focus-activity"><div className="focus-activity-heading"><div><span className="eyebrow">AKTIVITAS TERBARU</span><h2>Jejak belajarmu.</h2></div>{activityHistory.length > 3 && <Link href="/profil">Lihat semua <ArrowRight size={14} /></Link>}</div>{activityHistory.length ? <div>{activityHistory.slice(0, 3).map((activity) => { const material = activity.materialId ? materials.find((item) => item.id === activity.materialId) : undefined; return <article key={activity.id}><span><Check size={14} /></span><div><strong>{getActivityCopy(activity, material?.title)}</strong><small>{new Date(activity.occurredAt).toLocaleString("id-ID", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</small></div>{material && <Link href={`/materi/${material.id}`} aria-label={`Buka ${material.title}`}><ArrowRight size={16} /></Link>}</article>; })}</div> : <p className="focus-activity-empty">Jejakmu muncul setelah membuka materi atau menutup satu quiz.</p>}</section>
  </div></div>;
}
