// Style reminder: Paper Playground — progress is shown as a visible journey, with inked metrics, warm encouragement, and reward badges.

import { ArrowRight, Check, Flame, LockKeyhole, Target, Trophy } from "lucide-react";
import { Link } from "wouter";
import { materials } from "@/lib/materials";
import { useLearning } from "@/contexts/LearningContext";
import { getLearningRecommendations, getRecommendationSummary, learningGoals, type LearningGoalId } from "@/lib/learningPath";
import { toast } from "sonner";

const badgeData = [
  { title: "Pemula AI", copy: "Selesaikan 5 materi pertama", icon: "✦", check: (count: number) => count >= 5 },
  { title: "LLM Explorer", copy: "Selesaikan semua materi LLM", icon: "⌁", check: (count: number, completed: number[]) => materials.filter((item) => item.category === "Large Language Models").every((item) => completed.includes(item.id)) },
  { title: "RAG Master", copy: "Selesaikan semua materi RAG", icon: "⌗", check: (count: number, completed: number[]) => materials.filter((item) => item.category === "RAG & Teknik Lanjutan").every((item) => completed.includes(item.id)) },
  { title: "Full Stack AI", copy: "Selesaikan semua 33 materi", icon: "★", check: (count: number) => count === materials.length },
];

export default function Progress() {
  const { completed, completedCount, progressPercent, current, streak, quizAttempts, selectedGoal, setSelectedGoal } = useLearning();
  const currentMaterial = materials.find((item) => item.id === current) ?? materials.find((item) => !completed.includes(item.id)) ?? materials[0];
  const categoryStats = Array.from(new Set(materials.map((item) => item.category))).map((category) => { const list = materials.filter((item) => item.category === category); const done = list.filter((item) => completed.includes(item.id)).length; return { category, done, total: list.length }; });
  const activeGoal = (selectedGoal as LearningGoalId | null) ?? "ai-explorer";
  const recommendations = getLearningRecommendations(materials, completed, quizAttempts, activeGoal);
  const recommendationSummary = getRecommendationSummary(materials, completed, quizAttempts, activeGoal);
  return <div className="page"><div className="page-wrap progress-page"><div className="page-heading"><div><span className="eyebrow">DASHBOARD BELAJAR</span><h1>Progress kecil,<br /><em>bangga besar.</em></h1></div><div className="streak-stamp"><Flame size={22} fill="currentColor" /><strong>{streak}</strong><span>hari streak</span></div></div>
    <section className="goal-profile-panel"><div className="goal-panel-heading"><div><span className="eyebrow"><Target size={13} /> PROFIL TUJUAN BELAJAR</span><h2>Pilih arah, biar jalurnya lebih relevan.</h2><p>Tujuan ini tidak mengunci urutan materi. Ia hanya membantu memilih prioritas yang paling dekat dengan hal yang ingin kamu bangun.</p></div><span className="goal-note">tersimpan otomatis</span></div><div className="goal-options">{learningGoals.map((goal) => <button type="button" key={goal.id} className={`goal-option ${activeGoal === goal.id ? "goal-option-active" : ""}`} onClick={() => { setSelectedGoal(goal.id); toast(`Profil ${goal.label} dipilih.`); }}><span className="goal-emoji">{goal.emoji}</span><span><strong>{goal.label}</strong><small>{goal.description}</small></span>{activeGoal === goal.id && <Check size={16} className="goal-check" />}</button>)}</div></section>
    <section className="progress-overview"><div className="big-progress"><div className="progress-ring" style={{ "--progress": `${progressPercent * 3.6}deg` } as React.CSSProperties}><div><strong>{progressPercent}<small>%</small></strong><span>selesai</span></div></div></div><div className="overview-copy"><span className="eyebrow">OVERVIEW</span><h2>{completedCount === 0 ? "Kita mulai dari halaman pertama." : "Kamu sudah melangkah jauh."}</h2><p>{completedCount === 0 ? "Pilih satu materi untuk mengisi checklist pertamamu. Nggak perlu menunggu mood sempurna." : `Dari 33 materi, ${completedCount} sudah selesai. Setiap konsep yang kamu pahami bikin peta AI-mu makin lengkap.`}</p><div className="category-bars">{categoryStats.map((item) => <div className="category-row" key={item.category}><div><span>{item.category}</span><b>{item.done}/{item.total}</b></div><div className="category-track"><i style={{ width: `${(item.done / item.total) * 100}%` }} /></div></div>)}</div></div></section>
    <section className="continue-card"><div className="continue-art"><img src="/manus-storage/belajar-ai-learning-path_a2c3496e.png" alt="Ilustrasi jalur belajar AI" /></div><div className="continue-copy"><span className="eyebrow">LANJUTKAN BELAJAR</span><h2>{currentMaterial.title}</h2><p>{currentMaterial.summary}</p><div className="continue-meta"><span>{currentMaterial.category}</span><span>·</span><span>{currentMaterial.minutes} menit</span></div><Link href={`/materi/${currentMaterial.id}`} className="brutal-button button-pink">Lanjut baca <ArrowRight size={17} /></Link></div></section>
    <section className="learning-path-section"><div className="learning-path-heading"><div><span className="section-index">04 / 04 · PERSONALIZED PATH</span><h2>{recommendationSummary.headline}</h2><p>{recommendationSummary.body}</p></div><div className="path-signal"><span>{Object.keys(quizAttempts).length}</span><small>quiz<br />terbaca</small></div></div>{recommendations.length ? <div className="recommendation-list">{recommendations.map((recommendation, index) => <Link href={`/materi/${recommendation.material.id}`} className={`recommendation-card recommendation-${recommendation.accent}`} key={`${recommendation.type}-${recommendation.material.id}`}><div className="recommendation-step">{String(index + 1).padStart(2, "0")}</div><div className="recommendation-copy"><span className="eyebrow">{recommendation.label}</span><h3>{recommendation.title}</h3><p>{recommendation.reason}</p><div className="recommendation-material"><strong>{recommendation.material.title}</strong><span>{recommendation.material.category} · {recommendation.material.minutes} menit</span></div></div><ArrowRight className="recommendation-arrow" size={19} /></Link>)}</div> : <div className="learning-path-empty"><div className="empty-path-mark">✦</div><div><h3>Jalur belajarmu akan terbuka setelah quiz pertama.</h3><p>Kerjakan quiz di materi mana pun. Sistem akan membaca skor, melihat kategori yang perlu diperkuat, lalu menyusun langkah berikutnya.</p><Link href="/materi/1" className="text-link">Mulai dari materi pertama <ArrowRight size={16} /></Link></div></div>}</section>
    <section className="badges-section"><div className="section-intro"><span className="section-index">03 / 04</span><h2>Badge yang bisa kamu koleksi.</h2><p>Badge ini bukan kompetisi. Anggap saja stiker kecil untuk merayakan proses.</p></div><div className="badges-grid">{badgeData.map((badge) => { const unlocked = badge.check(completedCount, completed); return <div className={`badge-card ${unlocked ? "badge-unlocked" : ""}`} key={badge.title}><div className="badge-icon">{unlocked ? badge.icon : <LockKeyhole size={24} />}</div><div><strong>{badge.title}</strong><span>{badge.copy}</span></div>{unlocked && <Check size={17} className="badge-check" />}</div>; })}</div></section>
    <section className="progress-footnote"><Trophy size={20} /><p><strong>Tip konsistensi:</strong> pilih satu materi yang durasinya 5–8 menit, lalu berhenti saat selesai. Sedikit tapi rutin lebih kuat dari maraton semalam.</p></section>
  </div></div>;
}
